### ISSUE TITLE
"Dataset exceeds 15000 records, cannot render." when plotting

### ISSUE THREAD

**Issue by PathosEthosLogos** [man-group/dtale#100]
Really, really nice library. :)

There is a dataset limitation of 15.000. Any progress on this?

**Comment by phillipdupuis** [comment]
Hmm.  It looks like there are WebGL alternatives (so it'll use your GPU and be way faster) that could be used for line plots, scatter plots, and heatmaps...

I just tested it out myself, and it seems to work quite nicely for 50k data points.  So I think there's a good chance this will be added in the next release and the 15k limit will be dropped for line/scatter/heatmaps.   The next release should be coming out within the next couple days :)

**Comment by phillipdupuis** [comment]
In the meantime, if you really want to make charts with over 15k records and you're okay with it being a bit painfully slow you can cheat and remove the limitation...

Go into _dtale/charts/utils.py_ (it'll probably be in the .../python/site-packages folder), go to the 'check_exceptions' function, and comment out the following code:
`
    if len(df) > data_limit:
        raise Exception(limit_msg.format(data_limit))
`

**Comment by aschonfeld** [comment]
v1.7.13
