### ISSUE TITLE
Column filtering

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#102]
This is a feature request. Right now, filtering can be done using the df.query method from the main menu. That's great, but often you only need to filter by certain values in a column.

My suggestion would be to add a filtering option in the context menu of the columns, so that the filtering expression would be applied only to that column, saving you from having to type the full name of the column.

Another addition would be that for columns that include discrete values (categories), you could select the values you want to filter on instead of having to write them down.

Both options are implemented at [qgrid](https://github.com/quantopian/qgrid).

**Comment by aschonfeld** [comment]
@juanfcocontreras this will be the next thing I tackle :)

**Comment by aschonfeld** [comment]
@juanfcocontreras just released v1.8.0 which includes support for interactive column filtering!  Let me know what you think.  Here's a quick video of the functionality: https://www.youtube.com/watch?v=8zo5ZiI1Yzo

**Comment by juanfcocontreras** [comment]
> @juanfcocontreras just released v1.8.0 which includes support for interactive column filtering! Let me know what you think. Here's a quick video of the functionality: https://www.youtube.com/watch?v=8zo5ZiI1Yzo

I think it's just amazing. Thank you very much for your effort!

**Comment by aschonfeld** [comment]
Anytime!  Tell your friends 😉
