### ISSUE TITLE
Install to bare virtualenv fails

### ISSUE THREAD

**Issue by jasonkholden** [man-group/dtale#103]
Install to a bare virtualenv fails:
% virtualenv -p python3 virt-dtale
virt-dtale% pip install six
virt-dtale% python setup.py develop

yield the following error
<snip>
Moving flask_ngrok-0.0.25-py3.6.egg to /home/jason/virt-dtale/lib/python3.6/site-packages
flask-ngrok 0.0.25 is already the active version in easy-install.pth

Installed /home/jason/virt-dtale/lib/python3.6/site-packages/flask_ngrok-0.0.25-py3.6.egg
error: The 'Flask' distribution was not found and is required by dtale

A quick google shows maybe we should set the version in setup.py (it's pretty old)
https://github.com/pallets/flask/issues/1106

**Comment by aschonfeld** [comment]
v1.7.15
