### ISSUE TITLE
Save/Read DataFrame

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#114]
# Save
When the DataFrame is generated or manipulated or filtered with code and doesn't have csv to read.
It would be perfect to have a save option to export the DataFrame or specific columns or rows or cells
for example in the demo page
* Save  row3:row20, col9:col20
* Save the whole DataFrame
* Save as csv or tsv

For save I use these options which are useful.
df.to_csv(input_path, encoding='UTF-8', index=False)

I liked https://community.plotly.com/t/download-raw-data/4700/8

# Open
 It would be perfect to read or open a file in dtale. Now we read it in pandas and call dtale. In my opinion, we can act like excel. open dtale > read a csv

For read, I use these options which are useful.

pd.read_csv(input_path, encoding = "UTF-8", dtype=str, keep_default_na=False)

dtype option can be the default of pandas but we need to select dtype=str as an opinion (1- it is much faster 2-it doesn't change some strings which are like a number (i.e. '00001')

keep_default_na can be the default of pandas but we need it to auto-remove Null

**Comment by aschonfeld** [comment]
@reza1615 I have added the ability to download the raw data that goes into a chart as a CSV
![image](https://user-images.githubusercontent.com/11547371/77568378-e9864380-6e9e-11ea-81a0-650756ee5d08.png)

I can try adding what you're asking for in the main grid though

**Comment by aschonfeld** [comment]
exporting now available in v1.8.1

**Comment by reza1615** [comment]
Thanks
