### ISSUE TITLE
Meaningful data for demo

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#117]
In my opinion, having meaningful data in Demo helps to have a better understanding of the tool.
I added some extra random columns to the https://www.kaggle.com/shivachandel/kc-house-data
and uploaded the csv here. 
I added some extra txt and categorical columns + some null 
[kc_house_data.zip](https://github.com/man-group/dtale/files/4384945/kc_house_data.zip)

Now testing charts in the demo is difficult because the data doesn't have any meaning.

**Comment by aschonfeld** [comment]
donezo 👍
