### ISSUE TITLE
Select range of cells

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#123]
In the below image when I select cell 1 and drag to cell 2 it also selects range B and C. I only want to select range A like excel.
![image](https://user-images.githubusercontent.com/2202483/77672031-c58a3700-6f5e-11ea-8df3-36c9faaa09ba.png)
Also when I want to copy and past the cells all the cells convert to a row and it can not copy and paste data between plotly and excel.
I found https://community.plotly.com/t/copy-and-pasting-data-in-dash-table-experiment-to-excel/9914

**Comment by reza1615** [comment]
I opened a ticket in https://github.com/plotly/dash-table/issues/726

**Comment by aschonfeld** [comment]
Added in v1.19.0 here's the [documentation](https://github.com/man-group/dtale#copy-cells-into-clipboard) and here's a [demo](https://youtu.be/IqG54m47QTk)
