### ISSUE TITLE
Persisting data from demo after restart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#126]
In demo I built columns and they saved and still remain :)
It should get efalt data frame after each refresh

**Comment by aschonfeld** [comment]
Thats good correct? I hope 🙂

They will eventually get dropped though if enough people hit the demo and it runs out of memory and it has to restart.  Unfortunately thats the limitation of the free PythonAnywhere account ☹️

**Comment by reza1615** [comment]
maybe you can add cp (copy) at the first of the runing code to copy default csv

**Comment by aschonfeld** [comment]
Yea that will definitely take some thinking on my end.  I think it will take less time for me to figure out a way for people to upload csv/tsv files into the app

**Comment by reza1615** [comment]
Also, For the opening, it can offer them some in-house CSVs

**Comment by reza1615** [comment]
I think this is resolved. is it correct?

**Comment by aschonfeld** [comment]
I built the ability to upload/download csv files but i never did anything to automatically persist data changes made on the demo site between restarts.  I dont plan on doing that anytime soon since thats not really the purpose of the tool so if you want to close this thats great
