### ISSUE TITLE
Show dtype when mouse over the column name & main menu descriptions

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#129]
Showing dtype when the mouse hovers the column name. Now highlight type is perfect but it doesn't have any color legend. In my opinion, the best legend could Mouseover text box.

**Comment by reza1615** [comment]
Also, the Mouseover tip/help/description for the main menu is not set.

**Comment by aschonfeld** [comment]
I’ve added data type display on hover of column headers when you’ve turned on “Highlight Dtypes” but i dont think I understand your second comment.

**Comment by reza1615** [comment]
in the main menu all buttons dont have moreover text. for example when I move mouse over describe it should show some tip description like "describing data columns such as number of unique items, min, max ,..."

**Comment by aschonfeld** [comment]
@reza1615 if you want to supply me with descriptions for the buttons I'll be more than happy to add mousehovers

**Comment by reza1615** [comment]
@aschonfeld: please fill free to edit it.

* Describe > "Describe column's values (Top unique values, Min, Max, Sum, STD, Var,...)"
* Filter > "Defining custom Filtering for the main spreadsheet, Charts, ..." 
* Build Column > "Creating a/multi new column based on the existing columns or random values"
* Reshape **(In my opinion should be Summarizing table)** > "Creating new PIVOT table, Aggregated table GroupBy, Transpose"
* Correlations > "Presenting correlations matrix and chart" 
* Charts > "Plot chart (liner, scatterplot, bar chart, Pie, Map,...)"
* HeatMap > "Presenting heatmap for numerical values in the main table"
* Highlight Dtypes > "Highlight columns based on pandas dtypes. For dtype's name hover the mouse over column name"
* Instances **(In my opinion should be Sheets)** > "Show existing data sheets"
* Export > "Download DataFrame as CSV or TSV"
* Refreshing widths > "Auto-Resize the column widths"
 * About > "Link to the source code repository, documentation"

**Comment by aschonfeld** [comment]
@reza1615 this is great!  Thank you.  Documentation has never been my strong suit so this really helps.  I'll get to work adding this and show you a sample...

**Comment by aschonfeld** [comment]
@reza1615 Took a little longer than I thought, but I was able to add the descriptions.  Let me know what you think
https://youtu.be/1kvlzeAfmCE

**Comment by reza1615** [comment]
That is Great. Thanks.

**Comment by reza1615** [comment]
shutdown > "Close D-Tale and its instances without save. do you want to export DataFrame?"

**Comment by reza1615** [comment]
Would you please change css to show the mouseover in the broswer window? check demo. 
![image](https://user-images.githubusercontent.com/2202483/78208804-50919280-7473-11ea-902f-360d3bbbd7b0.png)

**Comment by aschonfeld** [comment]
That doesn't seem to happen to me on the demo site
![image](https://user-images.githubusercontent.com/11547371/78247328-b5bba700-74b8-11ea-84d7-9e2f8a7eeb66.png)
Did you shrink your browser down super small or something?

**Comment by reza1615** [comment]
hmm I have two monitors and it was on the right side. now i test it on the left monitor and it was ok. Maybe it is a bug which we should report to the plotly.

on the left monitor
![image](https://user-images.githubusercontent.com/2202483/78251834-e94dff80-74bf-11ea-9cf4-010456ce8e29.png)

**Comment by aschonfeld** [comment]
I have two monitors and I just tested it on each and both had the same correct behavior 🤷‍♂ 

Just to be clear this would be a CSS issue not plotly.  plotly only controls the "Charts" page.  Everything else is using custom ReactJS components.  For example:
main grid -> react-virtualized
popups -> react-modal-bootstrap
dropdowns -> react-select (plotly/dash happens to use the same thing)
datetime inputs -> @blueprintjs/datetime
etc...

I'm calling this one closed.

**Comment by reza1615** [comment]
I use windows 10 is you os windows?

**Comment by aschonfeld** [comment]
I am currently on windows 10, but I think the issue might lie with the browser you're using.  I've tested it on the following with no issue:

* IE11 (just locally there's a fix I need to deploy to get the grid to render)
* Microsoft Edge 41.16299.1480.0 (just locally there's a fix I need to deploy to get the grid to render)
* Chrome 80.0.3987.149
* Firefox 72.0.2

**Comment by reza1615** [comment]
It is so strange now it is not producible!! 
I tested on producible 
* Chrome Version 80.0.3987.149 (Official Build) (64-bit)

Anyway now it works properly. Thanks for your time
