### ISSUE TITLE
Pivot Table

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#130]
Thank you for adding the pivot table.  when I execute it in http://andrewschonfeld.pythonanywhere.com/dtale/main/4
1- it doesn't show the name of column and it has only row name.
![image](https://user-images.githubusercontent.com/2202483/77840156-04cca980-7152-11ea-9291-48d39b64905f.png)

2- Please rename Index label in the window to **Rows** ( index has a ambiguaty for PIVOT) 
![image](https://user-images.githubusercontent.com/2202483/77840145-e23a9080-7151-11ea-8254-200d2b83b44b.png)

**Comment by aschonfeld** [comment]
for question (1) are you asking that I add the name of the column as a prefix to each column name?  I can do that but in the use cases we had that wasn't really what the user wanted (say for security tickers).  Maybe I can make that a toggle option.

**Comment by reza1615** [comment]
for the below case. can you change date cell to the date\col2
![image](https://user-images.githubusercontent.com/2202483/77957130-02c53080-72a1-11ea-956f-2a7c1cd7cbdb.png)

**Comment by aschonfeld** [comment]
hmm, that rendering of 700\6 is some CSS magic so that's not really possible. It would have been great, but I can certainly give you the column name prefix toggle

**Comment by reza1615** [comment]
Thanks. Fixed
