### ISSUE TITLE
Reshape Data window

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#131]
1- Reshape in numpy and pandas has a different meaning and maybe **Summarizing table** is a good name. In excel they have this definition
![image](https://user-images.githubusercontent.com/2202483/77840287-9852aa00-7153-11ea-9b40-d206ae34a953.png)

2- In my opinion aggregation in this window has ambiguity. Maybe **GroupBy** is a good label.

![image](https://user-images.githubusercontent.com/2202483/77840213-dac7b700-7152-11ea-86f7-9d7a7bebb1b8.png)

3- here index has ambiguity. Maybe **Columns to GroupBy** is better
![image](https://user-images.githubusercontent.com/2202483/77840504-537c4280-7156-11ea-9f4a-f264bc0df3f5.png)

4- In my opinion, the **New Instance** as default is safer. usually, people need to keep the original table. Sorry, I forgot to set to the **New instance** and I replaced the original table! :(

**Comment by reza1615** [comment]
Thanks for all changes. I think i couldn't deliver properly my idea for the naming.
I mean changing: 

"Reshape" > "Summarizing table"
"Pivot (summarizing table)" > "Pivot"

**Comment by aschonfeld** [comment]
Ok, I think I prefer "Summarize Data"

**Comment by aschonfeld** [comment]
added v1.8.3
