### ISSUE TITLE
Aggregation by column vs aggregation by function

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#133]
I tested Aggregation by column and aggregation by function. both results are the same.

I set groupby 
* group by columns: yr_built , Exterior color 
* agg: Mean()
* column : Price

http://andrewschonfeld.pythonanywhere.com/dtale/main/6

http://andrewschonfeld.pythonanywhere.com/dtale/main/1
(Sorry I forgot to set to new instance :( )

**Comment by aschonfeld** [comment]
Is this an issue?  There's two different ways to produce the same results I understand, but that's not necessarily a problem.  Just giving the users access to every avenue of aggregation.

**Comment by reza1615** [comment]
**BY Column** has this possibility to have multiple rules but **By function** doesn't have.
Actually I was confused. 
Maybe adding a Tip note can be helpful or merging them into one page.

**Comment by aschonfeld** [comment]
I don't think I follow on the "Merging them into one page".  They're on the same popup it'sjust a toggle.  I think the tip is a good idea although I'm not sure of a good way to explain it without making some complex diagrams/grids.
