### ISSUE TITLE
Fill missing values

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#136]
It is good to have fill missing values. usallay I use these commands
* df.loc[:,'col']=df.loc[:,'col'].replace(r'^\s+$', np.nan, regex=True)  # Replace 1 space or multiple space
* .replace(r'[Uu]nknown', np.nan, regex=True) # replace unknown or Unknown
*  .replace(r'^ *[\-\_]+ *$', np.nan, regex=True) # replace '-' or ' - ' or ' ---- ' or '_'
* .fillna('') 
* .fillna(0) 
* .fillna(value) 
* .fillna(df.mean()/min/max/fisrt/last/mid) 
Also
* SimpleImputer
* KNNImputer 
* IterativeImputer
https://www.linkedin.com/posts/justmarkham_sklearntips-machinelearning-python-activity-6650374643419090944-GHyR
https://www.linkedin.com/posts/justmarkham_sklearntips-machinelearning-python-activity-6648932419095322624-hH5F

**Comment by reza1615** [comment]
Maybe it is better to have a replacement window with these sub-ages
*  filling missing value is a sub-page
* replace value1 > value 2

**Comment by reza1615** [comment]
I developed this notebook the aggr part needs more work.
The rest of the code works properly. If you work on the UI 
I will finish the functions and aggr part
[fill missings.zip](https://github.com/man-group/dtale/files/4411688/fill.missings.zip)

for UI I recommend to have some thing like this pipline
to replace
1-specific word (like "unknown") > null
2-specific  char (like "-")  > null
3-empty  > nul
.
.
.
.
10- null > value or empty or remain null
![image](https://user-images.githubusercontent.com/2202483/78077570-97e62900-7376-11ea-92a8-cbabdd950150.png)

**Comment by reza1615** [comment]
Added 
- SimpleImputer
- KNNImputer
- IterativeImputer
[fill missings3.zip](https://github.com/man-group/dtale/files/4416347/fill.missings3.zip)

**Comment by aschonfeld** [comment]
@reza1615 This is great!  Thanks for supplying the code.  I'll work on integrating this and hopefully this can be used for #86 as well

**Comment by aschonfeld** [comment]
@reza1615 here's the first cut of this new functionality.  It should also tackle #86 as well
[demo](https://youtu.be/ilgN2U9uiQk)

**Comment by reza1615** [comment]
That is great thanks

**Comment by aschonfeld** [comment]
added v1.8.14
