### ISSUE TITLE
DemoData to the Repo and Live demo

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#139]
I created a demo data and checked lat and long they are belong to Canada, USA, Germany.
It has all data types and most type of unclean data issues (some missing data,0, space ,...)
Also It has ZipCode (for each country based on their standard) + Neighborhood name, State Name ,...
I added some outliers to the price and made it unclean :) + some missing data,0, space ,...
Please add it to the Repo as exmple + to demo 
For opening the file should take care of these cases:
* It has Unicode characters (Accent characters)
* It has number dtype columns which starts with 0 (like 01234) so they should assume as text 

Attached excel and CSV file
[DemoData.xlsx](https://github.com/man-group/dtale/files/4422173/DemoData.xlsx)
[DemoData-csv.zip](https://github.com/man-group/dtale/files/4422176/DemoData-csv.zip)

**Comment by reza1615** [comment]
I updated excel file 
* Corrected the Price column
* Corrected country codes
Now you can use it for creating Choropleth Map
[DemoData2.xlsx](https://github.com/man-group/dtale/files/4427796/DemoData2.xlsx)

**Comment by reza1615** [comment]
Version 3
[DemoData3.xlsx](https://github.com/man-group/dtale/files/4434304/DemoData3.xlsx)
[DemoData3-csv.zip](https://github.com/man-group/dtale/files/4434305/DemoData3-csv.zip)

**Comment by aschonfeld** [comment]
@reza1615 data has now been loaded to: http://alphatechadmin.pythonanywhere.com/dtale/main/1
