### ISSUE TITLE
More Filters for string columns

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#140]
Is it possible to add these constraints to the filter?
* text starts/notstart with like (M for M2M3h8)
* text ends/not end with like (o for 'foo')
* text has/doesn't have  'foo' like ('5e8' for 'm3m 5e8')
* text length (len) is in range (2,10)
* **For above conditions:**  Case sensitive or not

 ![image](https://user-images.githubusercontent.com/2202483/78273267-9cc4ed00-74dc-11ea-993e-63ba8d3ef728.png)

**Comment by reza1615** [comment]
@phillipdupuis Thank you for functions. In my opinion it would be nice to have them on fly. creating new column for different explorations makes data messy 
@aschonfeld In my opinion beside = # we can have a dropdown with this cases and the below dopdown would hide and have a text box for input

**Comment by aschonfeld** [comment]
Added in v1.46.0
