### ISSUE TITLE
Currency Symbole for column Format

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#141]
Please add a currency inputbox to add the currency symbol to a column
For example adding $ or CAD to the Price column.

![image](https://user-images.githubusercontent.com/2202483/78274085-adc22e00-74dd-11ea-9426-e25da79aa229.png)

**Comment by aschonfeld** [comment]
This isn't really feasible.  Not sure what a currency label would add?  If you're dealing with prices in multiple currencies I would simply have them in separate column and have the currency label embedded in the column name.

The only way I could ever see this being remotely useful is if you have another column for currency code and that would be driving which currency symbol is being displayed for each price.  Either way, I think this would be building functionality around a major edge case.

Interested to hear if you feel differently. 🤔

**Comment by reza1615** [comment]
It is one kind of formatting like Abbreviation to distinguish currency columns from other columns. With style you can apply it to the column without touching the numbers
``` python
import pandas as pd
import numpy as np

constants = pd.DataFrame([('pi',np.pi),('e',np.e)],
                   columns=['name','value'])
C = constants.style.format({'name': '~~ {} ~~', 'value':'--> {:15.10f} <--'})
```
![image](https://user-images.githubusercontent.com/2202483/78302858-a749ab80-7509-11ea-8ec7-084d2df5c839.png)

Source: https://stackoverflow.com/questions/20937538/how-to-display-pandas-dataframe-of-floats-using-a-format-string-for-columns

**Comment by aschonfeld** [comment]
I still dont see much value in adding a currency symbol in front of your number.  You will have to do it manually everytime you load your dataframe and unless you plan on hosting your D-Tale session for a long period of time nobody will see it.

Also, i’m confused about what that code snippet with e & pi are for.

If you have floats with a currency symbol in front of them when loading the data it will treat it as a string and keep the currency symbol on the front.

For you test dataset i was stripping it from ‘price’ and converting it to a float so it could be used in aggregations.  Sorry

**Comment by reza1615** [comment]
If you don't want to add that is OK.

FYI: For style I read below article and it is interesting.
https://towardsdatascience.com/style-pandas-dataframe-like-a-master-6b02bf6468b0

**Comment by aschonfeld** [comment]
v1.8.7
