### ISSUE TITLE
Changing data type

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#144]
I tested data in the #139 pandas load most columns as dtype: mixed-integer which we can not use them for chart or aggregations.
In my opinion we should have a part for handling this problem which should cover:
* Replace missing data #136
* Replace wrong data (For example 9999999 in number columns)
* Change data type

**Comment by aschonfeld** [comment]
Here's a list of other conversions I could think of:
* string -> date, int, float, bool, category
* int -> float, category, string
* float -> string
* date -> string
* bool -> string, int
* category -> int, string

**Comment by reza1615** [comment]
+
float > int like 2.0 >2
date > int like julian calendar or 20200417
int> date like 20200417 to 2020-04-17
int > bool for 0,1 to true and false
category > bool for binary

**Comment by aschonfeld** [comment]
Added to "Build Column" popup in v1.8.8
