### ISSUE TITLE
Choropleth Map

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#145]
1- In the Choropleth Map we need:
* Help link to ISO-3 (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)
* Help link to USA- States code (Mention we need ISO) (https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations)
* Help link to Countries (https://www.worldometers.info/geography/alphabetical-list-of-countries/)

2-Location mode :  In the Plotly help page I didn't find country name

With this excel file I could get these charts
[DemoData2.xlsx](https://github.com/man-group/dtale/files/4427670/DemoData2.xlsx)

![image](https://user-images.githubusercontent.com/2202483/78368308-701edd00-7591-11ea-9e26-d594c15f80ca.png)

and

![image](https://user-images.githubusercontent.com/2202483/78368534-c5f38500-7591-11ea-804b-62ca923316bb.png)

3-Location dropdown: should only suggest dtype=txt not whole columns. to be precise may be only show the columns which their cells length are =<3.

**Comment by aschonfeld** [comment]
"country name" literally just corresponds to country names: https://stackoverflow.com/questions/56709920/list-of-locationmode-to-use-with-plotly

Here's the full list of options: https://plotly.com/python/reference/#choropleth-locationmode

Looks like they've added another for GeoJSON

**Comment by reza1615** [comment]
I tested with this excel file and it works :)
[countries.xlsx](https://github.com/man-group/dtale/files/4430668/countries.xlsx)

![image](https://user-images.githubusercontent.com/2202483/78417627-f5da7100-7601-11ea-8cbd-bf53606cd428.png)

**Comment by reza1615** [comment]
> "country name" literally just corresponds to country names: https://stackoverflow.com/questions/56709920/list-of-locationmode-to-use-with-plotly
> 
> Here's the full list of options: https://plotly.com/python/reference/#choropleth-locationmode
> 
> Looks like they've added another for GeoJSON

I made a notebook for GeoJSON
[UsingJSON.zip](https://github.com/man-group/dtale/files/4430848/UsingJSON.zip)

**Comment by aschonfeld** [comment]
added the informational popups to the "Location Mode" dropdown in v1.8.4

**Comment by aschonfeld** [comment]
Closing this since I've referenced your request for GeoJSON in #151
