### ISSUE TITLE
Chart: an option to choose random sample of data

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#148]
For huge datasets for exploring data we need to have rough chart which can possible by random sample
like **Select bank & dataset size** in the https://dash-gallery.plotly.host/dash-nlp/

It can be as a Pre-filter for all chart to avoid freezing the chart.

**Comment by aschonfeld** [comment]
@reza1615 not sure if this helps but if you go to the “upload” screen or start D-tale by invoking dtale.show() with no data you’ll see i’ve added a few sample datasets.  If you have a rough idea about how to construct the dataset you’re thinking of i’ll be happy to add it

**Comment by reza1615** [comment]
@aschonfeld. I asked for a bar like the below image which allow user to just load some random data from the dataset for charts
![image](https://user-images.githubusercontent.com/2202483/100032970-2e180500-2dc7-11eb-8cf4-cba7d30b6c1f.png)
For example: Imagine there is 100K row dataset. we want to get distribution chart. For the primary steps it doesn't need to get the chart for 100K. 
Getting chart just for the 20% of data would be ok.

**Comment by reza1615** [comment]
```
import dash
import dash_html_components as html
import dash_core_components as dcc

#external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__)
app.layout = html.Div([
    dcc.Slider(
        id='my-slider',
        min=0,
        max=100,
        step=10,
        value=20,
        marks={
        0: '0%',
        20: '20%',
        40: '40%',
        60: '60%',
        80: '80%',
        100: '100%',
    }
    ),
    html.Div(id='slider-output-container')
])




@app.callback(
    dash.dependencies.Output('slider-output-container', 'children'),
    [dash.dependencies.Input('my-slider', 'value')])
def update_output(value):
    return 'You have selected "{}"'.format(value)


if __name__ == '__main__':
    app.run_server()
```

**Comment by aschonfeld** [comment]
@reza1615 heres what I have so far: https://youtu.be/-cW0tomF58s

**Comment by reza1615** [comment]
Thanks this is great

**Comment by aschonfeld** [comment]
added in v1.25.0
