### ISSUE TITLE
Icon for Map charts

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#149]
In my opinion to see an icon is much comprehensive than a name. I suggest instaed of dropdown text box we use these icons for charts

* Choropleth Map
![001](https://user-images.githubusercontent.com/2202483/78386057-e1b75500-75aa-11ea-8499-38869100ceed.png)

* ScatterGeo Map
![002](https://user-images.githubusercontent.com/2202483/78386059-e24feb80-75aa-11ea-8e8d-8a7610babf6b.png)

Total size is 15K

**Comment by aschonfeld** [comment]
added v1.8.5
