### ISSUE TITLE
Consider if we should support dtale[arctic] extras functionality

### ISSUE THREAD

**Issue by jasonkholden** [man-group/dtale#15]
This may be a better way to conditionally support arctic as a conditional dependency

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

```
setup(
    name="Project-A",
    ...
    extras_require={
        'PDF':  ["ReportLab>=1.2", "RXP"],
        'reST': ["docutils>=0.3"],
    }
)
```

**Comment by aschonfeld** [comment]
Added in v1.7.0
