### ISSUE TITLE
Version 1.8.3

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#154]
After version 1.8.3 chart map doesn't work (both chart maps)
I tried to reproduce cases in the #145 and it doesn't show any chart

**Comment by aschonfeld** [comment]
Sorry, I know what the issue is.  It works for me locally but wont work in the egg because the topojson files I added are not being included.  I'll update that and have a new version out.

**Comment by aschonfeld** [comment]
fixed in v1.8.4
