### ISSUE TITLE
Option to filter out outliers from charts

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#160]
In the chart window we can have an option to filter out outliers from selected columns

for example: if yr_built selected exclude 99999999 and for price exclude 0

Also it can be as an option the filter window to list outliers of a column/ columns

**Comment by aschonfeld** [comment]
So this can obviously be done by adding a query "yr_build != 99999999 and price != 0" but I'll try adding an option to the "Describe" popup to view outliers for columns and a way to add a quick filter for them.  This filter would be brought over when opening up the "Charts" tab.

**Comment by reza1615** [comment]
Yes, I asked for semi-automated action as you said D-Tale suggests some outliers and user add the to the filter

**Comment by aschonfeld** [comment]
[Outlier filters](https://github.com/man-group/dtale/tree/v1.8.7#outlier-detection) will be carried over into Charts page
