### ISSUE TITLE
Syntax error in 1.8.6

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#161]
In the demo I tried to get chart for the house database. it shows syntax error for the columns which their name has space.
![image](https://user-images.githubusercontent.com/2202483/78521703-c611a180-7798-11ea-948a-dd13112613ac.png)

**Comment by aschonfeld** [comment]
Unfortunately, I don't think there's much that can be done about this issue. Pandas query language doesn't work well with column names that have spaces in them (e.g. "Exterior color")

**Comment by aschonfeld** [comment]
Oh wait, I think I have an idea on how to fix it.

**Comment by aschonfeld** [comment]
v1.8.7
