### ISSUE TITLE
chart map animation errors with aggrigations

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#162]
I tried to get animation for house dataset and cronavirus but i get some errors
my setting are
![image](https://user-images.githubusercontent.com/2202483/78521829-36b8be00-7799-11ea-960b-d98334477d17.png)

**Comment by reza1615** [comment]
I tested it works with no_aggregation 
![image](https://user-images.githubusercontent.com/2202483/78522341-1427a480-779b-11ea-900d-5c3e0709a93d.png)

**Comment by aschonfeld** [comment]
v1.8.7
