### ISSUE TITLE
Fix scale for animation mode in the chart 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#163]
Now when I run an animation it changes the color and value scale so each slid can not be comparable to the another. for example check this animation slide 0 dark red's price is not equal to slide 10's

![image](https://user-images.githubusercontent.com/2202483/78522395-4b965100-779b-11ea-912d-9b44c608f57f.png)

**Comment by reza1615** [comment]
Also it should present the plot in the same window and zoom
for example check this animation
![image](https://user-images.githubusercontent.com/2202483/78522803-8f3d8a80-779c-11ea-99ff-4fab611ccdd2.png)

**Comment by aschonfeld** [comment]
@reza1615 I believe I have a fix for the color range, but for the zoom are you just asking that it not zoom in and out when doing an animation?

**Comment by reza1615** [comment]
Yes, zoom shouldn't change to have smooth animation.

**Comment by aschonfeld** [comment]
v1.8.7
