### ISSUE TITLE
How to set up dtale through ssh tunnel?

### ISSUE THREAD

**Issue by dasturge** [man-group/dtale#166]
I'd like to make use of this package, but my setup is ssh tunneling to the remote jupyter notebook instance, i.e. the server is running on a remote machine behind a firewall and I'm just connecting the port via ssh.  This seems to break dtale though.  I get "HOST's server IP address could not be found." when running dtale.show

It seems it is trying to access the other port from my local web browser rather than on the back end.

**Comment by aschonfeld** [comment]
So you might be able to try dtale.show(df, host=‘localhost’) and then when accessing simply try doing http://[your server’s host]:[port dtale opened]

**Comment by dasturge** [comment]
yes, this does work, it looks like also forwarding port 40000 (dtale's default) and adding host="localhost" gets it to work.  Thanks!

**Comment by aschonfeld** [comment]
Phew!  Glad it worked.  Feel free to  give us a ⭐️😉
