### ISSUE TITLE
heat map

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#168]
1- Based on the https://en.wikipedia.org/wiki/Heat_map the most common colormaps is jet (blue to red)
please set it as 
* Blue (smallest number) 
* Red (biggest number)
![image](https://user-images.githubusercontent.com/2202483/78855891-21d76700-79f3-11ea-85ba-31a13d88668d.png)

Dark jet: https://stackoverflow.com/questions/58288579/how-to-get-a-lighter-jet-colormap-in-matplotlib

2- please increase number of color bucket. for example use 0-255 color to have wider range and more colors. now all cells are red or very near colors (by color option)

**Comment by aschonfeld** [comment]
This is now possible by way of the "Colorscale" dropdown
![image](https://user-images.githubusercontent.com/11547371/80316724-6756ab00-87cd-11ea-8daa-57a2ccec246f.png)

**Comment by aschonfeld** [comment]
@reza1615 is there still an action item left on this?  Or is the colorscale drop-down enough?  I can make the default scale "Jet" if you'd like?

**Comment by reza1615** [comment]
I suggest 
1- to have color scale drop-down
2- to make the default scale "Jet"

**Comment by aschonfeld** [comment]
So i think #1 is already done and i can include #2 in the next release

**Comment by aschonfeld** [comment]
added v1.8.14
