### ISSUE TITLE
lower and upper bounds of outlier have bug

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#169]
In the demo please check price column it shows minus number also it can not filter out 0$
the lower bound has bug
Also for bathrooms is the same

**Comment by reza1615** [comment]
Based on this code
```
s = df['Price']
q1 = s.quantile(0.25)
q3 = s.quantile(0.75)
iqr = q3 - q1
iqr_lower = q1 - 1.5 * iqr
iqr_upper = q3 + 1.5 * iqr
outliers = dict(s[(s < iqr_lower) | (s > iqr_upper)])
```
iqr_lower ==>  413750

now it shows (-164503)
![image](https://user-images.githubusercontent.com/2202483/78858667-1be58400-79fb-11ea-97aa-30e028e5b35d.png)

**Comment by aschonfeld** [comment]
So I dug into this code and for the `Price` column here are the values of the key playerss:
* q1 => 320000
* q3 => 643002
* iqr => 323002
* iqr_lower => -164503
* iqr_upper => 1127505

So i'm not sure what is wrong with the calculation or if you've made some changes to the `Price` but the numbers seem correct to me.

**Comment by reza1615** [comment]
Sorry it was my bad.
I tested another methods their results are also the same as this function.

**Comment by aschonfeld** [comment]
Haha, killin me Rezz 🤣 just glad i wasnt going insane
