### ISSUE TITLE
groups key error for 3d scatter plot and Surface plot

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#172]
When I select groups in 3d scatter plot it shows error. please check below chart
![image](https://user-images.githubusercontent.com/2202483/78857282-f35b8b00-79f6-11ea-9623-68b7b4ad6365.png)

without groups
![image](https://user-images.githubusercontent.com/2202483/78857354-31f14580-79f7-11ea-8378-6205e126e296.png)

**Comment by aschonfeld** [comment]
Ahhh, yes.  Sorry about that I think I intended for the charts which require a Z-axis to no allow for groups.  I can try getting that to work.

**Comment by aschonfeld** [comment]
fixed v1.8.10
