### ISSUE TITLE
highlight back color of outliers/missing values

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#176]
It is interesting to see where are the missing values or where are the outliers.
1- It can be like type high lighting for missing pink and for outliers range of colors 
* From dark blue to light blue for lower bound
* From light red to dark red for upper bound 
2- For missing values
* Null > Yellow
* Empty or space (one space or multi space > Orange

Some time outliers or missing values are in the very below rows so we  need a notifier

3- Render an start to the first of column name when it has outlier
4- Render ! to the first of column name when it has missing value

They can be two separate command

**Comment by aschonfeld** [comment]
Sorry, just trying to make sense of these requirements.  Does this sound right?

1. Outlier Highlighting
  * lower bounds will be blue with the opacity going from lighter to darker as you get closer to the lowest value
  * upper bounds will be red with the opacity going from lighter to darker as you get closer to the highest value
2. Missing values
  * `np.nan` values will be yellow
  * for string columns, empty or consisting entirely of spaces will be orange
3. Put a ⭐ on the front of column names that outliers
4. Prepend an "!" to any column names that have missing values

**Comment by reza1615** [comment]
Yes it is correct

**Comment by aschonfeld** [comment]
Here is the missing highlighting: 
![image](https://user-images.githubusercontent.com/11547371/80212786-23657980-8606-11ea-8ae4-7644dd7f5b68.png)

Hopefully have outlier highlighting done for a release this weekend.

**Comment by reza1615** [comment]
1- Does it support numeric columns? (like lat and long columns which have missing but didn't highlight)?
2- would you please use ❗ instead of !

**Comment by aschonfeld** [comment]
Ok, here's the final product.

**Outliers**
![image](https://user-images.githubusercontent.com/11547371/80287866-f0081500-8701-11ea-92bf-f51dbd125f83.png)
**Missing**
![image](https://user-images.githubusercontent.com/11547371/80287875-00b88b00-8702-11ea-89ff-1456d203ac39.png)

**Comment by reza1615** [comment]
That is great thanks

**Comment by aschonfeld** [comment]
added v1.8.10
