### ISSUE TITLE
Proportioned stacked bar

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#181]
Pleases add Proportioned stacked bar  with the proportion of Y axes like below
![image](https://user-images.githubusercontent.com/2202483/79501059-6f5b6180-7ffb-11ea-8443-13cc932f337b.png)

Code:
```
table=pd.crosstab(df.a,df.b)
table.div(table.sum(1).astype(float), axis=0).plot(kind='bar', stacked=True)

```

**Comment by aschonfeld** [comment]
fixed v1.8.10

**Comment by reza1615** [comment]
Hi I couldn't find this

**Comment by aschonfeld** [comment]
Sorry i meant to post more information on this issue.  The following aggregations are now available:
* Percentage Sum
* Percentage Count

They should give you what you’re looking for
