### ISSUE TITLE
Icons for dtype, missing, outliers

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#188]
For the main menu I suggest these icons for 
* https://commons.wikimedia.org/wiki/File:8-Point-Star_black.svg for outliers
* https://commons.wikimedia.org/wiki/File:Bang.svg for missing
*  [Dtypes.zip](https://github.com/man-group/dtale/files/4536035/Dtypes.zip) for dtypes

![image](https://user-images.githubusercontent.com/2202483/80314737-3f614a80-87c1-11ea-95b9-47dbfe3b0dd3.png)

**Comment by aschonfeld** [comment]
Interesting, I don't know why your icons don't show up.  They appear to on the demo site:
![image](https://user-images.githubusercontent.com/11547371/80315191-01b1f100-87c4-11ea-95d0-55ebe828ca88.png)

**Comment by reza1615** [comment]
http://alphatechadmin.pythonanywhere.com/dtale/main/1

**Comment by aschonfeld** [comment]
Yea they work fine for. Can you try doing a Ctrl + Shift + R?

**Comment by aschonfeld** [comment]
What browser are you using?

**Comment by reza1615** [comment]
Now it works. Thanks.

Google Chrome is up to date
Version 81.0.4044.122 (Official Build) (64-bit)
