### ISSUE TITLE
Percentage Sum and Percentage Count + Animation

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#190]
Percentage Sum and Percentage Count + Animation 
doesn't work

**Comment by aschonfeld** [comment]
Can you please tell me what you are trying to animate on?  I think this might be another scenario where animation should probably be hidden.

**Comment by reza1615** [comment]
You can hide.
Try to see the animation without these agregation. it would be the save as that animation
day1 bar is ...
day2 added new stacked bar
day3 added new stacked bar 
....

**Comment by aschonfeld** [comment]
fixed v1.8.11
