### ISSUE TITLE
Improving outlier filter suggestion

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#191]
If the suggestion range is lower or upper than the actual number doesn't show
for this case it should just show
**Remove outlier filter:(Price > 1127505.0)** because Price doesn't have lower than 0 (except oil :D)

![image](https://user-images.githubusercontent.com/2202483/80315416-78032300-87c5-11ea-9653-b21add6a05a8.png)

**Comment by aschonfeld** [comment]
So do you just want the upper & lower bounds to be cutoff by the actual min & max of the column we're searching outliers for?

**Comment by aschonfeld** [comment]
fixed v1.8.11
