### ISSUE TITLE
ModuleNotFoundError: No module named 'six.moves.collections_abc' when installing dtale in Google Colaba

### ISSUE THREAD

**Issue by jackesselink** [man-group/dtale#197]
After installing dtale on a new notebook in Google Colab using the `!pip install -U dtale `command I try to import the package using `import dtale` but I get the following error message `ModuleNotFoundError: No module named 'six.moves.collections_abc'`. Any workarounds for this for the time being? It works perfectly on my local Anaconda environment btw

**Comment by aschonfeld** [comment]
it's not as simple as running `!pip install -U six` in a cell in your Google Colab notebook?

And if that doesn't work try running the following:
```
!pip uninstall six
!pip install six
```

**Comment by jackesselink** [comment]
You are right. `!pip install -U six` did the trick. thanks for your quick reply.
