### ISSUE TITLE
RecursionError with d = dtale.show(df)

### ISSUE THREAD

**Issue by bastianpeter** [man-group/dtale#202]
Hi,

Your library looks great, but when I follow the example given here https://pypi.org/project/dtale/:

import dtale
import pandas as pd
df = pd.DataFrame([dict(a=1,b=2,c=3)])
# Assigning a reference to a running D-Tale process
d = dtale.show(df)

the last command generates a zillion warnings and errors (which are in the attached file). The last error statement is:
RecursionError: maximum recursion depth exceeded while calling a Python object

I use Python 3.7.3 on mac10.15.4, IDE = Pyzo

Many thanks in advance for your feedback.

Bastian
[errors and warnings.txt](https://github.com/man-group/dtale/files/4707412/errors.and.warnings.txt)

**Comment by aschonfeld** [comment]
@bastianpeter apologies for the error.  Is there any chance you could send me the output of running “pip freeze” on your environment?  Just want to try simulating your environment.  Thanks

**Comment by bastianpeter** [comment]
@aschonfeld 
No worries - thanks for your fast reply.

Please find the output of pip freeze in the attached file.
[pip_freeze.txt](https://github.com/man-group/dtale/files/4707674/pip_freeze.txt)

**Comment by aschonfeld** [comment]
Thanks I'll work on this alter today

**Comment by aschonfeld** [comment]
@bastianpeter I was able to create a python 3.7.3 virtual environment with everything from your pip freeze (with the exception of your local code, `-e git://github.com/ibeltagy/allennlp@718cc43e23eda54df37ba20c3a5cb7c65fae3788#egg=allennlp` and `color==0.1`) but I couldn't reproduce your error.  I'll keep digging...

**Comment by aschonfeld** [comment]
Oh, I just noticed you said you were using the IDE pyzo.  That has to be causing it.  I'll try installing that.

**Comment by aschonfeld** [comment]
@bastianpeter this should be all set now.  Pyzo had an issue with how our logging was setup.  I've pushed a new version, [1.8.15] (https://pypi.org/project/dtale/), which should solve your problem.  Apologies for the issue. 🙏

**Comment by bastianpeter** [comment]
It works - Thank you very much for solving this issue so quickly.

Have a good day
