### ISSUE TITLE
Range selection and resulting DataFrame extraction to develop custom functions and data management applications

### ISSUE THREAD

**Issue by alucab** [man-group/dtale#206]
This application is great.
It would be terrific if we had the possibility to have range selection and resulting DataFrame extraction to allow custom filtering and data mangling.

This would allow the development of several types of data management applications, this component is far more powerful and complete than any other (paid) grid i've seen until now.

As an example in my case, i'm writing a RNA data analysis application where i have to apply custom functions to calculate differences between specific columns after grouping on several dimensions, accumulate results etc..

**Comment by aschonfeld** [comment]
@alucab So I believe at least some of this functionality already exists.  
[Building Columns](https://github.com/man-group/dtale#building-columns)
[Summarize Data (aggregating data)](https://github.com/man-group/dtale#summarize-data)
[Replacements](https://github.com/man-group/dtale#replacements)
[Filtering](https://github.com/man-group/dtale#filtering)
[Custom Filtering](https://github.com/man-group/dtale#custom-filter)

Are you asking for the ability to filter out a slice of data and create a new instance from that so then you can perform operations on it without affecting your original data?  I know that with the "Building Columns" I give you the ability to create a new column so the original column is still intact and then if you don't like the output you have the ability to delete that column (it's an option available by clicking on a column name)

Let me know if there's a specific operation that isn't contained within what I just sent and I'll be happy to add it! 😃 

I know there are some other things I wanted to add to the "Build Column" feature for things like:
* group adjusting data (mean adjust)
* winsorize (although I think something like this may exist in the "Replacements" feature)

Thanks for the feedback!

**Comment by alucab** [comment]
@aschonfeld thanks for the swift answer and many cheers for your profile picture!
I will study your feedback and come back to you
