### ISSUE TITLE
conda-forge release not updated

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#207]
It seems that there has been some problem with the conda-forge release, since the last version available is 1.8.16:

https://anaconda.org/conda-forge/dtale

**Comment by aschonfeld** [comment]
@juanfcocontreras Sorry for this again, I keep forgetting that when I add a dependency the conda recipe needs to be updated as well.  🤦 

Should be all set now.

**Comment by juanfcocontreras** [comment]
Sorry to bother you with this again, but I think it's happening one more time.

Could you check?

Thank you very much.

**Comment by juanfcocontreras** [comment]
Great! Sorry for the inconvenience.

Thanks a lot!

**Comment by aschonfeld** [comment]
@juanfcocontreras looks like my recipe for the new dependency was [merged](https://github.com/conda-forge/staged-recipes/pull/12028) but i'm not sure how long it will take before its available on conda.  Once it is I can move forward with the release of v1.8.19

**Comment by aschonfeld** [comment]
@juanfcocontreras v1.8.19 should be available now, let me know of any issues.  Sorry for the wait

**Comment by juanfcocontreras** [comment]
Updated! Thank you so much!
