### ISSUE TITLE
Code export doesnt work on google colab

### ISSUE THREAD

**Issue by jainayush007** [man-group/dtale#211]
Hi,

I am a fist time user. I created some plots on colab using dtale and upon clicking"code export" a new window popped up with the below error -

'''
This site can’t be reached693378aef512.ngrok.iodtale’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN
'''

I am not behind any firewall or vpn.

Requesting help.

Thanks

**Comment by aschonfeld** [comment]
I was able to use the code export feature on the grid, but when I tried to use the code export from a chart I hit the issue you mentioned.  It looks like the URL that is getting created in the popup is missing a `/`.  It should be using `693378aef512.ngrok.io/dtale/code-popup`

I'll work on a fix for this tonight.  I also seem to be running into an issue with how many requests NGROK will allow you do within a 60 second window.  I might try looking into another way to access flask processes from google colab so you won't hit that issue.

Sorry for the inconvenience @jainayush007

**Comment by jainayush007** [comment]
I noticed the difference in url too. A fix tonight will be awesome!

**Comment by aschonfeld** [comment]
Fix for this issue has been released in v1.9.0 I'm still working on the `USE_COLAB` functionality.  For a preview I'm doing something like this in my Colab cell:
```
import pandas as pd
import dtale
from google.colab.output import eval_js

d = dtale.show(pd.DataFrame([1,2,3]), ignore_duplicate=True)
print(eval_js('google.colab.kernel.proxyPort(40000, {"cache": false})') + 'dtale/main/1')
```

I'll pick it back up in the morning...

**Comment by jainayush007** [comment]
Thanks @aschonfeld

**Comment by aschonfeld** [comment]
@jainayush007 The `USE_COLAB` functionality should finally work in v1.9.1. Just beware the inital page load is a little slow. For some reason colab's proxy takes a while to load the JS.
