### ISSUE TITLE
Enhancement Request -  Support Koalas dataframes

### ISSUE THREAD

**Issue by jainayush007** [man-group/dtale#213]
Hi,

This is a request to support Koalas dataframes as well. Since Koalas dataframes work very similar to panadas, hoping this should be easily possible.

Koalas library - 
https://github.com/databricks/koalas

**Comment by aschonfeld** [comment]
I've started digging into this and since pyspark is a pretty heavyweight package I don't want to make it a dependency of D-Tale.  I will try adding a type check for `databricks.koalas.frame.DataFrame` and just call `to_pandas()` on the object.   Should work fine :)

**Comment by jainayush007** [comment]
So, Pandas have memory constraints which why we use Pyspark and correspondingly Koalas to be able to quickly migrate a pandas script to Pyspark engine. to_pandas() may not be a good option in such scenarios.

**Comment by aschonfeld** [comment]
So I am about to add the simple (brute force solution) of converting the data to a pandas dataframe using `to_pandas()`.  I just tried passing a koalas dataframe into D-Tale directly and very quickly I ran into issues because not all of pandas functionality is available.  For example:
```
Traceback (most recent call last):
  File "/Users/andrewschonfeld/dev/git/dtale/dtale/views.py", line 75, in _handle_exceptions
    return func(*args, **kwargs)
  File "/Users/andrewschonfeld/dev/git/dtale/dtale/views.py", line 1692, in get_data
    sub_df = f.format_dicts(sub_df.itertuples())
  File "/Users/andrewschonfeld/.pyenv/versions/dtale_38-0/lib/python3.8/site-packages/databricks/koalas/missing/__init__.py", line 22, in unsupported_function
    raise PandasNotImplementedError(
databricks.koalas.exceptions.PandasNotImplementedError: The method `pd.DataFrame.itertuples()` is not implemented yet.
```

So I think for not the best approach is the brute force and any filtering to lower the size constraints will have to be performed by the user ahead of time before passing the dataframe into D-Tale.

**Comment by jainayush007** [comment]
ok. so even if I pass a Koalas df into dtale, it will ALWAYS convert into pandas and load the dataframe. I think that should be fine. Do we have dask support? I haven't used it personally, but maybe a route given koalas isn't a possibility.

**Comment by aschonfeld** [comment]
Umm, not sure I understand what you mean?  Do you mean some information about what the original data structure was that housed the data?  Or do you just mean assigning a name to your D-Tale session?  If its the second then thats possible by using the `name` parameter.  For example:
`dtale.show(df, name='foo')`

Then you can access it by `http://hostname:port/dtale/main/foo` or `http://hostname:port/dtale/main/1`

**Comment by jainayush007** [comment]
I mean, internally, dtale would be generating executing pandas code based on the UI operations a user performs. To be able to do that, dtale would use/create dataframes. What would be the names of those dataframes and can it override an existing dataframe which I may have already used on my script?

**Comment by aschonfeld** [comment]
ohhh, got it.  So if you store your D-Tale session in a local variable then you can access the current underlying data (including any modifications you've made from the UI):
```
d = dtale.show(df)
d.data  # this is the underlying data
```

You can also make modifications to the underlying data of your session and it should persist to the frontend if you refresh your browser.

**Comment by jainayush007** [comment]
Wow! That's great. I used Rattle library in R in the past and it made my life a lot easier. I was always looking for something similar in python and this is it! I will be a regular user, so expect many more coming from me!

**Comment by aschonfeld** [comment]
Sounds great!  If you haven't done so already, toss your ⭐  on the repo.  It means a lot to me 🙏

**Comment by aschonfeld** [comment]
added in v1.9.1

**Comment by jainayush007** [comment]
Am a follower, user, and I have offcourse star-red it. :-)
