### ISSUE TITLE
Importing dtale in Google Colab generating a python six error

### ISSUE THREAD

**Issue by chokosabe** [man-group/dtale#223]
import dtale (in Colab, version 1.9.2 of dtale)

results in the following error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-17e2711d7b82> in <module>()
----> 1 import dtale

2 frames
/usr/local/lib/python3.6/dist-packages/dtale/global_state.py in <module>()
      2 
      3 from six import PY3
----> 4 from six.moves.collections_abc import MutableMapping
      5 
      6 DATA = {}

ModuleNotFoundError: No module named 'six.moves.collections_abc'

**Comment by aschonfeld** [comment]
@chokosabe I'm sorry about that.  I've noticed that as well.  I think it might be something to do with the version of six that comes pre-packaged with Google Colab.

So the way I got around it was by running the following:
```
!pip install -U dtale
!pip install -U six
```
Once that was complete I restarted my runtime and I was able to run `import dtale` with no issue.

I'll look into getting that initial six error removed.  Sorry for the inconvenience.

**Comment by chokosabe** [comment]
Many thanks @aschofield. That worked. Hope someone else finds this useful. 

Much appreciated.

**Comment by aschonfeld** [comment]
@chokosabe feel free to ⭐ the repo if this package helps you out 🙏 and if not I'll be happy to add anything you need 🙂

**Comment by aschonfeld** [comment]
@chokosabe Ok so the issue is that Google Colab requires six==1.12.0 and six's remapping of the collections package was not added until 1.13.0.  I could force the version required by D-Tale to be at least 1.13.0, but I'll take the more democratic approach and update the code to handle the remapping manually if six < 1.13.0.  This way we can respect the versioning of Google Colab

**Comment by aschonfeld** [comment]
@chokosabe just released v1.10.0 which should fix this issue

**Comment by chokosabe** [comment]
@aschonfeld many thanks for this.
