### ISSUE TITLE
Create Bins column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#227]
Hi, It would be nice to have a tool to create a bin column of float columns.
for example:
Column_A
0
11
200
5
60

**Code snippet**
bin_num=5
bin_labels=range(5)
df['A']=pd.cut(df.A,bins = bin_num,labels=bin_labels)

**Suggestions for Bin window:**
To help the user to better decide:
1- The bin window shows histogram chart
2- min, max, and the average value

**Get**
1-get number of bins 
          Unique_items= len(df.A.unique())
          default_bin_num= min (Unique_items/10, 10)
2-get bin_labels as a list of names in an input box like ['borons', 'silver', 'gold'] or by default range of numbers
          default_bin_lable= range(bin_num)

**Comment by aschonfeld** [comment]
So this bins functionality already exists: https://github.com/man-group/dtale#building-columns

* You can already open the histogram in a separate window using the "Describe" popup now, but I can add a link in the "Bins" column builder which will open a histogram popup in another window.
* The "Describe" popup also shows min, max & average

I don't really understand what you asked for the *Get* section.  
1) the current bin column builder allows you to specify a `bin_num` value
2) there is also an input for labels which is just a comma-separated string which must have the same number of values as the number of bins.  If not specified it just defaults to `range(bin_num)`

I am closing this and will create a ticket for adding a histogram link
