### ISSUE TITLE
could not locate runnable browser

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#228]
I want to use dtale for a docker container  and it shows this error:
![image](https://user-images.githubusercontent.com/2202483/88480369-92af7a00-cf23-11ea-97ac-ecce616229bb.png)

**Comment by aschonfeld** [comment]
the `open_browser()` function is kind of experimental because it assumes some user setup exists.  If your machine has the `BROWSER` environment variable populated it should work.  Here's the documentation on the package: https://docs.python.org/2/library/webbrowser.html

So I'm thinking you'll have to update the docker image to include a version of whatever browser you like or a mount to a local installation of a browser and then add a `BROWSER` environment variable to point at that executable.

**Comment by reza1615** [comment]
@aschonfeld do you know the command that I can use/mount the local browser? Now I am using the below code to run the docker.
`docker run --name docker_name --restart unless-stopped -d -v ~/shared/:/home/shared/  -p 2000:8888 the_image start.sh jupyter lab`

**Comment by aschonfeld** [comment]
This [post](https://stackoverflow.com/questions/17736215/universal-path-to-chrome-exe) gives information about the different locations of chrome.  So once you find that i think in including that as a [volume](https://stackoverflow.com/a/40905828/12616360) in your docker-compose will do the trick

If not you could alway download firefox or chrome as part of your Dockerfile and use that as your local browser

**Comment by aschonfeld** [comment]
I'm having a lot of trouble with this one.  I've opened a [stackoverflow](https://stackoverflow.com/questions/64997127/how-can-i-use-webbrowser-get-within-a-docker-container) for it. We'll see what happens.

**Comment by reza1615** [comment]
I installed Chrome with the below code and it doesn't show the error. Now I have a firewall problem :)

```
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update 
sudo apt-get install google-chrome-stable
```

**Comment by reza1615** [comment]
Also with webbrowser I have this error
![image](https://user-images.githubusercontent.com/2202483/100231541-29516f00-2ef5-11eb-93eb-21dcffdd62bc.png)

**Comment by aschonfeld** [comment]
You already showed me this error in a previous post, but the one before that how did you start your container?  I recently realized on Macs `--network host` doesn't work.  So you would have to do `-p 40000:40000` although that would only allow you to view port 40000.  And I'd also try change your host from the one docker outputs to `0.0.0.0`

**Comment by reza1615** [comment]
> You already showed me this error in a previous post, but the one before that how did you start your container? I recently realized on Macs `--network host` doesn't work. So you would have to do `-p 40000:40000` although that would only allow you to view port 40000. And I'd also try change your host from the one docker outputs to `0.0.0.0`
> 
> Could you also share your Dockerfile with me? I couldn't get those chrome commands to work inside mine.

I started my docker with the below command. (I have to use 8888 as a port because of our IT policy)
`docker run --name docker_name --restart unless-stopped -d -v ~/shared/:/home/shared/ -p 2000:8888 the_image start.sh jupyter lab`

**Comment by aschonfeld** [comment]
Try updating your command to:
docker run --name docker_name --restart unless-stopped -d -v ~/shared/:/home/shared/ -p 2000:8888 -p 40000:40000 the_image start.sh jupyter lab

**Comment by reza1615** [comment]
Thank you for your reply. Finally, I found the answer.
1- doesn't need to have a browser on the docker
2-Just when we run the docker we should have -p 40000:40000 in the run command
3-The dtale address is http://Server_IP:40000/dtale/main/1 for example http://222.167.89.0:40000/dtale/main/1

My suggestions:
1-Instead of http://4ff03cc2ca15:40000/ dtale shows the right IP which the server IP
2-to have an option to change default 40000 to another number. Now we have a server with multiple users and multiple docker containers. if one of them uses dtale the rest can not. because port 40000 will reserve for the first user and docker doesn't allow to run the container on the same port

**Comment by aschonfeld** [comment]
Huzzah!
1) I definitely need to look into adding some flag that checks if D-Tale is being called from a docker container and return the IP address in that case.  For now you can specify the hostname by doing this: `dtale.show(df, host='222.167.89.0')`
2) this is already possible by setting the environment variables [DTALE_MIN_PORT & DTALE_MAX_PORT](https://github.com/man-group/dtale#startup-behavior) right now their defaults are 40000 & 49000.  So by setting those it will allow you to control the range used by D-Tale

**Comment by reza1615** [comment]
> 1. dtale.show(df, host='222.167.89.0')
It doesn't work. there is two problem
1- with out executing `IP addr` outside of the docker container I can not understand what is the server IP.
2- when I know the IP `dtale.show(df, host='The_IP') `and `dtale.show(df) ` doesn't have a difference. If I could assign different IP with the host var, It could be helpful
2- where can I set the `environment variables` for the min and max range

**Comment by aschonfeld** [comment]
* Using the `host` parameter essentially just controls what host is used when building URLs you can click on.  It doesn't actually affect any setup with D-Tale.  So it still doesn't address the fact that you have to do some digging to figure out the IP of your docker process.
* The environment variables can either be setup in your Dockerfile or you can specify them on the command line using:
`docker run --name docker_name --restart unless-stopped -d -v ~/shared/:/home/shared/ -p 2000:8888 -p 40000:40000 -e DTALE_MIN_PORT=40000 -e DTALE_MAX_PORT=49000 -the_image start.sh jupyter lab`

**Comment by aschonfeld** [comment]
Ok, just saw your `1-3` comment so I guess the code is probably testing the host to see if it actually exists to protect you from entering a bad one and if it can't connect it will go back to the logic trying to find the hostname.

**Comment by reza1615** [comment]
To have the server IP inside the docker. The below solution works for me

- adding `-e "DOCKER_HOST=$(hostname -I | cut -d' ' -f1)"` to docker run command. like below code
`docker run  -e "DOCKER_HOST=$(hostname -I | cut -d' ' -f1)" --name test_docker --restart unless-stopped -d -v ~/shared/:/home/jovyan/shared/  -p 4000:8888 -p 40000:40000 the_imagev start.sh jupyter lab`
- get environment var inside the docker `echo $DOCKER_HOST`

In my opinion in the documentation, we can mention. to have the best functionality for the docker please add the below code to your docker run. after that inside detail code, you can check the environmental var to print the correct URL.

`-e "DOCKER_HOST=$(hostname -I | cut -d' ' -f1)"  -p 40000:40000`

**Comment by aschonfeld** [comment]
@reza1615 `"DOCKER_HOST=$(hostname -I | cut -d' ' -f1)"` fails for me on my Mac.  It doesn't recognize the `-I` parameter. I switched it to `"DOCKER_HOST=$(hostname | cut -d' ' -f1)"` but that did not solve my issue where it was still returning the pid of the docker container as the hostname.

Also, I was able to run `dtale.show(df, host='localhost')` and it correctly returned `http://localhost:40000/dtale/main/1` to me.  I think you may have still had an instance running from before and so it defaulted to the old hostname stored in `dtale.app.ACTIVE_HOST`.  If you had run `dtale.get_instance('1').kill()` before calling `dtale.show(df, host='localhost')` it probably would have worked.

I did some more digging and the command that worked for me was by adding the following:
```-h `hostname`  -p 40000:40000```

Let me know if this works for you. Thanks

**Comment by aschonfeld** [comment]
added to documentation
