### ISSUE TITLE
Pivot operation allows selection of single column

### ISSUE THREAD

**Issue by mswastik** [man-group/dtale#237]
Pivot operation in summarize data allow selection of single row and column even though pandas pivot_table function allows selection of multiple rows and column.
Why not migrate from pandas pivot function to pivot_table function?

**Comment by aschonfeld** [comment]
@mswastik I can't remember a specific reason for why I'm only using `pivot_table` when the user selects an aggregation function.  I'll gladly update the rows & columns to be multi-selects.  I think I'll have some work to do around constructing the column names when multiple columns are selected, but I don't think thats too big a deal.

**Comment by mswastik** [comment]
Thanks, constructing multiple column names is already there in JavaScript when using group by operation, you just need to extend it for pivot operation also and replace `pivot` command in python with `pivot_table`.

**Comment by reza1615** [comment]
@aschonfeld Also when there is duplicate column or index in the pivot, pandas shows error but pivot_table has aggregations to select just one of them.
In my opinion pivot_table + aggregations is good enhancement

**Comment by aschonfeld** [comment]
@mswastik I've just released version 1.13.0 which includes this change.  Let me know how it goes 🤞

**Comment by mswastik** [comment]
Yes its working great, thanks a lot!
