### ISSUE TITLE
Force convert to float

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#240]
In the data type conversion, it would be helpful to have Force Convert to Float.
example:
``` python
import pandas as pd
import numpy as np
numbers=[1]
numbers.append('00')
numbers.append('1.05')
numbers.append(' ')  # one space
numbers.append('   ')# multi spaces
numbers.append('')   # empty
numbers.append('02')
numbers.append('..')
numbers.append('none')
numbers.append('nan')
df=pd.DataFrame({'col1': numbers})

```
![image](https://user-images.githubusercontent.com/2202483/89731172-f56c3f80-da12-11ea-9336-12a494c36a55.png)

**Comment by reza1615** [comment]
Code snippet for the Force convert to float. this code also prints replacement log. which is helpful to show it in the UI
Also it can handle:
* when whole column is string and can not convert to float
* when the column is already float 
* when there is unknown errors to convert to float
* when replacing  cell values to np.nan is not possible it will send the cleaner df with a False status. it means still the column is not float but cleaner than before. 
* print replaced strings with np.nan

``` python
import re
import numpy as np
def force_convert_to_float(df, column):
    if df[column].dtypes !='O':
        print(f"Column \"{column}\" dtypes = {df[column].dtypes}")
        print("doesn't need to use force convert")
        return df, True
    original_df=df.copy()
    df[column]=df[column].replace('',np.nan)
    count=0
    while True:
        if count>len(df) + 1 :
            print("couldn't replace whole missing with np.nan still there are some other values which are not numbers")
            return df,False # doesn't go to the infinit loop
        else:
            count+=1
        try:
            df[column]=df[column].astype(float)
            break
        except Exception as error:
            error=str(error)
            #print(error)
            if 'could not convert string to float' in error:
                matches = re.findall(r"\: \'(.*?)\'", error)
                if not matches:
                    regex_pat = re.compile(r'\s+')
                    df[column]=df[column].replace(regex_pat,np.nan)
                    print('replace >>>empty<<<')
                    continue
                error=matches[0]
                print('replace >>>'+error+'<<<')
                df[column]=df[column].replace(error,np.nan)
            else:
                print("Force  Convert doesn't work properly; there is another error")
                return original_df, False
    if len(df[df[column].isnull()])==len(df):
        print(f"Column {column} has text values and can not convert to float")
        return original_df,False
    return df,True

df, status=force_convert_to_float(df, 'col1')
```
Before the code
![image](https://user-images.githubusercontent.com/2202483/89731789-cad0b580-da17-11ea-9dfb-d98cf4ae0364.png)

After the code
![image](https://user-images.githubusercontent.com/2202483/89731766-a248bb80-da17-11ea-84da-9bd636a3fe94.png)
![image](https://user-images.githubusercontent.com/2202483/89731226-4f6d0500-da13-11ea-9d3b-82cc226aef7c.png)

**Comment by reza1615** [comment]
As a automatically reprocessing, it will be nice to run it on the whole mix-integer columns.

**Comment by aschonfeld** [comment]
So I can definitely hook this up, but I've been digging into pandas and it looks like it is virtually impossible to build an integer column with `NaN` values so it will have to convert them to floats.

Also, how would you treat booleans in this scenario?

`[True, True, '', False] => [True, True, nan, False]`
or 
`[True, True, '', False] => [True, True, False, False]`

**Comment by aschonfeld** [comment]
Also, just wanted to let you know that your code can be condensed into one simple function that already exists `pd.to_numeric(pd.Series([1, '00', 1.05, None, '', '', '02', '...', 'none', 'nan']), errors='coerce')` 😄

**Comment by reza1615** [comment]
> Also, how would you treat booleans in this scenario?

> [True, True, '', False] => [True, True, nan, False]
> or
> [True, True, '', False] => [True, True, False, False]

![image](https://user-images.githubusercontent.com/2202483/89858884-b1418200-db6d-11ea-8869-8e339994befc.png)

**Comment by aschonfeld** [comment]
@reza1615 Sorry I think I wasn't clear.  I'm going to offer an option to convert "mixed" columns to booleans and I was wondering how you'd like the `''` value treated in the example above.  Should it equate to `nan` or `False`.  Currently, it will default to `False` but I can try baking more logic into the code to make it `nan`

**Comment by reza1615** [comment]
it should be NaN. usualy when we dont have data, just leave it empty. if it
convert data to False they will take account in avrage and total valid data
count.
here ' ' is missing data

**Comment by aschonfeld** [comment]
@reza1615 here's what I've put together: https://youtu.be/yACTe22vSUw

This will do the following:
* mixed-integer conversions to floats
* mixed conversions to booleans
* allow you to do "inplace" type conversions
* allow you to apply an "inplace" type conversion to all other columns of the same type
* mixed column display in "Describe"
   * shows the counts of each type in the column
   * shows the top-100 unique values for each type
* I've also updated some of the labels and added "Total Rows" to the describe statistics

**Comment by reza1615** [comment]
@aschonfeld That is great. Nice enhancement 
I suggest to have also these modifications:
![image](https://user-images.githubusercontent.com/2202483/90037519-4ccc1300-dc92-11ea-9c04-9f76ba3d553f.png)

**Comment by aschonfeld** [comment]
Ahh, good idea! I’ll add that

**Comment by aschonfeld** [comment]
added in v1.13.0
