### ISSUE TITLE
Total count: count logic in description of numeric type and object type is different

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#241]
count in description of Float, Integer columns shows only the numeric values and doesn't take account the missing values
( count != total count)  but for the object type (string type) count == total count (missing + existing values) 

In my opinion, for the numeric column description, we should have 
* Total Count
    * Count
    * Missing count

Also for the Missing_pct it would be helpful to have % sign. like:
* Missing_pct: 66.67 %

![image](https://user-images.githubusercontent.com/2202483/89732274-8e9f5400-da1b-11ea-8a23-13901cc58b86.png)

**Comment by aschonfeld** [comment]
Good catch, i think this is just part of how pandas defines “count”.  I can update the wording to “count non-nan” and then add an entry for “entries” (overall count).

It should be noted that “entries” will be the same for all columns.

**Comment by aschonfeld** [comment]
added in v1.13.0
