### ISSUE TITLE
Suggestions for  Build column and Type conversion

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#242]
I have these suggestions for the Build column and  type conversion tab
* have suggested name  (for example for "Price" > "Price_Bin"). only random tab isn't based on a column which can be random_01
* Type convertion isn't a build column and should be in a separate window
* For type conversion please make Inplace as default
* It would be nice to have access to type convertion from pop up window in the main screen (in below)
![image](https://user-images.githubusercontent.com/2202483/90042108-3a54d800-dc98-11ea-91b4-5f15b7adcfcb.png)

**Comment by aschonfeld** [comment]
Here's what I got for this (still working on a way to make the names change as you change column builder) https://youtu.be/qRPHjEnW1Pk

**Comment by aschonfeld** [comment]
Added in v1.14.0
