### ISSUE TITLE
Treemap chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#244]
Please add Treemap chart
https://jingwen-z.github.io/data-viz-with-matplotlib-series5-treemap/#:~:text=volume%20=%20[%201783%20,%201221%20,%201097%20,%20839

**Comment by aschonfeld** [comment]
@reza1615 here's a [demo](https://youtu.be/yDEATkhn98E) of the treemap functionality I have right now

**Comment by aschonfeld** [comment]
Added in v1.15.2
