### ISSUE TITLE
Describe shows proper values, but repeats 'Total Rows:' heading instead of proper headings

### ISSUE THREAD

**Issue by accidentalfeature** [man-group/dtale#252]
Good day!
Just came across D-Tale yesterday thanks to a KDnuggets article. What a ridiculously awesome work of art you have here! Super slick and what a beautiful way to supercharge exploratory analysis!

Hoping I'm missing something obvious here...
When I leverage the describe functionality, I see the proper values for counts, min, max, etc. 
But I see the heading of 'Total Rows:' repeated for all headings instead of their proper names.  

Screenshot of a super simple dataframe to provide an example:

![image](https://user-images.githubusercontent.com/69994078/90835454-e6866680-e309-11ea-98dd-40a5521c2583.png)

Screenshot of what I see when I run a describe on the age column:

![image](https://user-images.githubusercontent.com/69994078/90835501-0027ae00-e30a-11ea-8478-1ca6cb905fd7.png)

I've tried updating all packages via Anaconda, then reinstalling dtale.
I've tried various datasets from work, and a sample one from a course I recently took:

`telco = pd.read_csv('https://raw.githubusercontent.com/datacamp/machine-learning-with-scikit-learn-live-training/master/data/telco_churn.csv', index_col = "Unnamed: 0")`

I tried dtale in Google Colab, using the sample telco dataset above, and had the same issue where every column in the describe report shows "Total Rows:". 

I've tried chrome & edge on a work pc, as well as personal. Same issue.

Hopefully I'm missing something obvious, would greatly appreciate any suggestions to try as it looks like everything is working like a charm for others.

Thank you! Incredible product again!

**Comment by aschonfeld** [comment]
Oh boy, i’m sorry about that.  If you revert back to 1.13.0 it should go away.  I recently pushed a change last night and somehow i missed that.  I’ll push a hotfix soon and let you know when its out there

**Comment by aschonfeld** [comment]
@accidentalfeature Just released v1.14.1 which should fix this, let me know how it goes 🤞
