### ISSUE TITLE
Option to disable actions

### ISSUE THREAD

**Issue by rahulvrane** [man-group/dtale#254]
Hello

Thanks for the package! It is very helpful from an end user point. I had a qs however - are we able to turn off buttons such as 'Shutdown' etc? If yes, how can we do it?

Cheers

**Comment by aschonfeld** [comment]
@rahulvrane Glad to hear D-Tale is helping 👍 As for your question about hiding the "Shutdown" button.  There is a way but it's not easily accessible at the moment.  What I can do is make it a global variable or an environment variable if that would help.  For example:
```
import dtale

dtale.HIDE_SHUTDOWN = True

dtale.show(df)
```

That would be how to hide the shutdown button.  Currently I have a flag for turning off cell editing `dtale.ALLOW_CELL_EDITS = False`.

The other option I can work on providing is through the use of an environment variable.  Say from your command line you ran `export DTALE_HIDE_SHUTDOWN=True`, that would turn off the shutdown button on any D-Tale instance opened in that command line terminal.

Let me know if those sound like good options?  Thanks

**Comment by rahulvrane** [comment]
@aschonfeld thanks for your response! The idea of having a global variable is probably more usable.
Also if multiple people are accessing it at the same time- does that change anything or need any special setup if edits and shut-downs are turned off?

Thanks again!

**Comment by aschonfeld** [comment]
@rahulvrane if you started sessions with these:
* `dtale.HIDE_SHUTDOWN = True` or `dtale.show(df, hide_shutdown=True)`
* `dtale.ALLOW_CELL_EDITS = False` or `dtale.show(df, allow_cell_edits=False)`

Then any one accessing those sessions will have those features turned off.  You can turn it back on by taking the data_id (the number on the end of your URL) of the session and doing:
`dtale.global_state.get_settings(data_id)['hide_shutdown' or 'allow_cell_edits'] = True or False`

**Comment by aschonfeld** [comment]
Added in v1.15.2

**Comment by sk1802** [comment]
@aschonfeld Is there another way to hide the shutdown button in jupyter notebook because the above mentioned way not working for me.

**Comment by aschonfeld** [comment]
@sk1802 sorry looks like there is a bug where it's not picking up whether `hide_shutdown` or `allow_cell_edits` has been set on an individual instance.  So the way around that would be to do `dtale.global_state.get_app_settings()['hide_shutdown'] = True`

I'll work on fixing the issue in the meantime

**Comment by aschonfeld** [comment]
@sk1802 just released v2.6.0 with these updates.  Let me know if you have any other issues.  Also, if you haven't done so already, please toss your ⭐ on the repo.  Thanks 🙏

**Comment by sk1802** [comment]
Thank you for the update @aschonfeld it really helped ☺️. The repo is starred.(i still need to work using dtale 🔥 so why not ).
