### ISSUE TITLE
Feature Request: Different aggregation functions for different y-columns

### ISSUE THREAD

**Issue by arashaneh** [man-group/dtale#255]
In many use cases where the measure columns have different types of data, different aggregation functions would be needed for them. for example, while sum would make sense for quantities, the average is more sensible aggregation function for ratios.
Is there any plan to add this feature that the aggregation function should be defined separately for each y column?
At least would you provide some thoughts on what would be the best way to add this feature to dtale?
Thanks,
Arash

**Comment by aschonfeld** [comment]
So, unfortunately this would be a large change to how the "Charts" UI works.  Not impossible, but a lot of work.  That being said I think there might be a different way to handle it using the "Build column" popup.

So you can go to "Build Column" from the main-menu button in the upper lefthand corner of the grid.  Then from there choose the "Transform" column type.  This will allow you to build aggregations based on any grouping (and no grouping at all if you'd like).  Then from there once you've built your aggregations you can go to the "Charts" popup and then select you columns that you build using the "Transform" column type and just choose the "Mean" aggregation.

The "Transform" function builds your aggregation but then transmits it back to the original dataframe so you'll be left with a lot of duplicate values.  But once you use the "Mean" function it will reduce the duplicates down to the single value and you chart should give you what you want.

A lot of work I know, but it should give you immediate results.  Let me know how it goes and thanks for using D-Tale 🙏

**Comment by aschonfeld** [comment]
@arashaneh Sorry for the wait, this was a much more complex problem to solve than I thought.  Couple notes:
* this only really affects line, bar, scatter & pie charts
* I still need to work on being able to intermingle line & bar charts

Here's a demo:
https://user-images.githubusercontent.com/11547371/112251299-5eff2e00-8c31-11eb-82b7-efb18bb302b1.mov

**Comment by aschonfeld** [comment]
@arashaneh just released version 1.41.0 (will be on conda-forge shortly as well) I'll keep working on adding the ability to mix line & bar charts. Please take a sec and toss your ⭐  on the repo.  Thanks for your help 🙏

**Comment by arashaneh** [comment]
Thanks, Andrew! sure certainly.
