### ISSUE TITLE
How to embed query in flask application

### ISSUE THREAD

**Issue by aagudeloz** [man-group/dtale#256]
Hi, I am developing a flask application and I would like to embed a pivot table on its pages on the data selected by the user.
Could you give me a light on how to do it? I've tried a lot and the only thing I can do is redirect to a link (http://127.0.0.1:40000/dtale/main/[1,2,3]). I know that Dtale creates a flask server to display the table.
Dtale is a wonderful tool. Thank you

**Comment by aschonfeld** [comment]
So here is a quick example of how to do this, but once again this will create a new flask process in the background:
```
import dtale
import pandas as pd
import time

from flask import Flask, redirect

app = Flask(__name__)


@app.route('/')
def hello_world():
    if not len(dtale.global_state.get_data()):
        dtale.show(pd.DataFrame([1, 2, 3, 4, 5]))
    return 'Hello, World!'


@app.route('/create-dtale')
def create_dtale():
    if not len(dtale.global_state.get_data()):
        d = dtale.show(pd.DataFrame([1, 2, 3, 4, 5]))
        retries = 0
        while not d.is_up() and retries < 10:
            time.sleep(0.01)
            retries += 1

    return redirect(dtale.get_instance('1')._main_url, code=302)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
```

There is another way you can override D-Tale which should stop it from creating a new Flask process for each piece of data:
```
from flask import redirect

from dtale.app import DtaleFlask
from dtale.views import startup

class MyDtaleFlask(DtaleFlask):
    def __init__(self, import_name, *args, **kwargs):
        super(MyDtaleFlask, self).__init__(reaper_on=False, url='', *args, **kwargs)

app = MyDtaleFlask(__name__)

@app.route("/view-pivot")
def view_pivot():
    # TODO: add your logic to build your pivoted data
    pivot_instance = startup("", data=pivot_df, ignore_duplicate=True)

    return redirect(dtale.get_instance(pivot_instance._data_id)._main_url, code=302)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
```

The thing to remember about the second example is that you'll need to remember to cleanup your data or else the size of your app will grow over time.  Here's an example of how to cleanup your data:
```
from dtale.global_state import cleanup

cleanup()
```

If you know the exact piece of data you want to clear (the data_id) from my earlier example you can also call `cleanup(data_id)`

Hope this helps and please toss your ⭐ on the repo if you haven't already :)

**Comment by aagudeloz** [comment]
Hi @aschonfeld , thank you for your reply. My app handles historical information for a Colombia University and we needed its tool to perform analysis. I have tried it in Jupyter Notebook and it has no problems, but our goal is that several users without python knowledge can analyze this data. My code that I had implemented is:

```
class DtaleView (BaseView):

    @expose ('/ dtale /')
    @has_access
    def sue_reporte (self):
        # Read data from view
        df = pd.read_sql (sqlquery, con = db.session.bind)

        dtale.show (sue_df, host = 'localhost', port = 8081, subprocess = False)

        return redirect ('http: // localhost: 8081', code = 302)
```
I thought the instruction was sending me the link but the call has an error.

Based on your code, I used the second version but I also had problems instantiating the object: MyDtaleFlask .

Anyway, thank you very much for your help. I'll be checking more. The framework I use is flask-appbuilder.

Another question, does it handle any file that can be translated to show the information in Spanish?

Thanks a lot.

**Comment by aschonfeld** [comment]
@aagudeloz  You should be fine with spanish characters but let me know if you hit issues because it should be an easy fix.  I had to do something similar for chinese characters but it may have been for a different app.
