### ISSUE TITLE
what is the best way to setup dtale project to local I mean using Docker or using virtualenv

### ISSUE THREAD

**Issue by ecakashjadhav** [man-group/dtale#257]
Hi sir I will develop one project using dtale. please suggest me to how I will setup the project locally. because I also need for debugging or some changes on it. eg- remove some features or adding another.
    Please suggest to me. :)

**Comment by aschonfeld** [comment]
@ecakashjadhav Personally, I develop using virtual environments on my mac using [pyenv](https://realpython.com/intro-to-pyenv/)

So if you go that route you can create a new virtual environment, fork the D-Tale repo & clone it, then run `python setup.py develop`.  This should install all the dependencies for you.

That being said there is a `docker-compose.yml` in the D-Tale repo that you can build off if you want to go the Docker route.

Now for debugging I currently use PyCharm and with a [custom data loader](https://github.com/man-group/dtale#custom-command-line-loaders) in debug mode.

Here's an example of a load of some COVID data:
```
from dtale.cli.loaders.csv_loader import loader_func as load_csv

'''
  IMPORTANT!!! This global variable is required for building any customized CLI loader.
  When find loaders on startup it will search for any modules containing the global variable LOADER_KEY.
'''
LOADER_KEY = 'covid-data'
LOADER_PROPS = []


# IMPORTANT!!! This function is required for building any customized CLI loader.
def find_loader(kwargs):
    if kwargs.get('covid_data', False):
        def _testdata_loader():

            data = load_csv(
                path='https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv',
                parse_dates=['date']
            )
            codes = load_csv(
                path='https://raw.githubusercontent.com/jasonong/List-of-US-States/master/states.csv',
            )
            codes = codes.set_index('State').to_dict()['Abbreviation']
            data['state_code'] = data['state'].map(codes)
            return data

        return _testdata_loader
    return None
```

Here is my PyCharm configuration:
![image](https://user-images.githubusercontent.com/11547371/91674901-7dbc9c80-eb08-11ea-9222-4cf55a4174f0.png)

And be sure to add an environment variable pointing to where you put your custom loader:
![image](https://user-images.githubusercontent.com/11547371/91674929-9d53c500-eb08-11ea-9a27-e710162c62bb.png)

Then from there you should go for making any changes you want and Flask hot-swapping should update on the fly.

Hope this helps and please toss your ⭐ on the repo if you haven't already :)

**Comment by akashjadhav3** [comment]
Great. I'm run the project using $ dtale --csv-path /home/jdoe/my_csv.csv --csv-parse_dates date
and browser working fine but it is the best way to run dtale project?. Because I will host AWS ubuntu server I think it is not correct.
 And one more question about it is possible to run more than one CSV file at a time?(command)

**Comment by aschonfeld** [comment]
Here's an example of a script that will preload a D-Tale instance with multiple csv files loaded
```
from dtale.utils import build_url
from dtale.views import startup
from dtale.cli.loaders.csv_loader import loader_func as load_csv
import dtale.app as dtale_app
import pandas as pd

if __name__ == '__main__':
    dtale_app.initialize_process_props(None, 80, False)
    url = build_url(dtale_app.ACTIVE_PORT, dtale_app.ACTIVE_HOST)
    startup(url, data=load_csv(path=path1, parse_dates=['date']), name='CSV1')
    startup(url, data=load_csv(path=path2, parse_dates=['date']), name='CSV2')
    startup(url, data=load_csv(path=path3, parse_dates=['date']), name='CSV3')
    # and so on and so forth...
    application = dtale_app.build_app(
        url, host=dtale_app.ACTIVE_HOST, reaper_on=False, hide_shutdown=True,
        github_fork=True
    )
```

**Comment by akashjadhav3** [comment]
Great.
I have a problem about big csv file running. basically I was clone this dtale repo and run 700mb csv data file using "$ dtale --csv-path /home/<user>/my_csv.csv --csv-parse_dates date" command. After that only show "killed" msg.
Suggest me how to run this big file using dtale?.
Thank you :)

screenshot below
![screenshot](https://user-images.githubusercontent.com/40736414/91888754-70d7ae80-ecaa-11ea-83fa-d9963237fdda.jpg)

**Comment by aschonfeld** [comment]
Hmm, how much power does your machine have?  Here's a video of me [loading a CSV of the size 827.4 MB](https://youtu.be/-o3BQspbfEY)

Here's the code I used to generate the CSV:
```
def test_data(rows, columns, no_of_dates=364):
    import pandas as pd
    import numpy as np
    import random
    from past.utils import old_div
    from pandas.tseries.offsets import Day
    from dtale.utils import dict_merge
    import string
    import datetime
    now = pd.Timestamp(pd.Timestamp('now').date())
    dates = pd.date_range(now - Day(no_of_dates), now)
    num_of_securities = max(old_div(rows, len(dates)), 1)  # always have at least one security
    securities = [
        dict(security_id=100000 + sec_id, int_val=random.randint(1, 100000000000),
             str_val=random.choice(string.ascii_letters) * 5)
        for sec_id in range(num_of_securities)
    ]
    data = pd.concat([
        pd.DataFrame([dict_merge(dict(date=date), sd) for sd in securities])
        for date in dates
    ], ignore_index=True)[['date', 'security_id', 'int_val', 'str_val']]
    col_names = ['Col{}'.format(c) for c in range(columns)]
    data = pd.concat([data, pd.DataFrame(np.random.randn(len(data), columns), columns=col_names)], axis=1)
    data.loc[data['security_id'] == 100000, 'str_val'] = np.nan
    data.loc[:, 'bool_val'] = data.index % 2 == 0
    data.loc[:, 'category_val'] = data['str_val'].astype('category')

    def pp(start, end, n):
        start_u = start.value//10**9
        end_u = end.value//10**9
        return pd.DatetimeIndex((10**9*np.random.randint(start_u, end_u, n, dtype=np.int64)).view('M8[ns]'))

    data.loc[:, 'ts_val'] = pp(pd.Timestamp('19600101'), pd.Timestamp('20500101'), len(data))
    data.loc[:, 'timedelta_val'] = [datetime.timedelta(seconds=random.randint(1, 100000000)) for _ in range(len(data))]
    return data

test_data(1000000, 35).to_csv('/Users/andrewschonfeld/large_df.csv', index=False)
```

**Comment by akashjadhav3** [comment]
ok, I'll try a deferent high power machine.
Thanks, sir for the quick reply.

**Comment by aschonfeld** [comment]
@akashjadhav3 No problem, I'll close this for now and just re-open it if you still have issues 👍
