### ISSUE TITLE
D-Tale does not spawn new windows or tabs when running in vscode's ipynb environment

### ISSUE THREAD

**Issue by Gdsimms** [man-group/dtale#258]
When running an ipython notebook in visual studio code, the main dtale table shows up when calling dtale.show(df) but it does not spawn any new windows or tabs when an option is selected from its drop-down menu (for example "Describe" or "Correlations" or "Charts").

The expected behavior is that it would be similar to how it works in a browser-based Jupyter lab instance where it creates a new tab containing and displaying the requested functionality.

**Comment by aschonfeld** [comment]
Unfortunately, I can't seem to find any documentation on how the VSCode notebook cell outputs work compared to a browser window.  The easiest solution I can think of is to simply copy the D-Tale url into your browser manually.  For example:
![image](https://user-images.githubusercontent.com/11547371/92331730-cb746000-f046-11ea-8b26-46ceea23abc8.png)

Then you'll have the full functionality.  I think that VSCode's browser window is far limited in functionality than an actual browser.  All the the "Correlations" or "Describe" links do is call the standard JS function `window.open`.  Here's some more information on VSCode's [webview](https://code.visualstudio.com/api/extension-guides/webview)
