### ISSUE TITLE
duplicate values

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#262]
It would be nice to have a popup window to ask for these options:
* Removing duplicate columns (all values of the columns are exactly similar. may be names are not the same)
         https://www.geeksforgeeks.org/how-to-find-drop-duplicate-columns-in-a-pandas-dataframe/
* Removing duplicated columns based on name. for example remove Foo, foo, FOo, FOO columns
         for the same case column name > `df = df.loc[:,~df.columns.duplicated()]`
* Remove duplicates in rows of a/multi columns
        `df.drop_duplicates (subset=['A', 'B'], keep='last', inplace=True)`
* Just show duplicates and hide the rest
`pd.concat(g for _, g in df.groupby("A") if len(g) > 1)`
* Just show duplicates of specific value 
```
df_d=pd.concat(g for _, g in df.groupby("A") if len(g) > 1)
df_d2=df_d[df_d['A']=='Foo']
```

* Highlight duplicates

**keep (first, last, none)

**Comment by aschonfeld** [comment]
@reza1615 This sounds good.  Couple questions:
1) What is entailed by "Highlight duplicates"?  It's a little vague.
2) Does "**keep (first, last, none)" pertain to anywhere we're trying to remove duplicates?

**Comment by reza1615** [comment]
@aschonfeld:
1- highlight the duplicate values in the main spreadsheet like excel
2-yes that is correct. These options are useful to remove duplicates

**Comment by aschonfeld** [comment]
added in v1.16.0
