### ISSUE TITLE
word value counts

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#263]
Value counts as a tab in the column analysis window

for dtype string value counts of words inside cells. also for word tokenization we can have NLTK tokenizer
https://www.nltk.org/api/nltk.tokenize.html

create new instance or show result in popup window 
For example
A
this is foo
this is bar

value counts of words:
this 2
is 2
foo 1
bar 1

**Comment by reza1615** [comment]
for the option 2:
https://stackoverflow.com/questions/46786211/counting-the-frequency-of-words-in-a-pandas-data-frame

**Comment by reza1615** [comment]
For string dtype it can be as a tab in the column analysis window with bar chart and word cloud charts
![image](https://user-images.githubusercontent.com/2202483/92258107-536e3480-eea4-11ea-825d-60f065167595.png)

**Comment by aschonfeld** [comment]
added in v1.16.0
