### ISSUE TITLE
Create a Cleaned column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#265]
It would be helpful to have some robust functions for data cleaning and save them in a new column
These option can be selected by radio button

* remove multi space
* remove punctuation
* remove a list of stop words
* remove default NLTK stop words for each language
* remove numbers for example Berlin 200 > Berlin
* keep only alphabets
* normalize accent characters https://gist.github.com/j4mie/557354
* remove space
* remove duplicated words in a cell for example : foo foo bar > foo bar
* Add Space between word and number like Berlin200
* remove repeated characters like bberlin > berlin
* convert to  lower case or upper or title case
* replace an/multi space cell with empty like ' ' > ''

**Comment by reza1615** [comment]
# Multi sapce
df['A']=df.A.str.replace(r'[ ]+','')

# stop words
Regex=r'\b('+r'|'.join(stop_words_list)+r')\b'
df['A']=df['A'].str.replace(Regex,'')

#keep only alphabets

**Comment by aschonfeld** [comment]
@reza1615 on the "keep only alphabets" would I expect `"a999b"` -> `ab`?  Or is "alphabets" mean something different?

**Comment by reza1615** [comment]
@aschonfeld Yes that is true. to have just language character execpt numbers
for example, There is a city address column and we just interested on street names. later for matching based on address we don't want to have match based on block number

**Comment by aschonfeld** [comment]
@reza1615  added in v1.25.0, here's a quick demo: https://youtu.be/LOnsuVlauPA

I know theres probably some modifications I can make to this so please let me know
