### ISSUE TITLE
Merge two column to a new column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#266]
It would be helpful to have a column with is concat of two columns with a separator

for string type
```
seperator =' '
df['C']= df['A']+seperator + df['B']
```

for number type
`df['C']= df['A']+df['B']`

**Comment by aschonfeld** [comment]
this already exists for numeric types in D-Tale: https://github.com/man-group/dtale#building-columns

I can work on adding string concatenation...

**Comment by reza1615** [comment]
Yes I didn't find concat strings

**Comment by aschonfeld** [comment]
added in v1.17.0
