### ISSUE TITLE
Filter outliers from the column menu

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#270]
Please add a possibility to filter out outliers. In the below menu by clicking on the outlier 572. Also it suggestion can be applied for filter out missing values. 
**Use case:** After turn on the heat map because of outliers some columns are totally in red (for example sqf_living column) . after hiding outliers we can see a better heat map 

Also hiding outliers can be as a pre-option for showing heat maps.

![image](https://user-images.githubusercontent.com/2202483/92260693-4d795300-eea6-11ea-8e17-f53b3d4f33f4.png)

**Comment by aschonfeld** [comment]
I can definitely incorporate a “hide outliers” link in the column menu.  Hiding all outliers when viewing the heatmap may be a bit much because that may end up hiding all data if the outliers are spread out over all the columns

**Comment by aschonfeld** [comment]
included in v1.18.0
