### ISSUE TITLE
RIP correlation

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#273]
RIP is a very powerful correctional algorithm

```
import ppscore as pps
pps.score(df, "A", "B")
```

https://towardsdatascience.com/rip-correlation-introducing-the-predictive-power-score-3d90808b9598

**Comment by aschonfeld** [comment]
@reza1615 here's a [demo](https://youtu.be/xDRXBC3sld0) of this feature I'm releasing in 1.26.0 soon

**Comment by aschonfeld** [comment]
Added in v1.26.0
