### ISSUE TITLE
URL linkouts 

### ISSUE THREAD

**Issue by rahulvrane** [man-group/dtale#274]
Hi
Thanks for the earlier fix! I am trying to enable another function where I want to have a linkout from the table. So Row 1 has gene names which I'm to allow people to click on and open a new page which has info on that gene.. I tried making HTML href records or just simple URL's - but neither seems to be working. 

Is this feature enabled at the moment? If so - how would my URL have to be formatted in the pandas dataframe? 

Thanks a ton
R

**Comment by aschonfeld** [comment]
@rahulvrane hmmm, this is a very interesting idea.  I can try adding a column builder which will allow you mark a column of URL strings as  links.  Seems like something that should be easy to implement.

Maybe I could even add the ability to specify another column that could be the titles.

**Comment by rahulvrane** [comment]
Either would be perfect. But the first suggestion you made seems most straight forward as a user. 👍

**Comment by aschonfeld** [comment]
@rahulvrane This has been added in v1.16.0.  Here's a little demo of it: https://youtu.be/8UIVtAKRMGA
