### ISSUE TITLE
Does not open in browser (safari 14.0) 

### ISSUE THREAD

**Issue by flight505** [man-group/dtale#275]
Hi, 

Wanted to try D-tail, but I just get the "Safari cannot connect to server" standard message in the browser. 
There was a new update to safari yesterday - Version 14.0 could this be the reason? 

```Python 
import pandas as pd
import dtale

df = pd.read_csv('mydata.csv')
d = dtale.show(df)
d.open_browser()
```

**Comment by aschonfeld** [comment]
I think this might be an issue with `open_browser()`.  This function is contingent upon your machine having a default browser assigned.  If it doesn't then it won't automatically popup for you.  To prove this fact I'll suggest running `print(d._main_url)`.  This should display the URL of your D-Tale instance and you paste that into Safari.  It should display.

Here is some information on how to solve the issues with `open_browser`.  Under the hood it's using the `webbrowser` package and it depends on a `BROWSER` environment variable existing which points to your default browser.
https://docs.python.org/2/library/webbrowser.html

**Comment by aschonfeld** [comment]
@flight505 Just checking in, any update on whether my suggestion worked or not?

**Comment by skvs2005** [comment]
I am seeing the following...
This site can’t be reached "xxx" refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by aschonfeld** [comment]
@skvs2005 can you try hitting http://localhost:40000/dtale/main/1

Also, is this a windows machine? If so, there’s some settings you’ll have to adjust to allow for hitting a python process: https://github.com/man-group/dtale#issues-with-windows-firewall

**Comment by salmanahmed84** [comment]
Hi,
I am going through similar issue. Python and pycharm both are added in firewall but still the same outcome

**Comment by salmanahmed84** [comment]
> Not only python but the browsers also

**Comment by fedderw** [comment]
> @skvs2005 can you try hitting http://localhost:40000/dtale/main/1
> 
> Also, is this a windows machine? If so, there’s some settings you’ll have to adjust to allow for hitting a python process: https://github.com/man-group/dtale#issues-with-windows-firewall

This isn't particularly helpful, what is the name of the process we need to allow?

My issue is actually on wsl2, so it might be different.

**Comment by fedderw** [comment]
> @salmanahmed84 apologies for the issues. Any chance you could try opening a browser, then going to the menu and clicking "More Tools" -> "Developer Tools". Then go to the network panel and showing me what you see for the D-Tale network calls?
> 
> Something like this: ![image](https://user-images.githubusercontent.com/11547371/145040442-bc40007d-e3a1-40c3-b478-a00e42b5d634.png)
> 
> And if some of the network calls are highlighted in red (which they should be if you're getting errors) then maybe clicking that row in the network calls and then opening the "Response" panel to show what error its giving. Something like this (although this is a successful call):
> 
> ![image](https://user-images.githubusercontent.com/11547371/145040668-d7821474-6b47-4e61-a7cc-5390d1ad6c94.png)

Here is what it looks like for me:
![image](https://user-images.githubusercontent.com/16396180/159068643-0b1ee1a3-e17c-45a6-b668-e84fc42cdc2a.png)

**Comment by MihaiZecheru** [comment]
After making sure you've allowed Pycharm / Python on your Windows Firewall, you have to keep the program alive after calling `d.open_browser()`.

Try this:
```
import pandas as pd
import dtale
import time

df = pd.read_csv('mydata.csv')
d = dtale.show(df)
d.open_browser()
time.sleep(600)
```

**Comment by aschonfeld** [comment]
@MihaiZecheru are you running this as a python script?  If that's the case you can solve you're issue by doing the following:
```
import pandas as pd
import dtale
import time

df = pd.read_csv('mydata.csv')
d = dtale.show(df, subprocess=False)
d.open_browser()
```
Here's some more information on running [D-Tale as a script](https://github.com/man-group/dtale#as-a-script)
