### ISSUE TITLE
help wanted: loading massive dataframes

### ISSUE THREAD

**Issue by rahulvrane** [man-group/dtale#276]
Hi again
I'm trying to make a large df (42cols x 20million rows) available to my team so they can add filters on columns and short list rows of interest etc. With a straight up pandas import this seems pretty slow on the users side. And given all data attempts to load at once in the HTML browser there seems to be an issue with speed and usually I can't safely browse beyond 100rows. Is there a format that works faster than CSV imports? Alternatively curious if we could define filtering criterion per column to reduce time in running a set operation.. also if there is a way to load lets say 1000 rows at a time in the view and paginate in stacks of 1000?

Apologies if it's something that's more dev than production. I'm wondering if using vaex etc might help here .. can vaex substitute pandas in dtale?

**Comment by aschonfeld** [comment]
So, just trying to understand, you've tried loading a dataframe with a shape of 42x20mil and passing that to D-Tale and its performance wasn't great?  So I had a friend of mine build a way to change how the data is stored in D-Tale so its not stored in memory (that is the default behavior).  So he built the option to use python's "shelve" or redis.  Here is some documentation on how to do it: https://github.com/man-group/dtale/blob/master/docs/GLOBAL_STATE.md

He built it in such a way that it shouldn't be too bad to fork the repo and add your own for something like dask.  Sorry I don't have an option that less work, but thats your best option for now

**Comment by bigbprp** [comment]
> So, just trying to understand, you've tried loading a dataframe with a shape of 42x20mil and passing that to D-Tale and its performance wasn't great? So I had a friend of mine build a way to change how the data is stored in D-Tale so its not stored in memory (that is the default behavior). So he built the option to use python's "shelve" or redis. Here is some documentation on how to do it: https://github.com/man-group/dtale/blob/master/docs/GLOBAL_STATE.md
> 
> He built it in such a way that it shouldn't be too bad to fork the repo and add your own for something like dask. Sorry I don't have an option that less work, but thats your best option for now

This is really impressive, I want to know if we take an approach for  dtale.global_state.use_shelve_store('/home/username/dtale_data') while doing column level analysis can it use complete data range?  e.g. If I have approx. 20 million rows then.. will it still consider all 20 million output?

Thank you...

**Comment by aschonfeld** [comment]
Honestly, this was a feature that my colleague handled all the work on so I don't know too much about it.  @phillipdupuis any chance you might be able to answer this question?

**Comment by phillipdupuis** [comment]
@aschonfeld @bigbprp absolutely, will take a look tomorrow, just need a quick refresher + a bit of playing around with it

FWIW, the current implementation is primarily aimed at making it possible for data to be persisted to disk or shared between multiple python processes; if your data is too big to fit in memory, not sure it will help that. But that would be really cool, so I'd like to see if it's possible..

**Comment by reza1615** [comment]
#287 is related to hug files

**Comment by AnthraX1** [comment]
I'm refactoring global_state and will add MongoDB Arctic store in a couple weeks.

**Comment by AnthraX1** [comment]
> I'm refactoring global_state and will add MongoDB Arctic store in a couple weeks or sooner.

I'm dropping Arctic store for now because ChunkStore in Arctic itself is just not ready and it would require a lot of extra work to fix Arctic before I could do anything with it for Dtale.

**Comment by aschonfeld** [comment]
@rahulvrane @bigbprp can this be closed?

**Comment by bigbprp** [comment]
Yes please. Thank you so much for all your hard work and focus. This is one of the fastest repository giving resolutions to raised issues.

**Comment by aschonfeld** [comment]
@bigbprp Thanks and please feel free to toss your ⭐️on the repo. Thanks🙏
