### ISSUE TITLE
Chart code export syntax errors

### ISSUE THREAD

**Issue by visualapproachanalytics** [man-group/dtale#283]
Quick fix:  When exporting code from charts, it is not supplying the necessary quotes for the syntax to be valid within the query() function:

`chart_data = chart_data.query((Data1 == 'AA') or (Data2 == 'BB'))`

As you can see, the query string is not being passed as a string, rather suggesting variables.  Would suggest:

`chart_data = chart_data.query("""(Data1 == 'AA') or (Data2 == 'BB')""")`

This also occurs again a few lines down in the generated code:

`chart_data = chart_data.query('Data1 == 'AA'')`

However, this time it looks as though single quotes were used to open the string, and it is breaking when a string is included in the query string.  Would suggest triple quotes again:

`chart_data = chart_data.query("""Data1 == 'AA'""")`

**Comment by aschonfeld** [comment]
Great idea with the triple quotes!  I'll add this support the current release i'm working on.  Thanks @visualapproachanalytics

**Comment by aschonfeld** [comment]
added in v1.17.0
