### ISSUE TITLE
column description has a lag 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#286]
After converting a column's type the column description doesn't change.
for example I change Price dtype to str this is after changing: (still shows float64)
![image](https://user-images.githubusercontent.com/2202483/95680257-4977d980-0ba6-11eb-97a0-dace6c4c3497.png)

It should show it in white. now it is green it means it is float which is outdate.
![image](https://user-images.githubusercontent.com/2202483/95680294-952a8300-0ba6-11eb-9919-ed79afc1a2a9.png)

**Comment by aschonfeld** [comment]
included in v1.18.0
