### ISSUE TITLE
Empty dtype column

### ISSUE THREAD

**Issue by mswastik** [man-group/dtale#293]
![Screenshot_20201015_204350](https://user-images.githubusercontent.com/7689061/96149903-7837dc00-0f27-11eb-9cd8-0d3b8d0bab53.png)

The column had a dtype originally but there was no data in it, D-Tale considered it as empty dtype and also not letting me convert to any dtype as shown in pic

**Comment by aschonfeld** [comment]
@mswastik is there any chance you can send over the output of running `df.dtypes`? 

`df` being the dataframe you've passed into D-Tale.  I'm just trying to figure out this dtype that I haven't mapped in D-Tale.  Once I have that I can start building out some tests and handlers for it.  Thanks

**Comment by mswastik** [comment]
It is shown of dtype `object`.

**Comment by aschonfeld** [comment]
Did it originally have data and then you filtered it down?

**Comment by aschonfeld** [comment]
This has been out here for a while and I'm going to close it because I can't reproduce it. @mswastik if this is still an issue for you please feel free to re-open it with more information. Thanks
