### ISSUE TITLE
Auto reload Demo data

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#300]
Please add a possibility to refresh the Demo data. now in the Demo page, House data is trimmed and needs to reload.

**Comment by aschonfeld** [comment]
So the best option that I can think of right now is the ability to add a conditional "Reload Data" button in the main menu (upper lefthand corner) which would, if you specified a `data_loader` property when you called `dtale.show` will call that function again and essentially refresh the data removing any edits made while running D-Tale.

Now this wouldn't auto-refresh, but it would at least give you the ability to go into the demo app whenever you wanted and if you click that button you could start fresh.  If you're fine with this solution I'm happy to add it.

**Comment by reza1615** [comment]
That is greate please add it

**Comment by aschonfeld** [comment]
@reza1615 I'll still plan on adding this, but I did some more digging and found a way to reload the site daily.  I'll set the reload to occur at midnight EST.
