### ISSUE TITLE
Normalized similarity

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#301]
It would be nice to have an option with check button to have normalized result for text similarity. I used this snippet
0 is similar
1 is not similar
``` python
def Norm_Levenshtein (a0,a1):
    if a0 is None:
           raise TypeError("Argument a0 is NoneType")
    if a1 is None:
           raise TypeError("Argument a1 is NoneType")
    if a0==a1:
           return 0.0
    max_len = Max(len(a0),len(a1))
    if max_len ==0:
           return 0.0
    return editdistance.eval(a0,a1)/max_len
```

**Comment by reza1615** [comment]
Only Jaro_winkler is between 0 to 1 for the rest we need normalized option

**Comment by aschonfeld** [comment]
I only see a "normalized" option for Levenshtein in `strsimpy`.  Not sure how to accomplish this on the Damerau & Jaccard options though...

**Comment by reza1615** [comment]
@aschonfeld: if you check code of (strsimpy.normalized_levenshtein.NormalizedLevenshtein) is the same as above snippet code 
for Damerau & Jaccard just need to replicate the above snippet code.

**Comment by aschonfeld** [comment]
added in v1.18.2
