### ISSUE TITLE
Configuration file for default options

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#302]
It would be possible to add some kind of configuration file to be able to overwrite some of the default options, so you don't have to type them over and over again.

I am thinking in particular of two (`ignore_duplicate` and `open_browser`) of the parameters I call, but it could be extended to other options:

```
show(df, ignore_duplicate=True, open_browser=True)
```

Thank you in advance!

**Comment by aschonfeld** [comment]
@juanfcocontreras Sorry for the long wait.  I will be addressing this for the next release. I think the way I'll go about it is like this:
1) You can call a function `load_confg` to load the config file once before calling the `show` function
2) You can set an environment variable `DTALE_CONFIG` which points to the location of the config file and it will be loaded up front for you each time you use D-Tale

Let me know if you can think of any other ways it should be loaded and I'll let you know of the final list of options when I finish.

**Comment by juanfcocontreras** [comment]
Hello @aschonfeld!

Don't worry about the wait, I'm sure it will be worth it!

As for the way to approach it, I think those two ways are great. However, I would add (or modify the first option) so that if there is a default configuration file in a pre-set path (for example: $HOME/.config/dtale.ini), it will be used without having to load it (like so many programs).

In particular, I install dtale for many of my colleagues in the research group. To avoid them problems, I tell them to call show function with the parameter of not checking for duplicates (sometimes they change the data but not the dimensions) and to always show in the browser (sometimes in the editor they use, nteract, if the data is too big, it gets stuck). If there was a config file, I would write it and avoid them to add parameters before the call to show or loading config lines (as in the first case you propose). I do not know if I have explained myself reasonably well.

Thank you so much!

**Comment by aschonfeld** [comment]
Ahh, good call.  Ok I'll have it check that location first (`$HOME/.config/dtale.ini`) then for an environment variable if a file doesn't exist there.  And I'll keep the ability to load the config manually using a `load_config` function which will keep those settings in memory for the extent of your python session.

So to summarize the hierarchy will be:
1) parameters passed directly to `dtale.show`
2) any configuration you've loaded using `load_config`
3) any configuration you have setup in `$HOME/.config/dtale.ini` and if not there then the `DTALE_CONFIG` environment variable

Here's an example `dtale.ini` file:
```ini
[app]
theme = 'light'

[show]
host = 'localhost'
port = 8080
reaper_on = True
open_browser = False
ignore_duplicate = True
allow_cell_edits = True
inplace = False
drop_index = False
hide_shutdown = False
github_fork = False
```

So as you can see we have any parameters to `dtale.show` under the `[show]` section and then the overall application specific ones (currently only the theme) under `[app]`

Let me know if this seems alright or not, thanks 🙏

**Comment by juanfcocontreras** [comment]
That would be amazing!!!

**Comment by aschonfeld** [comment]
Sorry some little changes to the location of some properties in the ini file:
```ini
[app]
theme = 'light'
github_fork = False
hide_shutdown = False
allow_cell_edits = True

[show]
host = 'localhost'
port = 8080
reaper_on = True
open_browser = False
ignore_duplicate = True
allow_cell_edits = True
inplace = False
drop_index = False
```

**Comment by aschonfeld** [comment]
Added in v1.21.0, here some [documentation](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md) on it

**Comment by juanfcocontreras** [comment]
I've just created a dtale.ini like this:

```
[show]
open_browser = True
ignore_duplicate = True
```

But when I try to import show I get the following error:

```
from dtale import show
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-48b12c4a2f69> in <module>
----> 1 from dtale import show

/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/__init__.py in <module>
      4
      5 # flake8: NOQA
----> 6 from dtale.app import show, get_instance, instances, offline_chart  # isort:skip
      7 from dtale.cli.loaders import LOADERS  # isort:skip
      8

/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/app.py in <module>
     24
     25 import dtale.global_state as global_state
---> 26 import dtale.config as dtale_config
     27 from dtale import dtale
     28 from dtale.cli.clickutils import retrieve_meta_info_and_version, setup_logging

/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/config.py in <module>
    125
    126 LOADED_CONFIG = get_config()
--> 127 load_app_settings(LOADED_CONFIG)

/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/config.py in load_app_settings(config)
     53         "github_fork",
     54         section="app",
---> 55         getter="getboolean",
     56     )
     57     hide_shutdown = get_config_val(

/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/config.py in get_config_val(config, defaults, prop, getter, section)
     40     if config.has_option(section, prop):
     41         return getattr(config, getter)(section, prop)
---> 42     return defaults[prop]
     43
     44

TypeError: 'bool' object is not subscriptable
```

Am I doing something wrong?

**Comment by aschonfeld** [comment]
@juanfcocontreras I'm sorry.  You are doing nothing wrong.  I completely forgot that the entire time I was writing that feature I had an `.ini` file with every property specified.  They were set to the defaults so they weren't really doing anything but they were there.

I'm going to whip up a fix for this and get it out there, but for the time being a workaround would be updating your `[app]` section to this:
```ini
[app]
theme = 'light'
github_fork = False
hide_shutdown = False
```
So these are just the default values so they won't really have any effect, but they will block the bad code from being hit.  Sorry again and I should have a fix out soon.

**Comment by juanfcocontreras** [comment]
Perfect, I thought I could imagine the reason, but I wasn't completely sure.

And please, there is nothing to apologize for. You are developing one of the most useful applications for data scientists. And although there are several other tools in the same field, one of the things that sets yours apart from others is how you listen to users and incorporate the improvements they suggest. Every time I have suggested a feature request, you have not only taken it into account, but you have incorporated it by improving my request!

Thank you very much for your time, many of us are really grateful to you!

**Comment by aschonfeld** [comment]
v1.21.1 should be available with the fix and thank you for the kind words 🙏
