### ISSUE TITLE
Ribbon Menu

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#306]
To make the UI more user friendly I suggest to have a ribbon menus at the top.
https://github.com/lgkonline/react-bootstrap-ribbon (**The simple ribbon**)
![image](https://user-images.githubusercontent.com/2202483/96346329-2d25e200-1069-11eb-892d-b64d2e6faad4.png)

**Comment by AnthraX1** [comment]
+1

Also use tabs on top for data instances like web pages in browser.

**Comment by aschonfeld** [comment]
This will be included in v1.42.0, here's a demo:

https://user-images.githubusercontent.com/11547371/114333255-de3b9f80-9b15-11eb-89dc-96e4bf1ade93.mov
