### ISSUE TITLE
Y-axis not showing the decimal points, if you can notice the range of the y-axis is [0.09,0.28].

### ISSUE THREAD

**Issue by Me514** [man-group/dtale#308]
![7F6E7756-42B2-4737-8004-13BD5003D474](https://user-images.githubusercontent.com/60988019/96711162-6b8b0c00-139d-11eb-932b-9a29ad645653.jpeg

**Comment by aschonfeld** [comment]
@Me514 based on you screenshot it looks like you actually entered the values `0,09` & `0,28` and because you used commas instead of decimal points it treats both the min & max as zero.

I think if you change your values to `0.09` & `0.28` it should work fine :)
