### ISSUE TITLE
Encoders error

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#310]
![image](https://user-images.githubusercontent.com/2202483/97094478-00526b80-1623-11eb-9de3-256c132d9ce7.png)
![image](https://user-images.githubusercontent.com/2202483/97094516-490a2480-1623-11eb-847f-a7221e1e1cc2.png)

**Comment by aschonfeld** [comment]
@reza1615 Not sure how you want me to treat `nan` but i'm going to keep them as `nan`

**Comment by reza1615** [comment]
In my opinion, when there is nan in the string column. 
1-check is there nan
2-ask to replace nan with empty or 'nan'

**Comment by reza1615** [comment]
https://stackoverflow.com/questions/50617442/how-to-replace-nan-values-meaningfully-for-machine-learning

we can suggest imputer or mean for nan values or 0

**Comment by aschonfeld** [comment]
Ok, right now I was keeping them as nan, but i'll set them to zero.  Thanks

**Comment by aschonfeld** [comment]
Fixed in v1.19.1
