### ISSUE TITLE
Support of numpy arrays

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#313]
Although to take full advantage of `dtale`, it is recommended to have pandas-like data: Series, DataFrame, xarray, koalas... It could also be very useful to visualize and explore numpy arrays.

The conversion is trivial, since `pandas` and derivatives are based on `numpy`:

```
import numpy as np

if isinstance(data, np.ndarray):
    data = pd.DataFrame(data)
```

**Comment by aschonfeld** [comment]
@juanfcocontreras This is a great idea and very low risk!  Can't believe I never thought of it 🤣 I'll add that in the release I'm planning to do by the end of this weekend.

**Comment by aschonfeld** [comment]
Should I include support for lists and dictionaries as well or is that overkill?

**Comment by juanfcocontreras** [comment]
Hi! I particularly think they would be very useful too. I understand that you don't want to add more types of data than necessary, but I think lists and dictionaries are so widely used that it would be great to be able to visualize them in `dtale` as well.

**Comment by aschonfeld** [comment]
It's still pretty low risk so I'll add them too.  Worse thing that could happen is someone passes a badly formatted one and an exception is thrown and hopefully pandas has some good information included with its exception about why it failed

**Comment by aschonfeld** [comment]
Added in v1.21.0

**Comment by juanfcocontreras** [comment]
Did you updated the conda-forge version? I can't wait to try it!! :)

**Comment by aschonfeld** [comment]
Still waitijg for the build to get generated.  For some reason it takes a while.  Not sure what kind of timer they have it set on.  If it isnt generated by tonight i’ll try forcing it

**Comment by aschonfeld** [comment]
Ok I just merged the version bump manually.  Should be built soon.  Sorry for the wait

**Comment by juanfcocontreras** [comment]
Great! Updated right now. Doing some testing... Thank you so much!

**Comment by juanfcocontreras** [comment]
I have found a little inconvenience in reading dictionaries with `dtale` but it has an easy solution.

The following dictionary:

```
dict_sample = {
  "Company": "Toyota",
  "model": "Prize",
  "year: 2012
}
```

Throw the following exception:

```
pd.DataFrame(dict_sample)

ValueError: If using all scalar values, you must pass an index
```

It seems that the easiest way to avoid the error is to convert the dictionary first to a `pd.Series` (a much more similar data type) and then to a `pd.DataFrame`:

```
pd.Series(dict_sample).to_frame()

               0
Toyota   Company
Model      Award
year        2012
```

**Comment by aschonfeld** [comment]
Ok I do one of two things:
1) check if the values of your dictionary contains iterables (lists, sets, etc...) and if so use `pd.Series(...).to_frame()`
2) use this block of code:
```
try:
  pd.Series(...).to_frame()
except:
  pd.DataFrame(...)
```

**Comment by juanfcocontreras** [comment]
Perfect! I think that effectively handles most situations where input data can converted to DataFrame.

Thank you very much!

**Comment by aschonfeld** [comment]
v1.21.1 should be available now with the fix
