### ISSUE TITLE
where is the language lib?

### ISSUE THREAD

**Issue by akeliduo** [man-group/dtale#315]
I want to translate dtale to other language for the purpose to let people in different countries to use.

Where is the language file to edit?

Thanks.

**Comment by aschonfeld** [comment]
@akeliduo do you mean that you would like to change the descriptions & labels that you see in D-Tale to be in a different language?  I can see if theres any front-end packages that support something like this.  Otherwise, it will take me some time to add localization.

Good suggestion!

**Comment by akeliduo** [comment]
Yes. I want to change the texts in menu, buttons, labels or hints. 

It's good to add localization.

**Comment by reza1615** [comment]
@aschonfeld mediawiki's localization is on the https://translatewiki.net/

**Comment by aschonfeld** [comment]
@akeliduo we have added partial support for chinese now in v1.37.1, still waiting for additional translation.  Here's how to activate it from the UI:

https://user-images.githubusercontent.com/11547371/110196791-efa5d380-7e14-11eb-8de5-0c3a1b47c742.mov

Please let me know if you want to help with the translation or if you want more information on how to set it as you default language.  You can do it through the use of a config file so you don't need to click the button everytime you use D-Tale
