### ISSUE TITLE
Add new views/functionality to Dtale 

### ISSUE THREAD

**Issue by liorfuks** [man-group/dtale#316]
Hello,
I stumbled upon Dtale and I must say its an amazing EDA tool.
I was wondering if there is any tutorial on how to extend by adding new view?
For example I would like to add on the left side menu another view with a new dash based viz.

thanks

**Comment by aschonfeld** [comment]
@liorfuks So here's some documentation on how to embed [D-Tale within your own Flask app](https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md). It also includes a link to some source code that I put together for a small example.

But if you think your change would be helpful to others let me know and I'd be happy to add it as a new feature :)

**Comment by aschonfeld** [comment]
@liorfuks I'm going to close this issue.  If there is additional functionality you want added in reference to this issue please re-open this with any additional information.  Thanks
