### ISSUE TITLE
Feature request: add number conversion

### ISSUE THREAD

**Issue by wenwen412** [man-group/dtale#317]
Thank you for building this amazing tool. I use it as db browser alternative. I was looking for a feature to do number convention, e.g., e.g., converting decimal to hexadecimal, but couldn't find it. Is it possible to add that feature?

**Comment by aschonfeld** [comment]
Sure thing.  Do you mean something like this? 
![image](https://user-images.githubusercontent.com/11547371/98995511-726df000-24ff-11eb-84e6-a611d5b04145.png)

**Comment by wenwen412** [comment]
Yes. Thank you for prompt reply. It would be nice if I could do number convention on certain column(s).

**Comment by aschonfeld** [comment]
So I was just going to add a "hexidecimal" checkbox to the "Formats" popup currently available for integer and float columns: 
![image](https://user-images.githubusercontent.com/11547371/98999396-b95ee400-2505-11eb-8428-672fbeeff726.png)
And once you check it then all the values in that column would be rendered as hexidecimals

**Comment by aschonfeld** [comment]
@wenwen412 so after digging into this a little deeper I decided to make this a standard column builder so that way the change would happen to the pandas dataframe itself and if you wanted to grab your dataframe after it had its specific columns converted to hex you can.  Here is a demo and I plan to release this by the end of the weekend: https://youtu.be/5xej0D2jz3E

**Comment by aschonfeld** [comment]
This has been added in v1.22.0

**Comment by wenwen412** [comment]
Hi,

Thank you so much for adding the feature. I tested the feature but found some issues:
1. The number conversion looks wrong to me. e.g., for int number 1, the hex result I got is 0x3f800000, but it should be 0x1.
Similar issue for float numbers, plus I don't see "." for float numbers. In my cases, it is not necessary to have support for float number conversion. Only supporting integer number would be enough. Python hex() function does the job.


2.Right now it is not possible to convert the hex numbers back to int. You can do it by checking string s.startswith('0X') and then  int(s, 16).

**Comment by aschonfeld** [comment]
Sorry, i ended up using what was in this post: https://stackoverflow.com/questions/23624212/how-to-convert-a-float-into-hex/38879403

I’m more than happy to update it to simply apply the hex() function to ints and if its a float then just the integer portion of the number.  If you can find a better option for floats let me know

**Comment by wenwen412** [comment]
Hi Andrew,

YES, That sounds good.

**Comment by aschonfeld** [comment]
@wenwen412  after some digging this is what I've got:
* int -> hex: `pd.Series([1, 2, 3]).apply(lambda v: v if pd.isnull(v) else hex(v))`
* hex (str) -> int: `pd.Series([1, 2, 3]).apply(hex).apply(lambda v: v if ps.isnull(v) else int(v, base=16))`
* float -> hex: `pd.Series([1.2, 2.1, 3.1]).apply(float.hex)`
* hex (str) -> float: `pd.Series([1.2, 2.1, 3.1]).apply(float.hex).apply(float.fromhex)`

Hope this sounds good

**Comment by aschonfeld** [comment]
@wenwen412 give v1.22.1 a try
