### ISSUE TITLE
Precision setting for all float columns

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#323]
Depending on the data loaded, many times the default precision may be insufficient. Even more so now that numpy arrays can be loaded.

Right now, I think the only option you have is to go column by column changing it.

Could you add an option to set precision settings for all floats columns?

Thanks in advance!

**Comment by aschonfeld** [comment]
@juanfcocontreras are you saying the precision displayed on the screen (default: 2 decimal points) or actually contained within the data?  

I can try adding a parameter to the configuration file & show function for default decimal points so you can alter that

**Comment by juanfcocontreras** [comment]
Sorry, I meant precision displayed on the screen. Sometimes when you work with small data, 2 decimal points is not enough. The problem now is that you have to change that setting column by column every time you show data.

**Comment by aschonfeld** [comment]
Sure thing, will keep you posted on when it's ready.

**Comment by aschonfeld** [comment]
@juanfcocontreras I've added this in the version I just released v1.25.0. You can set this in a few ways:
1) within the configuration file you can set `precision` in the `[show]` section, which will apply this value to every instance of `dtale.show`
2) `dtale.show(df, precision=6)` you can set this for each piece of data passed to D-Tale.  So for one dataframe the precision can be 3 and another it can be 4
3) when calling D-Tale from the command line: `dtale --precision 6 ...`

And you can still alter the precision from the UI using the Formatting popup.

**Comment by juanfcocontreras** [comment]
Thank you very much!
