### ISSUE TITLE
D-Tale Chart Colors

### ISSUE THREAD

**Issue by vijaydewan** [man-group/dtale#325]
Thanks for the colorscale update! The colors for the simple scatter still seems a bit different (see Dtale - Screen Colors.png vs. Dtale - Export Colors.png, attached).  Do you know why this?

![Dtale - Screen Colors](https://user-images.githubusercontent.com/71048263/100953403-8abea280-34e0-11eb-8ee2-78f410931719.png)
![Dtale - Export Colors](https://user-images.githubusercontent.com/71048263/100953419-8eeac000-34e0-11eb-94f7-af9b094d4ebf.png)

**Comment by vijaydewan** [comment]
I found a quick fix for this one.  It looks like when displayed, plotly is using px.colors.qualitative.D3 but as the colorway, but when exported it's using px.colors.qualitative.Plotly.  If you explicitly define the colorway in the build_layout function in charts.py, this fixes the problem.  You can choose any of Plotly's discrete color swatches (found at the bottom of this link https://plotly.com/python/discrete-color/) or define your own list of colors, and that will show both on display and export.

def build_layout(cfg):
    """
    Wrapper function for :plotly:`plotly.graph_objs.Layout <plotly.graph_objs.Layout>`

    :param cfg: layout configuration
    :type cfg: dict
    :return: layout object
    :rtype: :plotly:`plotly.graph_objs.Layout <plotly.graph_objs.Layout>`
    """


    return go.Layout(
        **dict_merge(
            dict(legend=dict(orientation="h"),
                 colorway=px.colors.qualitative.D3
                 ),
            cfg))

**Comment by aschonfeld** [comment]
@vijaydewan that fix worked perfectly!  Putting the finishing touches on my next release now.  Will keep you posted...

**Comment by aschonfeld** [comment]
fixed in v1.26.0
