### ISSUE TITLE
Trendline with datetime

### ISSUE THREAD

**Issue by vijaydewan** [man-group/dtale#326]
I also noticed that the trendline has issues when you have a datetime in the x axis. I did some research and think this may be an issue with plotly itself. I plugged in a fix in charts.py to convert the datetime to a float when there is a trendline (in the for loop in _build data() in _build_final_scatter(y_val) in charts.py) but I'm sure there's a more elegant solution:

                if trendline:
                    if pd.DataFrame(d["x"])[0].dtype == 'object':
                        d["x"] = pd.to_datetime(pd.DataFrame(d["x"])[0]).dt.strftime('%Y.%m%d').astype(float).values
                    if pd.DataFrame(d[y_val])[0].dtype == 'object':
                        d[y_val] = pd.to_datetime(pd.DataFrame(d[y_val])[0]).dt.strftime('%Y.%m%d').astype(float).values

**Comment by aschonfeld** [comment]
@vijaydewan sorry about that I'll tackle this and your other one right after I finish my work on Predictive Power Score

**Comment by vijaydewan** [comment]
Thanks again!

**Comment by aschonfeld** [comment]
@vijaydewan So what I have is a solution where if either of the datasets passed into x or y is of type datetime then it will convert them to millisecond integers.  It's will still crash if for some reason the values passed in are strings, but I don't think the UI should allow users to pass in string data to x or y 🤞 .  I'll include this in the next release, good catch!

**Comment by aschonfeld** [comment]
fixed in v1.26.0
