### ISSUE TITLE
CLeaning

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#327]
Thank you for adding the cleaning functionality.
There is an issue. when I select an option another click on that option should disable that option. Now there isn't an option to disable the selected cleaning method.
![image](https://user-images.githubusercontent.com/2202483/101035316-b5dcdc80-3548-11eb-88cd-4b1afbcdfc0b.png)

**Comment by aschonfeld** [comment]
Sorry about that.  The expected functionality was supposed to be if you the method again it will deselect it. I will fix that.

**Comment by aschonfeld** [comment]
fixed in v1.26.0
