### ISSUE TITLE
Feature Request: Add row diff to build column menu.

### ISSUE THREAD

**Issue by sprouse** [man-group/dtale#329]
Is it possible to support the Pandas Dataframe .diff() function.

**Comment by aschonfeld** [comment]
Sure thing, so is the idea that this will create a new dataframe based on the axis you choose? Based on the examples here: https://www.google.com/amp/s/www.geeksforgeeks.org/python-pandas-dataframe-diff/amp/

I already do something similar with the summarize functions so i can add it there

**Comment by sprouse** [comment]
Creating a new dataframe is one solution.

The specific use case I have in mind is to create just a new column from a row-wise diff of an existing column.
Something like this: https://stackoverflow.com/a/23143110

The user could specify the period parameter.

**Comment by aschonfeld** [comment]
Thanks for sending that, now i understand what that operation is doing a little better 🤦‍♂️.  I’ll add it to column builders and allow you to specify one or many columns and it will add one or many columns to your dataframe

**Comment by sprouse** [comment]
Thanks.
Great tool by the way. We used to use the SQlite Browser (DB Browser), but this has much more of the functionality  we need to quickly inspect our data frames.

**Comment by aschonfeld** [comment]
Thanks, feel free to toss your ⭐️ on the repo if you havent already.  I hope to start this in the morning. Shouldnt take long and i’ll shoot you a demo before i release it to make its not missing anything

**Comment by aschonfeld** [comment]
@sprouse here's what I have so far: https://youtu.be/2fC0US1WH-g

Let me know if you want anything else added.  The other functionality I mentioned about creating a new dataframe seems extraneous, but I'm happy to add it if you need it.

**Comment by sprouse** [comment]
@aschonfeld The behavior looks great. Regarding the button label. Would calling it "Row Difference" help contrast it from the "Column-wise difference" in the "Operation" section below?

**Comment by aschonfeld** [comment]
Good idea, i was thinking that exact thing when i made it but for reason couldnt put the words together in my head.

**Comment by aschonfeld** [comment]
added in v1.27.0
