### ISSUE TITLE
Timeseries data slope segmentation 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#330]
It would be helpful to have the feature which segment 
timeseries base on trend slope.
Previously I asked in stackoverflow https://stackoverflow.com/questions/55133427/pandas-splitting-data-frame-based-on-the-slope-of-data/55134347#55134347
it can be like below. 

A  Segment
5   1
7   1
5   2 
5   3 
5   3 
6   4 
3   5 
2   5 
0   5 
5   6

**Comment by aschonfeld** [comment]
@reza1615 just posted another solution which doesn't require a for-loop: https://stackoverflow.com/a/65176007/12616360

Also, is it fine to assume you'll always want to `bfill` and not `ffill`?

**Comment by aschonfeld** [comment]
@reza1615 any more information on this?  If not, I'm going to close it

**Comment by reza1615** [comment]
sorry for late answer. It can be as a new column.
In stackflow the new update the list length is 7

**Comment by aschonfeld** [comment]
Let me know if this looks good:

https://user-images.githubusercontent.com/11547371/104681049-6816d080-56bf-11eb-9c1a-0bf4fe98c305.mov

**Comment by aschonfeld** [comment]
added in v1.31.0
