### ISSUE TITLE
word counts for description window

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#332]
Like column analysis please also add word value counts to the column description 
![Screenshot_20201205-231017_Chrome](https://user-images.githubusercontent.com/2202483/101271249-35d49380-374f-11eb-96bf-f4d057731056.jpg)

![Screenshot_20201205-231226_Samsung Internet](https://user-images.githubusercontent.com/2202483/101271264-5d2b6080-374f-11eb-9e4b-338a55178af2.jpg)

**Comment by aschonfeld** [comment]
fixed in v1.27.0
