### ISSUE TITLE
diff for timeseries and sequential data in the column description 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#333]
for sequential data It would be helpful to have some informations about diff in the column description.
for date, float, int columns:

like below
12:30
12:31
12:33
12:34

* If data is sequential
    * min diff: 1 (2)
    * Aveage diff: 1.33
    * max diff: 2 (1)
    * diff: 1(2), 2(1)

**Comment by aschonfeld** [comment]
@reza1615 here's what this will look like: 
![image](https://user-images.githubusercontent.com/11547371/101583452-86dfc400-39a9-11eb-8975-3b9547cd22d6.png)

**Comment by aschonfeld** [comment]
added in v1.27.0
