### ISSUE TITLE
determine point distribution becomes long tail 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#334]
In the column description histogram chart and text determining long tail
https://stats.stackexchange.com/questions/468572/determine-point-distribution-becomes-long-tailed-python

**Comment by reza1615** [comment]
for example
![IMG_20201206_001650_955](https://user-images.githubusercontent.com/2202483/101272246-5fde8380-3758-11eb-8f5a-97e374445da7.jpg)

**Comment by aschonfeld** [comment]
@reza1615 can you point me to some python code examples on how to do this?  It's pretty unclear.

Also, what are you looking for in particular?  A line of best fit in the histogram chart?  And then some text that says "long tail: true/false"?

**Comment by reza1615** [comment]
I found an interesting article  https://medium.com/@atanudan/kurtosis-skew-function-in-pandas-aa63d72e20de
we can add these metrics to the column description with some labels

Skewness essentially measures the **symmetry of the distribution**, while kurtosis determines the **heaviness of the distribution** tails. 

- Pandas-Skew Function:  `df.skew(axis=1)`
                    fairly symmetrical:     skewness is between -0.5 and 0.5
                    moderately skewed:  skewness is between -1 and — 0.5 or between 0.5 and 1
                    highly skewed: skewness is less than -1 or greater than 1
![image](https://user-images.githubusercontent.com/2202483/101963165-081e9d00-3bdc-11eb-8f94-25a17f75bde9.png)

- Pandas Kurtosis Function:   `df.kurt(axis=1)`
                    leptokurtic (more than normal dist hight) : Kurtosis > 3
                    mesokurtic (normal dist hight): (Kurtosis=3)
                     platykurtic (less than normal dist hight): (Kurtosis <3)
![image](https://user-images.githubusercontent.com/2202483/101963142-fa691780-3bdb-11eb-943e-870a635b5319.png)

My suggestion:
In the **column description** and the **below window** we can have these metrics:

- skewness: 2
- Kurtosis: 1.5 

![image](https://user-images.githubusercontent.com/2202483/101963699-57b19880-3bdd-11eb-8e0a-3ccb0a32d90d.png)

**Comment by aschonfeld** [comment]
added in v1.28.0
