### ISSUE TITLE
more features for string in the column description

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#335]
It would be nice to have these items for column description when it is a string

' foo@'
'bar2 '
'test bar'
'å test'
'Foo      bar'

* characters
     * min char: 3
     * mean char: 3.5
     * max char: 8
     * std char: 0.2
     * row with space: 2
     * row with accent char: 1
     * row with num: 1
     * row with upper char: 1
     * row with lower char: 5
     * row with puncuation:1
     * has space as the first char: 1
     * has space as the last char:1
    * has multiple space after each other: 1
* words
     * min word: 1
     * mean word: 1.2
     * max word: 2
     * std word: 0.1

**Comment by reza1615** [comment]
``` python

import pandas as pd
df=pd.DataFrame({'a':['foo@','bar2','test  bar','åå test','Foo']})
char_min=df['a'].str.len().min()
char_max=df['a'].str.len().max()
char_mean=df['a'].str.len().mean()
char_std=df['a'].str.len().std()
with_space=df['a'].str.count(r'\s').astype(bool).sum()
with_accent=df['a'].str.count(r'[À-ÖÙ-öù-ÿĀ-žḀ-ỿ]').astype(bool).sum()
with_num=df['a'].str.count(r'[0-9]').astype(bool).sum()
with_upper=df['a'].str.count(r'[A-Z]').astype(bool).sum()
with_lower=df['a'].str.count(r'[a-z]').astype(bool).sum()
with_punch=df['a'].str.count(r'(\!|"|\#|\$|%|&|\'|\(|\)|\*|\+|,|\-|\.|/|\:|\;|\<|\=|\>|\?|@|[|\\|]|\^|_|\`|{|\||}|\~)').astype(bool).sum()
word_min=df['a'].str.replace('[\s]+',' ').str.split(' ').apply(lambda x: len(x)).min()
word_max=df['a'].str.replace('[\s]+',' ').str.split(' ').apply(lambda x: len(x)).max()
word_mean=df['a'].str.replace('[\s]+',' ').str.split(' ').apply(lambda x: len(x)).mean()
word_std=df['a'].str.replace('[\s]+',' ').str.split(' ').apply(lambda x: len(x)).std()
```

**Comment by aschonfeld** [comment]
![image](https://user-images.githubusercontent.com/11547371/101692209-dc65b080-3a3d-11eb-8f20-df8390c8abb2.png)

**Comment by aschonfeld** [comment]
added in v1.27.0
