### ISSUE TITLE
Feature request: Load dataframes from .sqlite file.

### ISSUE THREAD

**Issue by sprouse** [man-group/dtale#336]
Is possible to add the capability to read dataframes from .sqlite files?
The user would first specify the .sqlite filename, then be prompted to specify/select the table name.

**Comment by aschonfeld** [comment]
do you mind shooting me a small sample file?  Should be able to paste it directly in your reply

**Comment by sprouse** [comment]
Here's a sample of the first 100 entries from the Simpsons database.

[simpsons_100.sqlite.gz](https://github.com/man-group/dtale/files/5656353/simpsons_100.sqlite.gz)

**Comment by aschonfeld** [comment]
@sprouse what if I allow users to upload a file with the extension ".sqllite" and then my code will run the following query:
`SELECT name FROM sqlite_master WHERE type='table';`
And I can load each of the tables that are returned from that query into their own separate instance.

Obviously one worry is that the file will contain a ton of tables and overload D-Tale but until I can figure out a way for the file upload component to wait until the user enters a table name before loading the data to D-Tale.

**Comment by aschonfeld** [comment]
I've hit a snag.  The file upload component I use returns a byte stream to the app, but based on this post its not possible to use io.BytesIO for loading a sqlite file to `sqlite3.connect`: https://stackoverflow.com/questions/32620924/open-a-sqlite3-database-from-an-io-bytesio-stream

That being said, I can provide you a function to load sqlite files to D-Tale that can be called from a python console or jupyter notebook.  I can also provide a CLI loader.

The only way I can think of this working from the web would be if you manually typed out the path to your file and the app tries to load it.  Most likely this would only work if your running D-Tale locally and not from a docker container.

**Comment by sprouse** [comment]
I don't think it is good to load all the tables in the sqlite file. It could consume a lot of memory unnecessarily. Perhaps have the user specify the exact table they want and throw an error if it is not found.

As for loading the file, the CLI loader would work. We have written a CLI wrapper that loads the file in to a dataframe and then calls d-tale. I think others who use sqlite would find it useful.

**Comment by aschonfeld** [comment]
Sounds good, then i’ll make the table name argument required then.

I was thinking a little more and i could possibly load the files from the web if I took the bytes and then wrote them to a local file and then used that file to load to D-Tale.  If you think thats overkill then I wont try it

**Comment by sprouse** [comment]
Yes, I think that is overkill. The command line option is a good compromise for now.

**Comment by aschonfeld** [comment]
This has been added in v1.27.0.  You can now use it from the CLI:
`dtale --sqlite-path /test.sqlite --sqlite-table test_table`

You can also call the loader from code when in a python console or jupyter notebook:
```
import dtale

dtale.show_sqlite(path='/test.sqlite', table='test_table')
```

**Comment by sprouse** [comment]
Looks good. Thank you!
