### ISSUE TITLE
string column cleaning in build column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#340]
have an option to replace  _ to space in the **build column > cleaning**, i.e.  New_York > New York

Also for the word counts in the column description, it is much better to have a check box to ask do you want to remove _ or convert _ to space. now for the cases which they have _ it is useless. for example, see Fort_Nelsson
![image](https://user-images.githubusercontent.com/2202483/101919435-8a856d80-3b98-11eb-9bf9-ae5170bbfda4.png)

**Comment by aschonfeld** [comment]
Can you give me the list of "Cleaners" you want available?  I can make a multi-select dropdown of ones that don't require additional parameters (meaning we can't using "Drop Stop Words" or "Update Word Case").  The screen is already cluttered enough as it is, but I'm happy to add a multi-select for cleaners which will be applied in the order they are selected.

**Comment by reza1615** [comment]
in my opinion all cleaning that we have + replace _ with space
There are different use case for each function for example to check most mentioned street name we don't need numbers or punctuation
to check most mention zipcode we don't need alphabet chars
ans so on
so we can have all of the in the dropdown

**Comment by aschonfeld** [comment]
These are the options I can offer:
* Replace Multi-Space w/ Single-Space
* Remove Punctuation
* Remove Numbers
* Keep Only Alpha
* Normalize Accent Characters
* Remove Spaces
* Drop Repeated Words
* Add Space Between Word and Numbers
* Remove Repeated Chars
* Update Space Values to Empty String

**Comment by reza1615** [comment]
multi space doesn't need because it doesn't effect here
please also add replace _ with space

**Comment by aschonfeld** [comment]
added in v1.28.0
