### ISSUE TITLE
Column cleaning 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#341]
Please change the below cases: 

1- Drop Accent characters > Normalize Accent characters
we don't drop just replace with the normal char

2-Please add a dropbox to get the language name no it is just for English. it supports https://stackoverflow.com/questions/54812238/nltk-stopwords-languages/54812558
['arabic',
 'azerbaijani',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'turkish']

**Comment by aschonfeld** [comment]
added in v1.28.0
