### ISSUE TITLE
Cleaning function hover text

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#342]
In my opinion, the cleaning functions needs some description which can be above the code snip in another label box or hover text
There is my suggestion please feel free to modify them:
1- Replace Multi space.... > 'Replace multi spaces in the rows i.e. "Foo     Bar" > "Foo Bar"
2-Remove punchation > 'Remove Punctuations characters !"#$%&'|()*+,-./:;<=>?@[\]^_`{|}~ from the text. i.e. "foo." > "foo"
3-Drop stop words > ' Remove use-defined stop words'
4-Drop NLTK Stop Words > 'Remove stop words based on NLTK library'
5-Remove number > 'Remove numbers from the content. i.e. 'Foo123' > 'Foo'
6-Keep only Alpha > remove character which are not alphabet + space. i.e. 'BÀr. @123 foo' > 'BÀrfoo'
7-Drop Accent Characters > 'Normalizing Accent chacter with normal characters i.e. 'BÀr foö'> 'BAr foo'
8-Remove spaces > 'Remove all spaces in the row i.e. 'New York' > 'NewYork'
9-Drop repeated words > 'Remove repeated words i.e. 'Berlin Berlin #1234' > 'Berlin #1234'
10-Add space between word and numbers > 'Adding space between word and numbers. i.e. 'Berlin123' > 'Berlin 123'
11-Remove repeated characters > 'Removing charcters which are repeated after each other i.e. BBerlin > Berlin
12-Update word case > The name is obvious 
13-update space ... > The name is obvious

**Comment by aschonfeld** [comment]
Added in v1.28.0
