### ISSUE TITLE
bug in sequential data description + suggestion

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#343]
![image](https://user-images.githubusercontent.com/2202483/101925914-734a7e00-3ba0-11eb-95fe-43e51e747b33.png)

I did these steps:
1-Sorted data based on DateAdded
2- check the DateAdded column description

Min sequential is empty also it is empty in the unique value section

**Suggestion**:
Please add a radio button in front of **sequential Diffs** . sort base on this column or not.
with the button, the user can explore the column without the need to sort data on the main page and it is temporary sorting

**Comment by aschonfeld** [comment]
Fixed the bug with missing "min" in v1.28.0

**Comment by aschonfeld** [comment]
fixed in v1.31.0
