### ISSUE TITLE
Geolocation (lat and long) column description tab

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#345]
Exploring lat and log range without a map is difficult and doesn't make sense to just check numbers. It would be nice to have pines on the world map for lat and long columns. It can be a tab like a histogram graph tab. 

My suggestion is having a map like the below screenshot's setting

![image](https://user-images.githubusercontent.com/2202483/101935636-5e281c00-3bad-11eb-8a63-8b37c7ed0200.png)

This option when should be activated:
* Column type is float or int
* lat and long or latitude and longitude is in the lower name of the df columns. i.e.  x_lat, x_long or lat, long ,...
*  -90 < lat < 90 and long -180 < long <180 if the names are ok but it is not in the range just show a message that "lat and long are not in the range -90 < lat < 90 and long -180 < long <180".

**Comment by aschonfeld** [comment]
Quick question, what is "pines on world map"?  Latitude & Longitude lines?

So the tough part is the that the "Column Analysis" popup is based on the selection of one column.  For Lat/Lon analysis that assumes the presence of two columns matching the ranges you specified. I can add this check to the analysis of columns when they data gets loaded into D-Tale if you're viewing "Column Analysis" for one of the columns which match these rules if will display this option for Lat/Lon analysis (but only if there is other columns that match these rules as well).  Seems a little hacky though.

**Comment by reza1615** [comment]
It can be as a pin points when both columns are available.
for example when click on lat column description will display a map base on lat and long. If we don't have both column doesnt need to show any map.

**Comment by aschonfeld** [comment]
@reza1615 is this ok? 

https://user-images.githubusercontent.com/11547371/104143785-e8bb9100-538e-11eb-91fb-6d12c59d1e9e.mov

**Comment by reza1615** [comment]
Thanks that is greate. Is it possible to make it as a tab like word counts in column description.
In my opinion having geo view as separate button in that menu make it messy

**Comment by reza1615** [comment]
Or here


![Screenshot_20210111-001534_Samsung Internet](https://user-images.githubusercontent.com/2202483/104148907-2d9cf300-53a2-11eb-8df9-d35953c882cd.jpg)

**Comment by aschonfeld** [comment]
So unfortunately this is the best I can do re-using the plotly dash codebase I've already built.  I can look into using plotly on the React front-end but I think that seems overkill.  Plus where are you supposed to fit two more dropdowns on the "Describe" page?

**Comment by reza1615** [comment]
For dropdown it doesn't need as I mentioned it should selected by name and condition. User can change the column type like change type to it. he/she can change the column type to Geolocation.
Dtale in description column can check if there are two geolocation then draw the map.
Tabelue has geolocation type if you select map based on that auto detection type it draw the map if it couldn't automatically  find geolocation type user will select it.
This is my idea now your if in your opinion it is over kill let leave it as you implemented.
Thank you for your effort.

**Comment by aschonfeld** [comment]
I already have logic in place which follows your rules to determine if a column might contain latitude or longitude.  So I guess you're right.  We'll pre-populate the latitude or longitude (based on which one of your rules it met) and then another drop down of any columns which match the other geolocation type.

I'll see how tough it is to use plotly.js directly on the front-end.

**Comment by aschonfeld** [comment]
How about this: 

https://user-images.githubusercontent.com/11547371/104272387-f7777600-546a-11eb-98e1-a2fe9f8156c2.mov

**Comment by reza1615** [comment]
Wow, this is so greate. Thanks 👌
some so suggestions
1- please make long as default value of the dropdown.
If there are multi make the first one as default
2- At column description make the dtype column as some inline links when user click on for example string. he/she can choose another type. it can be like what we have for dtype converting but more simple and inplace.
As I mentioned another data analysis softwares have it to make the process more user friendly.
Thank you for implementation.

**Comment by aschonfeld** [comment]
1) in the process of updating this
2) i dont understand this request.  Could you maybe send a picture of what you’re expecting? Also, this doesnt seem to relate to this ticket

**Comment by reza1615** [comment]
1- Thanks
2- #392

**Comment by aschonfeld** [comment]
added in v1.31.0
