### ISSUE TITLE
map chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#346]
please rename **Mapbox** to **Detailed map** it is  vague
![image](https://user-images.githubusercontent.com/2202483/101937309-b2cc9680-3baf-11eb-92ac-7469c57b5332.png)

Also in the hover box please use the below icon for the **Detailed map** (Mapbox)
![image](https://user-images.githubusercontent.com/2202483/101938192-ef4cc200-3bb0-11eb-92cf-27ab195902df.png)

**Comment by aschonfeld** [comment]
updated in v1.30.0
