### ISSUE TITLE
How many items are loaded

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#347]
Please add a text to mention how many random items are loaded. also please open it to accept 10% it accepts 30% but has a problem with 10%

![image](https://user-images.githubusercontent.com/2202483/101938544-83b72480-3bb1-11eb-9f14-ca1f70b14c70.png)

**Comment by aschonfeld** [comment]
10% works fine for me
![image](https://user-images.githubusercontent.com/11547371/102928124-34e97480-4466-11eb-9985-8e2aa6d99f06.png)

**Comment by aschonfeld** [comment]
How's this? 
![image](https://user-images.githubusercontent.com/11547371/102935764-c6f87980-4474-11eb-9214-dc8d51d97d50.png)
Trying to show all 10 ticks is very cluttered

**Comment by aschonfeld** [comment]
Updated in v1.29.0
