### ISSUE TITLE
when color scale has just one color it shows error

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#349]
I had some exploration in the map chart when the color chart just has a color, after switching to another chart it shows this error. in my opinion for another chart like surface or heat map we the chart tab is activated shows an alarm that the color chart should have at least two colors.

![image](https://user-images.githubusercontent.com/2202483/101939779-769b3500-3bb3-11eb-970e-d7c519c18911.png)

**Comment by aschonfeld** [comment]
This error actually isn't related to the colorscale, but the fact that you've chosen a grouping (View, Bathrooms w/ No Aggregation) which contains duplicates.  If you apply an aggregation I'm sure it will work.

I can work on adding a better exception message

**Comment by aschonfeld** [comment]
Exception messages updated in v1.29.0
