### ISSUE TITLE
Charts with x as index

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#350]
I need the below chart

![image](https://user-images.githubusercontent.com/2202483/101944282-75213b00-3bba-11eb-975b-8d526df18fc7.png)

For the x axis, it is needed to have the df.index() as an option. and also please make it as default. sometimes just exploring one column is important

**Comment by aschonfeld** [comment]
Added in v1.29.0, in order to use this feature simply leave the X-axis dropdown blank
