### ISSUE TITLE
Liner curve on histogram in description column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#351]
Now histogram doesn't show well the long tail for example if the below graph has liner cure it could show the long tail
![image](https://user-images.githubusercontent.com/2202483/101946328-d34f1d80-3bbc-11eb-923f-65ece9b1bbba.png)

Like
![image](https://user-images.githubusercontent.com/2202483/101945902-89fece00-3bbc-11eb-9829-f10a7fa51c59.png)

**Comment by reza1615** [comment]
Seaborn's graphs are more pretty and the displot has the liner option
```
import seaborn as sns
sns.displot(x, kde=True)
```

**Comment by aschonfeld** [comment]
Not sure if this is correct or not but I'm trying to add the KDE using this code:
```
import scipy.stats as sts

hist_data, hist_labels = np.histogram(df[[selected_col]], bins=bins)
kde = sts.gaussian_kde(df[selected_col])
kde_data = kde.pdf(hist_labels[:-1])
```

Here's a sample image:
![image](https://user-images.githubusercontent.com/11547371/102801305-08a8f780-4383-11eb-9d73-6fbd09510cc8.png)

**Comment by aschonfeld** [comment]
Added in v1.29.0
