### ISSUE TITLE
cleaning for word counts and value counts

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#356]
1- Please also add the cleaning to the value counts (i.e. to sum **new_york** and **new york**)
2- Please also add the **hyphen, en dash, em dash, u002D, u2011** to space (i.e. balnk-sablon to blank sablon)
3- Also please add number two to the column cleaning in the column building part
4- apply #357 before all cleanings
5- Please change dropdown with one selection to dropdown with multi-select. to have multi-function at the same time

![image](https://user-images.githubusercontent.com/2202483/102225221-f297c480-3eb4-11eb-8617-81c7d358559a.png)

![image](https://user-images.githubusercontent.com/2202483/102225514-4f937a80-3eb5-11eb-860c-d3fd4e768765.png)

**Comment by aschonfeld** [comment]
Added in v1.29.0
