### ISSUE TITLE
kurt and skew

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#358]
Thank you for the nice implementation.
please in the below screenshot put them near to each other both should be the last case. they are in the same characteristic group 
![image](https://user-images.githubusercontent.com/2202483/102226880-ed3b7980-3eb6-11eb-87f8-6cb0a6119cbb.png)
It would be nice to have a small information symbol in from of these metrics and have a text hover description and link to the useful documentation.

![image](https://user-images.githubusercontent.com/2202483/102227197-4c00f300-3eb7-11eb-9487-2b42e01aa79c.png)

Information:

**Skewness**:
Measures the symmetry of the distribution.
* Fairly symmetrical: skewness is between -0.5 and 0.5
* Moderately skewed: skewness is between -1 and — 0.5 or between 0.5 and 1
* Highly skewed: skewness is less than -1 or greater than 1
![image](https://user-images.githubusercontent.com/2202483/102239758-31357b00-3ec5-11eb-9469-309781595af5.png)

Image source: https://en.wikipedia.org/wiki/Skewness#/media/File:Relationship_between_mean_and_median_under_different_skewness.png

**kurtosis**: Determines the heaviness of the distribution tails.
* Leptokurtic (more than normal dist hight) : Kurtosis > 3
* Mesokurtic (normal dist hight): (Kurtosis=3)
* Platykurtic (less than normal dist hight): (Kurtosis <3)

![image](https://user-images.githubusercontent.com/2202483/102240675-1dd6df80-3ec6-11eb-832f-80af32709172.png)

Image source:
https://analystprep.com/cfa-level-1-exam/quantitative-methods/kurtosis-and-skewness-types-of-distributions/

**Comment by reza1615** [comment]
2- error in the calculating skew and kurt (column 13 and 14 in the http://alphatechadmin.pythonanywhere.com/dtale/main/4)

![image](https://user-images.githubusercontent.com/2202483/102239024-6d1c1080-3ec4-11eb-987b-1688109b38e4.png)

![image](https://user-images.githubusercontent.com/2202483/102239108-802ee080-3ec4-11eb-8c04-4fb6061b6958.png)

**Comment by reza1615** [comment]
3- please also add skew and kurt in the histogram page 
![image](https://user-images.githubusercontent.com/2202483/102245155-3695c400-3ecb-11eb-9637-cb23a0c52a2e.png)

**Comment by aschonfeld** [comment]
Added in v1.29.0
