### ISSUE TITLE
Network graph

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#361]
It would be nice to have a graph visualization. I found [this](https://github.com/visjs/vis-network) project. it can be useful to show the connection and interaction between nodes. the input data can be in the below format

From | To | Weight
-- | -- | --
u1 | u2 | 0.3
u1 | u3 | 2
u2 | u1 | 1.5

Also, the dash implementation is in [here ](https://github.com/plotly/dash-cytoscape) and [here](https://github.com/jimmybow/visdcc)

**Comment by reza1615** [comment]
Intresting implementaion 
https://bl.ocks.org/almsuarez/4333a12d2531d6c1f6f22b74f2c57102

**Comment by aschonfeld** [comment]
I’ve actually used this same component at a previous job, but this seems very overkill for D-Tale.  This is more usable for a completely unstructured piece of data

**Comment by reza1615** [comment]
Ok if you don't have plan for that please feel free to close the ticket.

**Comment by aschonfeld** [comment]
@reza1615 you managed to pique my interest after all.  Here's what I have so far for your test data: 
![image](https://user-images.githubusercontent.com/11547371/103245862-89419800-492f-11eb-8fa5-b0c5f3818461.png)

I plan to add a dropdown for grouping and whether it applies to "To", "From" or both.  If you selected a grouping then a legend of the values and colors will also be displayed. This is using vis-network.

**Comment by reza1615** [comment]
Thank you for adding this part.
If you are agree we can add some network based functionalities to analyze data, based on graph logics. 
we use network theory for clustering and node relationship and node bundling

**Comment by aschonfeld** [comment]
Is there any way to achieve these things using features found in these examples? https://visjs.github.io/vis-network/examples/

**Comment by reza1615** [comment]
which data do you want to archive. do you mean the examples?

**Comment by reza1615** [comment]
> Is there any way to achieve these things using features found in these examples? https://visjs.github.io/vis-network/examples/

the codes are in cloud icon and most of the just modify the option var.
I am so intrested on an option which you select a node. It highlight the node + first links and fade the rest.

**Comment by aschonfeld** [comment]
Sorry, I meant are there any examples which illustrate the "clustering" logic you're looking for?  I've never really written code for that before.  I believe i've already built the highlighting logic you're looking for (I added a couple more nodes for the demo):

https://user-images.githubusercontent.com/11547371/103253255-670b4280-494e-11eb-9dc5-42517b31db57.mov

**Comment by reza1615** [comment]
I will open new tickets for the network functionalities

**Comment by reza1615** [comment]
please add edge direction as an optional column

**Comment by reza1615** [comment]
also I found https://flourish.studio/visualisations/network-charts/

**Comment by reza1615** [comment]
also please add graph display method to show graph as tree, circle, hierarchy,...

**Comment by aschonfeld** [comment]
added in v1.30.0
