### ISSUE TITLE
Pre-hide Columns Upon Load?

### ISSUE THREAD

**Issue by vijaydewan** [man-group/dtale#363]
Hi, is it possible to pre-hide columns upon load that could be made visible via the Describe page?  Thanks again for all of your help!

**Comment by aschonfeld** [comment]
I like this idea. So what I can do it add a couple optional parameters to the `dtale.show` function:
* `show_columns=`: this would take a list of string column names and only show those on initial load
* `hide_columns=`: this would take a list of string column names and hide those on initial load

For the time being, a hack to get this programmatically would be to do the following:
```
import dtale
import dtale.global_state as global_state

dtale.show(df) # take the data_id from the URL created from this (i.e. the number at the end http://.../dtale/main/1 -> 1 is your data_id)

for col in global_state.get_dtypes(1):
  if c in columns_you_want_to_hide:
    c['visible'] = False
```
Once you have set those `visible` flags just refresh your screen

**Comment by aschonfeld** [comment]
Added in v1.29.0

**Comment by vijaydewan** [comment]
Thanks again for all of your help Andrew!  Really appreciate it.

**Comment by ecinfosolutions** [comment]
Thanks Andrew!

**Comment by aschonfeld** [comment]
@ecinfosolutions No problem, feel free to toss your ⭐ on the repo

**Comment by vijaydewan** [comment]
Done! Thanks again!  Sorry, I'm new to GitHub otherwise would have absolutely done sooner.

**Comment by aschonfeld** [comment]
No worries! Thanks 🙏
