### ISSUE TITLE
Bug in KDE

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#365]
Thank you for implementing KDE. It has bug for some columns
![image](https://user-images.githubusercontent.com/2202483/103002739-724d1100-44fd-11eb-91b8-d574356a7a01.png)
![image](https://user-images.githubusercontent.com/2202483/103002806-990b4780-44fd-11eb-8531-46132db65db5.png)

**The KDE's bump should go upper than the actual data**
![image](https://user-images.githubusercontent.com/2202483/103002879-bc35f700-44fd-11eb-9fb5-1e8f8bd3b618.png)

**Comment by aschonfeld** [comment]
fixed in v1.29.1
