### ISSUE TITLE
simple Word cloud

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#369]
The below chart doesn't show any result. at least it should show world cloud base on City count.

![image](https://user-images.githubusercontent.com/2202483/103006897-7169ae80-4500-11eb-812d-043c687d4d19.png)

**Comment by reza1615** [comment]
Like https://www.wordclouds.com/

for this table. the weight can be count of words
![image](https://user-images.githubusercontent.com/2202483/103007038-b68de080-4500-11eb-87a3-24e700e3a3c5.png)

![image](https://user-images.githubusercontent.com/2202483/103007017-ab3ab500-4500-11eb-8b09-19592dbba1ac.png)

**Comment by aschonfeld** [comment]
Ok, so this would be an option to build charts strictly off of the X axis.  I'll have to think about how that would work behind the scenes.

For the time being, you could "Summarize Data" to create a new dataframe consisting of cities and their counts and then feed that data into the chart builder.  It should give you what you want.

**Comment by aschonfeld** [comment]
added in v1.29.1
