### ISSUE TITLE
Have an option to turn off live chart renderer

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#370]
It would be nice to have a radio button to turn off the live chart renderer. for some of the charts changing parameters cause render the chart multi times and take a while to get each result. for example try to product the below chart

when I want to remove condition 4 and 5 from the groups. it renders the chart multi time which isn't needed.

![image](https://user-images.githubusercontent.com/2202483/103007815-15a02500-4502-11eb-9714-f2176bb03738.png)

**Comment by aschonfeld** [comment]
I agree this is annoying.  The only way around this is to remove live updates altogether and add a “Load”(or whatever text you like) button which will build the chart when clicked.

**Comment by reza1615** [comment]
For example render the chart button

**Comment by reza1615** [comment]
It can be a switch button to **Turn on/off** auto render
![image](https://user-images.githubusercontent.com/2202483/103569895-1d62b080-4e96-11eb-8b68-777221940b6b.png)

**Comment by aschonfeld** [comment]
Here's how it would work: 

https://user-images.githubusercontent.com/11547371/104547616-f6764e00-55fc-11eb-9719-f1b1f6527cd1.mov

**Comment by reza1615** [comment]
That is great. is it possible to change its color to green or red or darker blue? because it functionality group is different from the others

**Comment by aschonfeld** [comment]
Here's the final product:

https://user-images.githubusercontent.com/11547371/104677978-73b2c900-56b8-11eb-9f74-7c0c79aa35cc.mov

**Comment by aschonfeld** [comment]
added in v1.31.0
