### ISSUE TITLE
Remove duplicated values (Keep First, last, remove both)

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#372]
Please add remove duplicates with these options in the chart windows.

**Duplicated values** 
-  Keep the first (as default)
-  Keep the last
-  Remove both
-  Keep both

**Comment by reza1615** [comment]
Sorry! I found them in the aggregations. In my opinion **First** or **Last** is not clear. may be
Keep Last
Keep First 
are more clear

**Comment by aschonfeld** [comment]
The idea is that these are the names of the pandas aggregations available so I would think most users would know what "First" & "Last" would mean.  That being said I can update the labels to "Keep First" & "Keep Last".

For "Remove all Duplicates" is this what you mean?

You data is:

|a|b|
|---|---|
|1|1|
|1|2|
|1|2|
|1|3|
|2|1|
|2|2|
|2|2|

You choose x = 'a', y = 'b' and aggregation = 'Remove all Duplicates' and here's your output:

| a | b |
| ---  | --- |
| 1 | 1 |
| 1 | 2 |
| 1 | 3 |
| 2 | 1 |
| 2 | 2 |

**Comment by reza1615** [comment]
remove both just keep cases which doesn't have duplicate
1 1
1 3
2 1

**Comment by aschonfeld** [comment]
Thanks for the “use case” since it did not make any sense to me initially

**Comment by aschonfeld** [comment]
added in v1.29.1
