### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#375]
In the below chart instead of this hug error log, it is much better to have a single line error  which has a link to the detailed error in an external or popup window.
![image](https://user-images.githubusercontent.com/2202483/103011167-7847ef80-4507-11eb-80d2-54e644fc1a2a.png)

**Comment by aschonfeld** [comment]
The error message is like that so the user can tell what groups it has available and then they can copy and paste the values they'd like into the query input box [ex: `security_id in (1,2,3,...)`]

For this example it doesn't make sense.  For this example I'd suggest using a 3 dimensional chart  like a heatmap.  Your "Bins" idea in the next issue is an interesting option for this though.
