### ISSUE TITLE
In the charts having bins of continues variable 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#376]
Columns with continues variables It would be nice to have bin option instead of Group(s). 
For example in the below chart Price group based on the actual value doesn't make sense and it is recommended to have bin number instead of Group(s). 

![image](https://user-images.githubusercontent.com/2202483/103011584-2ce21100-4508-11eb-95ba-e7e6a582dfa6.png)

**Comment by reza1615** [comment]
When number of groups are more than 30 it can suggest n bins instead of the actual values and the warning.
Group(s) labels can be range
![image](https://user-images.githubusercontent.com/2202483/103012259-53ed1280-4509-11eb-9b35-3089fe5f2a79.png)

**Comment by aschonfeld** [comment]
added in v1.31.0
