### ISSUE TITLE
adding cleaning functions to the word cloud chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#378]
It would be nice to have cleaning function also with wordcloud chart

**Comment by aschonfeld** [comment]
Real estate is limited in the chart builder, the easiest way to achieve this is to use the column builder and create a new column with the desired cleaners and then build your chart using that column.

**Comment by reza1615** [comment]
that is true but the main purpose is to explore the data on fly. now word count histograph is fantastic which has on fly cleaning functions

**Comment by aschonfeld** [comment]
@reza1615 sorry forgot I added cleaners to the chart builder back in version 1.41.1
