### ISSUE TITLE
Kill specific instances 

### ISSUE THREAD

**Issue by ecakashjadhav** [man-group/dtale#383]
how to kill specific running instances using data_id. I get all instance id and trying to kill instances but I not able to do that.
Thanks.

**Comment by aschonfeld** [comment]
So there are a couple variations on this.  One option is to "kill" D-Tale as a whole.  You can achieve this in a few ways:

**Find your instance and kill it (thus killing D-Tale as a whole)**
```python
import pandas as pd
import dtale

df = pd.DataFrame([1,2,3,4])
dtale.show(df)
dtale.instances()  # this should print out the IDs, names and URLs of any running pieces of data
dtale.get_instance(id)  # "id" is a value you take from the information displayed by running the previous line
```

**Store your instance in a variable and use the `kill` function on it (thus killing D-Tale as a whole)**
```python
import pandas as pd
import dtale

df = pd.DataFrame([1,2,3,4])
d = dtale.show(df)
d.kill()
```

**Drop a specific piece of data from a running instance of D-Tale (without killing it as a whole)**
```python
import pandas as pd
import dtale
import dtale.global_state as global_state

df = pd.DataFrame([1,2,3,4])
d1 = dtale.show(pd.DataFrame([1,2,3,4]))
d2 = dtale.show(pd.DataFrame([1,2,3,4]), ignore_duplicates=True)
global_state.cleanup(d1._data_id)  # this will remove any data associated with the data_id for d1, but leaving d2
```

Hope this helps, let me know if you have any other issues

**Comment by ecakashjadhav** [comment]
Thanks but I want to kill instances in different views. for eg: I have run instances in user login and I want to kill instances when the user clicks on the button or specific view

and another question How to get running instances names I use 'startup(" ",data=data, name=name)' to run instances in a loop

**Comment by aschonfeld** [comment]
Ok, I think I was misunderstanding earlier.  I thought you wanted to kill a specific D-Tale "process" not an specific "instance" (piece of data).  So this is possible through the UI.  If you click the "Instances" button from the main menu (click the triangle in the upper lefthand corner):  
![image](https://user-images.githubusercontent.com/11547371/103357974-7a1f2f00-4a82-11eb-8fb3-d1e093fa45f2.png)

Then from there you can click the trashcan on the left of each row of the grid in the "Instances" popup.  Currently this button is only available for instances you're not actively viewing: 
![image](https://user-images.githubusercontent.com/11547371/103358025-9de27500-4a82-11eb-8d53-ffe6d3c32b5e.png)

> and another question How to get running instances names I use 'startup(" ",data=data, name=name)' to run instances in a loop

If you are able to view D-Tale from the browser then using the approach I detailed earlier should work, but if you have access to the python terminal or jupyter notebook which called `startup` then you can run the following to drop specific pieces of data "instances":
```
import dtale.global_state as global_state
 
for data_id in global_state.get_data():
  name = (global_state.get_metadata(data_id) or {}).get('name')
  print(data_id, name)
  # this will drop the data and clean up all other information associated with that data
  # WARNING: removing all data will bring D-Tale to the base state where you'll be auto-directed to a
  #                    page where you can "Upload" data to it.
  global_state.cleanup(data_id)
```

Now if you are calling `startup` from within an app then this snippet can be used within your app somewhere to clear data as well.  And you can get the set of active data IDs in your app by returning the output of `global_state.get_data().keys()`.

Hope this helps, good luck

**Comment by ecakashjadhav** [comment]
Thank you
