### ISSUE TITLE
Random percentage doesn't work properly on detailed map chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#385]
It has lagged on choosing the percentage. for example, at the first it is 100% after selecting 10% it shows 100% data after switching to 20% it shows the previously selected percentage (10%)

After 10% > 100% now it should show all data but shows 10% data (previously selected percentage)
![image](https://user-images.githubusercontent.com/2202483/103559040-8260db00-4e83-11eb-8086-3856ee1b21b5.png)
After 100% > 20% now it should show 20% data but shows 100%
![image](https://user-images.githubusercontent.com/2202483/103559131-a6242100-4e83-11eb-9cca-33456dd786e9.png)

**Comment by aschonfeld** [comment]
Should be all set now.  I just needed to upgrade the version of `dash` on the demo site.
