### ISSUE TITLE
treemap error

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#388]
![image](https://user-images.githubusercontent.com/2202483/103570853-d5dd2400-4e97-11eb-9eb9-b638bee08e8b.png)

**Comment by aschonfeld** [comment]
@reza1615 any chance you can send me a sample of the data causing this?

**Comment by reza1615** [comment]
The data is instance 2 (rolling data) and selected columns are in the Screenshot

**Comment by aschonfeld** [comment]
I'm interested, what exactly are you trying to do here.  It looks like you're just choosing random columns.  If you can explain the validity of the chart you're constructing then I'll continue digging into this, otherwise I'm just going to chalk this up to an invalid use case.

**Comment by reza1615** [comment]
The data is toy and it is meaningless. In my opinion Dtail needs to show proper warning or doesn't show any thing instead of showing consul error.

**Comment by aschonfeld** [comment]
In my opinion the warning is correct.  There is no data for for that group because the group value (a float) is truncated to a certain amount of decimal points so when it goes to filter on it nothing is returned.

Not sure what other type of warning shoul

**Comment by reza1615** [comment]
Also applying bin idea

**Comment by aschonfeld** [comment]
I think i’ll start on the “binning” tomorrow

**Comment by aschonfeld** [comment]
Closing this because "binning" is covered by [#376](https://github.com/man-group/dtale/issues/376)
