### ISSUE TITLE
This site can’t be reached // refused to connect.

### ISSUE THREAD

**Issue by helloworldnoob** [man-group/dtale#394]
Dtale is awesome! Thanks for creating it.

I have just switched over to Atom editor instead of the basic python ide. Now dtale wont load in my browser with the message:
'This site can’t be reached 
refused to connect.'

Anyone know how I can get it working again?

**Comment by aschonfeld** [comment]
Try adding host=‘0.0.0.0’ to your dtale.show call

if that works i can show you how to setup a config file so that you wont have to set that parameter everytime you start D-Tale

**Comment by helloworldnoob** [comment]
Thanks but I am now getting '0.0.0.0 refused to connect.' 

Any ideas?

**Comment by aschonfeld** [comment]
I’ll try downloading atom myself and seeing if I run into any issues.  Couple other questions:

* what OS are you running? I’m on MacOS
* what URL gets pronted after you call dtale.show?
* how are you starting D-Tale? From a script, python console or debug process?

**Comment by aschonfeld** [comment]
@helloworldnoob I installed atom on my Mac and I was able to get D-Tale running from it.  I'm going to make the assumption that you are trying to run D-Tale from within a python script and not a python console debug process.  This means that you'll need to run D-Tale as a long-running process (the default behavior is it tries to run it in a separate thread which will die automatically if you're running a script).  Here's an example of running D-Tale in a script as a long-running process:
```
import dtale
import pandas as pd

if __name__ == '__main__':
  dtale.show(pd.DataFrame([1,2,3,4,5]), subprocess=False)
```

I was able to run a python script from within Atom using the [scripts](https://atom.io/packages/script) package but I'm assuming you have more experience with Atom than I do 😉 

Good luck, hope this helps

**Comment by helloworldnoob** [comment]
Awesome man thanks for going to that length to help me out! 
Legend! I just used your code with a variation to show my own, as follows:
```
if __name__ == '__main__':
  d = dtale.show(df2, subprocess=False)
d.open_browser()
```

Thank you very much! :D I did write more about your questions but I tried your code and that fixed the problem :)

**Comment by aschonfeld** [comment]
Great! Happy to help. I’ll close this and feel free to toss your ⭐️ on D-Tale
