### ISSUE TITLE
column describtion

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#396]
In the below Screenshot there are these issues:
* date type doesn't have kuratosis metric
* float column the diff desc show as day diff
![Screenshot_20210116-230607_Chrome](https://user-images.githubusercontent.com/2202483/104830812-4bf66900-5850-11eb-8f82-76d452b222b9.jpg)
![Screenshot_20210116-230531_Chrome](https://user-images.githubusercontent.com/2202483/104830816-4ef15980-5850-11eb-94ca-3474800e9119.jpg)

**Comment by aschonfeld** [comment]
I'll look into the first issue. As for the second I can't seem to reproduce it, locally or on the demo site.

**Comment by reza1615** [comment]
The second one the lag exists in demo. now I checked it has lag of last column asc data

**Comment by aschonfeld** [comment]
Can you send a screen recording? I was not able to reproduce

**Comment by reza1615** [comment]
Uploading 20210117_124816.mp4…

**Comment by reza1615** [comment]
select a float column > select date column > select float 
You will see it has lag and shows previous types data

**Comment by aschonfeld** [comment]
Thanks that really helps, I'll take a look

**Comment by aschonfeld** [comment]
Fixed in v1.32.0
