### ISSUE TITLE
binning numeric column in chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#397]
I search on demo version and I couldn't find the binning float columns.

**Comment by aschonfeld** [comment]
So it's there but in order to activate it you must have a float column selected as a group:

https://user-images.githubusercontent.com/11547371/104847928-93acdd00-58b0-11eb-8cbf-0184d2d8affd.mov

**Comment by reza1615** [comment]
It is intresting I couldn't reproduce your Ui in demo!
![Uploading Screenshot_20210117-111421_Chrome.jpg…]()

**Comment by aschonfeld** [comment]
My screen recording was using the demo

**Comment by aschonfeld** [comment]
Ahh its because price is an integer.  I guess i can add logic that checks how many unique values exist for that integer when deciding whether yo use groups or binning.  Right now it considers integers to be categoricals

**Comment by reza1615** [comment]
In my opinion we can have 
* both bin and group for int
* bin for float

**Comment by reza1615** [comment]
Also please add binning based on data frequency
https://www.google.com/amp/s/www.geeksforgeeks.org/binning-in-data-mining/amp/

when user selected frequency the input is the number of bins but inside bins number of samples are equal

**Comment by reza1615** [comment]
https://pbpython.com/pandas-qcut-cut.html

**Comment by aschonfeld** [comment]
Currently the bins are calculated using `qcut`.

**Comment by reza1615** [comment]
We can have this buttons 
![image](https://user-images.githubusercontent.com/2202483/104921397-3b84e200-5967-11eb-868f-1e663378d633.png)

and their hover mouse can be these:
* Bins have equal frequency
* Bins have equal width

**Comment by aschonfeld** [comment]
https://user-images.githubusercontent.com/11547371/105123685-83f6e980-5aa6-11eb-9108-c00f90bb8c62.mov

**Comment by reza1615** [comment]
That is great

**Comment by aschonfeld** [comment]
Added in v1.32.0
