### ISSUE TITLE
charts x, y, z dropdowns box should only suggest numeric column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#398]
charts x, y, z dropdowns box should only suggest numeric column. I.e. bar chart x drop down has city column in its suggestions.

**Comment by aschonfeld** [comment]
So I don't think your logic is correct. Why wouldn't users be allowed to select strings for the x-axis in a bar chart?  I could understand the y-axis only being numeric data, but you should be able to select string values for the x-axis.  For example:

![image](https://user-images.githubusercontent.com/11547371/104848037-1fbf0480-58b1-11eb-9d83-8b0d3ca19f53.png)

Ultimately I think it's on the user to realize that strings can't be used for numeric operations and I think throwing an exception to the screen should be sufficient behavior. Also, string columns are valid selections if your aggregation is set to something like "Count"
