### ISSUE TITLE
column!=column

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#399]
In this binning what does lat!=lat means? does it mean these values are None or empty values? If it means missing values may be having another label is more clear like missing data, None data

![image](https://user-images.githubusercontent.com/2202483/104920375-ab926880-5965-11eb-9f17-64f6e4dfa773.png)

**Comment by aschonfeld** [comment]
It means NaN values, i’ll see what I can do but that value is what gets user for building the popup chart so it’s not a trivial task.  Trust me, i tried when i was originally building it

**Comment by aschonfeld** [comment]
Fixed in v1.32.0
