### ISSUE TITLE
Show Top 5, 10, etc. on barsort when aggregating

### ISSUE THREAD

**Issue by vijaydewan** [man-group/dtale#401]
Hey @aschonfeld,

Thanks again for all your amazing work on this.  I was wondering if it was possible to include an option in the charts function that allows you to only show top 5/10/etc. when you're doing a bar sort by aggregation (e.g., sum or mean).  There may be a lot of categorical data and you want to only see the top few.  Thanks!

**Comment by aschonfeld** [comment]
Sure thing, I've already added this feature to the "Column Analysis" popup

https://user-images.githubusercontent.com/11547371/105128623-59f6f480-5ab1-11eb-819b-8f7adabcc2c5.mov

**Comment by vijaydewan** [comment]
Thanks!  Would it be possible to add it to the chart feature as well?  This way you can pick the top in one column when comparing with another column.  Eg. top five "Exterior color" when summing "Price"

**Comment by aschonfeld** [comment]
I was actually just putting the finishing touches on this 😄 

https://user-images.githubusercontent.com/11547371/105644760-435fed00-5e65-11eb-92aa-8149f1f0c486.mov

**Comment by vijaydewan** [comment]
Looks amazing!  Can't wait to play around with it!  Thanks again.

**Comment by aschonfeld** [comment]
Added in v1.32.0
