### ISSUE TITLE
column description value counts

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#405]
After adding cleaning to the value_counts it will be useless.

https://user-images.githubusercontent.com/2202483/105761621-6059f600-5f21-11eb-910b-d31189ea0c84.mp4

**Comment by aschonfeld** [comment]
Not sure what this means and the video doesnt play

**Comment by reza1615** [comment]
https://user-images.githubusercontent.com/2202483/105768520-7cae6080-5f2a-11eb-8263-92368a85d6bb.mp4

**Comment by reza1615** [comment]
in my opinion cleaning function the string functionalities just  should load for string column not int, float and date

**Comment by aschonfeld** [comment]
got it, will update that.  Thanks

**Comment by aschonfeld** [comment]
Fixed v1.32.1
