### ISSUE TITLE
Timeseries smoothing

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#407]
Please Also add move hover for Alpha

"Alpha is a smoothing factor that takes values between 0 and 1. The alpha number near 0 makes data more abstract and smoother than 1."

**Comment by aschonfeld** [comment]
![image](https://user-images.githubusercontent.com/11547371/105775694-33afd980-5f35-11eb-80f8-021e907544af.png)

**Comment by aschonfeld** [comment]
Added in v1.32.1
