### ISSUE TITLE
Unique count warning

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#411]
Please check against the Stock dataset.
In my opinion, instead of this message, it can just get the unique count and add a warning message like:
"Instead of count unique count used"
 
![Screenshot from 2021-01-26 11-45-43](https://user-images.githubusercontent.com/2202483/105875667-137f2980-5fcc-11eb-925e-0c31f4aef857.png)

**Comment by aschonfeld** [comment]
I think this is more of a scenario where "Count" shouldn't be an option for Category because of the fact that Category analysis brings back "Count" by default as a way to draw the line for Frequency.  Good catch though!

**Comment by aschonfeld** [comment]
Fixed in v1.33.0
