### ISSUE TITLE
Q-Q plot in column description

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#413]
It would be nice to have Q-Q plot in column description to have a better understanding of data distribution.
Implementation: https://stackoverflow.com/questions/13865596/quantile-quantile-plot-using-scipy
About Q-Q: https://data.library.virginia.edu/understanding-q-q-plots/#:~:text=A%20Q%2DQ%20plot%20is%20a,a%20line%20that's%20roughly%20straight.

**Comment by aschonfeld** [comment]
Boom 

https://user-images.githubusercontent.com/11547371/106228333-2276ff00-61b9-11eb-871c-c26869b8d49a.mov

**Comment by reza1615** [comment]
Thank you for swift implementation
is it possible also  to add the regression line?

**Comment by reza1615** [comment]
the green line
![Screenshot_20210128-231959_Samsung Internet](https://user-images.githubusercontent.com/2202483/106231304-5fde8b00-61bf-11eb-817f-1f917618b386.jpg)

**Comment by aschonfeld** [comment]
I wanted to but the probplot function only returns a few points for the line of best fit. I didnt really know how to plot that.  Does it mean just evenly place those few points along the axis?

**Comment by reza1615** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.probplot.html

**Comment by aschonfeld** [comment]
That doesnt really tell me anything. When i tried using the output of the least-squares fit it was just giving me 3 floats for the example on stackoverflow.  I’m not sure how to turn that into a plot(the red line).

if you could show me how to create an array of points (x/y coords) representing the red line that would really help

**Comment by aschonfeld** [comment]
So I was able to get a trendline to show up using [chartjs-plugin-trendline](https://github.com/Makanz/chartjs-plugin-trendline)

Hopefully this looks fine for your use case.  The data in this video was built using the example from stackoverflow

https://user-images.githubusercontent.com/11547371/106292635-0c018f80-621b-11eb-96a5-5ec27b6db0f5.mov

**Comment by aschonfeld** [comment]
Added in v1.33.0
