### ISSUE TITLE
Chart Export Error When using "Top" option in Bar Charts

### ISSUE THREAD

**Issue by vijaydewan** [man-group/dtale#414]
Hey aschonfeld, I noticed a small issue when exporting a bar chart when using the new "Top" feature.  Since it is passing the variables via an html string, you need to re-define top_bars as an int, otherwise it will think it is a string and throw an error.  I added a quick fix below.  Just when you are using top_bars in df.head(),  add int(), so it's: df=df.head(int(top_bars)).  I hope that makes sense.  I also pasted the code below.

    def _build_sorted_bars(sort_col, series, data, hover_text, axes):
        df = pd.DataFrame(series)
        df = df.sort_values(sort_col)
        if top_bars:
            df = df.sort_values(sort_col, ascending=False)
            df = df.head(int(top_bars))
        data["data"][series_key] = {c: df[c].values for c in df.columns}
        tickvals = list(range(len(df["x"])))
        data["data"][series_key]["x"] = tickvals
        hover_text[series_key] = {
            "hovertext": df["x"].values,
            "hoverinfo": "y+text",
        }
        axes["xaxis"] = dict_merge(
            axes.get("xaxis", {}), build_spaced_ticks(df["x"].values, mode="array")
        )

**Comment by aschonfeld** [comment]
Great catch! I’m working on a branch with a few other bug fixes and i’ll include this with it. Hopefully get it out this weekend

**Comment by vijaydewan** [comment]
Thanks! Really appreciate it!

**Comment by aschonfeld** [comment]
Fixed in v1.33.0
