### ISSUE TITLE
Is it possible to display a heatmap of a single column?

### ISSUE THREAD

**Issue by alegonz** [man-group/dtale#415]
Hi, thanks for this great tool.

As the issue title says, is it possible to display a heatmap for a single column (and without hiding any other non-numerical columns)? Is it possible programmatically?

It would be very helpful to be able to see the values of other columns while looking at the values that standout from the heatmap (e.g. very red or very green).

If it is currently not possible and the above makes sense, perhaps I could help and contribute :)

**Comment by aschonfeld** [comment]
So I think what you're looking for right now is the "By Col" heatmap.  That will treat each column as its own separate heatmap and not be skewed by values from other columns.

What I would need to add for your use case would be the ability to un-hide the non-numerical columns.  I hid those by default just because originally the heatmap was something I constructed as something to "look pretty" and for that purpose the non-numerical columns we'ren't adding any value. That being said, for the purposes of "By Col" I can unhide the non-numerical columns if you think it proves valuable.

Once that happens you should be able to hide all columns except for the one column you want the heatmap for and then any non-numerical ones you like to compare values for and then click the "By Col" option for heatmap in the main menu.  Here is a video detailing how to do it (of course the non-numerical column get hidden in it, which I intend to change for you)

https://user-images.githubusercontent.com/11547371/106294949-d3af8080-621d-11eb-9194-5f32ab7dfb8c.mov

**Comment by alegonz** [comment]
Thank you for your thoughtful and thorough answer.

In the example you suggested, assuming non-numerical columns are not hidden, one would end up looking at a single numerical column with a heatmap together with any other non-numerical columns, right?

If that's the case then that's not quite what I meant. Sorry for the confusion, I realize now my original question was not properly posed. What I'm looking for is the ability to apply a heatmap to any numeric column of my choice (say, by clicking on the header and choosing the option, like I would for sorting or formatting), without affecting any other columns (regardless of their data type).

Say you have this dataset (just a toy example I made):
![toyexample](https://user-images.githubusercontent.com/26665243/106344591-01fc9100-62ee-11eb-8f49-59bdf9597906.png)

Then, if I am interested in the heatmap for the BMI of the patients while looking at other columns, I'd like to see something like this (just a mock image):
![toyexample_bmi_heatmap](https://user-images.githubusercontent.com/26665243/106344622-32442f80-62ee-11eb-8686-66d52a4b0233.png)

Pretty much like one would do in Microsoft Excel, for example.

Since a heatmap is meant as a visual aid, the reasons why it is preferable to apply it to a single column are:
* Very often one needs to check the values of other columns for samples that stood out from the heatmap (e.g. whether the patients with a "somewhat green" bmi are smokers or not). So it is useful to not hide any other columns.
* There are columns where a heatmap makes little sense and applying a heatmap to all numerical columns indiscriminately can be visually distracting. For example, id's, timestamps, latitude, longitude, zip codes, etc.

I hope the above made it clearer. Let me know what you think.

**Comment by aschonfeld** [comment]
@alegonz this is very clear and definitely doable! Thanks for the response. I’ll try and include this in my next release. I’ll send youa screen recording once I have something

**Comment by alegonz** [comment]
Thank you! Let me know if you need any extra hands for it, I'd be happy to help :)

**Comment by aschonfeld** [comment]
Alrighty, here ya go

https://user-images.githubusercontent.com/11547371/106347778-edd57700-628e-11eb-8c32-2c3cacb4bbdf.mov

**Comment by alegonz** [comment]
Wow, that was quick!
Looks good! 👍

**Comment by aschonfeld** [comment]
@alegonz just released v1.33.0 with this in it.  Let me know how it works out and feel free to toss your ⭐  on the repo if it helps you out.  Thanks for the suggestion 🙏

**Comment by alegonz** [comment]
@aschonfeld Thank you very much, it works great!

Just a minor observation: when the single-column heatmap is enabled, the By Col/Overall heatmap button is shown on fire. I don't know if that is what you intended, but if it is then nevermind.
![image](https://user-images.githubusercontent.com/26665243/106410710-c9dc8600-6486-11eb-86da-836e84fe654e.png)

> feel free to toss your :star: on the repo if it helps you

Starred since long ago!

**Comment by aschonfeld** [comment]
Ahh, great catch! I’ll address that. And thanks for the ⭐️

**Comment by aschonfeld** [comment]
Fixed the display issue in v1.33.1

**Comment by artemizawoodgate** [comment]
Thanks for improving this heatmap feature. Would it be possible to unhide an index or select non-numerical columns (e.g. date and name)? I love the "overall heatmap" feature as it looks at the outliers across a large table, but without the non-numerical index/columns it's a little harder to identify where the outliers are. The "by col" option works well in a small sample, but across a large table (where the heatmap comes especially handy as it's hard to spot the outliers visually), turning this on column by column is a bit harder. Also, if I understand it right, "by col" only computes the outliers in that specific column, while the "overall" feature looks at outliers in the entire table.

Thank you!

**Comment by aschonfeld** [comment]
@artemizawoodgate I have added the feature you're looking for and will include it in the next release.  Here's a demo:

https://user-images.githubusercontent.com/11547371/121287061-e19d9e00-c8ae-11eb-8c7f-bd8aaabc9110.mov

**Comment by artemizawoodgate** [comment]
Awesome, thank you very much!
