### ISSUE TITLE
Removed Python2.7 support?

### ISSUE THREAD

**Issue by AnthraX1** [man-group/dtale#420]
Hi,

In https://github.com/man-group/dtale/pull/419 you've removed Py2.7 support. Even though I don't use dtale with py27 direactly but I think we should just keep it for the sake of communitiy unless it's too hard to maintain support for both versions? Pypy2.7 is still actively supported and I use dtale with the Pypy sandbox.

**Comment by aschonfeld** [comment]
The reason why I removed it was because pypi is supposed to be removing support for python2 soon. But I can add it back in if you feel its necessary

**Comment by AnthraX1** [comment]
> The reason why I removed it was because pypi is supposed to be removing support for python2 soon.
> 
> I'll add it back in tomorrow, sorry about that

No need to feel sorry about anything, you are the creator and owner of the repo and I fully respect that. I'm just saying it would break some people's use case if we make breaking changes without warning.

**Comment by AnthraX1** [comment]
oh, issue #420, nice.

**Comment by aschonfeld** [comment]
Just added it back in v1.33.1
