### ISSUE TITLE
Replace 0 with nan doesn't work

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#421]
In the below code 
``` python
import dtale
import pandas as pd

df = pd.DataFrame({'year':[1992.0, 2005.0, 2011.0, 0.0, 2008.0, 1999.0, 1983.0, 2010.0, 0.0, 2002.0]})
```
I want to replace 0 with Nan
The replacement function doesn't work. Its snippet is ok.
![image](https://user-images.githubusercontent.com/2202483/106515817-36b24900-64a4-11eb-9cc6-9901a1fd1dad.png)

**Comment by aschonfeld** [comment]
Fixed in v1.34.0
