### ISSUE TITLE
Add sheet name selection in web upload

### ISSUE THREAD

**Issue by AnthraX1** [man-group/dtale#422]
In web upload popup, after a multi document file is uploaded, eg. excel, return a list of sheet names for user to pick before importing the DF into dtale. This feature could be used in other multi-doc files such as PDF with multiple tables inside.

Edit: I'm happy to do this but it'll take a few days.

**Comment by aschonfeld** [comment]
Here's what I got so far (I still need to add it for URL excel uploads)

https://user-images.githubusercontent.com/11547371/107109135-9180d300-680b-11eb-9205-c7a41b6ed07c.mov

**Comment by aschonfeld** [comment]
Some other notes on how this feature will work.
* If there is only one sheet in the file you've uploaded then it will automatically jump to the dataset
* I think I might switch to a modal window for presenting the sheet selection so it will prevent users from trying to upload additional files which would become tough to manage.

**Comment by aschonfeld** [comment]
Here's the final version and the same behavior applies to web uploads:
https://user-images.githubusercontent.com/11547371/107123470-c3c21d00-686b-11eb-8053-07e1cfd231c5.mov

**Comment by aschonfeld** [comment]
Here's the final version and the same applies to web uploads:

https://user-images.githubusercontent.com/11547371/107123502-e7856300-686b-11eb-8ee5-56b7ef03c5c0.mov

**Comment by AnthraX1** [comment]
It looks really awesome!

**Comment by aschonfeld** [comment]
Added in v1.34.0
