### ISSUE TITLE
Log scale for charts

### ISSUE THREAD

**Issue by ben-watt-es** [man-group/dtale#423]
I have been using dtale recently, and it would be useful if there was an option to enable a log scale for charts instead of the default scaling.

**Comment by aschonfeld** [comment]
Great suggestion! Will do

**Comment by aschonfeld** [comment]
@ben-watt-es 

https://user-images.githubusercontent.com/11547371/107166456-13940780-6984-11eb-8256-332680f03cd9.mov

**Comment by aschonfeld** [comment]
Added in v1.34.0
