### ISSUE TITLE
error on Merge & Stack

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#429]
Thank you for adding Merge & Stack. I tested it on the attached csv and shows this error.
![image](https://user-images.githubusercontent.com/2202483/107960926-3a999d00-6f73-11eb-83a4-5220dff81cbe.png)

Because of GitHub limitation I modified the csv extension to txt
[Dummy_Invoice.txt](https://github.com/man-group/dtale/files/5982226/Dummy_Invoice.txt)

**Comment by aschonfeld** [comment]
That file worked fine for me

https://user-images.githubusercontent.com/11547371/107992794-6df61f00-6fa7-11eb-94e0-21938c55036f.mov

**Comment by aschonfeld** [comment]
Cannot reproduce
