### ISSUE TITLE
Upload excel has bug

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#430]
I open the below excel file in Pandas with out any error but It is not possible to open it by upload in dtale. It shows the below error
[Dummy_Invoice.xlsx](https://github.com/man-group/dtale/files/5982263/Dummy_Invoice.xlsx)

![image](https://user-images.githubusercontent.com/2202483/107961374-d4f9e080-6f73-11eb-86c8-d7f355132bdd.png)

In below I opened it in pandas
![image](https://user-images.githubusercontent.com/2202483/107961462-f2c74580-6f73-11eb-8112-4fb1dab7d1fb.png)

**Comment by aschonfeld** [comment]
Small bug with the conversion of timestamps to floats for skew & kurtosis breakdowns.  Looks like it was returning an empty string for missing timestamps and it was later causing an issue.  Will have a fix included in the next release

**Comment by aschonfeld** [comment]
Fixed in v1.36.0
