### ISSUE TITLE
Merge & Stack the final code has some issues

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#432]
1- it has error to execute 

https://user-images.githubusercontent.com/2202483/108008714-00f67f80-6fcf-11eb-8e72-f2bcb8436178.mp4

**Comment by aschonfeld** [comment]
Good catch!  I just need to add `.data` to the end of every call to `dtale.get_instance`

**Comment by aschonfeld** [comment]
Fixed in v1.36.0
