### ISSUE TITLE
Merge & Stack doesn't work for duplicate column names

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#433]
When user doesn't set suffix and wants to merge two tables. if the columns have similar name. it doesn't work. In my opinion it should have a default value like 1_ and 2_ or A_ and B_

https://user-images.githubusercontent.com/2202483/108009220-394a8d80-6fd0-11eb-8711-b27e3c421606.mp4

**Comment by aschonfeld** [comment]
So this is expected, although the lack of exception message is not (that was working at one point).  I could try adding a better exception message to tell the users how to fix it, but I fear going down the path of adding automated logic to handle column name collisions could become unwieldy.

**Comment by aschonfeld** [comment]
Fixed display of error message in v1.36.0
