### ISSUE TITLE
pip install dev version missing dist folder

### ISSUE THREAD

**Issue by cdeil** [man-group/dtale#443]
I did this:
```
gh repo clone man-group/dtale
cd dtale
pip install .
```
and got this error when trying to start dtale:
```
Exception on /dtale/main/1 [GET]
Traceback (most recent call last):
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/dtale/views.py", line 973, in view_main
    return _view_main(data_id)
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/dtale/views.py", line 958, in _view_main
    return base_render_template("dtale/main.html", data_id, title=title, iframe=iframe)
  File "/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/dtale/views.py", line 925, in base_render_template
    if not len(os.listdir("{}/static/dist".format(os.path.dirname(__file__)))):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/dtale/static/dist'
```
So the problem is here:
https://github.com/man-group/dtale/blob/d3559bf5d8361be92a56be57306dae51bf3ee982/dtale/views.py#L925
because with `pip install .` there will be no `dist` folder, I have this:
```
% ls -1 /Users/cdeil/opt/anaconda3/envs/hpred_free_lime/lib/python3.8/site-packages/dtale/static
css
fonts
images
maps
```

I see the same error now when I tried with `python setup.py develop`.

Do you see or understand the issue?
Or should I try to create a reproducer with a Dockerfile?

**Comment by aschonfeld** [comment]
Yep, sorry forgot about this step.  You need to have node & npm installed.  Once you get that you can navigate to where you checked out the code and run:
* `npm run install`
* `npm run build`

Or if you have yarn installed, simply replace the `npm` with `yarn` in those commands

**Comment by cdeil** [comment]
Ah OK. Following the README instructions is a good idea after all. :-)

**Comment by zxhmike** [comment]
> Yep, sorry forgot about this step. You need to build the JS and in order to that you need to have node & npm installed. Once you get that you can navigate to where you checked out the code and run:
> 
> * `npm run install`
> * `npm run build`
> 
> Or if you have yarn installed, simply replace the `npm` with `yarn` in those commands

Just found this. Thank you Andrew. Note for the other folks: I did the following and it works for me:
- `npm install`
- `npm run build`

**Comment by aschonfeld** [comment]
@zxhmike great catch! I’ll be sure to update the documentation

**Comment by Balaguru16** [comment]
I was also facing the above mentioned problem.
so,i did npm install and tried npm run build.But,
I'm getting this error while running 'npm run build'

npm ERR! missing script: build

Can anyone help me out?Thanks:))

**Comment by Balaguru16** [comment]
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:350:20)
4 verbose stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16)
4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
5 verbose cwd /home/i_balagurum/Desktop/TICC/ticc_code/ticc_exp/dtale_final/dtale
6 verbose Linux 4.15.0-153-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
8 verbose node v12.22.1
9 verbose npm  v6.14.12
10 error missing script: build
11 verbose exit [ 1, true ]

This is complete log of the error
