### ISSUE TITLE
Jupyterlab running in Docker... How to enable dtale.show()?

### ISSUE THREAD

**Issue by gsimmskutta** [man-group/dtale#444]
This may be a documentation issue rather than a code issue. I am running a container with an in-house configured jupyterlab (port 8888) environment. When I try to run dtale.show(dataframe) within a notebook, I get a blank rectangle with the message: "[hostname]’s server IP address could not be found."

I've looked this up and there's this from the dtale docs:

![dtale_·_PyPI](https://user-images.githubusercontent.com/34314474/109337590-4a8e6800-7822-11eb-8ba3-e1a8b8b68ebf.png)

Aside from the broken formatting (take this issue as a call to fix that), I can't seem to implement the fixes. So far I have tried adding port 40000 to the container, and I have tried both the Mac and "everything else" fix. I'm using portainer to manage my containers and in its network configuration section I entered the host system's hostname for the container's hostname (which I believe is equivalent to the backticks on the hostname command in the suggested fix). I also tried changing the network type from bridged to host. 

Is the fix in the documentation for some kind of standalone dtale container? How can I get it to work nicely within (or alongside?) my main Jupyterlab container?

**Comment by aschonfeld** [comment]
Sorry about the formatting, I will fix that.  And yes this is for running a standalone D-Tale container.

As for your issue, I wonder if using Jupyter Server Proxy will solve your issues?  Here's some docs on how to use it: https://github.com/man-group/dtale#jupyterhub-w-jupyter-server-proxy

In the meantime I'll ping once of my colleagues who has done a lot of jupyter integrations.  @aflag have you seen anything like this before?

**Comment by aschonfeld** [comment]
Hmm, the formatting looks fine when I view it in my browser:
![image](https://user-images.githubusercontent.com/11547371/109342711-42422700-783a-11eb-926b-5dbd23f6e8a7.png)

**Comment by aschonfeld** [comment]
Oh I see it now, this is the documentation on PyPi.  Sorry

**Comment by gsimmskutta** [comment]
> As for your issue, I wonder if using Jupyter Server Proxy will solve your issues? Here's some docs on how to use it: https://github.com/man-group/dtale#jupyterhub-w-jupyter-server-proxy

We are not using JupyterHub, though.... Forging ahead anyway, I was encouraged by the fact that the server-proxy python and jupyter components don't seem to have have installation dependencies on jupyterHub, but following those directions in a vanilla jupyter lab results in a 404 message appearing in the notebook when I try to show().

**Comment by aschonfeld** [comment]
so if you try `d = dtale.show(...)` can you output the contents of `d._main_url` and then pasting that in your browser?  I wonder if this is an issue where its trying to use an invalid hostname

**Comment by gsimmskutta** [comment]
It comes out as `/home/username/proxy/40000/dtale/main/$n`, where `$n` is an integer that increments each time I try it.

This happens whether or not I start the container with -h `hostname`

**Comment by aschonfeld** [comment]
Ok, so the URL path (`'/user/username/proxy/40000/dtale/main/4'`) that seems to be getting generated makes me think that you are using server-proxy.

If it was not using server-proxy then the paths would look more like `http://[hostname]:40000/dtale/main/4`

**Comment by gsimmskutta** [comment]
I installed server-proxy, tried it, found it unusable, and uninstalled it, so I thought it was out of the picture, but the commands were still in the notebook. Now, running without a trace of server-proxy stuff:

```
d._main_url
'http://HOSTNAME:40000/dtale/main/2'
```

This gave me the idea of appending ".local" to the end of the hostname to get the zeroconf name (this is on my home network and I don't run name services), and when I pasted that, I got the dtale grid in my browser. 

I went back to portainer and changed the hostname for the container to `"HOSTNAME.local"`. After a restart, it appears to work! It even spawns new tabs when needed. Thank you for walking through this with me.

**Comment by aschonfeld** [comment]
Great!  Happy to hear it worked.  Apologies for the issues and I really appreciate you the prompt responses for info 🙏 If you haven't done so yet, feel free to toss your ⭐ on the repo.  Let me know of anything else that arises or new features.

**Comment by gsimmskutta** [comment]
Be careful what you wish for...

**Comment by aschonfeld** [comment]
🤣
