### ISSUE TITLE
Export to PNG has some errors in 

### ISSUE THREAD

**Issue by priyankguddu** [man-group/dtale#447]
Exporting PNG in line chart
{"error":"Invalid \\escape: line 1 column 104 (char 103)","success":false,"traceback":"Traceback (most recent call last):\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/dtale/views.py\", line 85, in _handle_exceptions\n    return func(*args, **kwargs)\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/dtale/views.py\", line 3120, in chart_export\n    output = export_png(data_id, params)\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/dtale/dash_application/charts.py\", line 3070, in export_png\n    write_image(chart, file=image_buffer, format=\"png\")\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/plotly/io/_kaleido.py\", line 245, in write_image\n    img_data = to_image(\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/plotly/io/_kaleido.py\", line 131, in to_image\n    img_bytes = scope.transform(\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/kaleido/scopes/plotly.py\", line 102, in transform\n    response = self._perform_transform(\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/kaleido/scopes/base.py\", line 201, in _perform_transform\n    self._ensure_kaleido()\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/site-packages/kaleido/scopes/base.py\", line 122, in _ensure_kaleido\n    startup_response = json.loads(startup_response_string)\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/local/mnt/workspace/PubBi\builds/conda/envs/dtale/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Invalid \\escape: line 1 column 104 (char 103)\n"}

**Comment by aschonfeld** [comment]
Any chance you can give me some more information on what type of chart you're generating?  I've already checked if I can generate a simple line chart on the latest version of `kaleido` (that handles the PNG generation) and it worked with no issue.  Helpful information would be:
* chart type
* does it have multiple y-axes?
* what is the data type of the x-axis?
* is there any extra formatting being applied?  Bar sorting?  Trendline?

**Comment by priyankguddu** [comment]
its a Line chart, X axis is integer with value from 100 to 65535 and Y has floating point on both axes

**Comment by aschonfeld** [comment]
Hmm, yea that doesn't help much.  I can create a line chart with an integer value x-axis & float y-axis and export to PNG with no issue.  Are you 100% certain that those are the data types of your axes?  

This error: `json.decoder.JSONDecodeError: Invalid \escape: line 1 column 104 (char 103)`

Leads me to believe there is an invalid value in your data somewhere that causes invalid JSON.  Is there NaNs or empty strings (`''`) somewhere?

**Comment by aschonfeld** [comment]
@priyankguddu are you still encountering this issue?  The only other thing I can recommend is re-installing kaleido.  If not, I'm going to close this issue.  Thanks

**Comment by priyankguddu** [comment]
Will check with the latest version and update the kaleido. 
@aschonfeld can we get Data loading slider both ways (as some time we have very large set and interesting data is towards end, if we can just load the Data frame to say load last 20% of data (right now u have from the 1st 20%-100%), that way the speed and response will be much faster 
![image](https://user-images.githubusercontent.com/25154108/113643429-28fd7900-9637-11eb-8087-9e93aa0917ad.png)

**Comment by aschonfeld** [comment]
Thanks for your help. If the PNG is still failing i may need you to send me a .har recording.

As for the “Load” slider its choosing a random sample of data so choosing a specific percentage doesnt actually choose data from the front or back.  I can try adding an option to allow that though. Shouldnt be hard.

**Comment by aschonfeld** [comment]
@priyankguddu just released v1.44.0 with that extra functionality on the "Load" slider to choose between random/head/tail.  To get the last 20% simply choose "Tail" & "20%"
