### ISSUE TITLE
Edit cells and update df

### ISSUE THREAD

**Issue by kurucan** [man-group/dtale#450]
We are able to edit the cells on dtale.show but I guess the changes does not get updated on the df. 

Is it possible to save edits to the df ?

**Comment by aschonfeld** [comment]
Hmm, it should get updated.  Couple questions?

* How are you checking your dataframe after editing? If you're starting D-Tale from a notebook you can do the following:
```
d = dtale.show(df)
d
```
And then after you've updated a cell from the app you should be able to view your changes in the underlying dataframe using:
```
d.data
```
* What was the data type of the cell you were updating? For example, were you updating a float to NaN?

Also, I just opened a python console and ran the following:
```
import dtale
import pandas as pd

d = dtale.show(pd.DataFrame([1,2,3,4]))
print(d._main_url)
```
Went to the UI and updated the first cell from 1 to 2 then went back to my console and ran:
```
d.data
```
I correctly saw the data updated from [1,2,3,4] to [2,2,3,4]

Please let me know if you hit any other issues or have any other questions

**Comment by aschonfeld** [comment]
@salihkurucan are you still having issues?  If not, I'll close this.  Happy to help more
