### ISSUE TITLE
Page goes blank when clicking on columns with parenthesis

### ISSUE THREAD

**Issue by dulti** [man-group/dtale#454]
Anaconda, python=3.8.8, pandas=1.2.3, dtale=1.40.1
Windows 10, Chrome 89.0.4389.90
When I'm clicking on the column headers with parenthesis in them, the whole page goes blank. Drops two errors in the JS console, see screenshot. 
![Screenshot 2021-03-21 183451](https://user-images.githubusercontent.com/7579568/111912845-2534f880-8a74-11eb-862d-b1cc6811b65a.png)
Found some older closed issues which addressed the same problem, but with periods and commas.
The column names look like this:
```
 0   Q1                                         3093 non-null   int64  
 1   Total Traffic(MB)                          3093 non-null   float64
 2   Downlink Throughput(Kbps)                  3093 non-null   float64
 3   Uplink Throughput(Kbps)                    3093 non-null   float64
 4   Downlink TCP Retransmission Rate(%)        3093 non-null   float64
 5   Video Streaming Download Throughput(Kbps)  3093 non-null   float64
 6   Video Streaming xKB Start Delay(ms)        3093 non-null   int64  
 7   Web Page Download Throughput(Kbps)         3093 non-null   float64
 8   Web Average TCP RTT(ms)                    3093 non-null   int64  
 9   Q2_1                                       3093 non-null   int32  
 10  Q2_2                                       3093 non-null   int32  
 11  Q2_3                                       3093 non-null   int32  
 12  Q2_4                                       3093 non-null   int32  
 13  Q2_5                                       3093 non-null   int32  
 14  Q2_6                                       3093 non-null   int32  
 15  Q2_7                                       3093 non-null   int32  
```

**Comment by dulti** [comment]
Now I've removed parens from column names, everything works as it should except for the column #4 - it has got the percentage sign in it, has the same effect.

**Comment by aschonfeld** [comment]
@dulti Got it, I'll dig into this.  Thanks for all the detail 🙏

**Comment by aschonfeld** [comment]
Already got a fix.  I'll let you know when I released a hotfix for it.  Sorry for the inconvenience.  If you get a sec please toss your ⭐ on the repo.  Thanks!

https://user-images.githubusercontent.com/11547371/111916253-5f8c9e80-8a50-11eb-9904-6de39f06cc1d.mov

**Comment by dulti** [comment]
Amazing! Thanks a lot! I sure will!

**Comment by aschonfeld** [comment]
v1.40.2 is now available on pypi and should be on conda-forge shortly.  Thanks again for your help
