### ISSUE TITLE
Unable to kill a single DtaleData instance

### ISSUE THREAD

**Issue by jnissin** [man-group/dtale#458]
Hey,

First of all thank you for your amazing work on this library. This has been one of the most useful data visualisation libraries paired with Jupyter for me. I am running Jupyter in a Google Cloud AI Platform Notebook instance. I can use dtale with the jupyter-server-proxy plugin by specifying the `app_root` to the `dtale.show` function:

```
dtale_data = dtale.show(df, name=name, app_root="/proxy/")
```

I get a valid instance which I can view embedded in Jupyter Lab as well as in another tab. The only thing that isn't working is when I try to kill the instance calling the `.kill()` function:

```
dtale_data.kill()
```

This results in an error:

```
---------------------------------------------------------------------------
MissingSchema                             Traceback (most recent call last)
<ipython-input-14-ab3ed06eab2c> in <module>
      1 import dtale
----> 2 dtale.get_instance(1).kill()

/opt/conda/lib/python3.7/site-packages/dtale/views.py in kill(self)
    219 
    220         """
--> 221         kill(self._url)
    222 
    223     def open_browser(self):

/opt/conda/lib/python3.7/site-packages/dtale/views.py in kill(base)
    132 
    133     """
--> 134     requests.get(build_shutdown_url(base))
    135 
    136 

/opt/conda/lib/python3.7/site-packages/requests/api.py in get(url, params, **kwargs)
     74 
     75     kwargs.setdefault('allow_redirects', True)
---> 76     return request('get', url, params=params, **kwargs)
     77 
     78 

/opt/conda/lib/python3.7/site-packages/requests/api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

/opt/conda/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    526             hooks=hooks,
    527         )
--> 528         prep = self.prepare_request(req)
    529 
    530         proxies = proxies or {}

/opt/conda/lib/python3.7/site-packages/requests/sessions.py in prepare_request(self, request)
    464             auth=merge_setting(auth, self.auth),
    465             cookies=merged_cookies,
--> 466             hooks=merge_hooks(request.hooks, self.hooks),
    467         )
    468         return p

/opt/conda/lib/python3.7/site-packages/requests/models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
    314 
    315         self.prepare_method(method)
--> 316         self.prepare_url(url, params)
    317         self.prepare_headers(headers)
    318         self.prepare_cookies(cookies)

/opt/conda/lib/python3.7/site-packages/requests/models.py in prepare_url(self, url, params)
    388             error = error.format(to_native_string(url, 'utf8'))
    389 
--> 390             raise MissingSchema(error)
    391 
    392         if not host:

MissingSchema: Invalid URL '/user/root/proxy/40000/shutdown': No schema supplied. Perhaps you meant http:///user/root/proxy/40000/shutdown?
```

To me this seems like the URL isn't parsing correctly due to the proxy. Even if I manually parse the correct URL it seems like this URL would point to shutting down the whole dtale process instead of freeing up the resources of the single DtaleData view. Is there something I am missing here? I have tried to reverse engineer any possible endpoints that I could call to reproduce the described `kill()` behaviour in the [documentation](https://github.com/man-group/dtale#startup-behavior) without luck. Any help would be much appreciated!

**Comment by jnissin** [comment]
I would also like to add that using a more comprehensive specification for `host`, `port` and `app_root` for the `show` function results in an invalid URL for viewing the DtaleData, kill also doesn't work:

```
import dtale
d = dtale.show(pd.DataFrame([1,2,3]), host="localhost", port=40000, app_root="http://localhost:8080/proxy/")
d._main_url
```

```
'http:/localhost:8080/proxy/40000/dtale/main/10'
```

I am using the latest dtale version `1.41.0` from conda-forge with python 3.7.

**Comment by jnissin** [comment]
Thanks a lot! Let know if I can provide any help with that.

**Comment by aschonfeld** [comment]
Doing some further digging it seems that when calling the shutdown programmatically (from `d.kill()`) we just need to specify the actual host/port we used when starting D-Tale and not the proxy path.  So the kill function needs to use `http://localhost:40000/shutdown` and not `http://localhost:8000/user/root/proxy/40000/shutdown` (this does work when using the "Shutdown" button from the main menu though)

Currently kill was just trying to use `user/root/proxy/40000/shutdown` so I'll try updating that. If you want to test if my hypothesis is correct you can try running the following snippet in your notebook and it should kill you D-Tale instance:
```
import dtale.app as d_app
import requests

requests.get('http://{}:{}/shutdown'.format(d_app.ACTIVE_HOST, d_app.ACTIVE_PORT))
```

I'll keep you posted on when I get this stuff released.

P.S. If I wanted to continue going the route of using the jupyter server proxy path (`http://localhost:8000/user/root/proxy/40000/shutdown`) programmatically I think I would have had to do some work around accessing the cookie that gets passed between the D-Tale web UI & the notebook.  Sounded like a nightmare.

**Comment by aschonfeld** [comment]
@jnissin Just released 1.41.1 to pypi (will be on conda-forge shortly) which will hopefully fix your issues.  Ultimately, if calling `d.kill()` from your notebook doesn't work (which I'm hoping it will) you can still use the "Shutdown" button from the main menu of the web UI:
![image](https://user-images.githubusercontent.com/11547371/113083400-223fb380-91aa-11eb-9c1a-9e918b3c2f5d.png)

Let me know how it goes and feel free to toss your ⭐ on the repo 🤞

**Comment by jnissin** [comment]
Alright, I'll test it out!

Just to make sure - is there a way to free up the resources used by a single DtaleData instance, i.e. the resources allocated to a single DataFrame, without killing the whole dtale session? According to the behaviour described in the documentation I imagined that `dtale.get_instance(instance_id).kill()` would free up the resources of a single DtaleData instance without shutting down the whole session. Shutting down the whole session will clean the resources for all the different DtaleData instances. Previously, I did manage to make the session shutdown work correctly by patching the URL as you suggested, but could not free the resources reserved for individual instances.

**Comment by jnissin** [comment]
So, to be exact when I do this:

```
import dtale
d1 = dtale.show(pd.DataFrame([1,2,3,4]))
d2 = dtale.show(pd.DataFrame([5,6,7,8]))
print(dtale.instances())
```

I get two instances

```
ID Name                                    URL
 1      http://97f5e49772ef:40000/dtale/main/1
        http://97f5e49772ef:40000/dtale/main/1
 2      http://97f5e49772ef:40000/dtale/main/2
        http://97f5e49772ef:40000/dtale/main/2
```

When I kill `d1` and print the instances both of the instances are gone:

```
d1.kill()
dtale.instances()
```

Output:

```
currently no running instances...
```

I would have expected that instance with ID 1 would have been killed while maintaining instance with ID 2.

By the way I did this using the version `1.41.1` from conda-forge and the `.kill()` command seems to be fixed with Jupyter Server Proxy. Even if it works unlike I expected 😅 .

**Comment by aschonfeld** [comment]
@jnissin there is a way to do what you're asking (sorry I need to do a better job of documenting 🤦 ).

So the first option is to use the web UI:
1) click the "Instances" button on the main menu:
![image](https://user-images.githubusercontent.com/11547371/113141644-f3502e80-91f7-11eb-8057-4e1aa1bf9f3c.png)
2) click the trashcan on any instance (it doesn't show up on the instance you're currently viewing but I can update that)
![image](https://user-images.githubusercontent.com/11547371/113141719-0ebb3980-91f8-11eb-9a73-08c5153f1769.png)

The next option is from your notebook (or console):
```
import dtale
import pandas as pd
import dtale.global_state as global_state

d = dtale.show(pd.DataFrame([1,2,3,4,5]))
global_state.cleanup(d._data_id)
```

I'll work on adding a `cleanup()` function to the `DtaleData` object that comes out of the `show` function.

Thanks for asking about this 🙏

**Comment by jnissin** [comment]
Alright!

So it was a PEBCAK problem after all 😅 . I'll wrap that into something nicer in my libraries. Thank you for all your support 🙏 !
