### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by nemonominem** [man-group/dtale#465]
Hello,

Could you please consider adding some form of user authentication?

Maybe using the Flask-User or Flask-Security libraries, or even better the MSAL for those running Active Directory (https://github.com/AzureAD/microsoft-authentication-library-for-python) which is very common in a corporate environment.

Right now any user on the network can access the UI by just going to the 4000n port on the server.
This means that any data set is visible to anybody in the organisation.

For all the companies working with confidential or client information, that is unacceptable and would introduce huge compliance risk.
So most banks, insurance companies, etc would have problem with that. 

It is for sure ok within MAN or any hedge fund if you are working with time series and deploying D-Tale on a private server of your research department, but imagine that you were working with your investors names and balances instead of time series - on a server visible within your company - and you would immediately be breaking a few compliance rules.

Tx,
Gilles

**Comment by aschonfeld** [comment]
Sorry, so this was never an issue at MAN because we always had a private firewall controlling everything.  So you could spin up local apps and only other devices within the intranet could connect to it.

That being said I can surely add some optional Flask-based authentication that can be controlled by a global config file.  If that is alright?  I've never really worked with MSAL so I think for a first try I'll go the simple route and if we want to continue to build on top of that we can.  Since this would be optional I'd like to start small if that ok.

Thanks for your suggestion

**Comment by nemonominem** [comment]
Thanks.
Yes, I understand where you started from.

What some users may not realize is that just calling it within a notebook (VSCode/Jupyter/etc) still spins up the full server, and thus exposes the data to anybody the organisation being able to access that server address via a web browser and simply poking the 4000x ports.
Effectively the notebook support is just a byproduct of the server mode.

For this application to get the recognition and pick-up it fully deserves, you may need to start building some security features. So as suggested, maybe start simple with the Flask-User or Flask-Security libraries.
That already should assuage some security concerns with quite a few potential users.

Some (and major ones) may still not be able to roll it out without Active Directory support. But  at least that is a good beginning.

Tx,
Gilles

**Comment by aschonfeld** [comment]
@nemonominem I'm about to merge my initial version of optional authentication to master.  Here's how it works.

You can choose to use optional authentication by adding the following to your D-Tale `.ini` file ([directions here](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md)):

```ini
[auth]
active = True
username = johndoe
password = 1337h4xOr
```

Or you can call the following:

```python
import dtale.global_state as global_state

global_state.set_auth_settings({'active': True, 'username': 'johndoe', 'password': '1337h4x0r'})
```

If you have done this before initially starting D-Tale it will have authentication applied.  If you are adding this after starting D-Tale you will have to kill your service and start it over.

When opening your D-Tale session you will be presented with a screen like this:

![](https://raw.githubusercontent.com/aschonfeld/dtale-media/master/images/login.png)

From there you can enter the credentials you either set in your `.ini` file or in your call to `dtale.global_state.set_auth_settings` and you will be brought to the main grid as normal.  You will now have an additional option in your main menu to logout:

![](https://raw.githubusercontent.com/aschonfeld/dtale-media/master/images/logout.png)

Let me know what you think.  We can continue to iterate on this functionality until it meets your needs.  I'd like to get it to the point where it is easy to specify your own authentication mechanism but you wouldn't be able to do that without using at least a little code.

**Comment by aschonfeld** [comment]
@nemonominem Just released v1.44.0 with this functionality.  If you'd be so kind, please toss your ⭐ on the repo 🙏

**Comment by nemonominem** [comment]
Thanks. testing it right now.
A bit of tuning may be needed - but I shall check precisely how this answers the typical use cases first.

**Comment by aschonfeld** [comment]
@nemonominem sorry forgot to mention that my code is still in a branch. You can try it out if you cloned it and built the JS manually but that will take a little work on your end. Let me kno if you want to go that route and i can walk your thru it.
