### ISSUE TITLE
Manually specify (maximum) column widths

### ISSUE THREAD

**Issue by jnissin** [man-group/dtale#472]
I use D-Tale almost daily with datasets that contain columns with long strings that can be for example a thousand characters long. The automatic sizing of the column decides the column width according to the longest string in the dataset. Having a long column such as this in the middle of other columns can thus effectively hide all the data in the columns to the right of the long column. This can make browsing the data unwieldy and resizing the column by dragging in the UI can be excruciating. Is there a way to enforce a global level maximum column size limit or size for a specific column? 

I tried to browse through the Python source code but couldn't find anything related to column widths so I imagine the column widths are currently entirely calculated in the JavaScript frontend?

**Comment by aschonfeld** [comment]
@jnissin Yes I can definitely add a maximum initial column size.  How about 1000px?  I can also try adding a slider somewhere which will adjust every column width to a specific size if you want?

I'll try addressing this right after #471

**Comment by jnissin** [comment]
That sounds good, I guess for backwards compatibility it could behave as it does now if no maximum initial column size is specified :)

**Comment by aschonfeld** [comment]
@jnissin So I've got a solution working currently.

Here is a screen shot of some columns without a maximum width applied:
![image](https://user-images.githubusercontent.com/11547371/117198584-33866c00-adb7-11eb-89a2-5eb1e856b501.png)

Then I go back and update my code that loads the dataframe to D-Tale and add these lines of code before calling `dtale.show`:
```
import dtale.global_state as global_state

global_state.set_app_settings(dict(max_column_width=100))
```
Now when D-Tale initially loads a maximum of 100 pixels is applied:
![image](https://user-images.githubusercontent.com/11547371/117199060-c0312a00-adb7-11eb-84fb-c20030d12be3.png)

So the idea is that this would be one of the app-level configuration options.  So you could set it using the code I posted above or by having a global configuration file (documentation [here](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md)). Let me know if this is fine and i'll work on cutting a release 🙏 

I can work on adding a more GUI-based approach later on.  I was thinking of having a little popup where you do the following:
* turn on/off a maximum column width
* adjust what the maximum column width is
* after an update to either of the 2 items above your columns would resize

**Comment by aschonfeld** [comment]
@jnissin I added this feature in the newly released v1.45.0 let me know of any issues

**Comment by jnissin** [comment]
Sorry for the long answer period for some reason I didn't get notifications from this to my email. This looks like just what I need! Thank you so much! I'll upgrade our systems to the new version right away and test this :)

**Comment by aschonfeld** [comment]
Great! I’m actually putting the finishing touches on a way to update that max width from the UI. There are some demos in this issue: https://github.com/man-group/dtale/issues/477

**Comment by jnissin** [comment]
That looks really nice as well. Very helpful for us where the end user might be someone else than a developer 👍
