### ISSUE TITLE
Scatter charts in chart builder

### ISSUE THREAD

**Issue by aschonfeld** [man-group/dtale#48]
If a user selects a numeric (int/float) column for the x-axis & y-axis then you should have the ability to select "Scatter" as a chart type.  This will be limited to 15,000 points or else the client will crash.

You should also be able to group by a column, but in this case the user will be presented with scatters for each group since it is impossible to display them all in one scatter chart.

**Comment by mindlessbrain** [comment]
@aschonfeld, it could also be useful to be able add color bars for date or value ranges.
Here's a matplotlib example from PyMC3.

![image](https://docs.pymc.io/_images/notebooks_GLM-rolling-regression_24_0.png)

**Comment by aschonfeld** [comment]
fixed in v1.6.6
