### ISSUE TITLE
flexible branding?

### ISSUE THREAD

**Issue by fredzannarbor** [man-group/dtale#480]
Might it be possible to configure the layout so that "D-TALE" in the top left can be replaced by a string or image for the host website?  I do not see the need to change things like the file structure (dtale/ is a pretty big clue) but would like to give users the impression they are still on the same site.

**Comment by aschonfeld** [comment]
Yea let me see what i can come up with. The hard part is that “D-Tale” is actually a font and not an image so it will be tough for someone to swap something out with equal size. But i guess the work to correctly size the image would be on them so its all good 👍

**Comment by fredzannarbor** [comment]
I don't mind the D-Tale font! In a perfect world, I'd like to be able to tweak the font, style, and string.

**Comment by aschonfeld** [comment]
So tweaking the font will be hard since that will require overriding the CSS somehow.  But I could certainly allow you to change the title from D-Tale to whatever you'd like.  You'll probably run into sizing issues . Anyways here's the small snippet of react which renders the title currently:
```reactjs
<span className="title-font" style={{ fontSize: "16px", cursor: "default" }}>
  D-TALE
</span>
```
So I could try allowing you to specify your own snippet of HTML which can replace this, but I'm not sure how customized styling would work if you're not integrating D-Tale into your own Flask app.  Which you can do, here's [documentation](https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md)

**Comment by fredzannarbor** [comment]
That snippet would work fine for now.  

I am running D-Tale as a standalone and linking to it from my original app for simplicity's sake -- I wanted to be able to isolate D-Tale while I get it working. Eventually, I do want to integrate it so that I can take advantage of my app's user model, dbs, etc.

**Comment by aschonfeld** [comment]
https://user-images.githubusercontent.com/11547371/119266068-48d10800-bbb7-11eb-9d9a-8ae8e69b1ec6.mov

@fredzannarbor Then I go back and update my code that loads the dataframe to D-Tale and add these lines of code before calling `dtale.show`:
```
import dtale.global_state as global_state

global_state.set_app_settings(dict(main_title="My App", main_title_font="Arial"))
```

You could also add the following properties to your [global configuration](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md) file:
```
[app]
theme = light
github_fork = False
hide_shutdown = False
pin_menu = False
language = en
max_column_width = 100
# new properties
main_title = My App
main_title_font = Arial
```

Let me know what you think

**Comment by aschonfeld** [comment]
Added in v1.48.0

**Comment by fredzannarbor** [comment]
>  rebranding.mov 
> @fredzannarbor To change the title I updated my startup code that loads the dataframe to D-Tale and add these lines of code before calling `dtale.show`:
> 
> ```
> import dtale.global_state as global_state
> 
> global_state.set_app_settings(dict(main_title="My App", main_title_font="Arial"))
> ```

> Let me know what you think

Looks great!  Thanks.
