### ISSUE TITLE
Dtale not working on AWS Sagemaker Juptyer Notebook

### ISSUE THREAD

**Issue by m-ciniello** [man-group/dtale#483]
I'm having trouble getting dtale to work in my AWS sagemaker notebook instances. Everything seems fine at first, but when I try to display a dataframe I get an error message that says "localhost refused to connect". 
```
import pandas as pd
import dtale
d = dtale.show(pd.DataFrame([1,2,3]))
d._main_url  
#  'http://localhost:40000/dtale/main/1'

dtale.instances()
# ID Name                                  URL
#  1       http://localhost:40000/dtale/main/1
#           http://localhost:40000/dtale/main/1

d # returns 'localhost refused to connect' error
 
```

**Comment by aschonfeld** [comment]
Hmm, i’ve never used sagemaker before but under the hood of “dtale.show” it tries to figure out the name of the host where D-Tale will be running. But if you’re running a notebook and have the ability to install “jupyter-server-proxy” then you can use that to help host D-Tale in notebooks spun up uaing other services.  Heres the documentation: https://github.com/man-group/dtale#jupyterhub-w-jupyter-server-proxy

**Comment by aschonfeld** [comment]
Looks like a package does exist for notebooks in AWS: https://pypi.org/project/aws-jupyter-proxy/

if you use that then you can still use the settings in the “jupyter server proxy” docs i sent but make sure to specify your path using the “app_root” parameter to “dtale.show”

**Comment by m-ciniello** [comment]
I have pip installed the jupyter-server-proxy and tried the following (per the docs), and now I'm getting a _404 : Not Found
You are requesting a page that does not exist!_ error.

```
!pip install jupyter_server_proxy
import pandas as pd

import dtale
import dtale.app as dtale_app

dtale_app.JUPYTER_SERVER_PROXY = True

d = dtale.show(pd.DataFrame([1,2,3]))
print(d._main_url) # /user/ec2-user/proxy/40000/dtale/main/1
d
```

**Comment by aschonfeld** [comment]
Good news, I messed around with Sagemaker and was finally able to get this working
![image](https://user-images.githubusercontent.com/11547371/118560177-10ed3f00-b737-11eb-9904-4cc476890d11.png)

The key was that I had to install the `@jupyterlab/server-proxy` extension, wait for the server to rebuild and then start my D-Tale instance using the code snippet:
```python
import dtale
import pandas as pd
import dtale.app as dtale_app

dtale_app.JUPYTER_SERVER_PROXY = True

d = dtale.show(
    pd.DataFrame([1,2,3,4,5]),
    app_root="/proxy"
)
```

Then from there you should be able to open your D-Tale instance directly in the notebook or by entering a URL in another tab similar to this structure: `https://[notebook host]/proxy/[D-Tale port (most likely 40000)]/dtale/main/[D-Tale instance (most likely 1)]`

Here's an example of my URL: `https://d-tale.notebook.us-east-2.sagemaker.aws/proxy/40000/dtale/main/1`

You can also jump to a new tab by clicking "Open in New Tab"
![image](https://user-images.githubusercontent.com/11547371/118560467-8822d300-b737-11eb-8942-7cf8d0d68696.png)

Hope this helps.  Let me know if you hit any other issues

**Comment by aschonfeld** [comment]
Also, I had to install the extension using the extension manager which needs to be turned on from the "Settings" tab in Sagemaker

**Comment by m-ciniello** [comment]
It works! Thanks so much for the help!

**Comment by aschonfeld** [comment]
@m-ciniello when you get a sec please toss your ⭐️ on the repo 🙏

**Comment by angiraldoc** [comment]
I had the same error and followed the steps described here, but now I have an error that says unsupport URL path
