### ISSUE TITLE
Showing ratio on Stacked bar chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#484]
Hi Is it possible to show the ratio of each group on the stacked bar chart?
![image](https://user-images.githubusercontent.com/2202483/118998008-19bc5b80-b957-11eb-8ac3-f3d7cd4c5be7.png)

**Comment by aschonfeld** [comment]
So there's currently a bug with this function (I have a fix for it that hasn't been released yet) but perhaps you could use the "Percentage Count") aggregation to get the number you're looking for.

**Comment by aschonfeld** [comment]
@reza1615 please give "Percentage Count" a try it has been updated in v1.48.0

**Comment by aschonfeld** [comment]
@reza1615 any update?  Did "Percentage Count" work?

**Comment by reza1615** [comment]
Yes it works like a charm. Thanks
May be changing its name to 
**Count (Percentage)**
is better because it will sort after **Count** and user can find all existing options

**Comment by aschonfeld** [comment]
added in v1.50.0
