### ISSUE TITLE
Correlations Scatter - make 15K point limitation an editable setting

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#486]
Is it possible to have an option to select random 15K records when the number of records is more than 15K?

![image](https://user-images.githubusercontent.com/2202483/119002827-335fa200-b95b-11eb-856d-c78af48511bd.png)

**Comment by reza1615** [comment]
Also please make this 15K limitation a setting variable. For my case, I have resources to increase it to 1M

**Comment by aschonfeld** [comment]
So I'm going to add a `charts` section to the global configuration file which will hold the limits on points sent to the client.  Here's a demo:

https://user-images.githubusercontent.com/11547371/119280888-662ac400-bc01-11eb-918d-8e216ab20583.mov

@reza1615 so to change the title I updated my startup code that loads the dataframe to D-Tale and add these lines of code before calling `dtale.show`:
```
import dtale.global_state as global_state

global_state.set_chart_settings(dict(scatter_points=20000))
```

You could also add the following properties to your [global configuration](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md) file:
```
[charts]
scatter_points = 20000
```

**Comment by reza1615** [comment]
That is great please also point to the above code snipt in the warning text to help user to solve the sucuation.

**Comment by aschonfeld** [comment]
Updated in v1.48.0
