### ISSUE TITLE
Pre-Encoding for Correlations

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#488]
As you know Correlations just works on the numerical columns and for the categorical doesn't work.
It would be nice to have an option to one-hot (encode) all categorical columns in a batch after that user can get the Correlations.

**Comment by aschonfeld** [comment]
Can you refresh my memory on how the "one-hot" (encode) works?  We made column builders for this, correct?

**Comment by reza1615** [comment]
yes we have column builder.
Image the data has 20 categorical column. to have onehot for all of them to get correlation we should 20 times in column builder create onehot column

**Comment by aschonfeld** [comment]
* So what if I added a toggle which checks for any string or categorical column and auto convert using OneHotEncoder
* Also what if there was a toggle to add in date columns which have been converted to millisecond timestamps

**Comment by reza1615** [comment]
In my opinion when we open correlation window
1-A multi select drop down lists all dtype(object)
2-An exclud multi select drop down list all column with high cardinality
(df['A'].nunique()>50) as exclud from one-hot
3-by default user only get numerical col correlation
4-by click on a button Dtale convert all object columns -exclud the second
list then calculate correlation.

for the date why you want check military second?

**Comment by aschonfeld** [comment]
added in v1.48.0
