### ISSUE TITLE
Charts: stratified random samplin base on a target

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#490]
Now the random sampling for charts doest apply stratified
sampling based on target.
It would be helpful to have a drop down to set the target column and generate stratified samples based on that.
It will help to have the same distribution of the whole data set.

**Comment by harshithakolipaka** [comment]
hey, I would like to work on this issue. Can you help me direct to the source code so that I can add the feature

**Comment by aschonfeld** [comment]
@harshithakolipaka thanks for your interest in this feature! Ok so to give you some background on how this will work you'll have to update the `run_query` function to have a boolean named parameter `stratified_random_sample`.  So it will look something like this
```
run_query(
          handle_predefined(data_id),
          query,
          global_state.get_context_variables(data_id),
          pct=inputs.get("load"),
          pct_type=inputs.get("load_type"),
          stratified_random_sample=True
)
```
 The `run_query` function is located [here](https://github.com/man-group/dtale/blob/master/dtale/query.py#L33)

The idea is that you'll want to check this boolean parameter and if its `True` then you'll run your random sampling code.  You'll want to run it on the `df` parameter passed into `run_query`, it's the dataframe you've loaded into D-Tale.  You'll probably want to call that function before anything else in `run_query`.  Lastly, your random sampling function will return a dataframe that will later be used in the rest of the `run_query` function.

Honestly, if you'd just like to provide the random sampling function I can plug in the rest and make sure you still get credit for the code you've committed. Let me know if you have any other questions.  Thanks

**Comment by aschonfeld** [comment]
@reza1615 I'm looking to implement this but wanted to know which of these two solutions were more suitable:

* https://stackoverflow.com/a/44115314
* https://stackoverflow.com/a/74493296 (and if this one what should the value of `sampling_rate` be set to and would an input be made available on the UI for this?)

**Comment by reza1615** [comment]
> @reza1615 I'm looking to implement this but wanted to know which of these two solutions were more suitable:
> 
> * https://stackoverflow.com/a/44115314
> * https://stackoverflow.com/a/74493296 (and if this one what should the value of `sampling_rate` be set to and would an input be made available on the UI for this?)

Hi, the second one. The sampling_rate is the ratio that we choose to down sample data. already you have it for down sampling. for example if user select 30% from UI the sample_rate is 0.3

**Comment by reza1615** [comment]
![Screenshot_20230410_155030_Chrome](https://user-images.githubusercontent.com/2202483/230985348-fa43e500-261c-4dcc-9b24-39be85599f40.jpg)

**Comment by aschonfeld** [comment]
@reza1615 @harshithakolipaka just realeased v2.15.0 with this feature. Let me
Know if you have any issues
