### ISSUE TITLE
Overlap histogram Chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#491]
It would be nice to have overlap histogram of a different distributions 
![image](https://user-images.githubusercontent.com/2202483/119210238-2afd8900-ba79-11eb-82d7-cd5c4b44e64d.png)
for example in above chart 40-100 is conflict region 
use case:
checking conflict of the distribution of a column per target. for example see witch range of a column have target 0 and 1
base on this chart we realize data > 120 should be in target 1

**Comment by aschonfeld** [comment]
@reza1615 could you supply me with some code to generate values that would populate a chart like this?

**Comment by reza1615** [comment]
@aschonfeld: please find the overlap histogram function in attached.
I zipped it because github doesn't support Jupyter notebook

``` python
import pandas as pd
import matplotlib.pyplot as plt

# data from https://www.kaggle.com/c/titanic/data
df=pd.read_csv('train.csv')

def plot_overlap_histogram(df,col,target, bins =10 ):
    plt.figure(figsize=(8,6))
    for target_value in df[target].unique():
        data1=df.loc[df[target]==target_value,col]
        plt.hist(data1, bins=bins, alpha=0.3, label= f"{target} = {target_value}");
    plt.xlabel(col + " Data", size=14)
    plt.ylabel("Count", size=14)
    plt.title(col + " Distribution based on "+ target + " Column")
    plt.legend(loc='upper right')
    plt.show()
    
target='Survived'
col='Fare'
bins = 50
plot_overlap_histogram(df,col,target, bins=bins)
```
![image](https://user-images.githubusercontent.com/2202483/120072025-ba013700-c05f-11eb-9543-e4d0e34f56b9.png)

[Overlap Histogram.zip](https://github.com/man-group/dtale/files/6564740/Overlap.Histogram.zip)

**Comment by reza1615** [comment]
With graph_objects
``` python
import plotly.graph_objects as go
def plot_overlap_histogram(df,col,target, bins =bins):
    fig = go.Figure()
    for target_value in df[target].unique():
            data=df.loc[df[target]==target_value,col]
            fig.add_trace(go.Histogram(x=data, nbinsx=bins, histfunc="count", name= f"{target} = {target_value}"))
    fig.update_layout(
        barmode='stack',
        height=800,
        title_text=col + " Distribution based on "+ target + " Column",
        xaxis_title=col + " Data",
        yaxis_title= "Count",
        legend_title_text=target,
    )   
    fig.update_traces(overwrite=True, marker={"opacity": 0.3}) 
    fig.show()

plot_overlap_histogram(df,col,target, bins =bins)
```

**Comment by reza1615** [comment]
With plotly.express
``` python
target='Survived'
col='Age'
bins = 50
import plotly.express as px
def plot_overlap_histogram(df,col,target, bins =bins):
    figure_data=[]
    for target_value in df[target].unique():
        data1=df.loc[df[target]==target_value,col]
        figure_data.extend([i for i in px.histogram(data1, x=col, y=col, histfunc="count",  nbins=bins, labels= f"{target} = {target_value}").to_dict()['data']])
    fig=go.Figure(figure_data)
    
    fig.update_layout(
        barmode='stack',
        height=800,
        title_text=col + " Distribution based on "+ target + " Column",
        xaxis_title=col + " Data",
        yaxis_title= "Count",
        legend_title="Legend",
        showlegend=True,
        legend_title_text='Trend',
        legend=dict(
                yanchor="top",
                y=0.99,
                xanchor="left",
                x=0.01
            )
    )   
    fig.update_traces(overwrite=True, marker={"opacity": 0.3}) 
    fig.show()

plot_overlap_histogram(df,col,target, bins =bins)
```

**Comment by aschonfeld** [comment]
Thanks @reza1615

**Comment by aschonfeld** [comment]
Ok so after looking over this and the docs for chart.js this should definitely be doable.  One last question, what columns should be considered a "target"? Anything with less than 20 unique values?  Honestly you'd probably want it even lower than that because the chart will be very cluttered.

**Comment by reza1615** [comment]
In my opinion make it open to any column but before applying columns with more than 20 show a warning. some times chacking pairvize two features is usuful

**Comment by reza1615** [comment]
https://seaborn.pydata.org/generated/seaborn.pairplot.html

**Comment by aschonfeld** [comment]
added in v1.49.0

**Comment by reza1615** [comment]
The current chart is great and useful please keep it. It also can be generated by the below chart
![image](https://user-images.githubusercontent.com/2202483/121530339-536b0a00-c9cb-11eb-8e4e-17ee6c3067e5.png)
