### ISSUE TITLE
another report for the correlation matrix 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#493]
It would be helpful that below of correlation matrix to have a sorted tabel of correlated column per a column. 
for example:

sorted correlated to col1 score
col5      0.9
col10    0.8
col2       0.5
...

**Comment by aschonfeld** [comment]
@reza1615 are you saying as you click each column it shows a sorted list of correlations with the other columns?  Or are you just asking for the ability to sort columns in Correlation matrix?

**Comment by reza1615** [comment]
I need to have decending sorted list of corelated features 
For example. I need to know which features are the most corelated to the col1

**Comment by aschonfeld** [comment]
Ok, what I will do is implement sorting on the correlations grid.  That way you just need to click the header at the top to see the most/least correlated features.

**Comment by aschonfeld** [comment]
https://user-images.githubusercontent.com/11547371/122317769-0ff12e00-ceec-11eb-8d48-afc632f27cdc.mov

**Comment by aschonfeld** [comment]
fixed in v1.50.0
