### ISSUE TITLE
Dash embedding 

### ISSUE THREAD

**Issue by firmai** [man-group/dtale#499]
Hi Kudos for the project, haven't seen this asked before, is there a way to integrate it with a Dash app?

**Comment by aschonfeld** [comment]
So D-Tale actually uses Dash under the hood for its chart builder.  But to answer your question, if you're building a dash app then you should be using flask.  And it is pretty easy to embed D-Tale into your own flask application.  Here is some documentation on how: https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md

Let me know if you run into any issues or have any questions
