### ISSUE TITLE
Cleaning should have sperate window

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#503]
Now cleaning is inside the build column. In my opinion, it should be in a separate window.
Cleaning also should accept Inplace replacement as i mention in #502 
![image](https://user-images.githubusercontent.com/2202483/119821858-095d3100-bec1-11eb-83ca-75a36d86b0e2.png)

**Comment by aschonfeld** [comment]
@reza1615 this actually already exists for columns with a dtype of "string"

https://user-images.githubusercontent.com/11547371/121456978-eaf13e00-c974-11eb-829b-fc7dde99e88f.mov

**Comment by reza1615** [comment]
I know it is exist. I mean we need to move cleaning part to a new window. The new window or menu's name should be cleaning.
Now it is under creating column which doesn't make sense

**Comment by aschonfeld** [comment]
I’m confused, the button to activate that popup was named “Clean Column” & the header said “Clean [column name]”.  It was a completely separate popup from “Column Builders”

**Comment by reza1615** [comment]
![image](https://user-images.githubusercontent.com/2202483/121525573-8068ee00-c9c6-11eb-9e8b-2aa3277b3d5e.png)

**Comment by aschonfeld** [comment]
Sorry that was unclear. So you just want another button added to the main menu. Not sure how much you gain from that, but sure thats easy enough.

**Comment by reza1615** [comment]
> Sorry that was unclear. So you just want another button added to the main menu. Not sure how much you gain from that, but sure thats easy enough.

Now The cleaning is under building column which is the command hierarchy is not clear. thank you for reopening

**Comment by aschonfeld** [comment]
added in v1.50.0
