### ISSUE TITLE
UI Bug: Describe window

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#504]
In the describe window on a text column when I toggle between **Word Value Counts** tab and **Describe** tab. the **Word Values** stays from **Word Value Counts** tab and doesn't show "Unique Values"  any more.
Also to make it more clear please change "Unique Values" > "Unique Row Values"

https://user-images.githubusercontent.com/2202483/119824561-09aafb80-bec4-11eb-8b8d-0a9b5efb31cf.mp4

**Comment by aschonfeld** [comment]
Fixed in v1.48.0
