### ISSUE TITLE
Features for the Filtering data

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#505]
It would be nice to have the below features for the Filtering data:
- **Invert filter**: Inverting the filter condition . 
   Use case:  I filter outlier based on the Describe window. After that I need to see data without outliers. Now it just show the data with outlier (Image in below)
- **Drop rows**: Drop rows based on the filter. 
Use case: In the EDA process we need to remove outliers and after that checking the rest of EDA pipeline.
- **Auto refreshing**: Refreshing data based on the filter. Now when I select Apply outlier filter I should refresh the browser page manually to see its effect.
The Auto refreshing True or False can be set in the setting. 
![image](https://user-images.githubusercontent.com/2202483/119828698-6f00eb80-bec8-11eb-861a-1c6f84b447b5.png)

**Comment by fredzannarbor** [comment]
I also strongly suggest Save Current Filter and Save Custom Filter.

**Comment by aschonfeld** [comment]
##Invert Filter##: when applying the outlier filter it actually removes the outliers (I know the auto-refresh is broken currently which I have a fix for) so inverting will show only the outliers
##Drop Rows##: So it is sounding like these changes are strictly related to the outlier filters.  Do you want this functionality available for any filter you've entered?
##Auto-Refreshing##: As mentioned earlier I have a fix for this.  I missed it when I moved to the sliding side-panel version of the "Describe" window

**Comment by reza1615** [comment]
> **Invert Filter**: when applying the outlier filter it actually removes the outliers (I know the auto-refresh is broken currently which I have a fix for) so inverting will show only the outliers
> **Drop Rows**: So it is sounding like these changes are strictly related to the outlier filters. Do you want this functionality available for any filter you've entered?
> **Auto-Refreshing**: As mentioned earlier I have a fix for this. I missed it when I moved to the sliding side-panel version of the "Describe" window

Thanks for fixing autorefress
Dropping rows base on filter would be useful. for example I need to just work on houses with >=3 rooms

**Comment by aschonfeld** [comment]
Here's what I got for "Drop Rows":

https://user-images.githubusercontent.com/11547371/121990937-a7c80e00-cd6c-11eb-8749-6b27229b956b.mov

**Comment by reza1615** [comment]
That is greate. Thanks

**Comment by aschonfeld** [comment]
added in v1.50.0
