### ISSUE TITLE
Generate Charts inside the jupyter notebook notebook instead of popping up a new window

### ISSUE THREAD

**Issue by HindyDS** [man-group/dtale#507]
Generate Charts inside the jupyter notebook notebook instead of popping up a new window

**Comment by reza1615** [comment]
You have code snippet and you can use it in jupyter notebook

**Comment by HindyDS** [comment]
U mean the code export right? That’s what I tried in the first place, but I
just find multiple  errors in the code exported. So I just wanna use the
cell as the plot directly instead of exporting the code.

「Reza ***@***.***>」在 2021年5月29日 週六，下午12:34 寫道：

**Comment by reza1615** [comment]
@aschonfeld : I couldn't find code snippet for charts. May be we need to add it to the chart window

**Comment by aschonfeld** [comment]
@reza1615 the code export is located here 
![image](https://user-images.githubusercontent.com/11547371/120082836-277a8b00-c093-11eb-9940-945ae9527a37.png)

@HindyDS if you would like to open a cell in your notebook directly to the charts page you can do that by doing the following:

```
import dtale
import pandas as pd

d = dtale.show(pd.DataFrame([1,2,3,4]))
d.notebook(route='/dtale/charts/', height=800)
```
Now be aware that if your browser window isn't open wide enough the chart type tabs will appear a little wonky. In that case just resize your browser to be a little wider.

Hope this helps

**Comment by HindyDS** [comment]
@aschonfeld just tried out the code but no plots.
![image](https://user-images.githubusercontent.com/69097028/120088510-e088a600-c123-11eb-9506-ff2df463c693.png)

**Comment by aschonfeld** [comment]
@HindyDS so that will just fet you to the “Charts” page. You’ll have to build the plot you want at that point just like you would using the browser. Once you do that you can click the “copy link” button and then pass that to the “d.notebook” function to  have it popup automatically in the future.  Not sure if this is what you were looking for. 

Also let me know what kind of chart you tried the “code export” on. When i did an overhaul a few months back all were working for mw

**Comment by HindyDS** [comment]
Thanks. I gonna try you suggestion.

Actually I was just playing dtale with the titanic dataset. Around 4/5 of
the code exported had about 3 mistakes, besides, ‘figure.show()’ were
always missing. Maybe I need to install a newer version of dtale.

「Andrew Schonfeld ***@***.***>」在 2021年5月30日 週日，上午9:05 寫道：

**Comment by aschonfeld** [comment]
@HindyDS can you send me the contents of the "Code Export"?
