### ISSUE TITLE
Change side window width

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#509]
Please make a possibility to change the side window's width

![image](https://user-images.githubusercontent.com/2202483/120076288-d8bcf900-c072-11eb-9c8c-0fab59bee2ee.png)

**Comment by aschonfeld** [comment]
So it's a little janky but this was the best I could do:

https://user-images.githubusercontent.com/11547371/120110381-30bf3280-c13b-11eb-89be-7935b659ba82.mov

**Comment by aschonfeld** [comment]
added in v1.49.0
