### ISSUE TITLE
Titanic dataset

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#513]
Please add Titanic dataset to the demo for the binary classification machine learning examples

[Titanic.zip](https://github.com/man-group/dtale/files/6631413/Titanic.zip)

**Comment by aschonfeld** [comment]
Just the `titanic.csv` from that ZIP file?

**Comment by reza1615** [comment]
Yes please

**Comment by aschonfeld** [comment]
http://alphatechadmin.pythonanywhere.com/dtale/main/7
