### ISSUE TITLE
Histogram with target

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#514]
1- Please make the bins title more clear
2- the first row isn't clear. what is it?

![image](https://user-images.githubusercontent.com/2202483/121529100-118d9400-c9ca-11eb-8d59-8a907ffa7c8c.png)

**Comment by aschonfeld** [comment]
2) Sorry there must be a bad boolean check in there it should read `0: 37`

**Comment by aschonfeld** [comment]
fixed in v1.50.0
