### ISSUE TITLE
adding dataframe.index() to chart axis

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#515]
Please add df.index() as an option for X or Y. Now building aggregation chart, based on a column is not possible. 
the variable can be like **`__index__`**
Here I used **Id** column. if the id column doesn't exist or had duplication it cause some issues
![image](https://user-images.githubusercontent.com/2202483/121531182-2e2acb80-c9cc-11eb-9b01-51dcca587255.png)

**Comment by aschonfeld** [comment]
I believe charts do work using the index right now by choosing the "No Aggregation" option from the **Aggregation** dropdown.  It essentially allows you to build a chart which ignores duplication.

Are you asking that we allow for the raw index (0, 1, 2,..., N) to be one of the column options in the X, Y, or Z dropdowns?

**Comment by reza1615** [comment]
I need aggregation. For example a chart base on **x** and **y == count (x)** 
Yes we need raw.index() as a an option in dropdown and the name should be clear and distinguish some thing like **raw.index()** or **index()** or **__index__**

**Comment by aschonfeld** [comment]
I wouldn’t think that an aggregation would be possible since the raw index will always be monotonically increasing and distinct.  So an aggregation will do nothing

**Comment by reza1615** [comment]
here for the index, i mean  each raw. so you can create a temp index by df.reset_index().index()

**Comment by aschonfeld** [comment]
I'm still not 100% following.  You shouldn't need something distinct if you're trying to use the "Count" aggregation as in your screenshot above, but maybe I'm wrong.  I thought it simply counts whatever value you use for Y regardless of whether its distinct or not.  

But anyways, sure I can add `df.index()` as an option in the X, Y & Z dropdowns.

**Comment by aschonfeld** [comment]
I've added it to the X & Y dropdowns and here's your example from above:
![image](https://user-images.githubusercontent.com/11547371/123163879-3e1cc380-d440-11eb-9de2-319fad954e28.png)

**Comment by aschonfeld** [comment]
added in v1.50.0
