### ISSUE TITLE
Keep less correlated columns

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#517]
It would be a great feature for dtale to keep just effective features based on a threshold.
I checked this ticket 
https://stackoverflow.com/questions/29294983/how-to-calculate-correlation-between-all-columns-and-remove-highly-correlated-on?answertab=votes#tab-top
There is my snippet

``` python
# this code gets the max correlation of all features and sort them and remove the first top correlated feature and continue it until the first top feature correlation with other became less than threshold.

def get_corr_feature(df):
    corr_matrix = df.corr().abs()
    # Select upper triangle of correlation matrix
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool_))
    upper['score']= upper.max(axis=1)
    upper.sort_values(by=['score'],ascending=False)
    column_name=upper.sort_values(by=['score'],ascending=False).index[0]
    max_score=upper.loc[column_name,'score']
    return column_name, max_score

max_score=1
threshold = 0.5
while max_score>threshold:
    column_name, max_score=get_corr_feature(features_df)
    features_df.drop(column_name,axis=1,inplace=True)
```
I compared my method and others based on the attached csv. Other's has the below issues
* drop both high related features which is not correct. If A and B are related it doesn't mean that we shouldn't have both of them
* drop the root feature which cause many correlations with others. for example 
     *  corr(A,B)==0.9 
     * corr(A,C)==0.8 
     * corr(B,C)==0.5 

Their solution remove randomly and in most cases remove A so we will have B and C but my solution just Keep A (Our goal is to have less features but the most effective)

[for_text.txt](https://github.com/man-group/dtale/files/6658442/for_text.txt)

**Comment by aschonfeld** [comment]
@reza1615  what if I added a button which ran your code and displayed the columns which would get dropped from it and then users can decide whether to drop them or not.  Maybe also display information about the max scores across each column as well so their not just agreeing to drop the columns on blind faith 😄 

Let me know if you have a better way to display this information

**Comment by reza1615** [comment]
That is great Idea. Yes the new popup can have this information as a table

- Max correlation of that column
- Number of columns with correlation more than the threshold 
- Number of null or empty cells in that column
- Table can be Sortable based on the columns (Max correlation, Number of correlation)
Some thing like below


Check box | column | Max Correlation | Number of   Correlations | Number of   missing
-- | -- | -- | -- | --
Yes | A | 0.9 | 2 | 235
Yes | B | 0.85 | 5 | 635
Yes | D | 0.82 | 6 | 23
Yes | R | 0.75 | 2 | 12
Yes | G | 0.6 | 1 | 566
Yes | S | 0.55 | 10 | 45

**Comment by aschonfeld** [comment]
https://user-images.githubusercontent.com/11547371/122814097-c0bb4c80-d2a1-11eb-9046-023963acebcc.mov

**Comment by aschonfeld** [comment]
added in v1.50.0
