### ISSUE TITLE
Is there a way to cumsum()?

### ISSUE THREAD

**Issue by appznoix** [man-group/dtale#518]
The only think I could not do so far with this great piece of software is a way to cumsum a column. Is there a way or am I missing something?

**Comment by aschonfeld** [comment]
Good catch!  I'll add a button for "Cumulative Sum" next to the "Numeric" button and you'll just have to select any column containing numeric data.

![image](https://user-images.githubusercontent.com/11547371/122813710-42f74100-d2a1-11eb-870c-ada30e429eb2.png)

**Comment by aschonfeld** [comment]
https://user-images.githubusercontent.com/11547371/122858454-4a8e0880-d2e8-11eb-9061-d1cca02844b9.mov

**Comment by appznoix** [comment]
🤩 So glad!

**Comment by aschonfeld** [comment]
I'll let you know when the new version is released.  I have a couple more issues to add to the release.

**Comment by aschonfeld** [comment]
Added in v1.50.0
