### ISSUE TITLE
Possible to display image/HTML data

### ISSUE THREAD

**Issue by msabramo** [man-group/dtale#519]
I have some columns that have HTML `<img>` tags. Dtale displays the raw HTML rather than rendering the images. Is it possible for me to configure the column type or pass a render function for the column so I can see the images?

**Comment by aschonfeld** [comment]
I can certainly build a formatter that will allow you to take a column containing HTML and render it as HTML.  I'll include that in the next release.  It will work in a similar way to how I allow for links directly for Simpsons images in this demo: https://www.youtube.com/watch?v=M18vJVcFNBQ&t=1s

**Comment by msabramo** [comment]
Thanks, @aschonfeld!

**Comment by aschonfeld** [comment]
@msabramo  I've got HTML strings displaying as HTML, but images get shrunk to the size of the cell.  I'm trying to add a way to display the full image on hover but right now `react-virtualized` is trimming the size of the grid to how many cells there are. So this example is hiding some of the image.  I'll keep working on that, but regardless its not going to be perfect without some really clever CSS magic.

https://user-images.githubusercontent.com/11547371/123025212-46292480-d3a8-11eb-946a-9d524d0a4c90.mov

**Comment by aschonfeld** [comment]
Nevermind, got it working!

https://user-images.githubusercontent.com/11547371/123025813-378f3d00-d3a9-11eb-8042-22a39c15d964.mov

**Comment by msabramo** [comment]
Nice work, @aschonfeld! Thanks! Is there a branch that I can pull down to try it out for my use case?

**Comment by aschonfeld** [comment]
Sorry, here's the branch: https://github.com/man-group/dtale/tree/bugfixes_20210613

**Comment by aschonfeld** [comment]
Added in v1.50.0

**Comment by msabramo** [comment]
Just ⭐ ed it!

This is grerat, @aschonfeld!

A few questions:

1. Is there a way I can programmatically invoke D-Tale, telling it that some set of columns should be rendered as HTML, so I don't need to change it in the UI?

2. Is it possible for me to tell D-Tale to make the row height bigger so that I can show a smallish image inline in the table without having to hover over it? Right now I'm getting something like this (these images are faces but it might be hard to tell):

![Screen Shot 2021-06-24 at 12 05 07 PM](https://user-images.githubusercontent.com/305268/123318832-81307280-d4e4-11eb-8a5e-f237acca4460.png)

I'm trying to use D-Tale within Streamlit (as described at https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_DTALE_STREAMLIT.md) and so I'm using:
```python
dtale.views.startup(data_id="1", data=filtered_df
```

It looks like `startup` takes quite a few parameters:
```python
def startup(
    url="",
    data=None,
    data_loader=None,
    name=None,
    data_id=None,
    context_vars=None,
    ignore_duplicate=True,
    allow_cell_edits=True,
    inplace=False,
    drop_index=False,
    precision=2,
    show_columns=None,
    hide_columns=None,
    optimize_dataframe=False,
):
```

but I'm not seeing a way to configure how columns and rows are displayed, but I'm very new to D-Tale so I might be missing out on something very basic.

**Comment by aschonfeld** [comment]
@msabramo thanks!
1) so there may actually be a way to do this it just might be a little clunky. I’ll send you a code snippet firat thing tomorrow
2) yea i wanna to do dig into adding more height but its going to be a big undertaking so i decided to just give you what I had for now. You could also force some sizing on your <img> tags if you add ‘style=“height: 25px; width: 25px”’ (it probably wont look great but the max height for cells currently is 25px) Maybe i can add a height slider for the cells in the grid… i will keep digging

**Comment by aschonfeld** [comment]
@msabramo here's the answer to your first question (assuming this is being run in a jupyter notebook):
```python
import pandas as pd
import dtale
import dtale.global_state as global_state

df = pd.DataFrame(dict(a=[
    '<span style="font-weight: bold">FOO</span>',
    '<a href="http://www.espn.com" target="_blank">ESPN</a>',
    '<pre style="padding: 0; margin: auto;">HTML Code</pre>',
    '<img src="https://i.kym-cdn.com/photos/images/original/000/076/524/Haters.gif" />'
]))
d = dtale.show(df)
formatting = {'a': {'fmt': {'html': True}}}
global_state.set_settings(d._data_id, {'columnFormats': formatting})
d
```

If you want this as a python script:
```python
import pandas as pd
import dtale
import dtale.global_state as global_state

if __name__ == '__main__':
    df = pd.DataFrame(dict(a=[
        '<span style="font-weight: bold">FOO</span>',
        '<a href="http://www.espn.com" target="_blank">ESPN</a>',
        '<pre style="padding: 0; margin: auto;">HTML Code</pre>',
        '<img src="https://i.kym-cdn.com/photos/images/original/000/076/524/Haters.gif" />'
    ]))
    formatting = {'a': {'fmt': {'html': True}}}
    global_state.set_settings('1', {'columnFormats': formatting})
    dtale.show(df, subprocess=False)
```
This script is a little hacky because when starting up D-Tale in a script it's a long-running process.  So once we call `dtale.show` no more code gets executed.  And because of that we cant have access to what `data_id` is assigned.  But because this is a script we can assume that this is the first piece of data loaded and it will always be assigned the identifer of `1`.  

So in order to ease this burden I'll see if I can add a `column_formats` parameter to `dtale.show` so that you can eventually do something like this:
```python
dtale.show(df, column_formats={'a': {'fmt': {'html': True}}})
```

**Comment by msabramo** [comment]
Thanks again, @aschonfeld! This is some of the most responsiveness I've seen in an open-source project! You are obviously very committed to D-Tale. 👏 

This looks cool what you posted. Unfortunately, I haven't been able to use it yet, because I'm opening D-Tale from within a Streamlit app, so I'm using `dtale.views.startup` and that doesn't seem to support the `subprocess` keyword argument:

![Screen Shot 2021-06-25 at 9 38 03 AM](https://user-images.githubusercontent.com/305268/123457731-11c88a80-d599-11eb-99d3-954fa163c161.png)

I do feel that I should be transparent here and say that I'm not sure yet whether D-Tale will be valuable for this particular project that I'm working on, mainly because it is heavily involved with images (viewing results of how humans have been annotating said images). The stakeholders want something akin to Google's [Know Your Data](https://knowyourdata-tfds.withgoogle.com/) and D-Tale is the closest thing I've found so far, though it does seem like it was designed more with heavily quantitative data in mind. I mention this only because you've been so responsive and have put a lot of work into helping me and have made changes to D-Tale and I just want you to know that I'm still experimenting with D-Tale and this may or may not end up with this project using D-Tale, but you definitely already got a ⭐ from me and even if I don't use D-Tale on *this* project, it might be something that I might use on a future project!

**Comment by msabramo** [comment]
Hmmm this seems to work decently for setting 3 of my columns to display HTML (the images look bad still because they're much too big for the 25px row height, but one thing at a time...)

```python
    if st.button('Open following dataframe in D-Tale...'):
        column_formats = {
            'prepended_method_a_efs': {'fmt': {'html': True}},
            'prepended_gt_efs': {'fmt': {'html': True}},
            'prepended_method_b_efs': {'fmt': {'html': True}},
        }
        dtale.views.startup(data_id="1", data=filtered_df)
        dtale.global_state.set_settings('1', {'columnFormats': column_formats})
        components.html("""
            <script>
                window.open("/dtale/main/1", "_blank");
            </script>
        """)
```

**Comment by aschonfeld** [comment]
@msabramo sorry I completely forgot you were using streamlit.  The way that you're setting `global_state` is the exact way I would have suggested.  Also, you much more control over the `data_id` when using streamlit so thats good news.

As for column widths, you're in luck.  There is an application to change the default width size to not auto-size.  It's treating the HTML as a string, which is pretty long so thats why it's so wide.  Here's a code snippet to change the column widths (this is from this [issue](https://github.com/man-group/dtale/issues/472):
```
import dtale.global_state as global_state

global_state.set_app_settings(dict(max_column_width=100))
```

So I guess in your case I'd use something like 30 since you're setting the height to 25px.

As for the row heights, I'm going to go a similar route as I did with column widths. I'll add a slider right underneath the widths slider.  There's a demo of the slider [here](https://github.com/man-group/dtale#resize-columns) but in addition to that widget I'll allow you to do something like `global_state.set_app_settings(dict(max_row_height=100))`

Don't worry about not using D-Tale for it's original chosen purpose.  I was planning on addressing some of these use cases and it's been interesting as well.

**Comment by aschonfeld** [comment]
@msabramo here's what I got so far in this branch: https://github.com/man-group/dtale/tree/bugfixes_20210627

https://user-images.githubusercontent.com/11547371/123553580-fe105600-d749-11eb-8a99-b6e2e904e5db.mov

**Comment by msabramo** [comment]
Hi @aschonfeld,

Thanks again!

This might be more of a pipenv issue than a dtale one, but I attempted to install your branch with:

```
pipenv install -e 'git+https://github.com/man-group/dtale.git@bugfixes_20210627#egg=dtale'
```

and the command completes, but then I get errors like this when I try to use D-Tale:

```pytb
FileNotFoundError: [Errno 2] No such file or directory: '/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/src/dtale/dtale/static/dist'
2021-06-29 17:00:12.215 Exception on /dtale/main/1 [GET]
Traceback (most recent call last):
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/src/dtale/dtale/views.py", line 1006, in view_main
    return _view_main(data_id)
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/src/dtale/dtale/views.py", line 991, in _view_main
    return base_render_template("dtale/main.html", data_id, title=title, iframe=iframe)
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/src/dtale/dtale/views.py", line 955, in base_render_template
    if not len(os.listdir("{}/static/dist".format(os.path.dirname(__file__)))):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/src/dtale/dtale/static/dist'
2021-06-29 17:00:12.234 500 GET /dtale/main/1 (::1) 22.61ms
```

I also tried doing a `git clone` and then doing `python setup.py sdist`, `python setup.py bdist_wheel`, etc. and installing the artifacts of that and I tried `npm run build` and that chugged along for a while and then seemed to fail with:

```[WEBPACK] Build failed after 141.391 seconds
[WEBPACK] Errors building dtale_bundle.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/abramowi/dev/git-repos/dtale/node_modules/d3-array/src/cumsum.js: Unexpected token (4:15)

  2 |   var sum = 0, index = 0;
  3 |   return Float64Array.from(values, valueof === undefined
> 4 |     ? v => (sum += +v || 0)
    |                ^
  5 |     : v => (sum += +valueof(v, index++, values) || 0));
  6 | }
```

Maybe there is some build step I'm missing that is necessary to do when checking out the dtale source code?

**Comment by msabramo** [comment]
Oh I just realized there's a `yarn.lock`, so I should probably be using yarn instead of npm. Let me see if that helps.

**Comment by aschonfeld** [comment]
Yea, sorry. yarn will get you where you need to go 😉

**Comment by msabramo** [comment]
Ah I just got every thing built with yarn and then created an sdist and installed that and it's working in Python. Trying it out now 🎉

**Comment by msabramo** [comment]
Hmmm I've been doing:

```python
dtale.global_state.set_app_settings(dict(max_column_width=400, max_row_height=400))
```

and it doesn't look like `max_row_height` is being honored?

![Screen Shot 2021-06-29 at 6 14 06 PM](https://user-images.githubusercontent.com/305268/123887144-d4039300-d905-11eb-9bd4-ee2dc7311a53.png)

**Comment by msabramo** [comment]
Hmmm I am able to set the row height in the UI though and it looks pretty good!

![Screen Shot 2021-06-29 at 6 14 06 PM](https://user-images.githubusercontent.com/305268/123887588-a3702900-d906-11eb-95a1-8d4aa41a8a45.png)

**Comment by aschonfeld** [comment]
Hmm you should be able to edit the height using the slider as i was able to do in the demo I posted earlier. I can look into why the code isnt being honored though. Sorry about that

**Comment by msabramo** [comment]
Oh yeah slider is fine. It's just the code that doesn't work. I looked around for maybe something missing by comparing to code for `max_column_width` but I didn't spot anything.

Oh here's one other weird thing. I'm not sure why but it's not in my last screenshot, but it's in this one:

![Screen Shot 2021-06-29 at 7 04 17 PM](https://user-images.githubusercontent.com/305268/123890950-f6e57580-d90c-11eb-9f81-684722da2190.png)

Note how the `winner` values are centered vertically but the `simple_win_count` values are at the tops of the cells?

**Comment by msabramo** [comment]
Hmmm, if I resize the `winner` column with the mouse, then the values seem to be top aligned, like with `simple_win_count` and it all looks consistent.

**Comment by aschonfeld** [comment]
@msabramo I've updated the branch with the fix for setting the row height programmatically.  Just be sure if your refreshing your local branch to run `git reset --hard origin/bugfixes_20210627` since I had to do some reshuffling for another commit.

As for the issue with the vertical alignment, is there any chance you could send me a sample of the data in columns `winner` & `sample_win_column`?  Without that I can't really figure out what's driving the alignment.

Thanks

**Comment by msabramo** [comment]
Is 05cca69d3bc784ad91163dced0995ff57c6825b8 the right commit?

I'll work on crafting some data you can use to reproduce the alignment bug.

Thanks, @aschonfeld!

**Comment by aschonfeld** [comment]
Yep looks like that is the right one. Thanks

**Comment by msabramo** [comment]
Cool yeah I was just checking because it wasn't working for me at first, but I think it's because I forgot to restart streamlit and it was holding on to some old dtale bits. Now it's working! Thanks!

**Comment by msabramo** [comment]
OK, for reproducing the vertical alignment bug, I was able to reproduce it with a regular old off-the-shelf CSV that I found:

[auto-mpg.csv](https://github.com/man-group/dtale/files/6750519/auto-mpg.csv)

In my code, I have:

```python
        dtale.global_state.set_app_settings(dict(max_column_width=120, max_row_height=120))
```

That results in this:

![Screen Shot 2021-07-01 at 1 06 34 PM](https://user-images.githubusercontent.com/305268/124183523-31662400-da6d-11eb-882c-e4a79dadb03a.png)

The last column (`name`) starts out top-aligned and all the other columns start center-aligned. If I resize any of those center-aligned columns, then the values become top-aligned. This is true regardless of whether I make the column wider or narrower.

**Comment by msabramo** [comment]
It looks like from setting a DOM breakpoint, it *might* have something to do with it changing the `"class"` attribute of the cell to `"cell editable resized"`?

**Comment by enovid** [comment]
The ability to set formatting per column is a great feature, and saves a lot of clicking when I'm frequently reloading the page.

I spent several hours trying to tell my "url" column to display as hyperlinks by default. The following code snippet is what finally worked (adapted from the replies above): 

```python
formatting = {'url': {'fmt': {'link': True}}}
dtale.global_state.set_settings('1', {'columnFormats': formatting})
```

**Comment by aschonfeld** [comment]
@envoid the branch that @msabramo is working off has an update for passing column formats like this:
```
dtale.show(df, column_formats={'url': {'fmt': {'link': True}}})
```

**Comment by aschonfeld** [comment]
@msabramo I've done some digging on the text columns being vertically aligned to the top.  So this only affects text columns and because when you resize text columns it has to be able to add an ellipses "..." to the end of the text if it's width is longer than that of the column.  Now when doing that you need to apply `display: block` which forces the text to the top.

I'll keep digging to see if there's a way to alter this, but just wanted to give a little background on what is going on.

**Comment by aschonfeld** [comment]
@msabramo Success!

https://user-images.githubusercontent.com/11547371/124215718-9304ad80-dac2-11eb-8ec0-a71fa4f0cf70.mov

**Comment by msabramo** [comment]
@aschonfeld: It looks great with the new changes! Thanks again!

**Comment by aschonfeld** [comment]
Great! Hoping to get a new version out soon, just gotta pick off a fee more issues

**Comment by msabramo** [comment]
Great! I saw that 1.52.0 was released and I just tried it out and it seems to work!

Thanks again for all your work on this, @aschonfeld!

**Comment by aschonfeld** [comment]
Happy to do it!

**Comment by msabramo** [comment]
FYI: I'm currently cleaning up a PR to add D-Tale to an internal tool that I'm working on (I work at Adobe so image support was pretty important for this tool).

Then our data science and ML folks can start exploring D-Tale and seeing how they can use it for their use cases.

**Comment by aschonfeld** [comment]
Tell your coworkers who have github accounts to throw their ⭐️ on the repo too 🙏

**Comment by hoangphucITJP** [comment]
Hi @aschonfeld . Can we show the local images? Like, allow to set up image folder as a static folder
