### ISSUE TITLE
sorting target column results

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#522]
In the column description by target please sort the columns based on number of cases in the pop up. 
Now the below Screenshot doesn't show columns which have result
![Screenshot_20210625-090711_Samsung Internet](https://user-images.githubusercontent.com/2202483/123429760-52260980-d595-11eb-8670-848cc0e9e0f2.jpg)

**Comment by reza1615** [comment]
in my opinion it should sorted by number, name

**Comment by aschonfeld** [comment]
![image](https://user-images.githubusercontent.com/11547371/123563817-cecb0a80-d784-11eb-8c6c-3038ad6399b0.png)

**Comment by aschonfeld** [comment]
updated in v1.51.0
