### ISSUE TITLE
Installation - No module named 'plotly.express'

### ISSUE THREAD

**Issue by ItayKishon-Vayyar** [man-group/dtale#523]
Hi,
I've tried installing dtale, via conda.
After this [small issue](https://github.com/smicallef/spiderfoot/issues/1124), solved by installing networkx=2.5, I've encountered the following error:

```
ModuleNotFoundError: No module named 'plotly.express'
```

I understand there's been some change recently to plotly's express submodule, but I can't seem to fix this.

Installed versions:
Python 3.9.5
dtale 1.50.1
plotly 3.10.0

Thanks.

**Comment by aschonfeld** [comment]
@ItayKishon-Vayyar  I was able to create a fresh conda environment w/ D-Tale installed:
```
conda create -n py39 python=3.9 anaconda
conda activate py39
conda install dtale -c conda-forge
```

Then I opened a python console and ran the following commands:
```
import dtale
import pandas as pd
dtale.show(pd.DataFrame([1,2,3,4,5]))
```

I had no issues bringing up the app.  Is there some operation you're trying to perform that brings up the `plotly.express` error?  I'd also suggest maybe reinstalling `plotly`

Let me know how it turns out.  Good luck

**Comment by ItayKishon-Vayyar** [comment]
@aschonfeld,
Indeed, a fresh installation (python=3.9, anaconda) works.

I've noticed that with this installation, `plotly 5.1.0` is installed, whereas my original environment had `plotly 3.10.0` for some reason. It seems that `plotly 4` had a major change with the `plotly.express` submodule ([see here](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#added-15)).

Perhaps `plotly 5` should be added as a module requirement?

Thanks.

**Comment by aschonfeld** [comment]
Thabks @ItayKishon-Vayyar, i can look into updating the dependencies to be pinned to plotly 5. Do you mind tossing your ⭐️ on the repo? 🙏

**Comment by aschonfeld** [comment]
So the current plotly versions being used are:
```
plotly==4.14.3; python_version < '3.6'
plotly>=4.9.0; python_version >= '3.6'
```

I'm going to update this to:
```
plotly==4.14.3; python_version < '3.6'
plotly>=5.0.0; python_version >= '3.6'
```

**Comment by ItayKishon-Vayyar** [comment]
That sounds a bit strange - as you can see in my first post, I installed the latest dtale version (1.50.1), yet ended up with plotly 3.10.0 (with Python 3.9.5). So perhaps something wasn't configured correctly with the requirements?
Also, there was this issue with networkx.

Thanks for looking into this. I've started playing with your project, and it seems very cool.

**Comment by aschonfeld** [comment]
Ahhhh, looks like conda doesn't follow the version pinning used in `pip`.  I'm going to update the [conda build recipe](https://github.com/conda-forge/dtale-feedstock/blob/master/recipe/meta.yaml) to follow the version restrictions of [requirements.txt](https://github.com/man-group/dtale/blob/master/requirements.txt)

**Comment by aschonfeld** [comment]
@ItayKishon-Vayyar try installing 1.50.1 of the conda version now.  I updated the recipe to have `plotly >=4.14.3`

**Comment by aschonfeld** [comment]
Updated in v1.51.0
