### ISSUE TITLE
correlation analysis

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#528]
1- To make it more clear please:
* Rename it to **Feature analysis by correlation**. for the left to make the title shorter label it as **Feature analysis** 
* Max Correlation > Maximum correlation with other columns

2- After draping a column it will drop after that if we reopen the Correlation Analysis still that column remains. for example drop 
Pclass and reopen the Correlation Analysis. still show it.

![image](https://user-images.githubusercontent.com/2202483/123631938-521c4880-d7e5-11eb-890e-f1a5ebac5eb4.png)

**Comment by aschonfeld** [comment]
(2) is strictly a bug with the demo site, which I have detailed in the past.  If you refresh the page it should resolve itself.

**Comment by aschonfeld** [comment]
Updated in v1.51.0

**Comment by reza1615** [comment]
I believe you for got the
 Max Correlation > Maximum correlation with other columns

**Comment by aschonfeld** [comment]
Fixed in v1.52.0
