### ISSUE TITLE
Resampling timeseries

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#529]
Pandas has a very useful functionality to aggregating timeseries 
For example the below code
``` python
import pandas as pd
import numpy as np
start, end = '2000-10-01 23:30:00', '2000-10-03 00:30:00'
rng = pd.date_range(start, end, freq='7min')
ts = pd.Series(np.arange(len(rng)) * 3, index=rng)
ts2 = pd.Series(np.arange(len(rng)) * 0.32, index=rng)
d = {'col1': ts, 'col2': ts2}
df = pd.DataFrame(data=d)
df.resample('17min').mean() # Resample data per 17 min interval 
```
It would be nice to have a subsection for TimeSeries  to resample. (We need a window similar to build columns for time series because timeseries need many enhancements which is specified to them. so it is much better to separate them from build column) 
for this enhancement we need these inputs
* date time column name (to set it as DataFrame index for resampling)
* pre-defined **Offset aliases** as drop down option ([here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases) there is list of pre-defined rules) for cases like (rule == B or C or D ,...)
* Interval value for some Offset aliases (for cases like 17M or 23S or 5H ,....) 
* Aggregation dropdown (sum, mean, std, sem, max, min, median, first, last, ohlc) [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#resampling)

output : 
* Save results in a new instance.

**Comment by reza1615** [comment]
I like the ohlc. It is so interesting
``` python
import pandas as pd
import numpy as np
start, end = '2000-10-01 23:30:00', '2000-10-03 00:30:00'
rng = pd.date_range(start, end, freq='7min')
ts = pd.Series(np.arange(len(rng)) * 3, index=rng)
ts2 = pd.Series(np.arange(len(rng)) * 0.32, index=rng)
d = {'col1': ts, 'col2': ts2}
df = pd.DataFrame(data=d)
df.resample('17min').ohlc() # Resample data per 17 min interval 
```
![image](https://user-images.githubusercontent.com/2202483/123659484-bdbfdf00-d800-11eb-8788-83edb8b8738f.png)


![image](https://user-images.githubusercontent.com/2202483/123659437-af71c300-d800-11eb-9e2c-5d01630d0457.png)

**Comment by aschonfeld** [comment]
https://user-images.githubusercontent.com/11547371/125150411-a5f42f00-e10d-11eb-9aea-b8dd7dd07d44.mov

**Comment by aschonfeld** [comment]
added in v1.52.0
