### ISSUE TITLE
UI: organizing the Build Column department

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#531]
To make it more clear I purpose the below UI. Also In my opinion its name should be **Data Functionality** or **DataFrame functions**
also theses section can be a tab
![image](https://user-images.githubusercontent.com/2202483/123666915-a3d5ca80-d807-11eb-9839-4e20521f94d0.png)

**Comment by aschonfeld** [comment]
updated in v1.51.0

**Comment by reza1615** [comment]
I believe you forgot to rename it to the

 **Data Functionality** or **DataFrame functions**

**Comment by aschonfeld** [comment]
Fixed in v1.52.0
