### ISSUE TITLE
Shift and expanding

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#532]
For build column. Please add Shift and expanding functionality 
* [shift](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shift.html?highlight=shift#pandas.DataFrame.shift) 
* [expanding](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.expanding.html#pandas.DataFrame.expanding)

**Comment by aschonfeld** [comment]
added in v1.52.0
