### ISSUE TITLE
split timeseries to cycle and trend in chart and as a two new columns

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#533]
There is a possibility to split a timeseries to trend and cycle like below.
It can be on fly for chart and new columns in build column department
```python
import pandas as pd
df = # load stock data
from statsmodels.tsa.filters.hp_filter import hpfilter
# Tuple unpacking
gdp_cycle, gdp_trend = hpfilter(df['open'], lamb=1600)
df['trend'] = gdp_trend
df[['trend','open']].plot()
```
Original 
![image](https://user-images.githubusercontent.com/2202483/123671672-89eab680-d80c-11eb-8d4d-472b61b529d5.png)

Trend
![image](https://user-images.githubusercontent.com/2202483/123671324-1fd21180-d80c-11eb-81a7-e4ad2ffef0c2.png)

and for cycle
`gdp_cycle.plot()`
![image](https://user-images.githubusercontent.com/2202483/123671090-e699a180-d80b-11eb-8fe4-3c6935146e88.png)

**Comment by reza1615** [comment]
Also there are another algorithms which user can select from them. for example 
``` python
from statsmodels.tsa.seasonal import seasonal_decompose
result = seasonal_decompose(df['open'], model='multiplicative')  
result.plot();

# or
result.trend.plot()
result.seasonal.plot()
result.resid.plot()

```
![image](https://user-images.githubusercontent.com/2202483/123693842-93811800-d826-11eb-938f-fb40e867c042.png)

**Comment by aschonfeld** [comment]
Added in v1.60.1

Here's a [demo](https://youtu.be/LqSryRv7QO4)
