### ISSUE TITLE
ImportError: cannot import name 'geoplot' from 'missingno.missingno'

### ISSUE THREAD

**Issue by enovid** [man-group/dtale#534]
`missingno` version 0.4.3 (released on pypi today) breaks an import in `dtale`. 

**What happened:**

```python
!pip install dtale
import dtale
>>> ImportError: cannot import name 'geoplot' from 'missingno.missingno' ...
```

**Temporary solution:**
```
pip install missingno==0.4.2
```

**Comment by aschonfeld** [comment]
Yep, looks like they just released a new version of `missingno` with that bug in it 🙄 I'll pin it to 0.4.2.  Thanks for the heads up!

**Comment by aschonfeld** [comment]
updated in v1.51.0
