### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by firmai** [man-group/dtale#541]
Sorry for being that guy, but it would be amazing to have the ability to switch between a dark and light mode (if it was my project I would ignore this request for as long as possible though :) 

Thanks again for the great project, following it very closesly.

**Comment by reza1615** [comment]
It has this possibility 
![Screenshot_20210723-055531_Samsung Internet](https://user-images.githubusercontent.com/2202483/126766241-4df44573-9354-4131-8378-ca2380708cca.jpg)

**Comment by aschonfeld** [comment]
@firmai here's a demo of the functionality, let me know if its missing anything you need

https://user-images.githubusercontent.com/11547371/127083280-0ba63912-dfc7-4430-b83f-05991cfaa8af.mov

**Comment by firmai** [comment]
Your just too great!! Thanks.

**Comment by firmai** [comment]
@aschonfeld  When it comes to the auxiliary screens, can we achieve a similar effect, ?  

http://alphatechadmin.pythonanywhere.com/dtale/charts/4?chart_type=3d_scatter&query=&x=date&z=Col0&agg=raw&cpg=false&y=%5B%22security_id%22%5D


![image](https://user-images.githubusercontent.com/26666267/127144723-fdfac283-9446-4f93-98b2-01685581b2b9.png)

**Comment by aschonfeld** [comment]
How's this?

![image](https://user-images.githubusercontent.com/11547371/127153421-7f3e9ecc-d0ac-493b-9564-2a7912b461b9.png)

It's going to take some work to try and get the actual chart itself to no longer have a white background.

**Comment by aschonfeld** [comment]
@firmai added the changes shown above in v1.53.0

**Comment by firmai** [comment]
beautiful thanks!

**Comment by aschonfeld** [comment]
@firmai if you haven’t already, please toss your ⭐️ on the repo. Thanks 🙏
