### ISSUE TITLE
Attribute Error while using Dtale .

### ISSUE THREAD

**Issue by sayedathar11** [man-group/dtale#542]
I am trying to do EDA on a pandas Dataframe using Dtale , My Pandas Dataframe has combination of Numerical , Categorical and Date time type columns , but problem is when I calling dtale.show(data,ignore_duplicate=True) .
It is showing error "AttributeError: 'int' object has no attribute 'strip'"

I am also attaching screenshot of the error please find the attachment .
![dtaleerror](https://user-images.githubusercontent.com/17905011/126976083-aa1d6e62-afb4-4c7d-8bdb-45be07a24acc.PNG)

**Comment by aschonfeld** [comment]
@sayedathar11 good catch!  I'm working on adding some handling that will check if the dtype of the categories is of "string" type before performing this operation.

So `if dtype.startswith("category")` will become `if dtype.startswith("category") and classify_type(s.dtype.categories.dtype.name) == "S"`

**Comment by sayedathar11** [comment]
Thanks @aschonfeld  for solving this issue.

**Comment by aschonfeld** [comment]
No problem, happy to help @sayedathar11 please take a second to toss your ⭐ on the repo if you haven't already.  Thanks 🙏

**Comment by sayedathar11** [comment]
Hiii @aschonfeld  unfortunately the issue is still persisting !  Can you please check it ? I am attaching the snapshot
![dtale2](https://user-images.githubusercontent.com/17905011/127456173-228aa342-0011-49ae-9ae3-4d233ff0fda4.PNG)

**Comment by aschonfeld** [comment]
Based on the line of code that it failed on, it looks like your version of D-Tale has not been updated.  If you're using a virtual environment please run the following:
```
pip uninstall dtale
pip install dtale==1.53.0
```

If using conda:
```
conda uninstall dtale
conda install dtale -c conda-forge
```

**Comment by sayedathar11** [comment]
@aschonfeld Thanks alot will check it .
