### ISSUE TITLE
More cumsum... now with 

### ISSUE THREAD

**Issue by appznoix** [man-group/dtale#543]
@aschonfeld , hope this finds you well.

Few week ago, I opened an issue pertaining the cumsum function, remember? You've added it to Build Column dialog. Kudos!

Still, can't find a way to do something like this:

`df["total_profit"] = df.groupby(["product"])['profit'].cumsum()`

Using Transform in the Build Column dialog, the closest I got was:

`new_column = df.groupby(['product'])['profit'].transform('sum')`

Can it be done?

**Comment by aschonfeld** [comment]
Sure thing @appznoix  I can add an optional "Group By" dropdown to the "Cumulative Sum" builder.  Good catch

**Comment by aschonfeld** [comment]
@appznoix this was added in v1.53.0
