### ISSUE TITLE
DTale missing analysis Bar chart could not be loaded!

### ISSUE THREAD

**Issue by Basavaraj-Hadapad** [man-group/dtale#544]
Many a times bar chart in 'Missing Analysis' does not open up and throws error 'Chart could not be loaded!'. It usually happens when have more columns or rows. Please fix this. Thank you

**Comment by aschonfeld** [comment]
@Basavaraj-Hadapad apologies for the issues.  Can you give me some more information around the dimensions of your dataframe?  I need some more context so I can build some test data.  It might be an issue with the `missingno` package and not D-Tale itself.

**Comment by aschonfeld** [comment]
@Basavaraj-Hadapad I think I have figured out the issue.  I'll let you know once a new version has been released

**Comment by aschonfeld** [comment]
@Basavaraj-Hadapad this has been fixed in v1.54.0.  If you haven't already, please toss your ⭐ on the repo.  Thanks 🙏
