### ISSUE TITLE
Add prefix and/or suffix to column content

### ISSUE THREAD

**Issue by Chocoder** [man-group/dtale#545]
Hello, thanks for achieving my last - and first - post!

I have a new request, maybe the option already exists... could we offer the possibility to add a suffix and/or prefix to an existing column? Option for replacing existing one or creating a new one would be appreciated !

Thanks

**Comment by aschonfeld** [comment]
@Chocoder you are correct.  It does not appear that this functionality exists.

So for adding a prefix/suffix I can do something similar to the "Numeric" add/subtract/multiply/divide function where you can specify a column or a static value:
![image](https://user-images.githubusercontent.com/11547371/127562044-79e486d3-7ae5-4a93-8ada-8a6f3d2f1bc3.png)

I will call this **"Concatenate"** and you can either concatenate:
**prefix**: a static value as the first value and a column as the second
**suffix**:  a column as the first value and a static value as the second

For the other are you asking to replace/remove a prefix/suffix?  Essentially replace any substring? Or does it always have to occur at the beginning or the end?

**Comment by Chocoder** [comment]
Hello! It is a starting or finish need there so your proposition looks nice to me!

**Comment by aschonfeld** [comment]
I'll add a function called "Replace" in addition to the "Concatenate" function which will allow you to use the `str.replace` function in pandas shown [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.replace.html)

**Comment by aschonfeld** [comment]
I'll add a function called "Replace" in addition to the "Concatenate" function which will allow you to use the `str.replace` function in pandas shown [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.replace.html)

**Comment by aschonfeld** [comment]
@Chocoder this has been added in v1.54.0
