### ISSUE TITLE
grouping charts by multiple columns is not working

### ISSUE THREAD

**Issue by arashaneh** [man-group/dtale#549]
In many cases, we want to create charts that are the result of grouping more than one categorical column. When trying that we get this error: "too many values to unpack (expected 2)".
Is that a known issue that is not yet fully implemented or it is a simple bug to fix?

I attached an screenshot of the error message:
<img width="953" alt="Capture46 (002)" src="https://user-images.githubusercontent.com/6926086/129078741-8aec8d15-615a-40d4-beb6-bb7e33942286.PNG">

**Comment by aschonfeld** [comment]
@arashaneh sorry about that. I'm digging into this now.

**Comment by aschonfeld** [comment]
@arashaneh just released a hotfix v1.54.1 with a fix for this issue.  Hope this helps.  Also, if you haven't already please toss your ⭐  on the repo. Thanks 🙏

**Comment by arashaneh** [comment]
I appreciate it!
