### ISSUE TITLE
Mis-renamed colums crash dtale under Jupyter

### ISSUE THREAD

**Issue by eeaston** [man-group/dtale#55]
The following minimal example will cause the Jupyter kernel to crash with all sorts of amazing looking IO errors:

    import dtale
    import pandas as pd

    df = pd.DataFrame([[1,2],[3,4]], columns=['a','b'])

    dtale.show(df.rename(columns={'a':'b'}))

The subtle error here is where I rename a column over the top of another one.  This new dataframe seems to look OK, and can be printed to a terminal, but dtale blows up when rendering it.  

Ideally, pandas should not allow me to do this, and this might just be dtale not being able to handle corrupted internal memory in pandas (in which case I'll go file this in pandas instead).

**Comment by aschonfeld** [comment]
Fixed in v1.7.0
