### ISSUE TITLE
Return current state dataframe

### ISSUE THREAD

**Issue by cmartinotti** [man-group/dtale#550]
Is there a way to return the current state of the dataframe  directly into a dataframe rather than saving a csv or exporting the whole code? What I mean would be similar to the qgrid function: df.get_changed_df() .
 
I can't find it in the documentation, in the case that there isn't it would be very useful to have a function that returns the current state of the dataframe, especially for casual users.

**Comment by aschonfeld** [comment]
@cmartinotti here's some documentation on [programatic functions](https://github.com/man-group/dtale#additional-functions-available-programmatically) available in D-Tale.

For your case I think you'd like to make use of the `.data` property on your D-Tale instance. For example:
```
import dtale
import pandas as pd

d = dtale.show(pd.DataFrame([1,2,3,4,5]))
updated_df = d.data
```

Hope this helps and if you haven't already please toss your ⭐ on the repo. Thanks! 🙏
