### ISSUE TITLE
Exceptions when filtering on dtypes that support pd.NA

### ISSUE THREAD

**Issue by lcorrigan** [man-group/dtale#552]
For the record, I'm just getting started with Dtale and I'm blown away by it's capabilities - thank you for creating it.

I've found that Dtale throws an exception when I try to filter on columns that have dtypes which support NA (vs np.nan): https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#support-for-integer-na
The error it throws is below.
I was getting in this state by calling '[dataframe].convert_dtypes()' which I was using for some dynamic column adding routines. This function chooses the best fit dtype that supports NA.

Also odd but not breaking, is that if the Integer type is an _**unsigned**_ numpy dtype (e.g.: np.uint16) filtering will render no results. The query single-quotes the chosen filter value as though it were a string but signed works fine.

`Traceback (most recent call last):
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\views.py", line 105, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\views.py", line 2317, in get_data
    data = run_query(
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\dtale\query.py", line 65, in run_query
    df = df.query(
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 4055, in query
    res = self.eval(expr, **kwargs)
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 4186, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\computation\eval.py", line 353, in eval
    ret = eng_inst.evaluate()
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\computation\engines.py", line 80, in evaluate
    res = self._evaluate()
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\computation\engines.py", line 121, in _evaluate
    return ne.evaluate(s, local_dict=scope)
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\numexpr\necompiler.py", line 823, in evaluate
    signature = [(name, getType(arg)) for (name, arg) in
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\numexpr\necompiler.py", line 823, in <listcomp>
    signature = [(name, getType(arg)) for (name, arg) in
  File "C:\Users\lcorrigan\AppData\Local\Programs\Python\Python38\lib\site-packages\numexpr\necompiler.py", line 705, in getType
    raise ValueError("unknown type %s" % a.dtype.name)
ValueError: unknown type object`

**Comment by aschonfeld** [comment]
@lcorrigan thanks for the kind words.  Apologies for the bug, I'll start digging into it now.  In the meantime, if you haven't already please toss your ⭐ on the repo.  Thanks 🙏

**Comment by aschonfeld** [comment]
So I have already fixed about 3 bugs related to this (although I haven't see the exact exception you were seeing).  Here's the test data I used:
```
import pandas as pd

s_int = pd.Series([1, 2, 3, 4, 5], index=list("abcde"), dtype=pd.Int64Dtype())
s2_int = s_int.reindex(["a", "b", "c", "f", "u"])
df = pd.DataFrame(dict(x=s2_int))
```


https://user-images.githubusercontent.com/11547371/129662749-fbd50f48-abf8-4aa7-975b-4f95e4799ba3.mov

Let me know what you think

**Comment by lcorrigan** [comment]
Thanks @aschonfeld. Your example test throws the exception on my machine with 1.54.1, so looks like your fix would cover my problem. Thanks for jumping on this so quickly. Would it also fix how unsigned types were filtering incorrectly in queries? If it does not, I could split that into a separate issue if you would prefer.

**Comment by aschonfeld** [comment]
I mocked up some data using this:
```
import pandas as pd

s_int = pd.Series([1, 2, 3, 4, 5], index=list("abcde"), dtype=pd.Int64Dtype())
s2_int = s_int.reindex(["a", "b", "c", "f", "u"])
ints = pd.Series([1, 2, 3, 4, 5], index=list("abcfu"))
df = pd.DataFrame(dict(na=s2_int, int=ints))
df.loc[:, 'unsigned_int'] = pd.to_numeric(df['int'], downcast='unsigned')
```

https://user-images.githubusercontent.com/11547371/129727151-3e645618-6b1c-45c2-8c76-be93e9683b18.mov

**Comment by lcorrigan** [comment]
@aschonfeld Looks great.

**Comment by aschonfeld** [comment]
Terrific, I just need to add some testing and I'll try getting out a release either tonight or tomorrow.

**Comment by aschonfeld** [comment]
@lcorrigan just released v1.55.0 with a fix for this, let me know if you still have issues

**Comment by lcorrigan** [comment]
Thanks @aschonfeld - can filter correctly on the nullable Int types now.
I was not successful however in filtering when the data type was dtype uint64 (trips safe cast rule?) or using nullable UInt64 type (unknown object). For reference, there is no missing data in this column I'm playing with and I'm importing the data as those types for this - not getting dtale to convert them for me first.
![Filtering_UInt64](https://user-images.githubusercontent.com/12451259/129906382-b57a0e65-e025-48bb-b0b2-5f0ce8255b7a.png)
![Filtering_dtype_uint64](https://user-images.githubusercontent.com/12451259/129906388-3b5f9ee5-792c-42e8-a962-ce3dc9bf6d9f.png)

**Comment by aschonfeld** [comment]
@lcorrigan any chance you can send over a sample of data?  I'm using the following and everything seems to be working fine:
```
            import pandas as pd
            import random

            s_int = pd.Series([random.randint(1, 100000000000) for _ in range(5)], index=list("abcde"), dtype=pd.Int64Dtype())
            s2_int = s_int.reindex(["a", "b", "c", "f", "u"])
            ints = pd.Series([random.randint(1, 100000000000) for _ in range(5)], index=list("abcfu"))
            df = pd.DataFrame(dict(na=s2_int, int=ints))
            df.loc[:, 'unsigned_int'] = pd.to_numeric(df['int'], downcast='unsigned')
            return df
```

**Comment by lcorrigan** [comment]
Hi @aschonfeld. I've attached some data as csv but unless you import it as these types, pandas will just default to signed numpy types. I didn't see an option in Dtale to set any of the import csv pandas options. The types on my end are below. I've tried after calling "tempy = tempy.convert_dtypes()" to get the nullable versions, but I still get an error coming from the safe cast attempt with those (when unsigned). Note for unsigned types nullable or not, the 16 byte columns are ok for filtering - but if you filter on the 'id' column, I trip the exception as before. I'm not sure what numexpr's problem is, since the numbers are less than even the max for a signed int32 (there should be lots of room to play for casting).  
[example_data.csv](https://github.com/man-group/dtale/files/7031482/example_data.csv)


id                       uint64
creation_time    datetime64[ns]
timestamp        datetime64[ns]
packet_type              uint16
psn                      uint16
module                   uint16
component                uint16
parameter                uint16
dtype: object

I'm running this combo below:

python 3.8.10
numexpr  2.7.3  
dtale  1.55.0
pandas  1.3.2
numpy  1.21.2

**Comment by aschonfeld** [comment]
@lcorrigan I did some digging using the information you gave (thank you for that) and the issue appears to be your usage of `numexpr`.  If you uninstall that D-Tale should work correctly.  I'll keep digging on why `numexpr` breaks it.

**Comment by aschonfeld** [comment]
So it looks like the solution to this problem is to update my usage of `pandas.Dataframe.query` so that `engine='python'`.  By default `engine='numexpr'`.  If this seems fine to you I'll add this fix

**Comment by lcorrigan** [comment]
@aschonfeld, I'm glad you said that, as numpy is dependant on numexpr - I can't remove it.  Yes, specifying the engine is the way to go, however I would not suggest you change it for all cases of filtering (query) because the python engine is slower than numexpr.  Could you give the user the option of which one to use?

**Comment by aschonfeld** [comment]
Ok, I'll try adding an "engine" toggle in the "Custom Filter" modal window

**Comment by aschonfeld** [comment]
Here's what I got:

https://user-images.githubusercontent.com/11547371/130721978-ff7a77e9-f5cb-4f58-b421-fb24e68f0b16.mov

I have also added a property to the application settings `query_engine` and the two options are "python" & "numexpr" so if you want to set it to one of the other for all your sessions going forward you can by using a configuration file (heres the [documentation](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md))

**Comment by lcorrigan** [comment]
@aschonfeld That looks pretty good!

**Comment by aschonfeld** [comment]
updated in v1.56.0
