### ISSUE TITLE
Apply filter in describe or charts

### ISSUE THREAD

**Issue by Chocoder** [man-group/dtale#557]
Hello, when i apply some filtering to the dataset columns I would like this to apply in describe column or chart options. But it shows me the full dataset without applying the filtering...
Is this normal?

**Comment by aschonfeld** [comment]
Charts should be carrying over the current filters over and display them in the "Query" input at the top of the screen.  Then from there you can make the edits you like.  Here's a demo:

https://user-images.githubusercontent.com/11547371/130682449-340f13de-aac5-4161-b577-7b8d69db4134.mov

I can work carrying over the current filter into the "Describe" page for you.  Apologies for the inconvenience

**Comment by aschonfeld** [comment]
@Chocoder here's my progress on adding filtering to the "Describe" window

https://user-images.githubusercontent.com/11547371/131428386-7fac5c86-bba2-4bc5-bef3-576b04343414.mov

Gonna try adding a tooltip to the "Filtered" toggle so it's a little clearer what it is there for.

**Comment by aschonfeld** [comment]
Added in v1.56.0
