### ISSUE TITLE
Column "Variance Report" and "Describe" only apply to filtered data set (Visible rows in dtale)

### ISSUE THREAD

**Issue by ndgayan** [man-group/dtale#558]
Is there any way to change the default behavior of the "Variance Report" and "Describe" functions only applies visible rows if a filter/s exists? The default behavior is always to use the entire data set.

**Comment by aschonfeld** [comment]
@ndgayan i actually just did a release v1.56.0 including this change for the “Describe” panel (see video at bottom of this issue: https://github.com/man-group/dtale/issues/557).

i’ll work on updating the variance report with this feature as well

**Comment by ndgayan** [comment]
Thank you. I really appreciate it.

**Comment by aschonfeld** [comment]
@ndgayan sure thing, will update you once the Variance Report has been updated. If you havent already, please toss your ⭐️ on the repo. Thanks 🙏
