### ISSUE TITLE
Split or Merge columns

### ISSUE THREAD

**Issue by IanMayo** [man-group/dtale#563]
I've done some dtale research, but cannot see how to split or merge columns.

For example, my data may have separate date and time columns - which I wish to merge into one date-time column. Or, I may have an address column which I wish to split into house-number and street-name.

Any tips welcome :-)

**Comment by IanMayo** [comment]
Aah, I think I've got it.  Is in the `Dataframe functions`?

Are there any tutorials/guidance covering this capability?

**Comment by aschonfeld** [comment]
@IanMayo you are correct, this functionality will reside in "Dataframe Functions".  Here's a short video on how you can perform the operations you'd need: https://youtu.be/o4ieAymgUFY

**Comment by IanMayo** [comment]
Hello @aschonfeld - thanks for the prompt demo.  Note: I'll be looking for a YouTube setting to slow the video down - you're like a dtale wizard!

**Comment by aschonfeld** [comment]
@IanMayo hahaha, sorry about that. Was originally trying to paste the video right in github so i had to go fast. Any other questions on functionality happy to post additional videos or add features if they dont exist.

Good luck and if you havent already, please toss your ⭐️ on the repo. Thanks! 🙏

**Comment by IanMayo** [comment]
I tried to use the functionality myself, but got stuck due to being unfamiliar with some of the terms on the `Dataframe functions` page.

Are the terms used the same as used in pandas?  In that case I'll look to pandas for more explanations.  Or, have you devised the terms, in which case I'll look further in the `dtale` docs.
