### ISSUE TITLE
Geometric mean aggregation function

### ISSUE THREAD

**Issue by joewaihenya** [man-group/dtale#564]
Been using this wonderful tool and its great. Super thankful to have it for Exploratory Data Analysis.

I wonder if its possible to add the geometric mean to the list of functions that one can use to summarize data. Could someone offer some pointers as to how I can add it in?

**Comment by aschonfeld** [comment]
@joewaihenya i’m currently working on a new version with some new features. I can add this to the list.  Seems like a pretty easy add to the “summarize data” functionality. In addition, i can add it to the “dataframe functions” page if you want to work horizontally on columns like in this example: https://www.google.com/amp/s/www.geeksforgeeks.org/find-the-geometric-mean-of-a-given-pandas-dataframe/amp/

**Comment by aschonfeld** [comment]
@joewaihenya just added this feature to v1.57.0 which has just been released to pypi & conda-forge.  If you haven't already, please put your ⭐ on the repo. Thanks 🙏
