### ISSUE TITLE
Scatter Plot shows multiple charts for Y axis irrespective of whether Chart Per Y Toggle is On or Off

### ISSUE THREAD

**Issue by jasjyotsinghjaswal** [man-group/dtale#565]
Hi Team,

The bar plot in D Charts shows single or 2 charts depending on Selected Value for Toggle Button but scatter plot shows only 2 chart irrespective of whether Toggle value on the **Chart Per Y** button is on or off. It shows 2 charts despite the Off Value
Please see screenshot below
![image](https://user-images.githubusercontent.com/24617050/133905427-dd5970c4-01c4-4f95-ac7e-b410b28b98c0.png)

**Comment by aschonfeld** [comment]
@jasjyotsinghjaswal this fix has been included in the new version v1.57.0 just released to pypi & conda-forge.  IF you have yet, please put your ⭐ on the repo.  Thanks 🙏

**Comment by jasjyotsinghjaswal** [comment]
> @jasjyotsinghjaswal this fix has been included in the new version v1.57.0 just released to pypi & conda-forge. If you have yet, please put your ⭐ on the repo. Thanks 🙏

Sure. Manu thanks for the fix
