### ISSUE TITLE
Enhancement request for Clustermap

### ISSUE THREAD

**Issue by jasjyotsinghjaswal** [man-group/dtale#566]
Hi Team,

Great set of visualisation options in D-Tale . Is it possible to also add clustermap option in Charts window?

**Comment by aschonfeld** [comment]
Thanks for the kind words @jasjyotsinghjaswal, any chance you could send me an example of a clustermap?  Under the hood i'm using plotly dash to power the "Charts" page and I don't see an example of that in their documentation.  Thanks 🙏

**Comment by jasjyotsinghjaswal** [comment]
> Thanks for the kind words @jasjyotsinghjaswal, any chance you could send me an example of a clustermap? Under the hood i'm using plotly dash to power the "Charts" page and I don't see an example of that in their documentation. Thanks 🙏

Hi this is what it looks like https://dash.plotly.com/dash-bio/clustergram . Similar to Heatmap but not exactly that .. It basically clusters together rows that may be related to each other along with clustering columns that are similar to each other

**Comment by aschonfeld** [comment]
Cool! Thanks, I'll work on adding this in

**Comment by aschonfeld** [comment]
@jasjyotsinghjaswal just released v1.58.1 with this functionality.  Hope this helps and let me know if there are any issues
