### ISSUE TITLE
Allow for multiple instances of "Range Highlight" with different colors

### ISSUE THREAD

**Issue by aschonfeld** [man-group/dtale#568]
Ability to color rows in a more customized way. What I would really like to do is color them based on a certain value range. The closest thing to this is 'Highlight Range', which looks like it's almost exactly what I'd need, but it's currently limited to the color yellow. Ideally, it would be possible to set up more than 1 condition (e.g. if greater than x, then color it red, if greater than y, then color it orange, if less than z, color it blue). Personally, I don't need a gradient for my purposes, but I imagine some people might.
Additionally, it would be very meaningful if it was possible to configure this in code, before launching dtale. Otherwise, I'd need to set it up manually every time I run dtale.
I'd like to point out the obvious and say that this is also Excel-like functionality. But it really makes the data easier to make sense of at a quick glance.

**Comment by aschonfeld** [comment]
@proxseas here's what I have so far

https://user-images.githubusercontent.com/11547371/134611047-04fbe189-bf07-42d9-a830-f9cd47b16a35.mov

:

**Comment by aschonfeld** [comment]
@proxseas you will be able to set ranges programatically as follows:
```
import pandas as pd
import dtale

df = pd.DataFrame(dict(a=[1,2,3,4,5]))
d = dtale.show(df)
range_highlights = {
  'a': {
    'active': True,
    'equals': {'active': True, 'value': 3, 'color': {'r': 255, 'g': 245, 'b': 157, 'a': 1}}, # light yellow
    'greaterThan': {'active': True, 'value': 3, 'color': {'r': 80, 'g': 227, 'b': 194, 'a': 1}}, # mint green
    'lessThan': {'active': True, 'value': 3, 'color': {'r': 245, 'g': 166, 'b': 35, 'a': 1}}, # orange
  }
}
d.update_settings(range_highlights=range_highlights)
```

![image](https://user-images.githubusercontent.com/11547371/134692901-a535f5c9-71e5-4fa1-9e74-b0233219fc8f.png)

**Comment by proxseas** [comment]
Looking good!

**Comment by aschonfeld** [comment]
Added in v1.58.1
