### ISSUE TITLE
How to deploy dtale in voila?

### ISSUE THREAD

**Issue by JimmyLzy** [man-group/dtale#587]
Hi team,
When running this code locally with voila, I can't access dtale with http://localhost:8000/user/jliu05/proxy/40000/dtale/main/1. Could you please help me?
```python
import dtale
import dtale.app as dtale_app

dtale_app.JUPYTER_SERVER_PROXY = True

dtale.show(data_pivoted, show_columns=rows)
```
Thank you,
Jimmy

**Comment by aschonfeld** [comment]
@ndgayan thanks for the feedback!

@JimmyLzy I'm wondering if your original code snippet will work if you grab the latest version of D-Tale (1.59.1).  There was some updates I made to the JUPYTER_SERVER_PROXY functionality for the purposes of using it in Binder.  Also, I was able to bring up D-Tale with no issue in a local notebook with viola enabled.  theoretically you shouldn't need to wrap it in `widgets` or `HBox`.  When calling `dtale.show` it should display it using a combination of:
* `IPython.display.IFrame`
* `IPython.display.display`

Let me know how it goes.  Happy to keep digging into this.

Lastly, if either of you haven't already, please toss your ⭐ on the repo. Thanks 🙏
