### ISSUE TITLE
Pareto Chart with cumulative percentage

### ISSUE THREAD

**Issue by info-rchitect** [man-group/dtale#589]
Hi,

I have some `pandas` code that creates a pareto table from categorical data:

![image](https://user-images.githubusercontent.com/26782653/138108953-e7f077a7-e009-47fa-bb1a-dbbc39524c28.png)

Is there a way to get a pareto chart with cumulative percentage?  Here is an example using `plotly`:

```
from plotly.subplots import make_subplots
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(
    go.Bar(
        x=pareto['SOFT_BIN_DESC'], # assign x as the dataframe column 'x'
        y=pareto['COUNT'],
        name='Count'
    ),
    secondary_y=False
)
fig.add_trace(
    go.Scatter(
        x=pareto['SOFT_BIN_DESC'],
        y=pareto['CUMULATIVE_PERCENT'],
        name='CumPercent'
    ),
    secondary_y=True

)

fig.update_layout(
    title_text='Pareto Chart with Cumulative Percent',
    width=1000,
    height=500
)
    
fig.update_xaxes(title_text="<b>SOFT_BIN_DESC</b>")
fig.update_yaxes(title_text="<b>CumPercent</b>", secondary_y=True)
fig.update_yaxes(title_text="<b>Count</b>", secondary_y=False)
fig.show()
```

![image](https://user-images.githubusercontent.com/26782653/138112768-a02c38fd-fbdc-493a-8144-f2b858d16cef.png)

**Comment by aschonfeld** [comment]
@info-rchitect I can add a chart type for "Pareto" and with the following inputs (w/ mapping to your example):
* X (SOFT_BIN_DESC)
* BARS (COUNT)
* LINE (CUMULATIVE_PERCENT)
* SORT (COUNT)
* DIRECTION (DESC)

Does this sound like it should work?

**Comment by aschonfeld** [comment]
Added in v1.61.0
