### ISSUE TITLE
Feature Request: Histograms with Different Normalization for Y-axis

### ISSUE THREAD

**Issue by msat59** [man-group/dtale#595]
Hi Guys.

Currently, the histogram Y-axis is **Frequency** and the KDE line shows the **probability**. It's fine, but when the target is used to show different groups in one plot, Frequency doesn't make sense.

![image](https://user-images.githubusercontent.com/20813541/141121207-af41af1e-67b4-44e2-9d4f-5fcfaead4fa2.png)

Adding a toggle button is good to jump between Frequency and Probability. Plotly Histogram has few normalization methods.

**Comment by aschonfeld** [comment]
@msat59 thanks for the suggestion! I'll work on adding this.

**Comment by aschonfeld** [comment]
@msat59 so I've tried adding this feature (using the `density` parameter with the `np.histogram` function) and for some reason it appears that all my data keeps returning zeros (with the exception of the column filled with random floats `Col0` which returns the same as `density=False`)

https://user-images.githubusercontent.com/11547371/141404649-b7ea0aa8-cd79-48bd-87ad-22e25e69bc39.mov

:

**Comment by aschonfeld** [comment]
Ok I think the way to stop getting zeros is to no longer pass in the number of bins when using `density=True`.  Maybe I'll deactivate that input when "Probability" is selected.

**Comment by msat59** [comment]
I'm not sure how numpy.histogram works in this case. Why don't you use plotly histogram directly? Currently, bins are calculated by np.histogram and plotly bar plot us used.

`px.histogram(df, x="date", histnorm='probability density')`

**Comment by aschonfeld** [comment]
It would be too much work to replace the use of `np.histogram` with plotly.  Removing the bin control seemed to solve the problem

https://user-images.githubusercontent.com/11547371/141888999-82cf8763-2f02-46c4-9613-3140b549c946.mov

I'm about to release 1.61.0 with this update included.  Should be ready in the next hour or so.  IF you haven't already, please toss your ⭐ on the repo.  Thanks 🙏
