### ISSUE TITLE
Adding Aggregation to "Summarize Data" does not work

### ISSUE THREAD

**Issue by Bitterlemon42** [man-group/dtale#597]
Thanks a lot for the awesome package! I do have some problems trying to summarize data as a GroupBy-Operation. When trying to select an aggregation function the small + button is not clickable and therefore I cannot select an aggregation. As a result I get the "Missing an aggregation selection!" error. 

I tested this in multiple browsers (Firefox and Chrome) in Ubuntu and Windows, all with the same issue. Here are the installed versions for reference:

- dtale 1.61.0 (tried with 1.60.0 as well)
- pandas 1.3.3

Thanks for the help!

**Comment by aschonfeld** [comment]
@Bitterlemon42 apologies for the issue.  I upgraded some frontend packages a while back and I think it broke this functionality.  I have a fix and will release hotfix in the next couple days.

**Comment by aschonfeld** [comment]
Just released v1.61.1 to pypi (conda-forge will be available shortly) which includes this fix.  If you haven't already, please toss your ⭐ on the repo.  Thanks 🙏
