### ISSUE TITLE
dtale.show of a multi header dataframe

### ISSUE THREAD

**Issue by cmartinotti** [man-group/dtale#606]
Hello, 
I'm trying to use dtale.show() to visualize multi headers dataframes. It kinda works, but it does this aestethically displeasing thing of putting the indices column names with many empty strings after their actual name.

Basically if i go:
df_piv=pd.pivot(df, index = ['col1','col2','col3'], columns='col5',col6',col7',col8',values=col9',aggfunc='mean')
dtale.show(df_piv)

it shows df_piv, but with the column col1 (which should be named just 'col1' or ('col1') ) named :
('col1',",",",")

Is there a way to fix this while launching dtale? Tryed to look on the documentation, but I didn't have much luck

**Comment by aschonfeld** [comment]
@cmartinotti apologies for the wait.  I've added something to the data load where if the name of a column in the dataframe is of type `tuple` then it will join all the values (after applying some standard formatting based on the type of the value) together using underscores (ignoring any formatted values that are empty strings).

For example `('col1',",",",")` would become `col1` and `('col1',4,5.6666,True)` would be `col1_4_5.66_True`

**Comment by aschonfeld** [comment]
@cmartinotti just released v2.1.0 with this fix included, let me know how it works out
