### ISSUE TITLE
Add ability to build new basic columns

### ISSUE THREAD

**Issue by phillipdupuis** [man-group/dtale#61]
It would be nice if the menu had a "Build Column" option so that users could quickly & easily modify the underlying data.

The basic idea would be that the 'Build column' interface would prompt users to enter:
1. The new column's name (freetext w/ verification that it's valid)
2. The type of column (picklist)
3. The source column(s), i.e. the ones used to drive the calculations (picklist)
4. Any additional options dependent on column type

The types of columns could be:

1. Sum
Prompt the user to pick two numeric columns

2. Difference
Prompt the user to pick two numeric columns

3. Bins (evenly spaced)
Prompt the user to pick one column.
Additional options:  Number of bins, bin labels.
Use pd.cut

4. Bins (evenly sized)
Prompt the user to pick one column.
Additional options: number of bins, and bin labels)
Use pd.qcut

5. Datetime property
Prompt the user to pick one datetime column
Additional options: property (one of the Series.dt.__ properties like time, year, month, etc.)

6. (Maybe?) String function
Prompt the user to pick one string column
Additional options: function (Series.str.__ such as endswith, startswith, len, etc.) and value

And possibly more, will update this over time...

**Comment by aschonfeld** [comment]
Added in v1.7.5
