### ISSUE TITLE
[Bug] Cannot use replacement feature

### ISSUE THREAD

**Issue by bangnh1** [man-group/dtale#612]
**Current Behavior:**
- Start dtale with no data
- Upload csv file to import to dtale
- Choose any column and select **Replacements**
- Fill `Search for` and `Replace With` -> **Replace**

![Screen Shot 2021-12-15 at 14 31 40](https://user-images.githubusercontent.com/29230374/146142783-ef3e51a7-408e-4fc5-afe2-950deba784e7.png)

**Expected Behavior:**
- Can update cells with replacement

**Environment:**
```
dtale==1.61.1
Flask==2.0.2
```

**Comment by yiskylee** [comment]
![image](https://user-images.githubusercontent.com/2600667/151578366-a0fa7b83-abb8-412b-90a9-51ed1c7871c0.png)
Could you try clicking the "plus" button as shown in the screenshot?

**Comment by aschonfeld** [comment]
@bangnh1 just released v2.1.0 with this fix.  Let me know if it you have any other issues.  If you haven't already, please put your ⭐  on the repo.  Thanks 🙏
