### ISSUE TITLE
Enhancement Request to export as standalone HTML file

### ISSUE THREAD

**Issue by lcorrigan** [man-group/dtale#617]
There are many times I find myself wishing I could export the currently displayed table as an HTML report. Many people I send reports to  do not have Python or DTale installed, and exporting to CSV etc, loses any formatting I've applied and dates might look different on their locale etc if they open it in Excel.

Since management-folk seem to like colors to obtain that 2-second summary of a data set or report, it would be ideal if I could apply conditional highlighting like: https://github.com/man-group/dtale/issues/592#issuecomment-1007988105, and have the exported HTML file have those formats in it. Once it's in this format on the PC, I could then print to PDF.

**Comment by aschonfeld** [comment]
@lcorrigan I can certainly look into the ability to export the currently viewed data (the 55 or so rows rendered to the screen). If I can get more great, but ultimately you could have an extremely large dataset loaded and trying to build a static HTML file with all that data wouldn't be able to be loaded in any browser.

**Comment by aschonfeld** [comment]
@lcorrigan here's a sample of the HTML export (you'll have to unzip it since github wouldn't let me attach HTML files).  It embeds the JS/CSS as text so the scrolling/styling still works.  So the idea is that if you've applied some styling to your grid (heatmap, decimal formatting) it will be captured in your export.
[dtale_html_js_export_1646721218126.zip](https://github.com/man-group/dtale/files/8203413/dtale_html_js_export_1646721218126.zip)

**Comment by lcorrigan** [comment]
Thanks @aschonfeld  The fact that you kept the scrolling in makes it worth the massive file size.  I would likely not be doing this for files with more than 2K rows of data anyway.  Speaking of, would it be possible to export filtered data? I.e.: If I pull a 50K row dataframe open with DTale, and do some custom filtering, could I make it export just the data I filtered it down to? Either way, looks great to me.

**Comment by aschonfeld** [comment]
So i plan on having an input for row count for exports greater than 50K rows. But that will just execute a “df.head(rows)”. If you want a more complex filter you’ll have to apply it using the UI beforehand. It will apply it when exporting

**Comment by lcorrigan** [comment]
Sounds great, thanks!

**Comment by aschonfeld** [comment]
added in v2.1.0

**Comment by lcorrigan** [comment]
Hi @aschonfeld, I'm getting an error when I attempt to export to HTML, with or without filtering first.  Let me know if you want me to add info to this ticket or create a new one.

**Comment by aschonfeld** [comment]
can you send me the error? Everything is still working fine for me.

**Comment by lcorrigan** [comment]
Here you go. 
I'm using python 3.8.10. 
Here are my data types.  Some columns will have some empty/None/NaN entries. Not sure if that's my problem.
array([dtype('uint64'), dtype('O'), dtype('float64'), dtype('float64'),
       StringDtype, dtype('<M8[ns]'), dtype('<M8[ns]'), dtype('uint16'),
       dtype('float64'), dtype('uint16'), dtype('uint16'),
       dtype('uint16'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'),
       dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       StringDtype], dtype=object)

I attempted converting all types using pandas convert_dtypes() but that had no effect. I also deleted many columns to see if it might have been tripping over a specific one, but eventually gave up trying.

[dtale html eror.txt](https://github.com/man-group/dtale/files/8244938/dtale.html.eror.txt)

**Comment by aschonfeld** [comment]
Ahh, this is good thank you. I wonder if this is a windows vs. mac issue.  Since I never came across this and I've been working with missing data in my exports.  I'll keep digging...

**Comment by aschonfeld** [comment]
@lcorrigan just released v2.1.2 with a fix that should hopefully solve this

**Comment by lcorrigan** [comment]
Sorry @aschonfeld, but it's not working for me. I tried it with the most basic dataframe and it still wasn't successful (same error).
I don't know if this is a clue, but if you open that previous attachment I submitted, you will notice I'm running python from a different location (it's a virtual environment) than from where DTale is trying to pull the encoder file from (my main windows install that I generally don't touch). Maybe it needs to change where it goes looking for files?

**Comment by lcorrigan** [comment]
@aschonfeld, yes I'm on Windows.  Thanks for the suggestion - that worked.

**Comment by aschonfeld** [comment]
🥳

**Comment by lcorrigan** [comment]
@aschonfeld just FYI, I had this set in an environment variable in vscode for quite some time working well until about over a month ago and I couldn't figure out why (and never time to prioritize it).  I was able to work around it by changing line 2576 in env\Lib\site-packages\dtale\views.py to explicitly use utf-8 encoding like so:  main_styles = load_file("css/main.css", encoding=**"utf-8"**).split("\n").

**Comment by aschonfeld** [comment]
@lcorrigan getting ready to draft a new release, will include this.

**Comment by aschonfeld** [comment]
@lcorrigan just released v2.5.1 to pypi, conda-forge coming soon
