### ISSUE TITLE
Column widths when dtale initially hidden

### ISSUE THREAD

**Issue by rhjmoore** [man-group/dtale#628]
I'm a new user. I can see dtale is pretty great when using simply within a jupyter notebook.
I've tried incorporating multiple dtale views in a tabbed HTML interface using something like this:

    <div class="tab">
      <button class="tablinks" onclick="openCity(event, 'DF1')">DF1</button>
      <button class="tablinks" onclick="openCity(event, 'DF2')">DF2</button>
    </div>
    
    <div id="DF1" class="tabcontent">
      <iframe width="100%" height="500" src="http://localhost:40000/dtale/main/1"></iframe>
    </div>
    
    <div id="DF2" class="tabcontent">
      <iframe width="100%" height="500" src="http://localhost:40000/dtale/main/2"></iframe>
    </div>

Some javascript just sets the <div>.style.display = "block" or "none".

This works, but the dtale table that is initially blank has minimal column widths. It resets correctly if I got into Settings and toggle "Max Width".

Is there a way to automatically toggle this, or otherwise set the column width correctly regardless of whether the table initially shows?

**Comment by aschonfeld** [comment]
@rhjmoore sorry for the wait I’ve been putting the finishing touches on a typescript conversion. So the issue you’re facing is that you’re initially loading a D-Tale grid with no data and then when you eventually load data the columns are not being sized correctly?

If so, yea I should be able to fix this. Just wanted to make sure i’m understanding the issue correctly.

**Comment by rhjmoore** [comment]
@aschonfeld Not quite - sorry I see my phrasing isn't quite correct.
I loaded both tables with data, but they exist in a div which is either shown or hidden. This is so that we can click on the tabbed interface and see either one or the other table. The hidden table doesn't show with appropriate widths unless I show that table and then go in to toggle the max width setting.

**Comment by aschonfeld** [comment]
Ahhh, thank you. Yea this is a little tougher but i should be able to at least gove you some HTML to fix it. Let me mess around

**Comment by aschonfeld** [comment]
So this is kind of a until I can figure out what's really going on with the column resizing code (I'm assuming its a glitch with it being hosted within an iframe) but it should get you going until I can release a new version:
```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body>
        <div class="tab">
          <button id="btn" class="tablinks" onclick="toggleTab">DF1</button>
        </div>

        <div id="DF1" />
        <script type="text/javascript">
        function toggleTab () {
          const iframeWrapper = document.getElementById('DF1');
          if (iframeWrapper.innerHTML) {
            iframeWrapper.innerHTML = '';
          } else {
            iframeWrapper.innerHTML = '<iframe width="100%" height="500" src="http://localhost:40000/dtale/main/1"></iframe>';
          }
        }
        let btn = document.getElementById("btn");
        btn.addEventListener('click', event => {
          toggleTab();
        });
        </script>
    </body>
</html>
```

So essentially, rather than toggling the visibility of the iframe parent div I'm toggling whether the iframe is rendered or not.

**Comment by rhjmoore** [comment]
Thank you, I'll give it a go.

**Comment by aschonfeld** [comment]
@rhjmoore I've tried digging into this as much as possible and for the life of me I could not figure out how to fix this programmatically or expose the "Refresh Widths" function to the parent window (cross-scripting errors).  I have found a less heavy-handed approach to toggling the display of the iframes so that it won't re-load the data each time you display it.

```
<!doctype html>
<html>
    <head>
	    <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>
        body {background-color: powderblue;}
        </style>
    </head>
    <body>
        <div class="tab">
          <button id="btn1" class="tablinks">DF1</button>
          <button id="btn2" class="tablinks">DF2</button>
        </div>

        <div id="DF1-wrapper" style="position: relative">
          <iframe id="DF1-iframe" style="position: absolute; width: 100%; height: 500px; left: 105%; top: 0;" src="http://localhost:40000/dtale/main/1"></iframe>
          <iframe id="DF2-iframe" style="position: absolute; width: 100%; height: 500px; left: 105%; top: 0;" src="http://localhost:40000/dtale/main/2"></iframe>
        </div>
        <script type="text/javascript">
        document.getElementById("btn1").addEventListener('click', event => {
          document.getElementById('DF1-iframe').style.left = 0;
          document.getElementById('DF2-iframe').style.left = '105%';
        });
        document.getElementById("btn2").addEventListener('click', event => {
          document.getElementById('DF1-iframe').style.left = '105%';
          document.getElementById('DF2-iframe').style.left = 0;
        });
        </script>
    </body>
</html>
```

So I'm simply absolutely positioning them off the screen and then based on which button is pushed shift one into frame.

Lastly, I did notice that the scrollbar is rendering on the index column on the far left I have a styling fix for that I'll put in my next release.  It's not a big deal it just cuts off the display of the row numbers on the left in some browsers.  Also, if you haven't already, please toss your ⭐  on the repo.  Thanks 🙏
