### ISSUE TITLE
Histogram data precision config

### ISSUE THREAD

**Issue by Nriver** [man-group/dtale#641]
I am analysing some data with format from `.2f` to `.4f`, the default histogram seems to be fixed with `.1f` format, my diagram shows me 20 bars with the same value due to the precision loss.

I suggest a seperate config for precision for histograms, or make it read from the precision config value when initializing the table, like the `precision` in `dtale.show_excel(path=file_path, precision=3)`.

**Comment by Nriver** [comment]
For example:

![ksnip_20220303-163220](https://user-images.githubusercontent.com/6752679/156526822-09314629-3547-4671-bac1-82b206a35045.png)

There are several bars lebeled with 0.8, but actually they should be 0.82, 0.84, 0.86...etc

**Comment by aschonfeld** [comment]
so I just pushed an update to make the histogram label precision a little more dynamic.  I'll let you know when a new version has been released

**Comment by aschonfeld** [comment]
@Nriver just released v2.1.0 with this fix
