### ISSUE TITLE
Show/Hide columns shows no columns in form when first clicked

### ISSUE THREAD

**Issue by lcorrigan** [man-group/dtale#646]
Noticed this happening after upgrade to dtale-2.1.0.  
The first attempt to click the show/hide columns feature, either from the auto-hidden top menu or from the arrow menu on the left, show no columns to choose from.  On the second attempt, it's populated with the data frame's columns. If you reload the data, it's blank on the first attempt again.  Not sure if this is a clue or a separate problem, but if I delete some columns from the column's right-click menu, the columns are still in the presented columns of the Show/Hide columns form (when they do show up of course).

**Comment by aschonfeld** [comment]
fixed in v2.1.2
