### ISSUE TITLE
Pivot table fails with "Must provide 'func' or 'tuples' of (column, aggfunc)"

### ISSUE THREAD

**Issue by jmk007** [man-group/dtale#649]
Pivot table functionality (even on the dTale "live demo") fails in making a pivot table with error:
![image](https://user-images.githubusercontent.com/14846442/158561428-c1207e2e-bbfa-46e2-abf5-7d3bfd51a280.png)

Rolling back to earlier versions corrected the issue on one installation. However, on others the problem persists.  

Additional information at: https://stackoverflow.com/q/71466883/7490498

**Comment by aschonfeld** [comment]
@jmk007 apologies for the bug.  This was a frontend issue.  I'll include the fix in my next release.  It should still work in any version before 2.0.0

**Comment by jmk007** [comment]
@aschonfeld Many thanks for the prompt reply. Thanks for confirming and isolating the problem. Been uninstalling/reinstalling multiple times, rolling back, etc. I can confirm that rolling back to 1.61.1 works with Firefox as the browser. What's odd is that my personal laptop with Microsoft Edge (99.0.1150.39) works whereas my official employer-secured laptop (same version of Edge) consistently fails with same error as documented above. Weird...

**Comment by lijiapeng-bmc** [comment]
![image](https://user-images.githubusercontent.com/53208046/159822992-c8f5302b-140c-4451-bbfd-bb938b9973ca.png)
if we use func is instead of aggfunc，it can work。

**Comment by aschonfeld** [comment]
@jmk007 just released v2.2.0 with this fix, please let me know if you have any other issues.  Also, if you haven't already, please toss your ⭐  on the repo. Thanks 🙏

**Comment by lijiapeng-bmc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you for your reply, yesterday i just use pivot_table so I don’t find any question. ⭐  is already on the way.thanks🙏
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lijiapeng
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/24/2022 10:41，Andrew ***@***.***> wrote： 




@jmk007 just released v2.2.0 with this fix, please let me know if you have any other issues.  Also, if you haven't already, please toss your ⭐  on the repo. Thanks 🙏



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
