### ISSUE TITLE
can't use dtale.__version__ to check current version after import in python

### ISSUE THREAD

**Issue by injuryholmes** [man-group/dtale#653]
Hi all, apologize if this question seems silly.
I found that dtale can't use dtale.__version__ to check the current using version.
![image](https://user-images.githubusercontent.com/25261163/160583883-6ae84258-1a48-49a5-8977-3b361daf06f6.png)

I found it relate to missing \_\_verison\_\_ attribute in \_\_init\_\_ file under dtale package. 
But there is also a version parameter in setup.py, so it won't be a clever idea to keep the same value in two different locations.

I've checked pandas how they keep the version in \_\_init\_\_.py, and they've written a complex function;
https://github.com/pandas-dev/pandas/blob/3cb70a5f0d1dc386f7806fca75abff6f098b1539/pandas/_version.py#L1

Is there any good  and simple way to fix this?

**Comment by aschonfeld** [comment]
As a workaround until I update `__version__` you can do the following:
```
import dtale.cli.clickutils as dtale_clickutils

print(dtale_clickutils.retrieve_meta_info_and_version("dtale")[1])
```

**Comment by aschonfeld** [comment]
Release in v2.3.0
