### ISSUE TITLE
Installing in colab results dependencies issues and data visualization does not appear at all

### ISSUE THREAD

**Issue by Idolized22** [man-group/dtale#655]
Hello, 
I have been trying to use "dtale" in  google colab following your [tutorial](https://github.com/man-group/dtale#google-colab). However attempting to install (various versions from 1.6.x till the latest version) 
resulted with the following dependencies error: 
I have installed dtale following: 
`!pip install --upgrade dtale`
> Collecting dtale
  Downloading dtale-2.2.0-py2.py3-none-any.whl (12.7 MB)
     |████████████████████████████████| 12.7 MB 4.6 MB/s 
Collecting scikit-learn==0.24.2
  Downloading scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
     |████████████████████████████████| 22.3 MB 4.1 MB/s 
Requirement already satisfied: networkx in /usr/local/lib/python3.7/dist-packages (from dtale) (2.6.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from dtale) (1.21.5)
Collecting lz4
  Downloading lz4-4.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 42.3 MB/s 
Collecting dash-daq
  Downloading dash_daq-0.5.0.tar.gz (642 kB)
     |████████████████████████████████| 642 kB 47.7 MB/s 
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from dtale) (3.2.2)
Collecting squarify
  Downloading squarify-0.4.3-py3-none-any.whl (4.3 kB)
Collecting statsmodels==0.12.2
  Downloading statsmodels-0.12.2-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 28.9 MB/s 
Collecting strsimpy
  Downloading strsimpy-0.2.1-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 3.2 MB/s 
Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     |████████████████████████████████| 79.9 MB 131 kB/s 
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from dtale) (5.5.0)
Collecting ppscore
  Downloading ppscore-1.2.0.tar.gz (47 kB)
     |████████████████████████████████| 47 kB 2.2 MB/s 
Collecting dash>=2.0.0
  Downloading dash-2.3.1-py3-none-any.whl (9.6 MB)
     |████████████████████████████████| 9.6 MB 29.1 MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from dtale) (1.15.0)
Requirement already satisfied: future>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from dtale) (0.16.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from dtale) (1.1.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (from dtale) (1.1.0)
Collecting flask-ngrok
  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Collecting Flask-Compress
  Downloading Flask_Compress-1.11-py3-none-any.whl (7.9 kB)
Collecting dash-colorscales
  Downloading dash_colorscales-0.0.4.tar.gz (62 kB)
     |████████████████████████████████| 62 kB 497 kB/s 
Requirement already satisfied: cycler in /usr/local/lib/python3.7/dist-packages (from dtale) (0.11.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (from dtale) (0.11.2)
Collecting packaging<=21.0
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 4.9 MB/s 
Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (from dtale) (3.0.9)
Collecting dash-bootstrap-components
  Downloading dash_bootstrap_components-1.0.3-py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 45.7 MB/s 
Requirement already satisfied: Flask in /usr/local/lib/python3.7/dist-packages (from dtale) (1.1.4)
Collecting missingno<=0.4.2
  Downloading missingno-0.4.2-py3-none-any.whl (9.7 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from dtale) (1.3.5)
Requirement already satisfied: xarray in /usr/local/lib/python3.7/dist-packages (from dtale) (0.18.2)
Requirement already satisfied: itsdangerous in /usr/local/lib/python3.7/dist-packages (from dtale) (1.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from dtale) (2.23.0)
Collecting scipy==1.7.3
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 1.3 MB/s 
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2->dtale) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2->dtale) (3.1.0)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.7/dist-packages (from statsmodels==0.12.2->dtale) (0.5.2)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask->dtale) (1.0.1)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask->dtale) (2.11.3)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask->dtale) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask->dtale) (2.0.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging<=21.0->dtale) (3.0.7)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->dtale) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->dtale) (2.8.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly>=5.0.0->dtale) (8.0.1)
Collecting brotli
  Downloading Brotli-1.0.9-cp37-cp37m-manylinux1_x86_64.whl (357 kB)
     |████████████████████████████████| 357 kB 46.4 MB/s 
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->dtale) (1.4.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->dtale) (3.10.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->dtale) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->dtale) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->dtale) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->dtale) (3.0.4)
Requirement already satisfied: setuptools>=40.4 in /usr/local/lib/python3.7/dist-packages (from xarray->dtale) (57.4.0)
Building wheels for collected packages: dash-colorscales, dash-daq, ppscore
  Building wheel for dash-colorscales (setup.py) ... done
  Created wheel for dash-colorscales: filename=dash_colorscales-0.0.4-py3-none-any.whl size=62590 sha256=0cb53aac9eb788b606ee83292ebecaa28c4152a32e9984c74d9729de8515474c
  Stored in directory: /root/.cache/pip/wheels/2f/22/7e/183ba2af565e3eb955021fbb4fe8fe4a6b1ed8ae3e5c03236a
  Building wheel for dash-daq (setup.py) ... done
  Created wheel for dash-daq: filename=dash_daq-0.5.0-py3-none-any.whl size=669714 sha256=37bdba08abb9136933c27645b8236ff01edf40388951829945b9bd77b8a86b61
  Stored in directory: /root/.cache/pip/wheels/fe/54/53/a8d448db5592874db4313240571ca2c069e55f6a6b29bf5847
  Building wheel for ppscore (setup.py) ... done
  Created wheel for ppscore: filename=ppscore-1.2.0-py2.py3-none-any.whl size=13068 sha256=e535227be7c5dd3d85188f582e5d27bb83aab194e312e8aad5778658015bc33a
  Stored in directory: /root/.cache/pip/wheels/d2/3c/58/2ff786414b21713edc6f4fdb54fdee89ac37bca5edd1f60634
Successfully built dash-colorscales dash-daq ppscore
Installing collected packages: brotli, scipy, Flask-Compress, dash-table, dash-html-components, dash-core-components, scikit-learn, dash, strsimpy, statsmodels, squarify, ppscore, packaging, missingno, lz4, kaleido, flask-ngrok, dash-daq, dash-colorscales, dash-bootstrap-components, dtale
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      **Successfully uninstalled scipy-1.4.1**
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      **Successfully uninstalled scikit-learn-1.0.2**
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.10.2
    Uninstalling statsmodels-0.10.2:
      Successfully uninstalled statsmodels-0.10.2
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  Attempting uninstall: missingno
    Found existing installation: missingno 0.5.1
    Uninstalling missingno-0.5.1:
      Successfully uninstalled missingno-0.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed Flask-Compress-1.11 brotli-1.0.9 dash-2.3.1 dash-bootstrap-components-1.0.3 dash-colorscales-0.0.4 dash-core-components-2.0.0 dash-daq-0.5.0 dash-html-components-2.0.0 dash-table-5.0.0 dtale-2.2.0 flask-ngrok-0.0.25 kaleido-0.2.1 lz4-4.0.0 missingno-0.4.2 packaging-21.0 ppscore-1.2.0 **scikit-learn-0.24.2** **scipy-1.7.3** squarify-0.4.3 statsmodels-0.12.2 strsimpy-0.2.1

It seems dtale forces a relitively old version of scikit-learn and scipy. 
In addtion and more importently the a blank screen appear form the output link (http://c960-23-236-54-158.ngrok.io/dtale/main/1) of the both the codes:

`import dtale`
`import dtale.app as dtale_app`

`dtale_app.USE_NGROK = True`
`#dtale_app.USE_COLAB = True`
`dtale.show(pokemon_df, ignore_duplicate=True)`

And:

`dtale.show(path='https://gist.githubusercontent.com/aviasd/070b68d1068e92f059e143a1f4655e77/raw/2707de87c3f6ddc29246658bda5b1afc1058a4f7/Pokedex_Ver7.csv')`

Thanks in Advance for your help

**Comment by aschonfeld** [comment]
@Idolized22 which version of python are you running?  I start a fresh notebook using python 3.7.13 and this worked fine:
```
!pip install -U dtale

import dtale
import dtale.app as dtale_app

dtale_app.USE_COLAB = True

dtale.show_csv(path='https://gist.githubusercontent.com/aviasd/070b68d1068e92f059e143a1f4655e77/raw/2707de87c3f6ddc29246658bda5b1afc1058a4f7/Pokedex_Ver7.csv')
```

**Comment by Idolized22** [comment]
> @Idolized22 which version of python are you running? I start a fresh notebook using python 3.7.13 and this worked fine:
> 
> ```
> !pip install -U dtale
> 
> import dtale
> import dtale.app as dtale_app
> 
> dtale_app.USE_COLAB = True
> 
> dtale.show_csv(path='https://gist.githubusercontent.com/aviasd/070b68d1068e92f059e143a1f4655e77/raw/2707de87c3f6ddc29246658bda5b1afc1058a4f7/Pokedex_Ver7.csv')
> ```
I am using the same version as you: Python 3.7.13,  
I tried once again and it worked well. 

Thank you very much
