### ISSUE TITLE
Google Colab with local runtime doesn't work

### ISSUE THREAD

**Issue by rickybassom** [man-group/dtale#661]
Running the following code on Google Colab while connected to a [local runtime](https://research.google.com/colaboratory/local-runtimes.html) doesn't seem to produce a D-Tale link or any output. Enabling `USE_NGROK` also produces the following error `Permission denied: '/tmp/ngrok/ngrok'`.

```python
!pip install -U dtale
import pandas as pd

import dtale
import dtale.app as dtale_app

dtale_app.USE_COLAB = True
# dtale_app.USE_NGROK = True

dtale.show(pd.DataFrame([1,2,3]))
```

Python version: 3.7.13

Is there a way to get D-Tale working with a local runtime on Google Colab?

**Comment by aschonfeld** [comment]
Hmm, i've never worked with a local runtime before but is there any chance you could change your code snippet from earlier to:
```
!pip install -U dtale
import pandas as pd

import dtale
import dtale.app as dtale_app

dtale_app.USE_COLAB = True
# dtale_app.USE_NGROK = True

d = dtale.show(pd.DataFrame([1,2,3]))
d._main_url
```

Then try pasting that URL into your browser.  Since it's running locally I wonder if this would work:
```
!pip install -U dtale
import pandas as pd

import dtale

dtale.show(pd.DataFrame([1,2,3]), host='0.0.0.0')
```

`USE_NGROK` & `USE_COLAB` are only for when you're trying bootstrap on to colab's hosted notebooks but it seems like that wouldn't be the case here

**Comment by rickybassom** [comment]
Thanks for taking a look at this issue.

`d._main_url` returns `http://fedora:40000/dtale/main/5` and pasting it in the browser does open up a D-tale instance.

But `dtale.show(pd.DataFrame([1,2,3]), host='0.0.0.0')` or `dtale.show(pd.DataFrame([1,2,3]), host='fedora')` doesn't show a link in Google Colab. I think it might be caused by this error in the chrome console:
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure frame '<URL>'. This request has been blocked; the content must be served over HTTPS.
```

It looks like an iframe is being added with the `fedora` url, so the above error makes sense since HTTP can't be mixed with HTTPS requests in Chrome.

```
<iframe width="100%" height="475" src="http://fedora:40000/dtale/iframe/12" frameborder="0" allowfullscreen=""></iframe>
```

But using `d._main_url` is a good solution for me.

**Comment by aschonfeld** [comment]
ok, yea I think thats your best bet for now since D-Tale doesn't really support secure HTTP.
