### ISSUE TITLE
Not able to see the result of dtale.show() in jupyter notebook.

### ISSUE THREAD

**Issue by jrkarthik** [man-group/dtale#663]
I'm trying to use D-Tale to show a dataframe in jupyter notebook, so as to interact with it. But I'm witnessing a blank screen that says - [hostname]'s server IP address could not be found

Note: This jupyter notebook is in a remote AWS instance which has Ubuntu OS running.
These are the lines of the code I used -
``
emp = sample_df
``
``
d = dtale.show(emp, debug=True, open_browser=True)
``
The following is the error that is observed -

![image](https://user-images.githubusercontent.com/16251961/165297988-aa2fb9cb-ded1-4783-87d4-bdcabf508485.png)

sample_df is not empty. It has values and I cannot share them.

**Comment by aschonfeld** [comment]
Please try using [Jupyter Server Proxy](https://github.com/man-group/dtale#jupyterhub-w-jupyter-server-proxy)
