### ISSUE TITLE
Is there a reason why certain dependencies are pinned in requirements.txt?

### ISSUE THREAD

**Issue by SmokinCaterpillar** [man-group/dtale#665]
Thanks a lot for dtale, it's a super help and we use it a lot during our development process to investigate data issues with our customers.

I am just wondering if there are any particular reasons why many packages in the `requirements.txt` are pinned, e.g. `scikit-learn==0.24.2`. This messes a bit with our workflow, as we use `pipenv` for dependency resolution. The fixed requirements basically prevent us from correctly listing `dtale` as a `dev` dependency because otherwise our docker containers could no longer be built. These fixed dependencies block any dependency resolution with `pipenv` because it cannot find a valid set of dependencies.

**Comment by aschonfeld** [comment]
So i had actually been digging into updating scikit-learn to its most recent release but the package “ppscore” is preventing that. If you know of a way i could unpin scikit-learn while also keeping ppscore that would be great.

i was thinking of making ppscore an optional dependency but people seem to use it so i dont want them having to go through hoops to get it

**Comment by aschonfeld** [comment]
@SmokinCaterpillar `ppscore` actually has an issue open to upgrade scikit-learn and for some reason they just won't cut a new release even though its been in master for almost 3 months.  See [here](https://github.com/8080labs/ppscore/issues/53).  Please comment that you'd like to see this release cut like I have done and hopefully it will rattle the cage enough 🤞

**Comment by aschonfeld** [comment]
@SmokinCaterpillar I've integrated the ppscore code directly into the latest D-Tale release (v2.4.0) and thus unpinning sklearn for python environments greater than 3.7.  Hope this helps
