### ISSUE TITLE
[DOC] Reduce the size of documentation gifs

### ISSUE THREAD

**Issue by beckernick** [man-group/dtale#67]
Great work on this project. Cloning this repository is fairly time consuming, as there are 100 MB in the `/docs` folder. Of this 100 MB, 40 MB come from the gifs. It might be nice to try to reduce the size of these gifs, if possible, for people cloning with throttled/limited download speeds 😄

**Comment by aschonfeld** [comment]
Ahhhh, good catch.  Maybe i’ll split them into their own separate repo so they aren’t part of the cloning.  Thanks

**Comment by aschonfeld** [comment]
@beckernick  all set!  Thanks for the suggestion 👍
