### ISSUE TITLE
Charts: Plot columns from multiple DataFrames with same index in one graph

### ISSUE THREAD

**Issue by phme283** [man-group/dtale#678]
I am missing the feature to be able to plot specific columns from multiple DataFrames (with same index) in one graph. Is such a feature planned? Or is there a workaround? 

I have thought to merge or stack (concat) the DataFrames. However most columns have the same name. So I do not see this as a solution unless `MultiIndex` for columns is not supported.

**Comment by nfischer0** [comment]
You can add suffixes in pandas if you want to concat several DataFrames with same-named columns.

**Comment by phme283** [comment]
To be honest, this seems to be a non-satisfying workaround. However, as dtale bases at top-level on "Instances", where each instance is one dataframe, it would be counter-intuitive if one would be able to start something like an overall chart-session, where variable from multiple instances/dataframes could be visualized.

I'll close this issue.
