### ISSUE TITLE
Opening multiple datasets simultaneously on different URLs

### ISSUE THREAD

**Issue by sanikag97** [man-group/dtale#681]
Hello, I have created tables for different datasets using Arctic and I want to open those datasets using Dtale on different URLs. I tried using the combine_data file to open 2 datasets pn 2 different URLs but it is not working for me. Could you please let me know how this can be done? 
Thank you!

**Comment by aschonfeld** [comment]
If you've loaded multiple datasets into your D-Tale session this should be simple.

```
import dtale

from arctic import Arctic
from dtale.views import startup

if __name__ == "__main__":

  lib = db.get_library("my_library")
  
  d1 = startup(data=lib.read("dataset1", data_id=1)
  d2 = startup(data=lib.read("dataset2", data_id=2)
  # and so on and so forth...
  dtale.show(lib.read("datasetN", subprocess=False, open_browser=True)
```

I'm not totally sure how you could update the script to open multiple tabs for each dataset automatically but once you're in that first tab you can choose to view any dataset you've loaded into D-Tale from the menu if you hover around the top of the screen.

Hope this helps.

**Comment by aschonfeld** [comment]
@sanikag97 I'm going to close this since I haven't heard anything.  I can reopen it if you're still having issues
