### ISSUE TITLE
Animated and Offline Histograms

### ISSUE THREAD

**Issue by nfischer0** [man-group/dtale#685]
There does not appear to be an option to plot histograms inline.  Also, there is no way to animate a histogram or to have the histogram be generated as a "main" plot (ie not as a column description).

**Comment by aschonfeld** [comment]
@nfischer0 are you asking for a new chart option on the "Charts" page for histograms?  So a user would choose a column and it would generate a histogram from it as well as histograms on that column from a group column or animate a histogram by another date column?

**Comment by aschonfeld** [comment]
@nfischer0 @jrast just wanted to give you a heads up that I've finally gotten around to working on this and here's a sample of what I have.

- Simple single histogram:
![image](https://user-images.githubusercontent.com/11547371/221262860-33894463-1270-45b6-b2cb-8d26e4671bb2.png)

- Grouped histograms:
![image](https://user-images.githubusercontent.com/11547371/221262991-426ccfd8-df47-45e9-b243-9712892e1b64.png)

- Animated histogram:
https://user-images.githubusercontent.com/11547371/221263575-bf7ee08a-65d2-4d5a-b8b7-c84748c2987d.mov

**Comment by aschonfeld** [comment]
@nfischer0 @jrast just a heads up that I just released v2.13.0 to pypi and it should be on conda-forge shortly.  This version includes this functionality.  Let me know if you have any issues.

Also, if you haven't already, please put your ⭐  on the repo when you get a sec. Thanks! 🙏
