### ISSUE TITLE
dtale does not work with streamlit >=1.12.0

### ISSUE THREAD

**Issue by cod3licious** [man-group/dtale#693]
`dtale.cli.streamlit_script` raises a `ModuleNotFoundError: No module named 'streamlit.server'` with streamlit versions >=1.12.0 (it worked before up to version 1.11.1).

**Comment by aajmi** [comment]
The `streamlit.server` module was relocated to `streamlit.web.server` in the last versions >=1.12.0. Adding an exception when importing the `streamlit.server` should solve the issue, I guess.

**Comment by aschonfeld** [comment]
@cod3licious & @aajmi just released v2.8.0 to pypi (will be on conda-forge shortly) with this update.  Let me know if you have any other issues.  Also, if you haven't already, please toss your ⭐ on the repo.  Thanks! 🙏
