### ISSUE TITLE
Dtale not working on Hadoop cluster

### ISSUE THREAD

**Issue by vladcGit** [man-group/dtale#695]
Hello, my team is using hadoop in order to do big data analysis and we wanted to install dtale in order to be able to better understand the data. We created an env just for this but for some reason it is not working. The server is up and you can access the link but it is an empty page, that shows only one error in console: " SyntaxError: expected expression, got '?' ". It seems to be a frontend issue; I was wondering if you have any idea on how I may tackle this problem or how I may debug the error.
I am using python3.7 in a miniconda environment and if you think it is useful I can post the packages installed there.
Thank you very much.

**Comment by aschonfeld** [comment]
Apologies for the errors.  When you say "one error in console" do you mean the developer toolbar console in your browser?  If so then could you show the network calls and which one is failing along with any console messages?

**Comment by vladcGit** [comment]
Yes, the error appears in the developer console, but all the requests are completed with status 200. The error happens in the minified javascript file (dtale_bundle.js).

**Comment by aschonfeld** [comment]
Hmm, yea maybe your installed packages will help. As of right now i dont have enough to go on. Works fine in my 3.7 environment but havent updated it in a while

**Comment by vladcGit** [comment]
### This is everything i have after running conda list

#Name                    Version      
_libgcc_mutex             0.1           
_openmp_mutex             4.5         
brotli                    1.0.9           
brotli-bin                1.0.9           
brotli-python             1.0.9           
brotlipy                  0.7.0        
ca-certificates           2022.6.15       
certifi                   2022.6.15       
cffi                      1.15.0          
charset-normalizer        2.1.1           
click                     8.1.3           
cryptography              37.0.2          
cycler                    0.11.0          
dash                      2.6.1           
dash-bootstrap-components 1.2.1           
dash-core-components      2.0.0           
dash-daq                  0.5.0           
dash-html-components      2.0.0           
dash_colorscales          0.0.4           
docopt                    0.6.2           
dtale                     2.7.1           
et_xmlfile                1.0.1           
fastavro                  1.6.0           
flask                     2.2.2           
flask-compress            1.12            
fonttools                 4.37.1          
freetype                  2.10.4          
future                    0.18.2          
giflib                    5.2.1           
idna                      3.3             
importlib-metadata        4.11.4          
importlib_metadata        4.11.4          
itsdangerous              2.1.2           
jbig                      2.1             
jinja2                    3.1.2           
joblib                    1.1.0           
jpeg                      9e              
keyutils                  1.6.1           
kiwisolver                1.4.2           
krb5                      1.19.3          
lcms2                     2.12            
ld_impl_linux-64          2.36.1          
lerc                      3.0             
libblas                   3.9.0         
libbrotlicommon           1.0.9           
libbrotlidec              1.0.9           
libbrotlienc              1.0.9           
libcblas                  3.9.0         
libdeflate                1.10            
libedit                   3.1.20191231    
libffi                    3.4.2               
libgcc-ng                 12.1.0          
libgfortran-ng            12.1.0          
libgfortran5              12.1.0          
libgomp                   11.2.0    
liblapack                 3.9.0     
libnsl                    2.0.0     
libopenblas               0.3.20    
libpng                    1.6.37          
libstdcxx-ng              11.2.0        
libtiff                   4.3.0           
libwebp                   1.2.2           
libwebp-base              1.2.2           
libxcb                    1.13            
libzlib                   1.2.11       
lz4                       4.0.0           
lz4-c                     1.9.3           
markupsafe                2.1.1           
matplotlib-base           3.4.3           
missingno                 0.4.2           
munkres                   1.1.4           
ncurses                   6.3                 
networkx                  2.7.1           
numpy                     1.21.6          
openjpeg                  2.4.0           
openpyxl                  3.0.9           
openssl                   1.1.1o          
packaging                 21.3            
pandas                    1.3.5           
patsy                     0.5.2           
pillow                    9.1.1           
pip                       22.0.4           
plotly                    5.10.0          
pthread-stubs             0.4             
pycparser                 2.21            
pykerberos                1.2.4           
pyopenssl                 22.0.0          
pyparsing                 3.0.9           
pysocks                   1.7.1           
python                    3.7.12         
python-dateutil           2.8.2           
python-hdfs               2.7.0           
python_abi                3.7                   
pytz                      2022.2.1        
readline                  8.1              
requests                  2.28.1          
requests-kerberos         0.12.0          
scikit-learn              1.0.2           
scipy                     1.7.3           
seaborn                   0.11.2          
seaborn-base              0.11.2          
setuptools                59.8.0          
six                       1.16.0          
sqlite                    3.37.0              
squarify                  0.4.3           
statsmodels               0.13.2          
strsimpy                  0.1.9           
tenacity                  8.0.1           
threadpoolctl             3.1.0           
tk                        8.6.12              
tornado                   6.1             
typing-extensions         4.3.0           
typing_extensions         4.3.0           
unicodedata2              14.0.0          
urllib3                   1.26.11         
werkzeug                  2.2.2           
wheel                     0.37.1           
xarray                    0.20.2
xlrd                      2.0.1
xorg-libxau               1.0.9
xorg-libxdmcp             1.1.3
xz                        5.2.5
zipp                      3.8.1
zlib                      1.2.11
zstd                      1.5.2

**Comment by aschonfeld** [comment]
So I think the issue you might be having is with the fact that conda installs packages in a different style than pypi.  You can also intermingle installations using pip.  So I think some of your packages are beyond the versions required for dtale.  Also, some of the packages you listed I could not find on pypi.  Here is the list of packages I have installed python3.7:
```
Brotli==1.0.9
brotlipy==0.7.0
certifi==2022.6.15
cffi==1.15.0
charset-normalizer==2.1.1
click==8.1.3
cryptography==37.0.2
cycler==0.11.0
dash==2.6.1
dash-bootstrap-components==1.2.1
dash-colorscales==0.0.4
dash-core-components==2.0.0
dash-daq==0.5.0
dash-html-components==2.0.0
dash-table==5.0.0
docopt==0.6.2
dtale==2.7.1
et-xmlfile==1.0.1
fastavro==1.6.0
Flask==2.2.2
Flask-Compress==1.12
flask-ngrok==0.0.25
fonttools==4.37.1
future==0.18.2
idna==3.3
importlib-metadata==4.11.4
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.1.0
kaleido==0.2.1
kiwisolver==1.4.2
lz4==4.0.0
MarkupSafe==2.1.1
matplotlib==3.4.3
missingno==0.4.2
munkres==1.1.4
networkx==2.6.3
numpy==1.21.6
openpyxl==3.0.9
packaging==21.0
pandas==1.1.5
patsy==0.5.2
Pillow==9.1.1
plotly==5.10.0
pycparser==2.21
pykerberos==1.2.4
pyOpenSSL==22.0.0
pyparsing==3.0.9
PySocks==1.7.1
python-dateutil==2.8.2
pytz==2022.2.1
requests==2.28.1
requests-kerberos==0.12.0
scikit-learn==1.0.2
scipy==1.7.3
seaborn==0.11.2
six==1.16.0
squarify==0.4.3
statsmodels==0.12.2
strsimpy==0.1.9
tenacity==8.0.1
threadpoolctl==3.1.0
tornado==6.1
typing_extensions==4.3.0
unicodedata2==14.0.0
urllib3==1.26.11
Werkzeug==2.2.2
xarray==0.20.2
xlrd==2.0.1
zipp==3.8.1
zstd==1.5.2.0
```

Using this environment works fine with D-Tale.  I'd try creating a fresh miniconda env and then reinstalling dtale as the first package `conda install dtale -c conda-forge`

Hope this helps and let me know if you have any other issues.

**Comment by vladcGit** [comment]
Thank you very much for all the help, I will pass this to the devops team and will post an update if I face other issues.

**Comment by vladcGit** [comment]
In the end, we realised it is a browser issue. We updated firefox from version 63 to 104 and now it's working as intended. So the problem wasn't on your end. Thanks again for the help, you can close the issue.
