### ISSUE TITLE
Export all the charts rendered to a single html.

### ISSUE THREAD

**Issue by danyang-rainbow** [man-group/dtale#700]
Now, in charts view, we can export a single charts to a html, hoping that there is a button which can export all the charts saved to a single html file. Thanks！

**Comment by aschonfeld** [comment]
@danyang-rainbow thanks for your suggestion, are you asking for a button on the "Charts" screen that would allow you to do this?

**Comment by danyang-rainbow** [comment]
> @danyang-rainbow thanks for your suggestion, are you asking for a button on the "Charts" screen that would allow you to do this?

Thanks for reply, yes, like a buttom on the top of all the saved chats which can export all the saved chats to a html file.

**Comment by aschonfeld** [comment]
@danyang-rainbow I'll be releasing v2.12.0 of D-Tale soon with this new functionality. Here's how it will work:

https://user-images.githubusercontent.com/11547371/216410979-2db6d9b5-ae73-488e-b665-5b6cd36f3a35.mov
