### ISSUE TITLE
Replacements do not accept „0“ as replacer

### ISSUE THREAD

**Issue by hwesterholt** [man-group/dtale#704]
I have a column with numerical data. When I try to replace all `nan` values in that column with a raw value of 0, I am prompted to „Please enter a raw value!“. I guess I am doing something wrong. What would be the best approach to mirror `fillna(0)` functionality?

**Comment by hwesterholt** [comment]
@aschonfeld Please don't feel the need to apologise. Dtale is absolutely _mindblowing_ and I cannot tell you how many hours it has saved me already. I would have loved to try and contribute a fix myself, but my typescript foo is non-existent. Your efforts are highly appreciated!

**Comment by aschonfeld** [comment]
@hwesterholt thank you for the kind words.  I've just release v2.9.0 to pypi (soon to be on conda-forge) with this fix.  Let me know how it goes.

P.S. If you haven't already please toss your ⭐ on the repo.  Thanks 🙏
