### ISSUE TITLE
"Open in new tab" does not work in VSCode

### ISSUE THREAD

**Issue by gal064** [man-group/dtale#709]
In VS Code run `dtale.show(df)` and click "Open in New tab". Nothing happens.

My suggestion is to open a new tab in the browser and point it to dtail URL. For now, I created a new function for it:
```
def open(df):
    webbrowser.open(show(recording).build_main_url())
```

But it would be nice to modify the "Open in New Tab" button to work

**Comment by sockthem** [comment]
hi @gal064 : is visualization part working for u ? charts?

**Comment by gal064** [comment]
Some do and others don't

Describe when accessed from a column header, heatmaps, and corr analysis, predictive power work. But describe that's accessed from the "Visualize" menu, charts and network viewer don't

To clarify, I'm speaking about Jupyter notebook that's run through [VSCode jupyter feature](https://code.visualstudio.com/docs/datascience/jupyter-notebooks).

**Comment by aschonfeld** [comment]
So in VSCode it's not possible to spwan new windows.  See this previous [issue](https://github.com/man-group/dtale/issues/258)

**Comment by aschonfeld** [comment]
@gal064 is there any way you can run the folllowing command in your VS Code python console: 
```
import os
print(os.environ)
```

Currently the code checks to see if `VSCODE_PID` is present in the environment variables while it is running and if it is then it will force the app to open new screens within the current screen rather than opening a new tab (since it isn't allowed).  But if VS Code has changed the names of its environment variables then this check will no longer work.

Thanks

**Comment by aschonfeld** [comment]
Looks there is now a variable `VSCODE_INJECTION` that exists.  I'll update D-Tale to test for that as well.  Will let you know when a new version has been released

**Comment by aschonfeld** [comment]
@gal064 @sockthem just released v2.9.1 to pypi (will be on conda-forge shortly). Let me know if this update worked for you. Also, if you haven't already, please toss your ⭐ on the repo when you get a sec. Thanks 🙏

**Comment by gal064** [comment]
Unfortunately it still doesn't work. VSCODE_INJECTION is in my environment variables

https://user-images.githubusercontent.com/50427415/209919498-bfdd6a61-48e7-4180-834f-37d40af36f99.mov

**Comment by aschonfeld** [comment]
@gal064 ohh you're trying to actually click "Open in New Tab".  I should probably disable that button when using D-Tale in VSCode.  Sorry I thought you were clicking things that, if not run in VSCode, open new tabs.  I can update that button to either be hidden or to open in the same tab when using D-Tale in VSCode

**Comment by gal064** [comment]
Maybe open dtale in a new browser tab instead?

**Comment by aschonfeld** [comment]
So VSCode won't allow you to do such functions from within a jupyter notebook.  So I can either update that button (when using VSCode) to open a popup that will give you a URL you can paste into any browser.  Or you can update your notebook to try and use `open_browser` like this:
```
dtale.show(df, open_browser=True)
```

**Comment by gal064** [comment]
Oh understood. In that case, I think it's fine the way it is. Thanks!

The open_browser works great so that's a good workaround
