### ISSUE TITLE
Increase the graph layout boundary while in the dtale page. 

### ISSUE THREAD

**Issue by datadiv06** [man-group/dtale#714]
Firstly thanks for introducing a wonderful tool. which is indeed amazing. On selecting parameters the dtale page shows cut results

![issue dtale](https://user-images.githubusercontent.com/96575055/205072173-207d6693-23c4-4e1b-8d9d-394d12e43c9e.JPG)
 page , with x axis legends, y axis. Unless it is being downloaded as html , the axis can't be adjusted for proper readability. 

If you could please address this problem.

![image](https://user-images.githubusercontent.com/96575055/205072332-12e3f85e-b7b7-4ed1-9752-4f4a2765ab3b.png)

**Comment by aschonfeld** [comment]
@datadiv06 how does this look? 
![image](https://user-images.githubusercontent.com/11547371/209448667-0bf9b409-70fd-4c68-882e-57b7675503e1.png)

**Comment by aschonfeld** [comment]
@datadiv06 just released v2.9.1 to pypi (will be on conda-forge shortly).  Let me know if this update worked for you.  Also, if you haven't already, please toss your ⭐ on the repo when you get a sec.  Thanks 🙏

**Comment by datadiv06** [comment]
Thanks a lot Andrew Schonfeld.

**Comment by datadiv06** [comment]
I have few more issues 
1.  when I am trying to visualize a graph in multimode , it works , but while exporting the graph, it never saves the graph as multiple y axis. It saves that as default 
2. While doing column operation , I found that it is only allowing to do computation between two columns, not more. Is there any way to solve the issue 
3. Can we have linked graphs , like having same x axis and different y axis on the same page, and while changing the x axis of one graph it changes the x axis of all the other graphs , so that multiple parameter comparison could be made. 
4. Can we change the logo of the dtale , to something user defined. 

I use dtale on a daily basis. I want to deploy that into production env, so that it could be used as a strong analytics tool
Thanks again. 
Would be waiting for the use updates !!
Cheers

![image](https://user-images.githubusercontent.com/96575055/220317082-029e8b73-0ea5-46fc-8e2e-db3f79381a8c.png)

**Comment by aschonfeld** [comment]
@datadiv06 You can change the main title for D-Tale. The way to do it is described [here](https://github.com/man-group/dtale/issues/480)

I will dig into the other issues as soon as I get the chance

**Comment by aschonfeld** [comment]
@datadiv06 here's my responses to your questions:
1) I have found the issue and updated the code accordingly.  Will update when a version has been published which includes this update
2) Can you explain a little deeper?
3) So I think this can be achieved by using a combination of the `Group` & `Chart Per Group` inputs. So this way when you change the value of `X` it will update all the charts displayed on the screen.  I know this isn't completely perfect but it will give you the effect of changing the value of `X` updating multiple charts.
4) see previous comment.  You can also specify your own font styling too.  I know its not a logo but you can do a pretty go amount with test & font styling alone.

Let me know if you have any other questions. Thanks

**Comment by datadiv06** [comment]
@aschonfeld , thanks a lot for bringing a lot of changes in the profile. Really appreciate that. 
However, I have few more comments to add, 

1. The graph window. The window is small , that is why the legends collapses together unless they are exported as pictures. So, if anyone open the dtale window the window where the graph plots is relatively small . 
![image](https://github.com/man-group/dtale/assets/96575055/e4757cce-ec4f-4217-9b62-a8bf9ac95a08)


2. Is that possible to deploy dtale as an application ? currently I use jupyter to import the dtale and open the dtale window. How can someone who dosen't know about anaconda , or jupyter could use that . 

Thanks again :)

**Comment by aschonfeld** [comment]
@datadiv06 
1) I'm not really following, is the issue with the size of the text on the graph legend?  It appears that I can read the texst fine in that screenshot you posted.

2) So you can run D-Tale two other ways I can thinks (there are some others but they are more involved)
* You can use a python console.  Go to your command line and activate your virtual environment and run `python`.  Once that you can execute something similar to [this](https://github.com/man-group/dtale#python-terminal)
* [Standalone script](https://github.com/man-group/dtale#as-a-script)

Let me know if you have any other questions

**Comment by datadiv06** [comment]
Hi, 
in response to the above statement regarding the chart window:

![image](https://github.com/man-group/dtale/assets/96575055/5dedcee2-3923-4d0d-b201-34b610a6b0b4)

here in this image the chart window is really small. To view the plots or graphs with all the signals and legends intact , the window is very small. So can we have the chart window bigger and all the buttons  could be placed vertical . This would keep the chart window wide and bigger for a better view, 

Thanks !!
