### ISSUE TITLE
Can not import dtale in google collab

### ISSUE THREAD

**Issue by ABHISHEK64** [man-group/dtale#729]
ImportError                               Traceback (most recent call last)
[<ipython-input-4-8f34aecfc5df>](https://localhost:8080/#) in <module>
      1 import pandas as pd
      2 import seaborn as sns
----> 3 import dtale.app as dtale_app

5 frames
[/usr/local/lib/python3.8/dist-packages/statsmodels/tsa/filters/filtertools.py](https://localhost:8080/#) in <module>
     16 import scipy.fftpack as fft
     17 from scipy import signal
---> 18 from scipy.signal.signaltools import _centered as trim_centered
     19 
     20 from statsmodels.tools.validation import array_like, PandasWrapper

ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (/usr/local/lib/python3.8/dist-packages/scipy/signal/signaltools.py)

**Comment by aschonfeld** [comment]
@ABHISHEK64 this is actually a known issue with Google Colab as described [here](https://github.com/man-group/dtale/issues/656)

Looks like you can solve it by upgrading statsmodels. Let me know if you hit any other issues. Thanks

**Comment by aschonfeld** [comment]
Closing, duplicate
