### ISSUE TITLE
Incorrect links in README.md

### ISSUE THREAD

**Issue by albert-github** [man-group/dtale#737]
https://github.com/man-group/dtale/blob/eb0cd7b62effe9cfc194e2bbd96307ed0066ff28/README.md?plain=1#L90

The link:
`(#merge-&-stack)` should read `(#merge--stack)`

The link:
`(#load-data-&-sample-datasets)` should read `(#load-data--sample-datasets)`

Furthermore in general:
- using the `&` in running text / headers is not nice and should be replaced by the word `and`
- would be good when the lines in the text are not so long, but would be folded over multiple lines

**Comment by aschonfeld** [comment]
@albert-github fixed those links in the README.  Nice catch! Side note, if you haven't already, please put your ⭐  on the repo when you get a sec. Thanks! 🙏
