### ISSUE TITLE
Highlight options in backend

### ISSUE THREAD

**Issue by esq106** [man-group/dtale#738]
Hello, thanks for such a project. It provides great features. 

Edit: Sorry about edits. I want to make a clear explanation about the situation. Right now I am using "range_highlights" settings in dtale.show(). I am passing a dictionary with list if highlights criteria for different columns. On the interface, highlights are not visible at the beginning. When I click "Highlight Range" button I can see passed criterias and they look already selected. When I toggle one of them off and on, all criterias highlighted on the data. However, it is not working from beginning. How can I solve this issue?

**Comment by aschonfeld** [comment]
@esq106 so unfortunately the "Range Highlight" functionality is fairly complex from a configuration perspective, but here is how you would accomplish what you're asking for:
```
import dtale
import pandas as pd

df = pd.DataFrame({
  "foo": [1,2,3,4,5]
})
dtale.show(
  df,
  background_mode="rangeHighlight",
  range_highlights={
            "all": {
              "active": True,
              "equals": {"active": False},
              "greaterThan": {"active": True, "color": {"a": 1, "b": 157, "g": 245, "r": 255}, "value": 2},
              "lessThan": {"active": False},
            }
  }
)
```

This will give you this:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/11547371/224851332-e537b86d-6186-4070-828e-a92e7af0af3f.png">

Hope this helps.  Also, if you haven't already, please put your ⭐ on the repo when you get a sec.  Thanks! 🙏

**Comment by esq106** [comment]
Thank you for the answer and the solution a lot. I was doing range_highlights, but missing background part. It is very lovely. I also stared the repo. As a further development suggestion, right now I am using highlights with predefined filters and when I switch between filters to see specific rows, I am losing my highlights. It would be very lovely if I can keep my highlights while switching between filters.
