### ISSUE TITLE
Coverage Analysis

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#74]
In the [demo video](https://www.man.com/maninstitute/d-tale), there is Coverage Analysis. I installed version 1.7.6 and it doesn't have. where can I find or activate it?

**Comment by aschonfeld** [comment]
Oh sorry about that, coverage analysis was replaced by the "Charts" popup.  So an example of coverage would be something like [this](http://andrewschonfeld.pythonanywhere.com/charts/1?chart_type=line&x=date&agg=nunique&barmode=group&cpg=false&y=%5B%22security_id%22%5D)

I would choose either "Count" or "Unique Count" for the aggregation.  So under the hood this does a groupby on date (X-Axis) and then performs a count on security_id (Y-Axis)
