### ISSUE TITLE
Columns with no edit options show other options column and do not update

### ISSUE THREAD

**Issue by DiegoF90** [man-group/dtale#742]
I am trying to use the column_edit_options as part of dtale.show (using a Jupyter Notebook) with the below:

```
import pandas as pd
import dtale
df = pd.DataFrame({'a': ['yes', 'no', 'no', 'maybe'], 'b': ['foo', 'bar', 'spam', 'eggs']})
dtale.show(df, column_edit_options = {'a': ["yes", "no", "maybe"]})
```

However, when double clicking on column "b" I also get the options given only for column "a" (at the top edit bar, but not in the cell). Tipping a value outside the options (fails to find an option) and after an Enter does not update the corresponding cell value.

I have noticed that this happens only when trying to edit a cell in column "b" after editing one in column "a".

----------------------------------------------------------------------------------------------------------------------------------------

> pip show dtale
Name: dtale
Version: 2.13.0
Summary: Web Client for Visualizing Pandas Objects
Home-page: https://github.com/man-group/dtale
Author: MAN Alpha Technology
Author-email: ManAlphaTech@man.com
License: LGPL

**Comment by aschonfeld** [comment]
@DiegoF90 just released v2.14.0 to pypi (should be on conda-forge shortly) with this update.
