### ISSUE TITLE
code generation - why not use df.drop for column deletion in generated code ? it currently uses list comprehension

### ISSUE THREAD

**Issue by jj-github-jj** [man-group/dtale#748]
Trying to figure out why the generated code uses a long list comprehension for deleting columns instead of a simpler, abbreviated df.drop method

**Comment by aschonfeld** [comment]
@jj-github-jj no reason at all, I will update the code to use that instead.  Good catch

**Comment by aschonfeld** [comment]
@jj-github-jj just released v2.14.0 to pypi (should be on conda-forge shortly) with this update.  Also, if you haven't already, please put your ⭐ on the repo when you get a sec. Thanks! 🙏
