### ISSUE TITLE
How do I see all products with the same order ID

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#773]
I can see the dublicates Order IDs by selecting the same Order ID column from the Show duplicates section. So I want to see all products with same Order ID in Groupby. However, when I select the products in Col: section and select Product Of All item as Agg: section, I get the following warning. **can't multiply sequence by non-int of type 'str'**  The keep first and keep last options in the Agg: it does not matter. Because I need to see when there are more than two sales. I couldn't figure out how to see all products with the same order Id. I use another online tool for this. Is this a bug in dtale or is it supposed to work like this? By the way even if I don't do duplicates, the result does not change.

![1](https://github.com/man-group/dtale/assets/40146917/c98168ca-f6c1-4514-8ddd-8ce904242a48)
![2](https://github.com/man-group/dtale/assets/40146917/7ffc6d4a-0649-4956-b5ce-6af5a5d1f173)
![3](https://github.com/man-group/dtale/assets/40146917/79169f6e-5df8-4e56-ad5b-f511bf60f028)

[You can download the dataset here](https://filetransfer.io/data-package/FV796lvX#link)

**Comment by aschonfeld** [comment]
So I think you used an actual numeric column like `Price Each` or `Quantity` your aggregation would be fine.  Right now you're trying to multiply strings `Product of All Items`.  I think the best option I can think of is to add a "Select All" button to the "Show Duplicates" button so you don't have to click each duplicate one by one.

**Comment by aschonfeld** [comment]
It does look like there is a bug with how filtering is working on duplicates if you do try to click one of the checkboxes and then click "Execute" but that doesn't affect this situation where you want to see all duplicates

**Comment by T-a-c-h-y-o-n** [comment]
The problem is actually simple. Seeing all products with the same Order ID. If there is an option called Product of All Items, shouldn't it work? Because if we can see the first and last sales, shouldn't it show them all? When I groupby according to the order ID on the gigasheet site, it automatically displays all products with the same order ID. 
![sc](https://github.com/man-group/dtale/assets/40146917/8ecf433a-3db5-4178-ad8d-6efcf6e9b3f9)

**Comment by T-a-c-h-y-o-n** [comment]
The strange thing is that when you remove the duplicate order IDs, the problem does not appear.  Of course, it doesn't make any sense when you do it that way.

**Comment by aschonfeld** [comment]
All I can really offer on the "shouldn't it just work route" is that I'll filter out the "Product of All Items" option when you've selected a non-numeric column.

Clicking "Execute" on "Show Duplicates" without checking anything will show you all duplicated orders.  It won't give you that nice expandable row UI you get from gigasheet but it should give you what you need.

**Comment by T-a-c-h-y-o-n** [comment]
There's a misunderstanding. The problem is not with duplicate rows. The problem is seeing all products with the same order IDs.

**Comment by aschonfeld** [comment]
But doesn't this show you exactly that?  I can see that "Order ID" 141275 is duplicated and you can see the two Products that it uses are "USB-C Charging Cable" & "Wired Headphones"

https://github.com/man-group/dtale/assets/11547371/4b3ea621-9121-45d1-8bc4-8b5f977bfba5

**Comment by T-a-c-h-y-o-n** [comment]
As a solution to this, you can see the most repeated order IDs of the column in question from the describe and then filter. But it's a long road.

**Comment by T-a-c-h-y-o-n** [comment]
[Ekran Kaydı - 2023-07-03 22-37-35.webm](https://github.com/man-group/dtale/assets/40146917/c80993d7-8728-48a9-b68b-cba8ecdc7537)

**Comment by aschonfeld** [comment]
Ok so if I wanted to get to the Order ID that occurs the most then all I'd do is use "Summarize Data" w/ a GroupBy as shown here:

https://github.com/man-group/dtale/assets/11547371/de134cac-a17b-4fdc-8cbd-685055ce086e

**Comment by T-a-c-h-y-o-n** [comment]
Thanks for the answers.
I thought the same thing, it applies to the city and address. The problem here is not being able to see the products sold. If the first and last sold products can be displayed in Groupby, I couldn't quite figure out why not all products are shown.  Because the given error gives duplicate rows. When you remove these rows from remove from dublicates row, it does not give an error in the same way. So it looks like there's a bug there.

[sc.webm](https://github.com/man-group/dtale/assets/40146917/02d32cad-904e-476b-9a61-86ed2e35d45d)

**Comment by aschonfeld** [comment]
Got it.  Ok, so the main functionality you'd like added is a way to do a GroupBy on "Order ID" and then something that will aggregate the "Product" column into something like a comma-separated string?

I could try looking into add another aggregation which would strictly pertain to string-based columns.  So then you can do a GroupBy on "Order ID" w/ and aggregation on any column using Count, then add another aggregation on "Product" using this new string function.  That way the output would have a column you could sort on to find which Order ID occurs the most and then see the products associated with it.

Sound good?

**Comment by T-a-c-h-y-o-n** [comment]
Thank you for your help. 
Maybe you can give a new minor version number along with these features.
🙏 👏 👍

**Comment by aschonfeld** [comment]
How's this? 

https://github.com/man-group/dtale/assets/11547371/d98bda22-f792-4552-9de3-8eedea6bcb18

**Comment by T-a-c-h-y-o-n** [comment]
Very good.  It would be great if he also wrote down how many items there are.

**Comment by aschonfeld** [comment]
So, if I had added another aggregation for “count” you will see the number of items

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n just released v3.2.0 to pypi (will be ing conda-forge shortly) with this feature. Let me know how it goes

**Comment by T-a-c-h-y-o-n** [comment]
Thanks for the string joiner.
It was a great solution especially for data scientists who will do customer segmentation and product segmentation.
