### ISSUE TITLE
dtale.show(background_mode) not working

### ISSUE THREAD

**Issue by anavsh1** [man-group/dtale#779]
I have tried multiple background_mode options within dtale.show() and none of them are highlighting any columns. However when selecting the different highlighting options within a browser, they all work.

```python

d = dtale.show(df, open_browser=True, subprocess=False, vertical_headers=True, background_mode=“dtypes”)

``` 

All the other parameters within show() work as expected aside from background_mode. I have also tried it with subprocess=True, and all possible background_mode options.

**Comment by aschonfeld** [comment]
@anavsh1 just released v3.3.0 to pypi (should be on conda-forge soon) with this fix included.

Also, if you haven't already, please put your ⭐ on the repo when you get a sec. Thanks! 🙏
