### ISSUE TITLE
DataFrame Functions Promlem

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#785]
Hi again,
I can't get results from math operations in Dataframe functions. For example, when I want to do a cumulative aggregation, groupby doesn't collect its columns. It only shows the data in the column option. It gives the same error in other math operations such as transform.

**Comment by aschonfeld** [comment]
Just trying to understand the problem a little more.  I've gone to "Dataframe Functions", selected "Cumulative Sum" then selected a numeric column and a "group by" column. It adds a column to the end of the dataframe.  I'm able to verify that my cumulative sum is correct when I filter on individual groups.

Can you include a recording perhaps? Thanks

**Comment by T-a-c-h-y-o-n** [comment]
Hi,
I want to show the sum of country sales in the global_sales column as seen in the screenshot doesn't it make a cumulative sum? If not, how should we do it?
[sc.webm](https://github.com/man-group/dtale/assets/40146917/95e0b0d6-fa41-4951-8e49-7ed6ccb1e321)

**Comment by T-a-c-h-y-o-n** [comment]
Yes, it seems that I misunderstood. 
Thank you for your help.
