### ISSUE TITLE
It's a request rather than a problem

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#792]
Hi,
Dtale is an almost perfect application. But sometimes I need a percentage information. For example, in the Value Counts representation contained in the Describe, it will be great if it shows the  percentage while also showing the frequency. We can also do this in Pie Chart representation but it's a long way.

**Comment by aschonfeld** [comment]
So when you say percentage, you'd like to see what percentage of values are of that specific value in "Value Counts"?  For example for this screenshot BBBB would be roughly 11%
![image](https://github.com/man-group/dtale/assets/11547371/5848b005-b043-48e9-979b-f9fa2e82fcb8)

**Comment by T-a-c-h-y-o-n** [comment]
It would be more perfect if it was as you say.

**Comment by aschonfeld** [comment]
How does this look? 
![IMG_7389](https://github.com/man-group/dtale/assets/11547371/d3dc3b9f-df8a-47ae-ab80-7a9ad30c2d9a)

**Comment by T-a-c-h-y-o-n** [comment]
Maybe it would be better if it didn't write it as a percentage, but showed it as a % sign.

**Comment by T-a-c-h-y-o-n** [comment]
It's pretty good. Maybe it would be better if it was a little bigger in character as it looks in the picture.

![% 10](https://github.com/man-group/dtale/assets/40146917/33dfd8bb-da95-4f4a-8bef-c272d9d5cf16)

**Comment by T-a-c-h-y-o-n** [comment]
Or...

![% 10](https://github.com/man-group/dtale/assets/40146917/c59e3a13-34fc-4a29-8cea-69b77c6bab3a)

**Comment by aschonfeld** [comment]
This was the best I could do (unfortunately cant get it centered):
![IMG_3809](https://github.com/man-group/dtale/assets/11547371/ebd6cc1b-ce67-450a-85e3-47a098c15f8a)

**Comment by T-a-c-h-y-o-n** [comment]
It's not a problem, it's enough if it shows the percentage. Many thanks for your efforts.

**Comment by aschonfeld** [comment]
Do you want this percentage to show up in the "Word Value Counts" chart as well?

**Comment by T-a-c-h-y-o-n** [comment]
In fact, I think it should be exactly as you says and should be specified right next to the **Most Frequent** value in the **Describe** menu. If it is possible.

![ss2](https://github.com/man-group/dtale/assets/40146917/ecba2a1c-8422-4825-83cd-fab6594a96d3)

**Comment by aschonfeld** [comment]
This update has been added in v3.4.0 on pypi (should be available on conda-forge shortly), let me know if you have any issues
