### ISSUE TITLE
Some interface correction suggestions

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#798]
Hi,
I have to humbly inform you about some interface corrections I have seen in the application.
1- The one at the top menu (Actions, Visualize, etc.) should either be completely canceled or provide an option to be  pinned. Because it constantly appears and disappears with any mouse movement located on the top of the screen.

2- Show/Hide should offer a tool for performing batch operations on columns instead of columns. This tool should be similar to the current show/hide section, but it should provide some options on which we can perform basic batch operations. Thus, instead of dealing with each column separately, we should be able to control them all from one place. I tried to explain as much as I could in the pictures. I think that this way we can step into the next major update.  Thanks for everything.

![sss1](https://github.com/man-group/dtale/assets/40146917/36184420-e149-4f4a-b42f-ba08372d838c)
![ss2](https://github.com/man-group/dtale/assets/40146917/cc28eebe-5237-4d24-bab0-201d827505ae)
![ss3](https://github.com/man-group/dtale/assets/40146917/031988c3-ad8d-480a-b30b-d647a3861ea0)
![ss4](https://github.com/man-group/dtale/assets/40146917/81adc815-d42b-4d8b-9698-507c0985f1c6)

**Comment by aschonfeld** [comment]
1) You can currently lock the ribbon menu as detailed [here](https://github.com/man-group/dtale/issues/759) and I have committed the code to hide the ribbon menu but have not released a new version of the app yet as detailed [here](https://github.com/man-group/dtale/issues/796)

2) As for this one, it seems like a large undertaking.  I can certainly add the "Duplicate" button to the column menu.  I'll have to create a new ticket for the "batching" of column actions

**Comment by T-a-c-h-y-o-n** [comment]
Hi,
Thanks for reply. I'm looking forward to the new version.
For the other issue, as I said, 4. you can think about the version. Of course, there is no hurry, but I think it is a useful initiative for the interface

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n  just released v3.5.0 to pypi (will be on conda-forge shortly), which includes these changes. Let me know if you have any issues
