### ISSUE TITLE
Heatmaps break locked columns

### ISSUE THREAD

**Issue by ms32035** [man-group/dtale#800]
In my dataframe of several columns I have 5 locked columns (3 text, and 2 numeric). When I switch to highlight to heatmap (by columns or overall) the locked text columns are hidden, and as a result I see 5 numeric columns as locked columns. I guess the correct way would be to not hide locked columns in the heatmap view

**Comment by aschonfeld** [comment]
So the reason for certain columns being hidden is that they can't correctly be used in the heatmap calculation.  IF you want to display everything (anything that can't be calculation correctly just gets displayed in gray background) you can click this option: 
![image](https://github.com/man-group/dtale/assets/11547371/5af716a1-d0ea-472f-ae90-f852a6e88d01)


I can certainly look into the scenario where you haven't clicked that option and you have columns locked that can't be included in the heatmap calculation.  It appears that those column disappear and then it hides the next unlocked columns it's place.

**Comment by ms32035** [comment]
Thanks, the latter is exactly the scenario I am describing

**Comment by aschonfeld** [comment]
@ms32035 just release v3.5.0 to pypi (will be on conda-forge shortly), which includes this fix. Let me know if you have any issues

**Comment by ms32035** [comment]
The behaviour changed in that now only the numeric columns remain locked, so the number of locked columns goes down from 5 to 2. Not sure if that's a desired/correct behavior, but I guess that's up to you to decided. Either way, thanks for looking at it so quickly :rocket:

**Comment by aschonfeld** [comment]
I don't really know of any other option for behavior.  If you select the "Show All Heatmap Columns" option then all 5 locked columns will remain.  So in this instance it was the "desired" behavior.
