### ISSUE TITLE
Describe Section is Almost Perfect...

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#803]
### Frequency Tables
A frequency table for categorical variables. It would be perfect if there was a menu called frequency table in the Describe section and we could get the frequency and percentage information between two categorical variables. In order not to overload the application, let's set the maximum unique value option ourselves, for example 10-30-50. I tried to explain it as much as I could in the pictures.
![ss1](https://github.com/man-group/dtale/assets/40146917/3691afbd-3d87-4daa-9e56-2691e0a766be)

Frequency table when split is not selected.
![ss2](https://github.com/man-group/dtale/assets/40146917/913a8a13-0726-4f4a-895a-e64c5e307e09)

Frequency table when gender variable is selected from the split menu
![ss3](https://github.com/man-group/dtale/assets/40146917/0f403a5a-dcac-4594-9be6-be54d40c5573)

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n how's this? 

https://github.com/man-group/dtale/assets/11547371/c7067540-613c-4fc4-90f8-e2a4ecde3379

Couple notes: Getting Missing to show up for each group even if it doesn't exist was too much work. So I only have it showing if it `nan` values actually exist.  The other thing is that hiding the outer group when a split column is specified was a little too hard.  I can continue digging to get it work if you think it's necessary, but it seems like its not worth it

**Comment by T-a-c-h-y-o-n** [comment]
It's perfect. Much better than I thought. In this form, it serves all our purpose.

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n  just released v3.6.0 to pypi (should be on conda-forge soon) with this feature included.
