### ISSUE TITLE
NoneType object is not iterable

### ISSUE THREAD

**Issue by dd1118** [man-group/dtale#806]
I am trying to use dtale, and anytime I try to run the basic show or open_browser commands, I get TypeError: 'NoneType object is not iterable. This happens regardless of what data I am using the dataframe. I used the simple example from the github to rule out issues with my data.

import dtale
import pandas as pd

df = pd.DataFrame([dict(a=1,b=2,c=3)])

d=dtale.show(df)
d.open_browser()

![image](https://github.com/man-group/dtale/assets/48698948/6692e3d1-b91a-4be5-9671-ccb6aebd0efa)

**Comment by aschonfeld** [comment]
So I just ran this locally with no issue.  My first question is, are you running these commands in a python console or jupyter notebook?  Or are you trying to run this as a script?

If you're trying to run this as a script then you'll have to make some updates:
```
import dtale
import pandas as pd

if __name__ == '__main__':
    df = pd.DataFrame([dict(a=1,b=2,c=3)])
    dtale.show(df, subprocess=False, open_browser=True)
```

**Comment by dd1118** [comment]
I have tried it both in jupyter notebook and spyder with the same issue in both.

**Comment by aschonfeld** [comment]
Ok can you try uninstalling dtale and reinstalling it?  I've never seen this error before and it doesn't happen locally for me.  Even if I pass `None` to `dtale.show` it will just start D-Tale with the upload menu displayed when you hit the URL

**Comment by dd1118** [comment]
I reinstalled it and restarted and it is working now. Thanks

**Comment by aschonfeld** [comment]
Awesome!  @dd1118 if you haven't already would you mind putting your ⭐ on this repo?  Thanks 🙏
