### ISSUE TITLE
Dtale doesn't work when using Google Colab

### ISSUE THREAD

**Issue by hamadalaqeel** [man-group/dtale#81]
Using Google Colab, I installed Dtale first by doing: `!pip install -U dtale` and it installed successfully.
After installing dtale, I read my data using pandas `df = pd.read_csv("credit_card.csv")` then using dtale by doing the following: `dtale.show(df)` and It gives me a link. When opening, it says that the site can't be reached. I tried doing it again to have a new link, but still faced the same problem.

**Comment by aschonfeld** [comment]
And you made sure to set `USE_NGROK` to true?  ?Here's an example:
```
import pandas as pd

import dtale
import dtale.app as dtale_app

dtale_app.USE_NGROK = True

dtale.show(pd.DataFrame([1,2,3]))
```

I'll update the README to contain this example

**Comment by hamadalaqeel** [comment]
It worked! Thanks.

**Comment by aschonfeld** [comment]
@hamadalaqeel btw, great avatar

**Comment by hamadalaqeel** [comment]
Thanks :)
