### ISSUE TITLE
Day Name

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#811]
Hi,
If there was an option showing the days of the week in the data frame Function/Datetime section, it would be very functional.  It also works in its current form, but when we have to write the names of the days, we first need to convert the variable to a string, and then we need to convert each number to days with the replace function one by one. If there was an option called **Day Name** and we could easily get the names of the days of the week.

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n just added this feature in v3.7.0. Let me know if you have any issues

![image](https://github.com/man-group/dtale/assets/11547371/31d64805-8154-4da4-b3c1-9cbe175e06f7)

**Comment by T-a-c-h-y-o-n** [comment]
First of all, thank you very much for your efforts.
When I tested the Weekday function I got the following message
![Ekran Görüntüsü - 2023-10-02 23-26-30](https://github.com/man-group/dtale/assets/40146917/def660db-b3c7-4617-b296-b352ec0203a1)
