### ISSUE TITLE
Weekday Name Error

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#813]
First of all, thank you very much for your efforts.
When I tested the Weekday function I got the following message
![Ekran Görüntüsü - 2023-10-02 23-26-30](https://github.com/man-group/dtale/assets/40146917/def660db-b3c7-4617-b296-b352ec0203a1)

_Originally posted by @T-a-c-h-y-o-n in https://github.com/man-group/dtale/issues/811#issuecomment-1743713715_

**Comment by aschonfeld** [comment]
I just tried it locally and on the demo site and it worked completely fine for me.  Did you install the new version 3.7.0? 

https://github.com/man-group/dtale/assets/11547371/39e97688-4f71-48b7-a049-2c339fab44b3

**Comment by T-a-c-h-y-o-n** [comment]
I had installed the new version, but I had not logged out and logged in. It came to my mind when you mentioned it. The problem was resolved after logging in again.
Sorry about that

**Comment by aschonfeld** [comment]
No worries, happy to help
