### ISSUE TITLE
No module named past.utils

### ISSUE THREAD

**Issue by jeremyftaylor** [man-group/dtale#82]
Installation seems to miss a dependency. Works after a pip install future.

**Comment by aschonfeld** [comment]
Interesting, these are the current [installation requirements](https://github.com/man-group/dtale/blob/master/setup.py#L61) and `future` is in there.

Are you sure that you didn't have an old version of `future` previously installed?

Let me check into when they added `past.utils` and if I have to I can add some more granularity to which version can be used.

**Comment by aschonfeld** [comment]
Ok so it looks like `future.past.utils.old_div` didn't exist until version 0.140.  I'll update setup.py to require at least that version.

**Comment by aschonfeld** [comment]
v1.7.11
