### ISSUE TITLE
what is the double bounce graphic used for?

### ISSUE THREAD

**Issue by moltra** [man-group/dtale#821]
I ran Dtale on my complex data-frame.  Includes multiple data-frames.  I went to look at the correlations and I am getting the double bounce Icon.  I am thinking that it means that the package is working, but the kernel status indicator in my jupyter notebook is saying the kernel is idle.

**Comment by aschonfeld** [comment]
@moltra any chance you can send me a code snippet detailing this "complex" dataframe?  You can fill it with dummy data, but I just want to see what you're working with to see if I hit the same issue.  

As for the "double bounce" graphic, that is what is displayed on the UI when something is loading.  But there is a chance that the API returned an exception and it wasn't correctly handled on the UI, thus causing the "double bounce" icon to stay up forever.
