### ISSUE TITLE
Dtale.show() error with pyarrow backed pandas dataframe?

### ISSUE THREAD

**Issue by Valence-Shinei** [man-group/dtale#823]
Greetings,
I'm pretty new to Github, but I've been using Dtale for probably around a year now. I recently updated Dtale and Pandas to newer version to take advantage of the pyarrow datatypes in Pandas. So far so good, but when I try to use Dtale.show() as I've done previously, I encounter:

`TypeError: 'ArrowExtensionArray' with dtype int64[pyarrow] does not support reduction 'skew'`

Attached is the quick setup I did to test this with some quick and dirty dummy data. Please let me know if I should provide more information to help determine if this is an issue. Thank you in advance for your time and consideration of my comments!

![Screenshot 2023-11-01 233245](https://github.com/man-group/dtale/assets/147955316/0f49d6ab-9108-4345-b522-1d41134c6f9a)
![Screenshot 2023-11-01 233308](https://github.com/man-group/dtale/assets/147955316/5739b5bb-652f-4459-a3b9-2c9e5ed71c29)
![Screenshot 2023-11-01 233345](https://github.com/man-group/dtale/assets/147955316/27c9b295-fb3c-4b8b-aa7f-4a47c088d296)
![Screenshot 2023-11-01 233412](https://github.com/man-group/dtale/assets/147955316/43c448c4-b9db-4a2e-89bd-6e4a0de275ee)
![Screenshot 2023-11-01 233435](https://github.com/man-group/dtale/assets/147955316/e7991fe4-d1ea-47e4-bd2b-532547adf1b3)
![Screenshot 2023-11-01 233451](https://github.com/man-group/dtale/assets/147955316/b5d15595-b5ef-4acb-a542-a0194fc63305)

**Comment by Valence-Shinei** [comment]
However, no problems are observed using the standard pandas dataframe with numpy backed datatypes
![Screenshot 2023-11-01 233901](https://github.com/man-group/dtale/assets/147955316/e55d1507-bc5d-4a1f-af1a-ce3bd7042264)

**Comment by Valence-Shinei** [comment]
What's also interesting is that Apache Arrow has an article about extension arrays in R, but not for Python 🤔

https://arrow.apache.org/docs/r/reference/new_extension_type.html

**Comment by aschonfeld** [comment]
Thanks for the detailed ticket @Valence-Shinei so I think what I can do (assuming I can't get the skew function to work) is that I'll just turn off the skew calculation for dtypes that don't have it.

**Comment by Valence-Shinei** [comment]
You're certainly welcome and if possible and not asking too much, that
would be great!

Dtale has really helped me move from Excel into Python in an easier,
familiar fashion as I'm learning more Python to upskill, so thank you and
team for this amazing library 😊🤝💙.

**Comment by Valence-Shinei** [comment]
Certainly, I will review and I'll be glad to add my star to the repo 🤝.

My apologies, I'm new to github and this system, but I do want to help give
credit and praise where it is due 😎🙌!

**Comment by Valence-Shinei** [comment]
Greetings Andrew,
Unfortunately it looks like I'm receiving the same error =/ . Please see the attached screenshots indicating the error after the upgrade.

![Screenshot 2023-11-28 202112](https://github.com/man-group/dtale/assets/147955316/188773e7-dfb4-4938-9925-5d88e0c38829)
![Screenshot 2023-11-28 202133](https://github.com/man-group/dtale/assets/147955316/20ec5ed2-c42a-4885-b79c-c2e413e49e44)
![Screenshot 2023-11-28 202152](https://github.com/man-group/dtale/assets/147955316/769887f2-ad46-4e28-a456-4f729f27b0a3)
![Screenshot 2023-11-28 202217](https://github.com/man-group/dtale/assets/147955316/4f5aaaa8-dea9-4072-bdde-abeb985de6fc)
![Screenshot 2023-11-28 202236](https://github.com/man-group/dtale/assets/147955316/7c2a9497-b5ef-46da-b5a1-7e8b96be3c5c)
![Screenshot 2023-11-28 202256](https://github.com/man-group/dtale/assets/147955316/0b950d65-09ef-4924-a5ab-683a84199f0c)

**Comment by aschonfeld** [comment]
@Valence-Shinei i'm sorry, for some reason I thought the function didn't exist.  I didn't realize the exception is buried within the `skew` function. I'll release a hotfix handling this. Will keep you posted

**Comment by aschonfeld** [comment]
@Valence-Shinei just released v3.8.1 let me know how it goes

**Comment by Valence-Shinei** [comment]
Success =] ! Bravo and thank you Andrew and team 😁🤝!

![Screenshot 2023-11-29 234730](https://github.com/man-group/dtale/assets/147955316/3b1e5384-0c72-4a07-bc94-4721d81e5ca3)

![Screenshot 2023-11-29 235934](https://github.com/man-group/dtale/assets/147955316/3a5bfbf4-b75e-413d-8970-38a000374398)

![Screenshot 2023-11-29 235957](https://github.com/man-group/dtale/assets/147955316/da0e11f6-8ec3-4667-83d8-12e03e5aa8d6)
