### ISSUE TITLE
Time Difference

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#831]
It would be nice if there was an option called time difference in the operation option in the datetime menu in dataframe functions. If it could calculate the time difference between the current date and the date column among the options, as well as the date between two date columns and the time difference between two time columns, it would really work.

![time difference](https://github.com/man-group/dtale/assets/40146917/c0c16d01-d538-4753-b07f-b66cb484e3c0)

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n  just released v3.9.0 to pypi (will be on conda-forge shortly) with this update

**Comment by T-a-c-h-y-o-n** [comment]
It's great. Exactly what I wanted, thank you for your work.
