### ISSUE TITLE
hoverinfo cannot be displayed on the lines to the left of the chart

### ISSUE THREAD

**Issue by xayjin** [man-group/dtale#834]
I use dtale charts a lot. I find hoverinfo cannot be displayed on the lines to the left of the chart. 
I use chrome develop tools to check out, and find there is a Div on top of the chart. So the chart can't get mousemove event.
![image](https://github.com/man-group/dtale/assets/60728877/ee61fd87-6d60-4a71-afec-7f6cd5c379c4)

use chrome develop tool to check out:

![image](https://github.com/man-group/dtale/assets/60728877/4e5f15ce-6b4b-4e9b-b802-fc8855cb6e13)

I use the latest version 3.8.1

**Comment by aschonfeld** [comment]
@xayjin  just released v3.9.0 to pypi (will be on conda-forge shortly) with this fix
