### ISSUE TITLE
Highlight columns based on the dtype

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#84]
It would be perfect to have a setting which user can select it to change the column's back color based on the column dtype
for example

- Text is white
- Int is light blue
- Date is light pink
-

**Comment by aschonfeld** [comment]
@reza1615 I think I've got this in a good place, going to include it in the next release 
![image](https://user-images.githubusercontent.com/11547371/77377913-fb56d200-6d4a-11ea-88fd-c2a690f60274.png)

Current type mappings are:
string -> white
int -> light blue
floats -> light green
bool -> gold
date -> pink

Let me know if you think i'm missing anything

**Comment by reza1615** [comment]
there is more data types https://pbpython.com/pandas_dtypes.html

**Comment by aschonfeld** [comment]
Any suggestions on colors for those?

**Comment by reza1615** [comment]
![20200324_232752](https://user-images.githubusercontent.com/2202483/77498943-33cbde00-6e27-11ea-8865-1278d3425616.jpg)
In my opinion lighter colors are better than pure colors

**Comment by reza1615** [comment]
timedelta --> light  red or light orange 
categorical --> light violet

**Comment by reza1615** [comment]
![Screenshot_20200324-234156_Chrome](https://user-images.githubusercontent.com/2202483/77499721-3b8c8200-6e29-11ea-8c07-2fe854bca176.jpg)

**Comment by aschonfeld** [comment]
I probably should have listed this from the start.  Here's the actual mapping I'm using now.  Feel free to give me your final suggestion :)

* float -> #B2DFD8
* int -> #BBDEF8
* date -> #F8BBD0
* object(string) -> none (white)
* bool -> #FFF59D
* category -> #E1BEE7
* timedelta -> #FFCDD2

![image](https://user-images.githubusercontent.com/11547371/77528837-f8500480-6e64-11ea-983a-4fa9b82c7848.png)

**Comment by reza1615** [comment]
timedelta's color is very similar to the date

**Comment by aschonfeld** [comment]
Ok, I updated timedelta to #FFCDD2

![image](https://user-images.githubusercontent.com/11547371/77531697-ba091400-6e69-11ea-8737-a69d59663570.png)

**Comment by aschonfeld** [comment]
added in v1.8.1
