### ISSUE TITLE
Cannot open Dtale with browser from Notebook

### ISSUE THREAD

**Issue by GiacomoTel** [man-group/dtale#845]
Hi using this code in a jupyter notebook 

    import dtale
    import dtale.app as dtale_app
    import dtale.global_state as global_state
    
    global_state.set_app_settings(dict(enable_custom_filters=True))
    dtale_app.USE_NGROK = True
    dtale.show(dfUnion,host='localhost',enable_custom_filters=True)

it doesn't open the instance in the browser but instead it gives me this error

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[6], [line 7](vscode-notebook-cell:?execution_count=6&line=7)
      [5](vscode-notebook-cell:?execution_count=6&line=5) global_state.set_app_settings(dict(enable_custom_filters=True))
      [6](vscode-notebook-cell:?execution_count=6&line=6) dtale_app.USE_NGROK = True
----> [7](vscode-notebook-cell:?execution_count=6&line=7) dtale.show(dfUnion,enable_custom_filters=True)

tunnel_url = tunnel_url.replace("https", "http")

ecc  ....
return tunnel_url
IndexError: list index out of range

Can anyone show me how to open the browser view from visual studio jupyter notebook ?
Thank you

**Comment by aschonfeld** [comment]
I'd try using [jupyter-server-proxy](https://github.com/man-group/dtale?tab=readme-ov-file#jupyterhub-w-jupyter-server-proxy)

**Comment by aschonfeld** [comment]
Try taking `/40000/dtale/main/1` off the end, looks like it's repeated.  Just wanna see if that endpoint works.  If ti does I'll look into why its repeating
