### ISSUE TITLE
Option to pin the top menu?

### ISSUE THREAD

**Issue by typeEquirectangular** [man-group/dtale#848]
I'm having issues with the horizontal top menu expanding when I run my mouse over it and then collapsing again afterwards. I see no way to pin it, like I can do with the left menu bar?

**Comment by aschonfeld** [comment]
So you have two options.  You can either [lock it](https://github.com/man-group/dtale/issues/759#issuecomment-1549994385) or [hide it](https://github.com/man-group/dtale/issues/796#issuecomment-1719982089).  Let me know if you have any other issues

**Comment by aschonfeld** [comment]
@typeEquirectangular I'm gonna close this.  Just re-open it if those two options don't work for you.  Also, if you haven't already, please toss your ⭐ on the repo.  Helps justify my time spent on this project 😄
