### ISSUE TITLE
Add hot-keys

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#85]
It is helpful to have hotkeys

**Comment by aschonfeld** [comment]
So right of the bat I can try and add the following hot-keys:

* pressing "Esc" when a modal is open will close it
* pressing [key not chosen yet] will open the main menu in the upper lefthand corner

So you mind suggesting some others and maybe which key you envision would be associated with each?

**Comment by reza1615** [comment]
Shift + D > Describe
Shift + F > Filter
Shift + B > Build column (In my opinion Create Column is more convenient)
Shift + C > Chart
Shift +  X > Export Code or Snippet Code (In my opinion to have Export code in all UI places make it less confusing)

**Comment by nielsrolf** [comment]
An undo button would also be great

**Comment by aschonfeld** [comment]
@reza1615 I'm finally getting around to this and I have everything including opening the main menu (Shift + M). I'll let you know when its released.

@nielsrolf I'll be creating a separate issue for the "Undo" button.

**Comment by aschonfeld** [comment]
added v1.9.2
