### ISSUE TITLE
Info Page

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#854]
It would be nice if there was an option called info in the Actions or Visualize menu and we could see all the information about the dataset on a single page.

![ss](https://github.com/man-group/dtale/assets/40146917/4d7c0a1c-235d-43e2-9e8f-2e96c3983c86)

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n so I believe all this information is already displayed in the "Describe" page in D-Tale.  The only difference is that you can only view one column at a time.
![image](https://github.com/man-group/dtale/assets/11547371/d56c71b1-705b-4bb3-a9d6-e76e21aea746)

Would it really add that much value to display the raw output of these dataframe functions?

**Comment by T-a-c-h-y-o-n** [comment]
Hi, Of course, a detailed descrbe page works, but sometimes it may be necessary to obtain a view of the entire data. As I said, it is not essential. We can also handle it with Pandas. Thanks for your interest.

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n how's this?

https://github.com/man-group/dtale/assets/11547371/d9ee77e2-1145-4675-adb8-accc4691facf

**Comment by T-a-c-h-y-o-n** [comment]
It's better to have a tabbed view, thank you

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n just added this feature in v3.12.0 on pypi. Let me know how it goes.
