### ISSUE TITLE
selecting all columns instead of one by one

### ISSUE THREAD

**Issue by AdrienCss** [man-group/dtale#856]
Does anyone know how to format charts or use builder functions with all columns "__ columns __ " options?  which will directly select the entire dataframe / all columns?

![image](https://github.com/man-group/dtale/assets/49991971/e4ed34e6-5954-4503-9d8c-512a5abe85ee)
![image](https://github.com/man-group/dtale/assets/49991971/6be5d732-a8f1-4e88-b167-4c24992b5ef8)

**Comment by aschonfeld** [comment]
@AdrienCss how's this?

https://github.com/man-group/dtale/assets/11547371/de4913c8-aceb-419b-908f-933b91b61515


https://github.com/man-group/dtale/assets/11547371/37be912a-62cd-46e8-a8cf-fc8c3cec249e

**Comment by AdrienCss** [comment]
incredible! thank you Andrew.

**Comment by aschonfeld** [comment]
@AdrienCss i'm gonna keep this open until I release a new version.  I'll let you know when the new version is available.

**Comment by aschonfeld** [comment]
@AdrienCss just released v3.12.0 to pypi with this update.  Let me know how it goes.  Also, whenever you get a sec do you mind tossing your ⭐ on the repo?  Thanks 🙏
