### ISSUE TITLE
adding Replace command

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#86]
It would be helpful to replace a column's content like excel

**Comment by aschonfeld** [comment]
Are you talking about string replacement?
https://exceljet.net/excel-functions/excel-replace-function

If so i think this is a replacement of #136

**Comment by reza1615** [comment]
Replacing missing is specific type of replacement
I suggest to have strong replacement and replacing bull or missing data

**Comment by aschonfeld** [comment]
Once again, I don't see any difference with this and #136

**Comment by aschonfeld** [comment]
@reza1615 hahaha, sorry this whole time I didn't realize that #136 is talking about filling in data with missings.  I assumed it was talking about filling in missing values.  I'm wondering if we can simply extend your code from  #136 and make the fill value whatever we want?

**Comment by aschonfeld** [comment]
added v1.8.14
