### ISSUE TITLE
Add "is not nan" to simple filters context menu

### ISSUE THREAD

**Issue by Gdsimms** [man-group/dtale#868]
![image](https://github.com/man-group/dtale/assets/8623189/5f5bcc13-5623-4520-9ca2-41b03a699763)

I'm trying to filter my dataframe to rows where a particular column is not a "nan" and I can not find an easy way to do this with the filter context menu. I often need to do this for different columns at different times so it would be nice if this was a quick and easy entry in the simple filters list in this menu, called "not empty" or "not nan"

Alternatively, this syntax does not appear to work, though it feels like it should: 
![image](https://github.com/man-group/dtale/assets/8623189/c89fe29b-1e24-432d-901e-e83d7f0ed672)

**Comment by aschonfeld** [comment]
@Gdsimms how is this? 

https://github.com/man-group/dtale/assets/11547371/08487db7-3047-4d37-bfe7-0e125c2ad7ed

**Comment by aschonfeld** [comment]
@Gdsimms this feature has been added to the v3.13.0 release.  Let me know if you have any issues.

**Comment by Gdsimms** [comment]
Perfect; thank you. I hope others find this useful, too!
