### ISSUE TITLE
highlight numbers more/less than a number

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#87]
Now with the format, we can only highlight numbers <0. it would be helpful to have a range like
x>5 and x<10

**Comment by aschonfeld** [comment]
@reza1615 What color do you want applied?  Also, do you want the background changed or just the font color?

**Comment by reza1615** [comment]
It can be the same as numbers below <0. for example yellow

**Comment by aschonfeld** [comment]
added v1.8.14
