### ISSUE TITLE
Raw Pandas Output

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#876]
Raw pandas output is very useful but the font characters are very small and hard to read, so it would be good to have characters twice as big or a zoom option. Also, features like saving should come there. 
Thanks for everything.

**Comment by aschonfeld** [comment]
You can just control the zoom with your browser: 
![image](https://github.com/user-attachments/assets/1285ceb4-95a3-4b70-be59-2eff1b8e7c2f)

**Comment by aschonfeld** [comment]
How about this? 

https://github.com/user-attachments/assets/8790da9c-cdc0-44b2-aaf7-f7a70462e49c

**Comment by T-a-c-h-y-o-n** [comment]
It's great. It would be perfect if there was a save option. Thanks for your help.

**Comment by aschonfeld** [comment]
Included in v3.14.0
