### ISSUE TITLE
Inplace format

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#88]
Now when I set format for a column it only changes the view and doesn't inplace the format. it would be helpful to inplace it on the df

**Comment by aschonfeld** [comment]
@reza1615 not sure how possible this actually is.  For example, once you've applied formatting to a number in D-Tale its essentially like you're changing it to a string.  As far as I can tell you cant add commas to the display of your numbers and still have them maintained as numbers.

Same goes for dates, I don't know of a way to change the display of dates in a dataframe without altering the state of the date.

I think the only one where this could work is strings, but then again you would lose some state of the strings if you truncate them.

Please let me know if you've seen some display settings specific to dateframes and not global pandas settings.  If they exist I'm more than happy to try.

**Comment by reza1615** [comment]
That is True.
