### ISSUE TITLE
Type Conversion Bool

### ISSUE THREAD

**Issue by T-a-c-h-y-o-n** [man-group/dtale#880]
When we select bool in the Type Conversion option for numeric values, we should provide an option just like in filtering and we should determine whether the numbers are true or false by considering the cases where they are in certain ranges or greater or less than a number. It is currently useless. This also allows us to assign bool values ​​without writing a specific query code.

**Comment by aschonfeld** [comment]
"Useless" is a bit harsh.  The functionality was strictly for type conversion, which it did.  Regardless, here's what I got:

https://github.com/user-attachments/assets/a51fb457-17be-46e1-8c25-bbe19414c4c2

**Comment by T-a-c-h-y-o-n** [comment]
It's pretty good. At least it's better than the previous version :D 
Now simple queries can be made without writing code.

**Comment by aschonfeld** [comment]
Included in v3.14.0
