### ISSUE TITLE
IP Address Could not be found

### ISSUE THREAD

**Issue by hristogg** [man-group/dtale#98]
Hi, 

I am trying to use DTale on a jupyterhub running on a remote centos machine, however it is giving the below error. My guess it that I should somehow manually specify the IP Address of the machine or localhost so that it can link to itself properly but I am not sure how.

![image](https://user-images.githubusercontent.com/29353818/75665814-701f7a80-5c7d-11ea-8e42-166fc4f5b3b2.png)

Thanks in advance,
Hristo

**Comment by aschonfeld** [comment]
@hristogg luck for you I have built a way to do this: `dtale.show(df, host='localhost')`

Although I think you're right, you'll want to specify the host of the machine that jupyterhub is running.  The way the code detects the hostname is this:
```
import socket

socket.gethostname()
```
But I do have a check to see if what comes out of `socket.gethostname()` is actually reachable.  I've noticed on a Mac sometimes they specify a name that isn't actually reachable.  You can check if the host is valid by doing `socket.gethostbyname(socket.gethostname())`

If `socket.gethostbyname` doesn't return `True` then the code will default to `localhost`.  So you could also try setting `host=` to the raw IP address.

Hope this helps and let me know if you encounter further issues.

**Comment by hristogg** [comment]
Thanks, the host solved my issue, had to specify the IP itself and it worked.
