### ISSUE TITLE
Value Error 

### ISSUE THREAD

**Issue by mkashiouris** [man-group/dtale#99]
I have no idea what happened but this cannot run...

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 in 
----> 1 dtale.show(df)

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/dtale/app.py in show(data, host, port, name, debug, subprocess, data_loader, reaper_on, open_browser, notebook, force, context_vars, ignore_duplicate, **kwargs)
    465         url = build_url(ACTIVE_PORT, ACTIVE_HOST)
    466         instance = startup(url, data=data, data_loader=data_loader, name=name, context_vars=context_vars,
--> 467                            ignore_duplicate=ignore_duplicate)
    468         is_active = not running_with_flask_debug() and is_up(url)
    469         if is_active:

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/dtale/views.py in startup(url, data, data_loader, name, data_id, context_vars, ignore_duplicate)
    445         global_state.set_settings(data_id, dict(locked=curr_locked))
    446         global_state.set_data(data_id, data)
--> 447         global_state.set_dtypes(data_id, build_dtypes_state(data, global_state.get_dtypes(data_id) or []))
    448         global_state.set_context_variables(data_id, build_context_variables(data_id, context_vars))
    449         return DtaleData(data_id, url)

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/dtale/views.py in build_dtypes_state(data, prev_state)
    340     """
    341     prev_dtypes = {c['name']: c for c in prev_state or []}
--> 342     ranges = data.agg([min, max]).to_dict()
    343     dtype_f = dtype_formatter(data, get_dtypes(data), ranges, prev_dtypes)
    344     return [dtype_f(i, c) for i, c in enumerate(data.columns)]

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/pandas/core/frame.py in aggregate(self, func, axis, *args, **kwargs)
   6710         result = None
   6711         try:
-> 6712             result, how = self._aggregate(func, axis=axis, *args, **kwargs)
   6713         except TypeError:
   6714             pass

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/pandas/core/frame.py in _aggregate(self, arg, axis, *args, **kwargs)
   6724             result = result.T if result is not None else result
   6725             return result, how
-> 6726         return super()._aggregate(arg, *args, **kwargs)
   6727 
   6728     agg = aggregate

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    562         elif is_list_like(arg):
    563             # we require a list, but not an 'str'
--> 564             return self._aggregate_multiple_funcs(arg, _level=_level, _axis=_axis), None
    565         else:
    566             result = None

~/opt/anaconda3/envs/ThinkBayes2/lib/python3.7/site-packages/pandas/core/base.py in _aggregate_multiple_funcs(self, arg, _level, _axis)
    619         # if we are empty
    620         if not len(results):
--> 621             raise ValueError("no results")
    622 
    623         try:

ValueError: no results

**Comment by aschonfeld** [comment]
I’m sorry, this is a new one.  Any chance you can give me some information on your dataframe?

Maybe the output of df.describe()?

**Comment by mkashiouris** [comment]
Any pandas dataframe doesn’t work...


df = pd.DataFrame([dict(a=1,b=2,c=3)])




________________________________
On: 04 March 2020 18:18,
"Andrew Schonfeld" <notifications@github.com<mailto:notifications@github.com>> wrote:


I’m sorry, this is a new one. Any chance you can give me some information on your dataframe?

Maybe the output of df.describe()?

**Comment by mkashiouris** [comment]
Any dataframe will not work, for example this


df = pd.DataFrame([dict(a=1,b=2,c=3)])



________________________________
On: 04 March 2020 18:18,
"Andrew Schonfeld" <notifications@github.com<mailto:notifications@github.com>> wrote:


I’m sorry, this is a new one. Any chance you can give me some information on your dataframe?

Maybe the output of df.describe()?

**Comment by aschonfeld** [comment]
Thanks that helps, one last question.  What version of python & pandas are you using?

**Comment by aschonfeld** [comment]
Oh wait I see it there.  I’ve built it up to python 3.6, not sure if it will work with 3.7.  I’ll take a look in the morning and see how hard it would be to upgrade

**Comment by mkashiouris** [comment]
Thank you!
M


________________________________
On: 04 March 2020 18:47,
"Andrew Schonfeld" <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh wait I see it there. I’ve built it up to python 3.6, not sure if it will work with 3.7. I’ll take a look in the morning and see how hard it would be to upgrade

**Comment by mkashiouris** [comment]
Thank you Andrew!


________________________________
On: 04 March 2020 18:47,
"Andrew Schonfeld" <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh wait I see it there. I’ve built it up to python 3.6, not sure if it will work with 3.7. I’ll take a look in the morning and see how hard it would be to upgrade

**Comment by aschonfeld** [comment]
@mkashiouris I just ran a python3.7 build with no issue.  Is there any chance you could tell which version of pandas you have installed?  Sorry for all the questions

**Comment by mkashiouris** [comment]
Appreciate your help, Andrew, I am at work now will check when I get home and get back to you since i don’t have python at work

________________________________
On: 05 March 2020 05:35,
"Andrew Schonfeld" <notifications@github.com<mailto:notifications@github.com>> wrote:


@mkashiouris<https://urldefense.com/v3/__https://github.com/mkashiouris__;!!JqxBPMk!yeZnWMGBIxtdUYnaKPSkm2eTU_Zr89foSOMOJi_khYUHy4jVblQ4hHa-YhVyoTAuOKKDQQ$> I just ran a python3.7 build with no issue. Is there any chance you could tell which version of pandas you have installed? Sorry for all the questions

**Comment by aschonfeld** [comment]
No worries, thanks for bearing with me.  One other question is, how were you able to install it in python3.7?  I just created a 3.7 virtualenv and I can't install dtale from pip because I've only uploaded 2.7 & 3.6 eggs.  Did you use conda-forge?

**Comment by aschonfeld** [comment]
@mkashiouris Ok, so I was able to do some more digging.  I was able to get dtale installed on python3.7 using conda.  But I'm still not seeing the issue that you're seeing.  Not from the command-line or a jupyter notebook.  So I'm wondering if you have an old version of pandas installed.

You can view which version of pandas by running the following snippet in either a python console or jupyter notebook:
```
import pandas as pd
pd.__version__
```

**Comment by aschonfeld** [comment]
@mkashiouris good news, I managed to stumble upon your error when trying to pass some transposed data into dtale.  The `agg` function in pandas could handle when a dataframe had mixed dtypes for some reason.  I will be releasing a fix for this hopefully over the weekend.

Still a little worried why this was happening for every dataframe you passed it though.

**Comment by aschonfeld** [comment]
v1.7.13
